/* tslint:disable */
/* eslint-disable */
/**
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnswerCreate
 */
export interface AnswerCreate {
    /**
     * 
     * @type {number}
     * @memberof AnswerCreate
     */
    questionId: number;
    /**
     * 
     * @type {string}
     * @memberof AnswerCreate
     */
    content: string;
}

/**
 * Check if a given object implements the AnswerCreate interface.
 */
export function instanceOfAnswerCreate(value: object): value is AnswerCreate {
    if ((!('questionId' in value) && !('question_id' in value)) || (value['questionId'] === undefined && value['question_id'] === undefined)) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function AnswerCreateFromJSON(json: any): AnswerCreate {
    return AnswerCreateFromJSONTyped(json, false);
}

export function AnswerCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnswerCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'questionId': json['question_id'],
        'content': json['content'],
    };
}

export function AnswerCreateToJSON(json: any): AnswerCreate {
    return AnswerCreateToJSONTyped(json, false);
}

export function AnswerCreateToJSONTyped(value?: AnswerCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'question_id': value['questionId'],
        'content': value['content'],
    };
}

