/* tslint:disable */
/* eslint-disable */
/**
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPost
 */
export interface BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPost {
    /**
     * 
     * @type {string}
     * @memberof BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPost
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPost
     */
    imageUrl: string;
    /**
     * 
     * @type {string}
     * @memberof BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPost
     */
    prompt?: string | null;
}

/**
 * Check if a given object implements the BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPost interface.
 */
export function instanceOfBodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPost(value: object): value is BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPost {
    if ((!('imageUrl' in value) && !('image_url' in value)) || (value['imageUrl'] === undefined && value['image_url'] === undefined)) return false;
    return true;
}

export function BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPostFromJSON(json: any): BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPost {
    return BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPostFromJSONTyped(json, false);
}

export function BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPost {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'] == null ? undefined : json['model'],
        'imageUrl': json['image_url'],
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
    };
}

export function BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPostToJSON(json: any): BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPost {
    return BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPostToJSONTyped(json, false);
}

export function BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPostToJSONTyped(value?: BodyBackgroundGenerationApiV1TongyiImage2imageBackgroundGenerationPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'image_url': value['imageUrl'],
        'prompt': value['prompt'],
    };
}

