/* tslint:disable */
/* eslint-disable */
/**
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodySmsCallbackApiV1CallbackSmsPost
 */
export interface BodySmsCallbackApiV1CallbackSmsPost {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof BodySmsCallbackApiV1CallbackSmsPost
     */
    payload?: { [key: string]: any; };
}

/**
 * Check if a given object implements the BodySmsCallbackApiV1CallbackSmsPost interface.
 */
export function instanceOfBodySmsCallbackApiV1CallbackSmsPost(value: object): value is BodySmsCallbackApiV1CallbackSmsPost {
    return true;
}

export function BodySmsCallbackApiV1CallbackSmsPostFromJSON(json: any): BodySmsCallbackApiV1CallbackSmsPost {
    return BodySmsCallbackApiV1CallbackSmsPostFromJSONTyped(json, false);
}

export function BodySmsCallbackApiV1CallbackSmsPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodySmsCallbackApiV1CallbackSmsPost {
    if (json == null) {
        return json;
    }
    return {
        
        'payload': json['payload'] == null ? undefined : json['payload'],
    };
}

export function BodySmsCallbackApiV1CallbackSmsPostToJSON(json: any): BodySmsCallbackApiV1CallbackSmsPost {
    return BodySmsCallbackApiV1CallbackSmsPostToJSONTyped(json, false);
}

export function BodySmsCallbackApiV1CallbackSmsPostToJSONTyped(value?: BodySmsCallbackApiV1CallbackSmsPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payload': value['payload'],
    };
}

