/* tslint:disable */
/* eslint-disable */
/**
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeveloperLinkCreate
 */
export interface DeveloperLinkCreate {
    /**
     * 
     * @type {string}
     * @memberof DeveloperLinkCreate
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof DeveloperLinkCreate
     */
    cozeAccountId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeveloperLinkCreate
     */
    cozeAccountName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DeveloperLinkCreate
     */
    status?: number | null;
}

/**
 * Check if a given object implements the DeveloperLinkCreate interface.
 */
export function instanceOfDeveloperLinkCreate(value: object): value is DeveloperLinkCreate {
    if ((!('userId' in value) && !('user_id' in value)) || (value['userId'] === undefined && value['user_id'] === undefined)) return false;
    return true;
}

export function DeveloperLinkCreateFromJSON(json: any): DeveloperLinkCreate {
    return DeveloperLinkCreateFromJSONTyped(json, false);
}

export function DeveloperLinkCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeveloperLinkCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'cozeAccountId': json['coze_account_id'] == null ? undefined : json['coze_account_id'],
        'cozeAccountName': json['coze_account_name'] == null ? undefined : json['coze_account_name'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function DeveloperLinkCreateToJSON(json: any): DeveloperLinkCreate {
    return DeveloperLinkCreateToJSONTyped(json, false);
}

export function DeveloperLinkCreateToJSONTyped(value?: DeveloperLinkCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'coze_account_id': value['cozeAccountId'],
        'coze_account_name': value['cozeAccountName'],
        'status': value['status'],
    };
}

