/* tslint:disable */
/* eslint-disable */
/**
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PluginAudioReq
 */
export interface PluginAudioReq {
    /**
     * 
     * @type {string}
     * @memberof PluginAudioReq
     */
    botId: string;
    /**
     * 
     * @type {string}
     * @memberof PluginAudioReq
     */
    conversationId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PluginAudioReq
     */
    pluginId: string;
    /**
     * 
     * @type {string}
     * @memberof PluginAudioReq
     */
    audioData: string;
}

/**
 * Check if a given object implements the PluginAudioReq interface.
 */
export function instanceOfPluginAudioReq(value: object): value is PluginAudioReq {
    if ((!('botId' in value) && !('bot_id' in value)) || (value['botId'] === undefined && value['bot_id'] === undefined)) return false;
    if ((!('pluginId' in value) && !('plugin_id' in value)) || (value['pluginId'] === undefined && value['plugin_id'] === undefined)) return false;
    if ((!('audioData' in value) && !('audio_data' in value)) || (value['audioData'] === undefined && value['audio_data'] === undefined)) return false;
    return true;
}

export function PluginAudioReqFromJSON(json: any): PluginAudioReq {
    return PluginAudioReqFromJSONTyped(json, false);
}

export function PluginAudioReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginAudioReq {
    if (json == null) {
        return json;
    }
    return {
        
        'botId': json['bot_id'],
        'conversationId': json['conversation_id'] == null ? undefined : json['conversation_id'],
        'pluginId': json['plugin_id'],
        'audioData': json['audio_data'],
    };
}

export function PluginAudioReqToJSON(json: any): PluginAudioReq {
    return PluginAudioReqToJSONTyped(json, false);
}

export function PluginAudioReqToJSONTyped(value?: PluginAudioReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bot_id': value['botId'],
        'conversation_id': value['conversationId'],
        'plugin_id': value['pluginId'],
        'audio_data': value['audioData'],
    };
}

