/* tslint:disable */
/* eslint-disable */
/**
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Text-to-video generation request body.
 * @export
 * @interface VideoGenerateBody
 */
export interface VideoGenerateBody {
    /**
     * 
     * @type {string}
     * @memberof VideoGenerateBody
     */
    prompt: string;
    /**
     * 
     * @type {string}
     * @memberof VideoGenerateBody
     */
    modelName?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoGenerateBody
     */
    duration?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoGenerateBody
     */
    mode?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoGenerateBody
     */
    aspectRatio?: string;
    /**
     * 
     * @type {number}
     * @memberof VideoGenerateBody
     */
    cfgScale?: number;
    /**
     * 
     * @type {string}
     * @memberof VideoGenerateBody
     */
    negativePrompt?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof VideoGenerateBody
     */
    cameraControl?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the VideoGenerateBody interface.
 */
export function instanceOfVideoGenerateBody(value: object): value is VideoGenerateBody {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function VideoGenerateBodyFromJSON(json: any): VideoGenerateBody {
    return VideoGenerateBodyFromJSONTyped(json, false);
}

export function VideoGenerateBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoGenerateBody {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
        'modelName': json['model_name'] == null ? undefined : json['model_name'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'aspectRatio': json['aspect_ratio'] == null ? undefined : json['aspect_ratio'],
        'cfgScale': json['cfg_scale'] == null ? undefined : json['cfg_scale'],
        'negativePrompt': json['negative_prompt'] == null ? undefined : json['negative_prompt'],
        'cameraControl': json['camera_control'] == null ? undefined : json['camera_control'],
    };
}

export function VideoGenerateBodyToJSON(json: any): VideoGenerateBody {
    return VideoGenerateBodyToJSONTyped(json, false);
}

export function VideoGenerateBodyToJSONTyped(value?: VideoGenerateBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'model_name': value['modelName'],
        'duration': value['duration'],
        'mode': value['mode'],
        'aspect_ratio': value['aspectRatio'],
        'cfg_scale': value['cfgScale'],
        'negative_prompt': value['negativePrompt'],
        'camera_control': value['cameraControl'],
    };
}

