/*
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CozeAppsApi
 */
@Disabled
public class CozeAppsApiTest {

    private final CozeAppsApi api = new CozeAppsApi();

    /**
     * List Api Apps
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listApiAppsApiV1CozeAppsAppsListApiAppsGetTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        Object response = api.listApiAppsApiV1CozeAppsAppsListApiAppsGet(page, size);
        // TODO: test validations
    }

    /**
     * List Api Apps
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listApiAppsApiV1CozeAppsAppsListApiAppsGet_0Test() throws ApiException {
        Integer page = null;
        Integer size = null;
        Object response = api.listApiAppsApiV1CozeAppsAppsListApiAppsGet_0(page, size);
        // TODO: test validations
    }

    /**
     * List App Events
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAppEventsApiV1CozeAppsAppsEventsGetTest() throws ApiException {
        String appId = null;
        Integer page = null;
        Integer size = null;
        Object response = api.listAppEventsApiV1CozeAppsAppsEventsGet(appId, page, size);
        // TODO: test validations
    }

    /**
     * List App Events
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAppEventsApiV1CozeAppsAppsEventsGet_0Test() throws ApiException {
        String appId = null;
        Integer page = null;
        Integer size = null;
        Object response = api.listAppEventsApiV1CozeAppsAppsEventsGet_0(appId, page, size);
        // TODO: test validations
    }

    /**
     * List Apps
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAppsApiV1CozeAppsAppsListGetTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        Object response = api.listAppsApiV1CozeAppsAppsListGet(page, size);
        // TODO: test validations
    }

    /**
     * List Apps
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAppsApiV1CozeAppsAppsListGet_0Test() throws ApiException {
        Integer page = null;
        Integer size = null;
        Object response = api.listAppsApiV1CozeAppsAppsListGet_0(page, size);
        // TODO: test validations
    }

}
