/*
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.BodyLuyalaChat;
import org.openapitools.client.model.BodyLuyalaCompletion;
import org.openapitools.client.model.BodyLuyalaEmbeddings;
import org.openapitools.client.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LuyalaProxyApi
 */
@Disabled
public class LuyalaProxyApiTest {

    private final LuyalaProxyApi api = new LuyalaProxyApi();

    /**
     * 露雅拉对话
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void luyalaChatTest() throws ApiException {
        BodyLuyalaChat bodyLuyalaChat = null;
        String apiKey = null;
        Object response = api.luyalaChat(bodyLuyalaChat, apiKey);
        // TODO: test validations
    }

    /**
     * 露雅拉对话
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void luyalaChat_0Test() throws ApiException {
        BodyLuyalaChat bodyLuyalaChat = null;
        String apiKey = null;
        Object response = api.luyalaChat_0(bodyLuyalaChat, apiKey);
        // TODO: test validations
    }

    /**
     * 露雅拉文本补全
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void luyalaCompletionTest() throws ApiException {
        BodyLuyalaCompletion bodyLuyalaCompletion = null;
        String apiKey = null;
        Object response = api.luyalaCompletion(bodyLuyalaCompletion, apiKey);
        // TODO: test validations
    }

    /**
     * 露雅拉文本补全
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void luyalaCompletion_0Test() throws ApiException {
        BodyLuyalaCompletion bodyLuyalaCompletion = null;
        String apiKey = null;
        Object response = api.luyalaCompletion_0(bodyLuyalaCompletion, apiKey);
        // TODO: test validations
    }

    /**
     * 露雅拉Embedding
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void luyalaEmbeddingsTest() throws ApiException {
        BodyLuyalaEmbeddings bodyLuyalaEmbeddings = null;
        String apiKey = null;
        Object response = api.luyalaEmbeddings(bodyLuyalaEmbeddings, apiKey);
        // TODO: test validations
    }

    /**
     * 露雅拉Embedding
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void luyalaEmbeddings_0Test() throws ApiException {
        BodyLuyalaEmbeddings bodyLuyalaEmbeddings = null;
        String apiKey = null;
        Object response = api.luyalaEmbeddings_0(bodyLuyalaEmbeddings, apiKey);
        // TODO: test validations
    }

    /**
     * 可用模型列表
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void luyalaModelsTest() throws ApiException {
        Object response = api.luyalaModels();
        // TODO: test validations
    }

    /**
     * 可用模型列表
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void luyalaModels_0Test() throws ApiException {
        Object response = api.luyalaModels_0();
        // TODO: test validations
    }

}
