/*
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.HTTPValidationError;
import org.openapitools.client.model.RegisterRequest;
import org.openapitools.client.model.SmsCodeVerifyRequest;
import org.openapitools.client.model.SmsVerifyRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SmsProxyApi
 */
@Disabled
public class SmsProxyApiTest {

    private final SmsProxyApi api = new SmsProxyApi();

    /**
     * Get Proxy Config
     *
     * Return SMS proxy configuration.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProxyConfigApiV1ApiSmsProxyConfigGetTest() throws ApiException {
        Object response = api.getProxyConfigApiV1ApiSmsProxyConfigGet();
        // TODO: test validations
    }

    /**
     * Quick Register
     *
     * Quick register: verify code then register user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void quickRegisterApiV1ApiSmsProxyRegisterPostTest() throws ApiException {
        RegisterRequest registerRequest = null;
        Object response = api.quickRegisterApiV1ApiSmsProxyRegisterPost(registerRequest);
        // TODO: test validations
    }

    /**
     * Send Sms Code
     *
     * Send SMS verification code (proxy).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sendSmsCodeApiV1ApiSmsProxySendPostTest() throws ApiException {
        SmsVerifyRequest smsVerifyRequest = null;
        Object response = api.sendSmsCodeApiV1ApiSmsProxySendPost(smsVerifyRequest);
        // TODO: test validations
    }

    /**
     * Verify Sms Code
     *
     * Verify SMS code (proxy).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifySmsCodeApiV1ApiSmsProxyVerifyPostTest() throws ApiException {
        SmsCodeVerifyRequest smsCodeVerifyRequest = null;
        Object response = api.verifySmsCodeApiV1ApiSmsProxyVerifyPost(smsCodeVerifyRequest);
        // TODO: test validations
    }

}
