# P29 minikube 演练: 蓝绿切换 Service
# selector 切换实现流量切换: slot=blue 或 slot=green
apiVersion: v1
kind: Service
metadata:
  name: api-service-bluegreen
  namespace: zhs-staging
  labels:
    app: zhs-staging
    component: api
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: zhs-staging
    component: api
    slot: blue
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
