export { baseRoutes } from './base'
export { adminRoutes } from './admin'
export { userRoutes } from './user'
export { aiRoutes } from './ai'
export { apiRoutes } from './api'
export { communityRoutes } from './community'
export { learnRoutes } from './learn'
export { liveRoutes, memberRoutes } from './live-member'
export { publicResourceRoutes, indexRoutes } from './public-resources'
export { p19Routes } from './p19'
export { p20Routes } from './p20'
export { default as eduRoutes } from './edu'
