/** Coze / ihui API 路径前缀 */
export const COZE_API_PREFIX = '/cozeZhsApi'

/** API 端点（与小程序 apiConfig.js 对齐，作为多端单一数据源） */
export const API_ENDPOINTS = {
  AGENT: {
    BY_COLLECT: (uuid: string) => `/remote/agent/by/collect/${uuid}`,
    BY_TYPE: '/remote/agent/by/type',
    CATEGORY: '/remote/agent/category',
    BY_PAY: '/remote/agent/by/pay',
    EXAMINE_LIST: `${COZE_API_PREFIX}/agent-examine/list`,
    CATEGORY_BY_ID: (id: string | number) => `${COZE_API_PREFIX}/agent-category/agent/${id}`,
    BUY_CREATE: `${COZE_API_PREFIX}/agent-buy/create`,
    CATEGORY_CREATE: `${COZE_API_PREFIX}/agent-category/create`,
    CATEGORY_UPDATE: (id: string | number) => `${COZE_API_PREFIX}/agent-category/${id}`,
    CATEGORY_DELETE: (id: string | number) => `${COZE_API_PREFIX}/agent-category/${id}`,
    SETTLEMENT_INCOME: `${COZE_API_PREFIX}/agent-settlement/stats/income-overview`,
    SETTLEMENT_LIST: `${COZE_API_PREFIX}/agent-settlement/list`,
    WITHDRAWAL_LIST: `${COZE_API_PREFIX}/agent-withdrawal-detail/list`,
    TASK_NEED: '/remote/agent/task/need/task',
    TASK_ADD: '/remote/agent/task/need/task/add',
    TASK_INFO: (id: string | number) => `/remote/agent/task/need/task/add/${id}`,
    AI_MODEL_LIST: `${COZE_API_PREFIX}/ai-model-info/list`,
  },
  AI: {
    DASHSCOPE_IMAGE: `${COZE_API_PREFIX}/dashscope/image/generate`,
    DASHSCOPE_IMAGE_EDIT: `${COZE_API_PREFIX}/dashscope/image/edit`,
    DASHSCOPE_VIDEO: `${COZE_API_PREFIX}/dashscope/video/generate`,
    HUNYUAN_3D_SUBMIT: `${COZE_API_PREFIX}/hunyuan/3d/submit`,
    HUNYUAN_3D_QUERY: `${COZE_API_PREFIX}/hunyuan/3d/query`,
    LUYALA_CHAT: `${COZE_API_PREFIX}/luyala/chat/completions`,
    DOUBAO_SEEDREAM: `${COZE_API_PREFIX}/doubao/seedream/4.0`,
    LUYALA_VIDEO: `${COZE_API_PREFIX}/luyala/video/create`,
    SEARCH_WORKFLOW: `${COZE_API_PREFIX}/search/model/workflow/run`,
  },
  KLING: {
    GENERATE_VIDEO: '/kling/generate/video',
    VIDEO_INFO: (id: string | number) => `/kling/video/info/${id}`,
  },
  ALI: {
    GENERATE_TIMBRE: '/ali/generate/timbre',
  },
  SORA: {
    GENERATE_VIDEO: '/jianyi/sora2/generate/video',
    VIDEO_INFO: '/jianyi/sora2/video/info',
  },
  CATEGORY: {
    LIST: '/categoryDictionary/list',
  },
  DEVELOPER: {
    PRICE: '/resource/developer/price',
  },
  LOGIN: {
    REFRESH_TOKEN: '/api/v1/auth/refresh',
  },
  VIP: {
    PRICE: '/fund/getInfo',
    PURCHASE: '/zhs-user-vip/purchase',
    INFO: '/zhs-user-vip/info',
  },
  PAYMENT: {
    INITIATE_PAY: '/pay/initiatePay',
    APP_INITIATE_PAY: '/pay/app/initiatePay',
    UPDATE_STATUS: '/pay/updateStatus',
    CLOSE_ORDER: '/pay/closeOrder',
    CONSECUTIVE_PRODUCT: '/pay/consecutively/product',
  },
  RESOURCE: {
    TOKEN_COUNT: '/resource/getTokenCount',
    TOKEN_RETURN: '/resource/getTokenReturn',
    COURSE_PLANET: '/resource/getCoursePlanet',
    KNOWLEDGE_PLANET: '/resource/getKnowledgePlanet',
    POPULAR_COURSES: '/resource/postPopularCourses',
    PLANT_INFORMATION: '/resource/plantInformation',
    HOME_PAGE_RESOURCES: '/resource/getHomePageResources',
    RECHARGE: '/resource/recharge',
    FIRST_SHARE_SHOW: '/resource/first/share/show',
    FIRST_SHARE: '/resource/first/share',
    FILE_UPLOAD_BY_BASE64: '/file/uploadByBase64',
    FILE_CHUNKED_UPLOAD: '/file/uploadChunkedFile',
    FILE_CHUNKED_JOINT: '/file/uploadChunkedFile/joint',
    FILE_CHUNKED_UPLOAD_PC: '/file/uploadChunkedFile/pc',
    VIDEO_PRELOAD: '/general/api/video/preload',
    WATERMARK: '/resource/download/watermark',
    FILE_UPLOAD: '/resource/fileUpload',
  },
  COURSE: {
    LIST: '/course/list',
    DETAIL: (id: string | number) => `/course/${id}`,
    CREATE: '/course',
    UPDATE: '/course',
    DELETE: (ids: string) => `/course/${ids}`,
    DELIST: (id: string | number) => `/course/delist/${id}`,
    VIDEO_LIST: '/courseVideo/list',
    VIDEO_DETAIL: (id: string | number) => `/courseVideo/${id}`,
    VIDEO_CREATE: '/courseVideo',
    VIDEO_UPDATE: '/courseVideo',
    VIDEO_DELETE: (id: string | number) => `/courseVideo/${id}`,
    VIDEO_ISSUE: (id: string | number) => `/courseVideo/issue/${id}`,
    VIDEO_OPERATE: (videoId: string | number, type: string) => `/userVideoLog/operate/${videoId}/${type}`,
    VIDEO_LOG: (ids: string) => `/userVideoLog/${ids}`,
    VIDEO_COMMENT_LIST: '/userVideoComment/list',
    VIDEO_COMMENT: '/userVideoComment',
  },
  INFORMATION: {
    DICTIONARY: '/information/dictionary',
    LIST: '/information/list',
  },
  PLAZA: {
    DEMAND_LIST: '/remote/agent/task/need/task',
    DEMAND_ADD: '/remote/agent/task/need/task/add',
    DEMAND_INFO: (id: string | number) => `/remote/agent/task/need/task/add/${id}`,
  },
  DISTRIBUTION: {
    SUBORDINATES: '/distribution/getSubordinates',
    CHILDREN_ORDERS: '/distribution/getUserAndChildrenOrders',
    COMMISSION_DETAIL: '/distribution/getUserCommissionDetail',
    FLOW_LIST: '/flow/list',
    FLOW_ORDER_LIST: '/flow/orderList',
    TRADER_STATISTICS: '/flow/getStatistics',
    TRADER_TEAM: '/flow/getTraderTeamByCenter',
    WITHDRAWAL: '/zhsWithdrawal/withdrawal',
    WITHDRAWAL_STATUS: '/zhsWithdrawal/getWithdrawal',
    GET_WX_CODE: '/login/getWxCode',
  },
  AI_CHAT: {
    MODEL_CHAT_QUERY: `${COZE_API_PREFIX}/user-model-chat/query`,
    MODEL_CHAT_CREATE: `${COZE_API_PREFIX}/user-model-chat/create`,
    AGENT_CONTEXT_QUERY: `${COZE_API_PREFIX}/user-agent-context/query`,
    MODEL_CHAT_UPDATE_MARK: `${COZE_API_PREFIX}/user-model-chat/update/mark`,
    MODEL_CHAT_DELETE: (id: string | number) => `${COZE_API_PREFIX}/user-model-chat/${id}`,
    AIGC_LIST: '/general/ai_gc/list',
    AGENT_ALL_LIST: `${COZE_API_PREFIX}/agents/Alllist`,
  },
  N8N: {
    AGENT_UPLOAD: '/api/agent/upload',
    AGENT_PROCESS: '/api/agent/process',
  },
  FEEDBACK: {
    CREATE: '/userFeedback',
    LIST: '/userFeedback/list',
  },
  GROUP: {
    LIST: '/general/remote/third/group/list',
  },
} as const
