/**
 * other 子路由统一导出(barrel file)。
 * 供 other/index.ts 导入,避免 25 条 import 散落在 index.ts 中。
 */
export { activityRoutes } from './activity-routes.js'
export { addressRoutes } from './address-routes.js'
export { aiWorldRoutes } from './ai-world-routes.js'
export { aiCapabilityRoutes } from './ai-capability-routes.js'
export { auditRoutes } from './audit-routes.js'
export { businessCardRoutes } from './business-card-routes.js'
export { developerRoutes } from './developer-routes.js'
export { dramaRoutes } from './drama-routes.js'
export { imageGenRoutes } from './image-gen-routes.js'
export { knowledgeBaseRoutes } from './knowledge-base-routes.js'
export { llmStreamRoutes } from './llm-stream-routes.js'
export { memberRoutes } from './member-routes.js'
export { messageRoutes } from './message-routes.js'
export { notesRoutes } from './notes-routes.js'
export { notificationRoutes } from './notification-routes.js'
export { ossResourceRoutes } from './oss-resource-routes.js'
export { pdfRoutes } from './pdf-routes.js'
export { serviceAppointmentRoutes } from './service-appointment-routes.js'
export { shareRoutes } from './share-routes.js'
export { studentProfileRoutes } from './student-profile-routes.js'
export { studyPlanRoutes } from './study-plan-routes.js'
export { tourRoutes } from './tour-routes.js'
export { v1ContentRoutes } from './v1-content-routes.js'
export { v1CustomerServiceRoutes } from './v1-customer-service-routes.js'
export { v1ToolsRoutes } from './v1-tools-routes.js'
