/*
ZHS Platform

Testing AIVoiceprintAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zhs_api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_zhs_api_AIVoiceprintAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AIVoiceprintAPIService AddVoiceprintApiV1AiAudioGroupsGroupIdUsersPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string

		resp, httpRes, err := apiClient.AIVoiceprintAPI.AddVoiceprintApiV1AiAudioGroupsGroupIdUsersPost(context.Background(), groupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AIVoiceprintAPIService AddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string

		resp, httpRes, err := apiClient.AIVoiceprintAPI.AddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPost(context.Background(), groupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AIVoiceprintAPIService CreateVoiceprintGroupApiV1AiAudioGroupsCreatePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AIVoiceprintAPI.CreateVoiceprintGroupApiV1AiAudioGroupsCreatePost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AIVoiceprintAPIService DeleteVoiceprintApiV1AiAudioGroupsGroupIdUsersFeatureIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string
		var featureId string

		resp, httpRes, err := apiClient.AIVoiceprintAPI.DeleteVoiceprintApiV1AiAudioGroupsGroupIdUsersFeatureIdDelete(context.Background(), groupId, featureId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AIVoiceprintAPIService IdentifySpeakerApiV1AiAudioIdentifyPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AIVoiceprintAPI.IdentifySpeakerApiV1AiAudioIdentifyPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AIVoiceprintAPIService IdentifySpeakerUploadApiV1AiAudioGroupsGroupIdIdentifyPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string

		resp, httpRes, err := apiClient.AIVoiceprintAPI.IdentifySpeakerUploadApiV1AiAudioGroupsGroupIdIdentifyPost(context.Background(), groupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AIVoiceprintAPIService ListVoiceprintGroupsApiV1AiAudioGroupsListGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AIVoiceprintAPI.ListVoiceprintGroupsApiV1AiAudioGroupsListGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AIVoiceprintAPIService ListVoiceprintsApiV1AiAudioGroupsGroupIdUsersGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var groupId string

		resp, httpRes, err := apiClient.AIVoiceprintAPI.ListVoiceprintsApiV1AiAudioGroupsGroupIdUsersGet(context.Background(), groupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
