/*
ZHS Platform

Testing VIPAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package zhs_api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_zhs_api_VIPAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VIPAPIService CheckVipApiV1UserCheckGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VIPAPI.CheckVipApiV1UserCheckGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VIPAPIService GetMyVipApiV1UserMyGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VIPAPI.GetMyVipApiV1UserMyGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VIPAPIService GetVipLevelDetailApiV1UserLevelVipIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var vipId int32

		resp, httpRes, err := apiClient.VIPAPI.GetVipLevelDetailApiV1UserLevelVipIdGet(context.Background(), vipId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VIPAPIService GetVipLevelsApiV1UserLevelsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VIPAPI.GetVipLevelsApiV1UserLevelsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VIPAPIService SubscribeVipApiV1UserSubscribePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.VIPAPI.SubscribeVipApiV1UserSubscribePost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
