export { IDELayout } from './ide-layout'
export { ActivityBar } from './activity-bar'
export { IDETopBar } from './ide-top-bar'
export { ViewSwitcher } from './view-switcher'
export { FileExplorer } from './file-explorer'
export { FileTreeNode } from './file-tree-node'
export { EditorTabBar } from './editor-tab-bar'
export { CodeEditorPane } from './code-editor-pane'
export { EditorEmptyState } from './editor-empty-state'
export { DiffViewerPane } from './diff-viewer-pane'
export { DiffStatsBar } from './diff-stats-bar'
export { DiffFileList } from './diff-file-list'
export { SearchPanel } from './search-panel'
export { SourceControlPanel } from './source-control-panel'
export { DebugPanel } from './debug-panel'
export { ApplicationsPanel } from './applications-panel'
export { StatusBar } from './status-bar'
export { getFileIcon, getFileColor } from './file-icons'
