/*
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DatasetCreateReq
 */
public class DatasetCreateReqTest {
    private final DatasetCreateReq model = new DatasetCreateReq();

    /**
     * Model tests for DatasetCreateReq
     */
    @Test
    public void testDatasetCreateReq() {
        // TODO: test DatasetCreateReq
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'spaceId'
     */
    @Test
    public void spaceIdTest() {
        // TODO: test spaceId
    }

}
