{{- if and .Values.persistence.hls.enabled (eq (index .Values.persistence.hls.accessModes 0) "ReadWriteOnce") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zhs-platform.fullname" . }}-hls
  labels:
    {{- include "zhs-platform.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.hls.accessModes | nindent 4 }}
  {{- if .Values.persistence.hls.storageClassName }}
  storageClassName: {{ .Values.persistence.hls.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.hls.size | quote }}
{{- end }}
---
{{- if and .Values.persistence.static.enabled (eq (index .Values.persistence.static.accessModes 0) "ReadWriteOnce") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zhs-platform.fullname" . }}-static
  labels:
    {{- include "zhs-platform.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.static.accessModes | nindent 4 }}
  {{- if .Values.persistence.static.storageClassName }}
  storageClassName: {{ .Values.persistence.static.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.static.size | quote }}
{{- end }}
