apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zhs-platform.fullname" . }}-db
  labels:
    {{- include "zhs-platform.labels" . | nindent 4 }}
type: Opaque
# 默认空, 由运维在生产环境用 sealed-secret 或 external-secrets 覆盖
stringData:
  DB1_PASSWORD: ""
  DB2_PASSWORD: ""
  DB3_PASSWORD: ""
