export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/community/index',
    'pages/login/login',
    'pages/forgot-password/index',
    'pages/course/list',
    'pages/course/detail',
    'pages/live/list',
    'pages/live/detail',
    'pages/user/index',
    'pages/favorites/index',
    'pages/following/index',
    'pages/subscriptions/index',
    'pages/user/settings',
    'pages/user/orders',
    'pages/ai/chat',
    'pages/vip/index',
    'pages/vip/privilege',
    'pages/vip/upgrade',
    'pages/vip/details',
    'pages/vip/success',
    'pages/pay/index',
    'pages/pay/result',
    'pages/order/list',
    'pages/order/detail',
    'pages/order/refund',
    'pages/order/refund-list',
    'pages/user/profile',
    'pages/user/avatar',
    'pages/user/nickname',
    'pages/user/phone',
    'pages/user/password',
    'pages/user/email',
    'pages/user/realname',
    'pages/user/feedback',
    'pages/news/list',
    'pages/news/detail',
    'pages/topic/list',
    'pages/topic/detail',
    'pages/ai/history',
    'pages/ai/image',
    'pages/ai/voice',
    'pages/ai/agent',
    'pages/ai/agent-detail',
    'pages/ai/video',
    'pages/ai/special',
    'pages/live/history',
    'pages/live/calendar',
    'pages/live/subscribe',
    'pages/live/host/index',
    'pages/teacher/list',
    'pages/teacher/detail',
    'pages/about/index',
    'pages/about/help',
    'pages/about/protocol',
    'pages/about/privacy',
    'pages/about/contact',
    'pages/message/index',
    'pages/aigc/list',
    'pages/aigc/publish',
    'pages/model-plaza/index',
    'pages/ranking/index',
    'pages/ranking/detail',
    'pages/token/balance',
    'pages/developer/index',
    'pages/developer/income',
    'pages/developer/withdrawal',
    'pages/developer/subscribe',
    'pages/business-card/index',
    'pages/register/index',
    'pages/webview/index',
    'pages/plaza/index/index',
    'pages/plaza/cover/index',
    'pages/plaza/set-need/index',
    'pages/dev-enter/cover/index',
    'pages/dev-enter/model-edit/index',
    'pages/dev-enter/n8n-model/index',
    'pages/ai-group/index',
    'pages/ai-assistant-n8n/index',
    'pages/ai-assistant/index',
    'pages/ai-career/index',
    'pages/ai-circle/index',
    'pages/ai-chat-detail/index',
    'pages/agent-dialogue/index',
    'pages/cart/index',
    'pages/learn-develop/index',
    'pages/course-planet/index',
    'pages/account-cancel/index',
    'pages/about/business-license/index',
    'pages/about/icp-record/index',
    'pages/about/model-record/index',
    'pages/about/usage-rules/index',
    'pages/about/app-permission/index',
    'pages/about/api-settings/index',
    'pages/recruitment/index/index',
    'pages/vip-trader/index/index',
    'pages/share/index',
    'pages/share/creation',
    'pages/category-detail/index',
    'pages/carte/index',
    'pages/wallet/recharge/index',
    'pages/wallet/recharge/success',
    'pages/wallet/recharge/fail',
    'pages/wallet/top-up/index',
    'pages/wallet/withdrawal/index',
    'pages/wallet/commission/index',
    'pages/subscription/contracts/index',
  ],
  subPackages: [
    {
      root: 'pages/distribution',
      pages: [
        'index',
        'team',
        'commission',
        'withdraw',
        'rank',
        'order-list/index',
        'member-detail/index',
        'plan/index',
        'company/index',
      ],
    },
    {
      root: 'pages/exam',
      pages: ['list', 'detail', 'answer', 'result'],
    },
    {
      root: 'pages/study',
      pages: [
        'index',
        'record',
        'plan',
        'rank',
        'my-study/index',
        'publish/index',
        'video-detail/index',
      ],
    },
    {
      root: 'pages/circle',
      pages: ['index', 'detail', 'create'],
    },
    {
      root: 'pages/ask',
      pages: ['list', 'detail', 'create'],
    },
    {
      root: 'pages/member',
      pages: ['index', 'benefits', 'integral', 'coupon', 'coupon-list'],
    },
    {
      root: 'pages/setting',
      pages: ['index', 'notification', 'cache', 'language', 'theme', 'privacy'],
    },
  ],
  window: {
    backgroundTextStyle: 'dark',
    navigationBarBackgroundColor: '#121217',
    navigationBarTitleText: '智汇AI',
    navigationBarTextStyle: 'white',
    backgroundColor: '#121217',
  },
  tabBar: {
    // Taro 4 Vite 编译不输出 custom-tab-bar(GitHub #17978/#18415),暂用原生 tabBar
    // 后续改 webpack5 编译器后可恢复 custom: true
    custom: false,
    color: 'rgba(255,255,255,0.5)',
    selectedColor: '#00F2FF',
    borderStyle: 'black',
    backgroundColor: '#1F1F28',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '智汇社区',
        iconPath: 'assets/tabbar/community.png',
        selectedIconPath: 'assets/tabbar/community-active.png',
      },
      {
        pagePath: 'pages/community/index',
        text: 'AI agent',
        iconPath: 'assets/tabbar/agent.png',
        selectedIconPath: 'assets/tabbar/agent-active.png',
      },
      {
        pagePath: 'pages/plaza/index/index',
        text: 'Square',
        iconPath: 'assets/tabbar/square.png',
        selectedIconPath: 'assets/tabbar/square-active.png',
      },
      {
        pagePath: 'pages/user/index',
        text: '我的',
        iconPath: 'assets/tabbar/user.png',
        selectedIconPath: 'assets/tabbar/user-active.png',
      },
      {
        pagePath: 'pages/share/index',
        text: '分享星球',
        iconPath: 'assets/tabbar/share.png',
        selectedIconPath: 'assets/tabbar/share-active.png',
      },
    ],
  },
})
