export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/login/login',
    'pages/course/list',
    'pages/course/detail',
    'pages/live/list',
    'pages/live/detail',
    'pages/user/index',
    'pages/favorites/index',
    'pages/following/index',
    'pages/subscriptions/index',
    'pages/user/settings',
    'pages/user/orders',
    'pages/ai/chat',
    'pages/vip/index',
    'pages/vip/privilege',
    'pages/vip/upgrade',
    'pages/pay/index',
    'pages/pay/result',
    'pages/order/list',
    'pages/order/detail',
    'pages/order/refund',
    'pages/order/refund-list',
    'pages/user/profile',
    'pages/user/avatar',
    'pages/user/nickname',
    'pages/user/phone',
    'pages/user/password',
    'pages/user/email',
    'pages/user/realname',
    'pages/user/feedback',
    'pages/news/list',
    'pages/news/detail',
    'pages/topic/list',
    'pages/topic/detail',
    'pages/ai/history',
    'pages/ai/image',
    'pages/ai/voice',
    'pages/ai/agent',
    'pages/ai/agent-detail',
    'pages/ai/video',
    'pages/ai/special',
    'pages/live/history',
    'pages/live/calendar',
    'pages/live/subscribe',
    'pages/teacher/list',
    'pages/teacher/detail',
    'pages/about/index',
    'pages/about/help',
    'pages/about/protocol',
    'pages/about/privacy',
    'pages/about/contact',
    'pages/message/index',
    'pages/aigc/list',
    'pages/aigc/publish',
    'pages/model-plaza/index',
    'pages/ranking/index',
    'pages/token/balance',
    'pages/developer/index',
    'pages/developer/income',
    'pages/developer/withdrawal',
    'pages/developer/subscribe',
    'pages/business-card/index',
    'pages/register/index',
    'pages/webview/index',
    'pages/plaza/index/index',
    'pages/plaza/cover/index',
    'pages/plaza/set-need/index',
    'pages/dev-enter/cover/index',
    'pages/dev-enter/model-edit/index',
    'pages/dev-enter/n8n-model/index',
    'pages/ai-group/index',
    'pages/ai-assistant-n8n/index',
    'pages/ai-career/index',
    'pages/ai-circle/index',
    'pages/ai-chat-detail/index',
    'pages/agent-dialogue/index',
    'pages/cart/index',
    'pages/learn-develop/index',
    'pages/course-planet/index',
    'pages/account-cancel/index',
    'pages/about/business-license/index',
    'pages/about/icp-record/index',
    'pages/about/model-record/index',
    'pages/about/usage-rules/index',
    'pages/about/app-permission/index',
    'pages/about/api-settings/index',
    'pages/recruitment/index/index',
    'pages/vip-trader/index/index',
    'pages/share/index',
    'pages/share/creation',
    'pages/category-detail/index',
    'pages/carte/index',
    'pages/wallet/recharge/index',
    'pages/wallet/recharge/success',
    'pages/wallet/recharge/fail',
    'pages/wallet/top-up/index',
    'pages/subscription/contracts/index',
  ],
  subPackages: [
    {
      root: 'pages/distribution',
      name: 'pagesA',
      pages: [
        'index',
        'team',
        'commission',
        'withdraw',
        'rank',
        'order-list/index',
        'member-detail/index',
        'plan/index',
        'company/index',
      ],
    },
    {
      root: 'pages/exam',
      name: 'pagesB',
      pages: ['list', 'detail', 'answer', 'result'],
    },
    {
      root: 'pages/study',
      name: 'pagesB',
      pages: [
        'index',
        'record',
        'plan',
        'rank',
        'my-study/index',
        'publish/index',
        'video-detail/index',
      ],
    },
    {
      root: 'pages/circle',
      name: 'pagesC',
      pages: ['index', 'detail', 'create'],
    },
    {
      root: 'pages/ask',
      name: 'pagesC',
      pages: ['list', 'detail', 'create'],
    },
    {
      root: 'pages/member',
      name: 'pagesD',
      pages: ['index', 'benefits', 'integral', 'coupon', 'coupon-list'],
    },
    {
      root: 'pages/setting',
      name: 'pagesD',
      pages: ['index', 'notification', 'cache', 'language', 'theme'],
    },
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '智汇AI',
    navigationBarTextStyle: 'black',
    backgroundColor: '#f7f8fa',
  },
  tabBar: {
    color: '#999999',
    selectedColor: '#07c160',
    borderStyle: 'black',
    backgroundColor: '#ffffff',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home-active.png',
      },
      {
        pagePath: 'pages/course/list',
        text: '课程',
        iconPath: 'assets/tabbar/course.png',
        selectedIconPath: 'assets/tabbar/course-active.png',
      },
      {
        pagePath: 'pages/live/list',
        text: '直播',
        iconPath: 'assets/tabbar/live.png',
        selectedIconPath: 'assets/tabbar/live-active.png',
      },
      {
        pagePath: 'pages/ai/chat',
        text: 'AI',
        iconPath: 'assets/tabbar/ai.png',
        selectedIconPath: 'assets/tabbar/ai-active.png',
      },
      {
        pagePath: 'pages/user/index',
        text: '我的',
        iconPath: 'assets/tabbar/user.png',
        selectedIconPath: 'assets/tabbar/user-active.png',
      },
    ],
  },
})
