// © 2026 IHUI AI (智汇AI) · 版权所有者: 李春川 (Li Chunchuan) · https://aizhs.top
// Provenance-watermarked. 未授权商用可被溯源追责 (Apache-2.0 须保留本声明与 NOTICE)。
// [IHUI-AI-PROVENANCE]:⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠

// GENERATED FILE — DO NOT EDIT. 由 apps/miniapp-taro/scripts/generate-ui-routes.mjs 生成(pnpm gen:ui-routes)
// 数据源:src/app.config.ts(pages/subPackages/tabBar)+ 各页 *.config.ts 的 navigationBarTitleText;
// requiresParams 由扫描源码 navigateTo url 是否带 query 得出。改页面请改 app.config.ts 后重新生成。

/** AI 可导航页面条目:path 为 Taro 导航全路径(含前导斜杠,分包已拼 root) */
export interface TaroUiRouteEntry {
  /** Taro 导航 url,如 /pkg-ai/ai/chat */
  path: string
  /** navigationBarTitleText(无页面 config 时回落 app window 标题 / tabBar 文案) */
  title: string
  /** 是否 tabBar 页:true 必须走 Taro.switchTab(navigateTo 会直接失败) */
  tab: boolean
  /** 所属分包 root,主包为 ''(分包页必须用全路径才能命中) */
  subPackageRoot: string
  /** 源码中该页是否以 ?query 形式打开(如 /pkg-ai/ai/chat?id=xx) */
  requiresParams: boolean
}

/** app.config.ts → window.navigationBarTitleText,页面无显式标题时的回落值 */
export const TARO_APP_WINDOW_TITLE = '智汇AI'

/** 全量页面白名单(顺序与 app.config.ts 一致,便于 diff 审查) */
export const TARO_UI_ROUTES: readonly TaroUiRouteEntry[] = [
  {
    path: '/pages/index/index',
    title: '智汇社区',
    tab: true,
    subPackageRoot: '',
    requiresParams: false,
  },
  {
    path: '/pages/community/index',
    title: '智汇社区',
    tab: true,
    subPackageRoot: '',
    requiresParams: false,
  },
  {
    path: '/pages/login/login',
    title: '登录',
    tab: false,
    subPackageRoot: '',
    requiresParams: false,
  },
  {
    path: '/pages/forgot-password/index',
    title: '找回密码',
    tab: false,
    subPackageRoot: '',
    requiresParams: false,
  },
  {
    path: '/pages/webview/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: '',
    requiresParams: true,
  },
  {
    path: '/pages/register/index',
    title: '注册',
    tab: false,
    subPackageRoot: '',
    requiresParams: false,
  },
  {
    path: '/pages/user/index',
    title: '我的',
    tab: true,
    subPackageRoot: '',
    requiresParams: false,
  },
  {
    path: '/pages/plaza/index/index',
    title: '广场',
    tab: true,
    subPackageRoot: '',
    requiresParams: false,
  },
  {
    path: '/pages/share/index',
    title: '分享星球',
    tab: true,
    subPackageRoot: '',
    requiresParams: true,
  },
  {
    path: '/pkg-ai/ai/chat',
    title: 'AI 对话',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: true,
  },
  {
    path: '/pkg-ai/ai/history',
    title: '对话历史',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/ai/image',
    title: 'AI 绘图',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: true,
  },
  {
    path: '/pkg-ai/ai/voice',
    title: 'AI 语音',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: true,
  },
  {
    path: '/pkg-ai/ai/agent',
    title: 'AI Agent',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: true,
  },
  {
    path: '/pkg-ai/ai/agent-detail',
    title: 'Agent 详情',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: true,
  },
  {
    path: '/pkg-ai/ai/video',
    title: 'AI 视频生成',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: true,
  },
  {
    path: '/pkg-ai/ai/special',
    title: '特殊模型',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/ai-skill/index',
    title: 'AI 技能',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/ai-skill/detail/index',
    title: '技能详情',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: true,
  },
  {
    path: '/pkg-ai/ai-group/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/ai-assistant/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: true,
  },
  {
    path: '/pkg-ai/ai-assistant-n8n/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: true,
  },
  {
    path: '/pkg-ai/ai-career/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/ai-circle/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/ai-chat-detail/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/agent-dialogue/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: true,
  },
  {
    path: '/pkg-ai/aigc/list',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/aigc/publish',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/model-plaza/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/ranking/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/ranking/detail',
    title: '详情页',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: true,
  },
  {
    path: '/pkg-ai/developer/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/developer/income',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/developer/withdrawal',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/developer/subscribe',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/business-card/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/dev-enter/cover/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-ai/dev-enter/model-edit/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: true,
  },
  {
    path: '/pkg-ai/dev-enter/n8n-model/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-ai',
    requiresParams: false,
  },
  {
    path: '/pkg-shop/vip/index',
    title: 'VIP 会员',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: true,
  },
  {
    path: '/pkg-shop/vip/privilege',
    title: 'VIP 特权',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: false,
  },
  {
    path: '/pkg-shop/vip/upgrade',
    title: '升级VIP',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: true,
  },
  {
    path: '/pkg-shop/vip/details',
    title: '会员详情',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: false,
  },
  {
    path: '/pkg-shop/vip/success',
    title: '开通成功',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: true,
  },
  {
    path: '/pkg-shop/pay/index',
    title: '收银台',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: true,
  },
  {
    path: '/pkg-shop/pay/result/index',
    title: '支付结果',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: true,
  },
  {
    path: '/pkg-shop/order/list',
    title: '我的订单',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: false,
  },
  {
    path: '/pkg-shop/order/detail',
    title: '订单详情',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: true,
  },
  {
    path: '/pkg-shop/order/refund',
    title: '申请退款',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: true,
  },
  {
    path: '/pkg-shop/order/refund-list',
    title: '退款记录',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: false,
  },
  {
    path: '/pkg-shop/token/balance',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: false,
  },
  {
    path: '/pkg-shop/cart/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: false,
  },
  {
    path: '/pkg-shop/vip-trader/index/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: false,
  },
  {
    path: '/pkg-shop/wallet/recharge/index',
    title: '充值',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: false,
  },
  {
    path: '/pkg-shop/wallet/top-up/index',
    title: '充值',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: false,
  },
  {
    path: '/pkg-shop/wallet/withdrawal/index',
    title: '提现',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: false,
  },
  {
    path: '/pkg-shop/wallet/commission/index',
    title: '我的佣金',
    tab: false,
    subPackageRoot: 'pkg-shop',
    requiresParams: false,
  },
  {
    path: '/pkg-learn/course/list',
    title: '课程列表',
    tab: false,
    subPackageRoot: 'pkg-learn',
    requiresParams: false,
  },
  {
    path: '/pkg-learn/course/detail',
    title: '课程详情',
    tab: false,
    subPackageRoot: 'pkg-learn',
    requiresParams: true,
  },
  {
    path: '/pkg-learn/live/list',
    title: '直播列表',
    tab: false,
    subPackageRoot: 'pkg-learn',
    requiresParams: false,
  },
  {
    path: '/pkg-learn/live/detail',
    title: '直播详情',
    tab: false,
    subPackageRoot: 'pkg-learn',
    requiresParams: true,
  },
  {
    path: '/pkg-learn/live/history',
    title: '直播回放',
    tab: false,
    subPackageRoot: 'pkg-learn',
    requiresParams: false,
  },
  {
    path: '/pkg-learn/live/calendar',
    title: '直播日历',
    tab: false,
    subPackageRoot: 'pkg-learn',
    requiresParams: false,
  },
  {
    path: '/pkg-learn/live/subscribe',
    title: '我的订阅',
    tab: false,
    subPackageRoot: 'pkg-learn',
    requiresParams: false,
  },
  {
    path: '/pkg-learn/live/host/index',
    title: '主播端',
    tab: false,
    subPackageRoot: 'pkg-learn',
    requiresParams: false,
  },
  {
    path: '/pkg-learn/teacher/list',
    title: '讲师列表',
    tab: false,
    subPackageRoot: 'pkg-learn',
    requiresParams: false,
  },
  {
    path: '/pkg-learn/teacher/detail',
    title: '讲师详情',
    tab: false,
    subPackageRoot: 'pkg-learn',
    requiresParams: true,
  },
  {
    path: '/pkg-learn/learn-develop/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-learn',
    requiresParams: false,
  },
  {
    path: '/pkg-learn/course-planet/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-learn',
    requiresParams: false,
  },
  {
    path: '/pkg-learn/subscription/contracts/index',
    title: '自动续费管理',
    tab: false,
    subPackageRoot: 'pkg-learn',
    requiresParams: false,
  },
  {
    path: '/pkg-user/user/settings',
    title: '设置',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/user/orders',
    title: '我的订单',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/user/profile',
    title: '个人资料',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/user/avatar',
    title: '头像设置',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/user/nickname',
    title: '修改昵称',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/user/phone',
    title: '手机绑定',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/user/password',
    title: '修改密码',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/user/email',
    title: '邮箱绑定',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/user/realname',
    title: '实名认证',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/user/feedback',
    title: '意见反馈',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/favorites/index',
    title: '我的收藏',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/following/index',
    title: '我的关注',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/subscriptions/index',
    title: '我的订阅',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/message/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/account-cancel/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/check-in/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/task-center/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-user/bill/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-user',
    requiresParams: false,
  },
  {
    path: '/pkg-content/news/list',
    title: '资讯',
    tab: false,
    subPackageRoot: 'pkg-content',
    requiresParams: false,
  },
  {
    path: '/pkg-content/news/detail',
    title: '资讯详情',
    tab: false,
    subPackageRoot: 'pkg-content',
    requiresParams: true,
  },
  {
    path: '/pkg-content/topic/list',
    title: '话题',
    tab: false,
    subPackageRoot: 'pkg-content',
    requiresParams: true,
  },
  {
    path: '/pkg-content/topic/detail',
    title: '话题详情',
    tab: false,
    subPackageRoot: 'pkg-content',
    requiresParams: true,
  },
  {
    path: '/pkg-content/announcement/index',
    title: '平台公告',
    tab: false,
    subPackageRoot: 'pkg-content',
    requiresParams: false,
  },
  {
    path: '/pkg-content/announcement/detail/index',
    title: '公告详情',
    tab: false,
    subPackageRoot: 'pkg-content',
    requiresParams: true,
  },
  {
    path: '/pkg-content/activity/index',
    title: '平台活动',
    tab: false,
    subPackageRoot: 'pkg-content',
    requiresParams: false,
  },
  {
    path: '/pkg-content/search/index',
    title: '搜索',
    tab: false,
    subPackageRoot: 'pkg-content',
    requiresParams: false,
  },
  {
    path: '/pkg-content/category-detail/index',
    title: '分类详情',
    tab: false,
    subPackageRoot: 'pkg-content',
    requiresParams: false,
  },
  {
    path: '/pkg-content/recruitment/index/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-content',
    requiresParams: false,
  },
  {
    path: '/pkg-content/carte/index',
    title: '个人名片',
    tab: false,
    subPackageRoot: 'pkg-content',
    requiresParams: false,
  },
  {
    path: '/pkg-content/share/creation',
    title: 'AI 创作分享',
    tab: false,
    subPackageRoot: 'pkg-content',
    requiresParams: true,
  },
  {
    path: '/pkg-content/plaza/detail/index',
    title: '需求详情',
    tab: false,
    subPackageRoot: 'pkg-content',
    requiresParams: true,
  },
  {
    path: '/pkg-content/plaza/cover/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pkg-content',
    requiresParams: false,
  },
  {
    path: '/pkg-content/plaza/set-need/index',
    title: '设置需求',
    tab: false,
    subPackageRoot: 'pkg-content',
    requiresParams: false,
  },
  {
    path: '/pkg-content/community/create/index',
    title: '发布帖子',
    tab: false,
    subPackageRoot: 'pkg-content',
    requiresParams: false,
  },
  {
    path: '/pkg-about/about/index',
    title: '关于我们',
    tab: false,
    subPackageRoot: 'pkg-about',
    requiresParams: false,
  },
  {
    path: '/pkg-about/about/help',
    title: '帮助中心',
    tab: false,
    subPackageRoot: 'pkg-about',
    requiresParams: false,
  },
  {
    path: '/pkg-about/about/protocol',
    title: '用户协议',
    tab: false,
    subPackageRoot: 'pkg-about',
    requiresParams: false,
  },
  {
    path: '/pkg-about/about/privacy',
    title: '隐私政策',
    tab: false,
    subPackageRoot: 'pkg-about',
    requiresParams: false,
  },
  {
    path: '/pkg-about/about/contact',
    title: '联系我们',
    tab: false,
    subPackageRoot: 'pkg-about',
    requiresParams: false,
  },
  {
    path: '/pkg-about/about/business-license/index',
    title: '营业执照',
    tab: false,
    subPackageRoot: 'pkg-about',
    requiresParams: false,
  },
  {
    path: '/pkg-about/about/icp-record/index',
    title: 'ICP备案',
    tab: false,
    subPackageRoot: 'pkg-about',
    requiresParams: false,
  },
  {
    path: '/pkg-about/about/model-record/index',
    title: '模型备案',
    tab: false,
    subPackageRoot: 'pkg-about',
    requiresParams: false,
  },
  {
    path: '/pkg-about/about/usage-rules/index',
    title: '使用规范',
    tab: false,
    subPackageRoot: 'pkg-about',
    requiresParams: false,
  },
  {
    path: '/pkg-about/about/app-permission/index',
    title: '应用权限',
    tab: false,
    subPackageRoot: 'pkg-about',
    requiresParams: false,
  },
  {
    path: '/pkg-about/about/api-settings/index',
    title: 'API设置',
    tab: false,
    subPackageRoot: 'pkg-about',
    requiresParams: false,
  },
  {
    path: '/pages/distribution/index',
    title: '分销中心',
    tab: false,
    subPackageRoot: 'pages/distribution',
    requiresParams: false,
  },
  {
    path: '/pages/distribution/team',
    title: '我的团队',
    tab: false,
    subPackageRoot: 'pages/distribution',
    requiresParams: false,
  },
  {
    path: '/pages/distribution/commission',
    title: '佣金记录',
    tab: false,
    subPackageRoot: 'pages/distribution',
    requiresParams: false,
  },
  {
    path: '/pages/distribution/withdraw',
    title: '申请提现',
    tab: false,
    subPackageRoot: 'pages/distribution',
    requiresParams: false,
  },
  {
    path: '/pages/distribution/rank',
    title: '分销排行',
    tab: false,
    subPackageRoot: 'pages/distribution',
    requiresParams: false,
  },
  {
    path: '/pages/distribution/order-list/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pages/distribution',
    requiresParams: false,
  },
  {
    path: '/pages/distribution/member-detail/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pages/distribution',
    requiresParams: true,
  },
  {
    path: '/pages/distribution/plan/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pages/distribution',
    requiresParams: false,
  },
  {
    path: '/pages/distribution/company/index',
    title: '我的公司',
    tab: false,
    subPackageRoot: 'pages/distribution',
    requiresParams: false,
  },
  {
    path: '/pages/exam/list',
    title: '考试列表',
    tab: false,
    subPackageRoot: 'pages/exam',
    requiresParams: false,
  },
  {
    path: '/pages/exam/detail',
    title: '考试详情',
    tab: false,
    subPackageRoot: 'pages/exam',
    requiresParams: true,
  },
  {
    path: '/pages/exam/answer',
    title: '考试答题',
    tab: false,
    subPackageRoot: 'pages/exam',
    requiresParams: true,
  },
  {
    path: '/pages/exam/result',
    title: '考试结果',
    tab: false,
    subPackageRoot: 'pages/exam',
    requiresParams: true,
  },
  {
    path: '/pages/study/index',
    title: '学习中心',
    tab: false,
    subPackageRoot: 'pages/study',
    requiresParams: false,
  },
  {
    path: '/pages/study/record',
    title: '学习记录',
    tab: false,
    subPackageRoot: 'pages/study',
    requiresParams: false,
  },
  {
    path: '/pages/study/plan',
    title: '学习计划',
    tab: false,
    subPackageRoot: 'pages/study',
    requiresParams: false,
  },
  {
    path: '/pages/study/rank',
    title: '学习排行',
    tab: false,
    subPackageRoot: 'pages/study',
    requiresParams: false,
  },
  {
    path: '/pages/study/my-study/index',
    title: '智汇AI',
    tab: false,
    subPackageRoot: 'pages/study',
    requiresParams: false,
  },
  {
    path: '/pages/study/publish/index',
    title: '发布学习内容',
    tab: false,
    subPackageRoot: 'pages/study',
    requiresParams: false,
  },
  {
    path: '/pages/study/video-detail/index',
    title: '视频详情',
    tab: false,
    subPackageRoot: 'pages/study',
    requiresParams: true,
  },
  {
    path: '/pages/circle/index',
    title: '圈子',
    tab: false,
    subPackageRoot: 'pages/circle',
    requiresParams: false,
  },
  {
    path: '/pages/circle/detail',
    title: '圈子详情',
    tab: false,
    subPackageRoot: 'pages/circle',
    requiresParams: true,
  },
  {
    path: '/pages/circle/create',
    title: '发布圈子',
    tab: false,
    subPackageRoot: 'pages/circle',
    requiresParams: true,
  },
  {
    path: '/pages/ask/list',
    title: '问答',
    tab: false,
    subPackageRoot: 'pages/ask',
    requiresParams: false,
  },
  {
    path: '/pages/ask/detail',
    title: '问题详情',
    tab: false,
    subPackageRoot: 'pages/ask',
    requiresParams: true,
  },
  {
    path: '/pages/ask/create',
    title: '提问',
    tab: false,
    subPackageRoot: 'pages/ask',
    requiresParams: false,
  },
  {
    path: '/pages/member/index',
    title: '我的会员',
    tab: false,
    subPackageRoot: 'pages/member',
    requiresParams: false,
  },
  {
    path: '/pages/member/benefits',
    title: '会员权益',
    tab: false,
    subPackageRoot: 'pages/member',
    requiresParams: false,
  },
  {
    path: '/pages/member/integral',
    title: '积分明细',
    tab: false,
    subPackageRoot: 'pages/member',
    requiresParams: false,
  },
  {
    path: '/pages/member/coupon',
    title: '我的优惠券',
    tab: false,
    subPackageRoot: 'pages/member',
    requiresParams: false,
  },
  {
    path: '/pages/member/coupon-list',
    title: '领券中心',
    tab: false,
    subPackageRoot: 'pages/member',
    requiresParams: false,
  },
  {
    path: '/pages/setting/index',
    title: '设置',
    tab: false,
    subPackageRoot: 'pages/setting',
    requiresParams: false,
  },
  {
    path: '/pages/setting/notification',
    title: '通知设置',
    tab: false,
    subPackageRoot: 'pages/setting',
    requiresParams: false,
  },
  {
    path: '/pages/setting/cache',
    title: '清除缓存',
    tab: false,
    subPackageRoot: 'pages/setting',
    requiresParams: false,
  },
  {
    path: '/pages/setting/language',
    title: '语言设置',
    tab: false,
    subPackageRoot: 'pages/setting',
    requiresParams: false,
  },
  {
    path: '/pages/setting/theme',
    title: '主题设置',
    tab: false,
    subPackageRoot: 'pages/setting',
    requiresParams: false,
  },
  {
    path: '/pages/setting/privacy',
    title: '隐私与权限',
    tab: false,
    subPackageRoot: 'pages/setting',
    requiresParams: false,
  },
]

// ⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠
