'use client' import * as React from 'react'
import { type UseQueryResult } from '@tanstack/react-query'
import { Loader2 } from 'lucide-react' import { cn } from '@/lib/utils'
import { Card, CardContent, Badge, Dialog, DialogContent, DialogHeader, DialogTitle,
} from '@ihui/ui-react'
import { type CompletionStatsResponse, PLAN_STATUS_LABELS, type PlanStatus } from './types' export function StudyPlanStatsDialog({ open, onOpenChange, query,
}: { open: boolean onOpenChange: (v: boolean) => void query: UseQueryResult<CompletionStatsResponse>
}) { return ( <Dialog open={open} onOpenChange={onOpenChange}> <DialogContent className="sm:max-w-lg"> <DialogHeader> <DialogTitle>完成率统计</DialogTitle> </DialogHeader> <div className="space-y-4"> {query.isFetching ? ( <div className="flex items-center justify-center text-muted-foreground"> <Loader2 className="mr-2 h-5 w-5 animate-spin" /> 加载中... </div> ) : query.data ? ( <> {/* Overall stats */} <div className="grid grid-cols-3 gap-3"> <Card> <CardContent className="flex flex-col items-center justify-center p-4"> <span className="text-2xl font-bold text-primary"> {query.data.overallRate}% </span> <span className="text-xs text-muted-foreground">总体完成率</span> </CardContent> </Card> <Card> <CardContent className="flex flex-col items-center justify-center p-4"> <span className="text-2xl font-bold text-green-600"> {query.data.totalCompleted} </span> <span className="text-xs text-muted-foreground">已完成</span> </CardContent> </Card> <Card> <CardContent className="flex flex-col items-center justify-center p-4"> <span className="text-2xl font-bold text-muted-foreground"> {query.data.totalItems} </span> <span className="text-xs text-muted-foreground">总条目</span> </CardContent> </Card> </div> {/* Per-plan breakdown */} <div className="space-y-2"> <h4 className="text-sm font-medium">各计划详情</h4> {query.data.plans.length === 0 ? ( <p className="py-2 text-center text-sm text-muted-foreground">暂无计划数据</p> ) : ( <div className="space-y-1 rounded-md border"> {query.data.plans.map((plan) => ( <div key={plan.planId} className="flex items-center justify-between px-3 py-2 text-sm" > <div className="min-w-0 flex-1"> <p className="truncate font-medium">{plan.planTitle}</p> <div className="flex items-center gap-2 text-xs text-muted-foreground"> <Badge variant="outline" className="text-[10px]"> {plan.planType === 'monthly' ? '月计划' : '周计划'} </Badge> <Badge variant="outline" className="text-[10px]"> {PLAN_STATUS_LABELS[plan.status as PlanStatus] ?? plan.status} </Badge> </div> </div> <div className="flex shrink-0 items-center gap-3"> <span className="text-xs text-muted-foreground"> {plan.completedItems}/{plan.totalItems} </span> <span className={cn( 'text-sm font-semibold', plan.completionRate >= 80 ? 'text-green-600' : plan.completionRate >= 50 ? 'text-amber-600' : 'text-muted-foreground', )} > {plan.completionRate}% </span> </div> </div> ))} </div> )} </div> </> ) : ( <p className="py-4 text-center text-sm text-muted-foreground">暂无统计数据</p> )} </div> </DialogContent> </Dialog> )
}
