# coding: utf-8

"""
    ZHS Platform

    ZHS Platform API - AI Agent Marketplace & Educational Platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zhs_api.api.remote_third_api import RemoteThirdApi


class TestRemoteThirdApi(unittest.TestCase):
    """RemoteThirdApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RemoteThirdApi()

    def tearDown(self) -> None:
        pass

    def test_third_group_list_api_v1_remote_third_group_list_get(self) -> None:
        """Test case for third_group_list_api_v1_remote_third_group_list_get

        Third Group List
        """
        pass

    def test_third_group_list_api_v1_remote_third_group_list_get_0(self) -> None:
        """Test case for third_group_list_api_v1_remote_third_group_list_get_0

        Third Group List
        """
        pass


if __name__ == '__main__':
    unittest.main()
