# coding: utf-8

"""
    ZHS Platform

    ZHS Platform API - AI Agent Marketplace & Educational Platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zhs_api.api.agent_upload_api import AgentUploadApi


class TestAgentUploadApi(unittest.TestCase):
    """AgentUploadApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentUploadApi()

    def tearDown(self) -> None:
        pass

    def test_delete_upload_api_v1_agent_upload_uid_delete(self) -> None:
        """Test case for delete_upload_api_v1_agent_upload_uid_delete

        删除上传记录
        """
        pass

    def test_delete_upload_api_v1_agent_upload_uid_delete_0(self) -> None:
        """Test case for delete_upload_api_v1_agent_upload_uid_delete_0

        删除上传记录
        """
        pass

    def test_list_uploads_api_v1_agent_upload_list_get(self) -> None:
        """Test case for list_uploads_api_v1_agent_upload_list_get

        我的上传
        """
        pass

    def test_list_uploads_api_v1_agent_upload_list_get_0(self) -> None:
        """Test case for list_uploads_api_v1_agent_upload_list_get_0

        我的上传
        """
        pass

    def test_record_upload_api_v1_agent_upload_post(self) -> None:
        """Test case for record_upload_api_v1_agent_upload_post

        记录上传
        """
        pass

    def test_record_upload_api_v1_agent_upload_post_0(self) -> None:
        """Test case for record_upload_api_v1_agent_upload_post_0

        记录上传
        """
        pass


if __name__ == '__main__':
    unittest.main()
