# coding: utf-8

"""
    ZHS Platform

    ZHS Platform API - AI Agent Marketplace & Educational Platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zhs_api.models.app_api_v1_ai_dashscope_route_image_generate_body import AppApiV1AiDashscopeRouteImageGenerateBody

class TestAppApiV1AiDashscopeRouteImageGenerateBody(unittest.TestCase):
    """AppApiV1AiDashscopeRouteImageGenerateBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppApiV1AiDashscopeRouteImageGenerateBody:
        """Test AppApiV1AiDashscopeRouteImageGenerateBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppApiV1AiDashscopeRouteImageGenerateBody`
        """
        model = AppApiV1AiDashscopeRouteImageGenerateBody()
        if include_optional:
            return AppApiV1AiDashscopeRouteImageGenerateBody(
                prompt = '',
                negative_prompt = '',
                size = '',
                n = 56,
                style = '',
                sync = True,
                zidingyican = [
                    { }
                    ]
            )
        else:
            return AppApiV1AiDashscopeRouteImageGenerateBody(
                prompt = '',
        )
        """

    def testAppApiV1AiDashscopeRouteImageGenerateBody(self):
        """Test AppApiV1AiDashscopeRouteImageGenerateBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
