# coding: utf-8

"""
    ZHS Platform

    ZHS Platform API - AI Agent Marketplace & Educational Platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zhs_api.api.fund_management_api import FundManagementApi


class TestFundManagementApi(unittest.TestCase):
    """FundManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FundManagementApi()

    def tearDown(self) -> None:
        pass

    def test_agent_transfer_notify_api_v1_finance_fund_agent_transfer_notify_post(self) -> None:
        """Test case for agent_transfer_notify_api_v1_finance_fund_agent_transfer_notify_post

        Agent Transfer Notify
        """
        pass

    def test_file_to_stream_api_v1_finance_fund_file_to_stream_post(self) -> None:
        """Test case for file_to_stream_api_v1_finance_fund_file_to_stream_post

        File To Stream
        """
        pass

    def test_fund_app_notify_api_v1_finance_fund_app_notify_post(self) -> None:
        """Test case for fund_app_notify_api_v1_finance_fund_app_notify_post

        Fund App Notify
        """
        pass

    def test_fund_notify_api_v1_finance_fund_notify_post(self) -> None:
        """Test case for fund_notify_api_v1_finance_fund_notify_post

        Fund Notify
        """
        pass

    def test_get_info_api_v1_finance_fund_get_info_get(self) -> None:
        """Test case for get_info_api_v1_finance_fund_get_info_get

        Get Info
        """
        pass

    def test_get_product_api_v1_finance_fund_get_product_get(self) -> None:
        """Test case for get_product_api_v1_finance_fund_get_product_get

        Get Product
        """
        pass

    def test_get_statistics_api_v1_finance_fund_get_statistics_get(self) -> None:
        """Test case for get_statistics_api_v1_finance_fund_get_statistics_get

        Get Statistics
        """
        pass

    def test_use_token_api_v1_finance_fund_use_token_post(self) -> None:
        """Test case for use_token_api_v1_finance_fund_use_token_post

        Use Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
