export * from './users.js'
export * from './projects.js'
export * from './files.js'
export * from './files-extra.js'
export * from './notifications.js'
export * from './billing.js'
export * from './audit.js'
export * from './chat.js'
export * from './teams.js'
export * from './rbac.js'
export * from './workflow.js'
export * from './comments.js'
export * from './promotions.js'
export * from './gamification.js'
export * from './content.js'
export * from './system.js'
export * from './social.js'
export * from './community.js'
export * from './learn.js'
export * from './exam.js'
export * from './order.js'
export * from './live.js'
export * from './member.js'
export * from './resource.js'
export * from './point.js'
export * from './usercenter.js'
export * from './schedule.js'
export * from './statistics.js'
export * from './message.js'
export * from './topic.js'
export * from './behavior.js'
export * from './visit-tracking.js'
export * from './oss.js'
export * from './setting.js'
export * from './news.js'
export * from './certificate.js'
export * from './wallet.js'
export * from './commission.js'
export * from './oauth.js'
export * from './vip.js'
export * from './captcha.js'
export * from './admin-sys.js'
export * from './edu-extended.js'
export * from './misc-extended.js'
export * from './agents-extended.js'
export * from './agent-rule.js'
export * from './misc-extended-2.js'
export * from './member-extended.js'
export * from './exam-extended.js'
export * from './learn-extended.js'
export * from './payment-callbacks.js'
export * from './agent-context.js'
export * from './identity.js'
export * from './ai-config.js'
export * from './user-learning.js'
// CLI 配置导入(cc-switch / codex++ / 各 CLI 工具)历史表
export * from './cli-provider-imports.js'
export * from './bot-sites.js'
export * from './gen-table.js'
export * from './refund-audit.js'
export * from './customer-service.js'
export * from './tenant.js'
export * from './ai-cost.js'
export * from './ai-feed.js'
export * from './ai-education.js'
export * from './ai-gc.js'
export * from './circle-extra.js'
export * from './ask-extra.js'
export * from './learn-extra-extended.js'
export * from './learn-record.js'
export * from './user-auth-info.js'
export * from './tbox-extended.js'
export * from './stock.js'
export * from './srs.js'
export * from './remote-device.js'
export * from './canary.js'
export * from './tool.js'
export * from './developer-api-keys.js'
export * from './app-version.js'
export * from './monitor.js'
export * from './webhooks.js'
export * from './trader.js'
export * from './sdks.js'
export * from './miniprogram.js'
export * from './product-identity.js'
export * from './groups.js'
export * from './security.js'
export * from './tour.js'
export * from './ai-capabilities.js'
export * from './news-crawler.js'
export * from './user-memory.js'
export * from './agent-commerce.js'
export * from './sensitive-words.js'
export * from './agreements.js'
export * from './carousels.js'
export * from './message-templates.js'
export * from './edu-full.js'
export * from './zhs-full.js'
export * from './live-extended.js'
export * from './relation-tables.js'
export * from './upload-sessions.js'
export * from './auth-identity.js'
export * from './education-platform.js'
export * from './demand-square.js'
export * from './faq.js'
export * from './zone.js'
export * from './ai-user-model-chat.js'
export * from './ai-vendor-configs.js'
export * from './knowledge-base.js'
export * from './skills.js'
export * from './user-preferences.js'
export * from './funds.js'
export * from './ai-feed-posts.js'
export * from './ai-world-items.js'
export * from './workspace-ai-tasks.js'
export * from './security-logs.js'
export * from './export-tasks.js'
export * from './content-generation.js'
export * from './mcp-servers.js'
export * from './openclaw-items.js'
export * from './site-categories.js'
export * from './analytics-events.js'
export * from './resource-likes.js'
export * from './ai-modules.js'
export * from './email-logs.js'
export * from './developer.js'
export * from './coze-chat-history.js'
export * from './agent-reviews.js'
export * from './id-mapping.js'
export * from './user-addresses.js'
export * from './service-appointments.js'
export * from './business-cards.js'
export * from './themes.js'
export * from './point-redeem-items.js'
export * from './image-gen-favorites.js'
export * from './notes.js'
export * from './knowledge-base-categories.js'
export * from './agent-tasks.js'
export * from './clawdbot.js'
export * from './llm-call-logs.js'
export * from './wechat-pay-contracts.js'
export * from './knowledge-rag.js'
// 知识图谱(2026-07-21 新增,G5 任务:LLM NER 抽取 + 关系存储 + 前端可视化)
export * from './knowledge-graph.js'
export * from './crew.js'
export * from './oauth-private-keys.js'
export * from './search-contents.js'
export * from './agent-billings.js'
// R80 补齐: D 盘 coze_zhs_py/models 2 张缺失表
// 注: video-tasks.ts / simple-bot-configs.ts 与 ai-config.ts / bot-sites.ts 重复定义
// 已删除 R80 补齐文件,保留原有 ai-config.ts / bot-sites.ts 中的定义(被更多代码依赖)
// 27 张 D 盘表补迁移（2026-07-19）
// 5 个 supplement 文件，共 17 张新表 + 10 张已在其他文件迁移（live-extended.ts 3 / learn-extended.ts 1 / learn-extra-extended.ts 1 / relation-tables.ts 5）
export * from './social-supplement.js'
export * from './live-supplement.js'
export * from './resource-download.js'
export * from './admin-extended.js'
export * from './workspace-permissions.js'
// 自媒体已发布内容记忆(2026-07-20 新增,迁移自源项目 JSON 文件)
export * from './self-media.js'
// 多平台一键发布系统(2026-07-20 新增,14 平台 + 凭证加密 + 任务调度 + 历史记录)
export * from './publish-platform.js'
// 搜索热词表(2026-07-20 补建,迁移报告 P0 缺失项)
export * from './search-hot-words.js'
// 用户自定义 AI 对话框技能(2026-07-21 新增,AI 对话框 Skill 库统一面板支撑)
export * from './user-chat-skills.js'
// 插件市场事件流(2026-07-22 新增,管理端监测插件热度 / 安装量 / 点击量)
export * from './plugin-events.js'
// D3 edu Java 14 个未迁移实体补齐(2026-07-22):
//   学校组织架构 4 表(t_school/t_clazz/t_grade/t_subject)
//   题库知识点 1 表(t_knowledge_point;其余 5 表已等价于 examQuestions/examChapters/examChapterSections/examRecords)
//   课程推荐 2 表(t_course_recommend/t_course_recommend_log)
//   课程核心三表(t_lesson/t_lesson_chapter/t_lesson_chapter_section)已等价于 learn.ts 的 lessons/lessonChapters/lessonChapterSections,无需补建
export * from './school-org-supplement.js'
export * from './question-bank-supplement.js'
export * from './course-recommend-supplement.js'
// 四层记忆 + Dream 梦境系统(2026-07-22 立,对标 OpenClaw Mem:episodic/semantic/procedural 3 表)
export * from './memory.js'
// 代码库语义索引(2026-07-22 新增,AST 切片 + pgvector 向量检索)
export * from './codebase-index.js'
// 大模型排行榜(2026-07-22 新增,参考 arena.ai,6 类模型 + Agent 智能体 + 总榜)
export * from './model-leaderboard.js'
