/**
 * API 白名单
 * 合并源项目和目标项目的白名单
 * ihui API 路径从 backend-paths 引用以保持与 COZE_PATHS 一致
 */
import { COZE_PATHS } from '@/config/backend-paths'

export const API_WHITE_LIST = [
  // 源项目的白名单
  '/login/wechat/getOpenId',
  '/resource/getHomePageResources',
  '/login/wechat/getPhoneNumber',
  '/general/remote/third/group/list',
  '/information/list',
  '/coze/agents',
  '/remote/get/true',
  COZE_PATHS.agents.list,
  '/agent/rule/search/bylink',
  '/ali/audio/sys',
  COZE_PATHS.aiModelInfo.list,
  '/resource/first/share/show',
  '/remote/agent/task/need/task',
  '/agent/use/history',
  COZE_PATHS.cache.agentCategoryDict.categories,
  '/remote/agent/category',
  '/information/dictionary',
  '/resource/getUserContext',
  // 目标项目已有的白名单
  '/auth/login',
  '/api/auth/login',
  '/auth/register',
  '/api/auth/register',
  '/auth/refresh',
  '/auth/logout',
  '/auth/verify-email',
  '/auth/reset-password',
  '/auth/forgot-password',
  // 登录相关接口（连接到192.168.1.25:8080）
  '/login/pwd/login',
  '/api/login/pwd/login',
  '/ai-program/login/pwd/login',
  '/api/ai-program/login/pwd/login',
  '/login/pwd/registerLogin',
  '/api/login/pwd/registerLogin',
  '/ai-program/login/pwd/registerLogin',
  '/api/ai-program/login/pwd/registerLogin',
  '/login/pwd/smsVerify',
  '/api/login/pwd/smsVerify',
  '/login/pwd/verify',
  '/api/login/pwd/verify',
  '/login/pwd/refreshToken',
  '/api/login/pwd/refreshToken',
  '/login/pwd/editPasswd',
  '/api/login/pwd/editPasswd',
  '/login/pwd/replace/phone',
  '/api/login/pwd/replace/phone',
  '/login/pwd/third/wx/login',
  '/api/login/pwd/third/wx/login',
  '/login/pwd/send/batch/sms',
  '/api/login/pwd/send/batch/sms',
  // AI平台登录接口（/api/ai路径）
  '/api/ai/login/pwd/smsVerify',
  '/api/ai/login/pwd/verify',
  '/api/ai/login/pwd/registerLogin',
  '/api/ai/login/pwd/login',
  '/api/ai/login/pwd/refreshToken',
  '/api/ai/login/pwd/editPasswd',
  '/api/ai/login/pwd/replace/phone',
  '/api/ai/login/wechat/getOpenId',
  '/api/ai/login/wechat/getPhoneNumber',
  '/api/ai/auth_accounts/bind',
  '/public/resources',
  '/public/agents',
  '/public/models',
  '/public/categories',
]
