import type { LeaderboardEntry } from '../types'

export const FALLBACK_LEADERBOARD_PART_2: LeaderboardEntry[] = [
  {
    id: 'fb-o9',
    modelId: 'claude-opus-4-7-thinking',
    modelName: 'Claude Opus 4.7 Thinking',
    vendor: 'Anthropic',
    category: 'overall',
    subcategory: null,
    arenaScore: 1503,
    arenaRank: 9,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 4,
    winRate: null,
    voteCount: null,
    contextWindow: '1M',
    maxOutput: '64K',
    inputPrice: '$5',
    outputPrice: '$25',
    releaseDate: '2026-07-12',
    highlight: '总榜排名第 9,Opus 4.6 升级版,推理能力进一步提升',
    capabilities: { coding: 94, math: 91, reasoning: 95, creative: 85, chinese: 89 },
    license: 'Proprietary',
    isOverall: true,
    sortOrder: 9,
  },
  // LLM 通用(3)
  {
    id: 'fb-lg1',
    modelId: 'claude-fable-5',
    modelName: 'Claude Fable 5',
    vendor: 'Anthropic',
    category: 'llm',
    subcategory: 'general',
    arenaScore: 1507,
    arenaRank: 1,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 7,
    winRate: null,
    voteCount: null,
    contextWindow: '1M',
    maxOutput: '128K',
    inputPrice: '$10',
    outputPrice: '$50',
    releaseDate: '2026-07-15',
    highlight: 'Anthropic 旗舰模型,综合能力较为全面',
    capabilities: { coding: 95, math: 90, reasoning: 94, creative: 88, chinese: 90 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 1,
  },
  {
    id: 'fb-lg2',
    modelId: 'claude-opus-4-6-thinking',
    modelName: 'Claude Opus 4.6 Thinking',
    vendor: 'Anthropic',
    category: 'llm',
    subcategory: 'general',
    arenaScore: 1504,
    arenaRank: 2,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 4,
    winRate: null,
    voteCount: null,
    contextWindow: '1M',
    maxOutput: '64K',
    inputPrice: '$5',
    outputPrice: '$25',
    releaseDate: '2026-07-10',
    highlight: '深度推理强项,数学与代码表现较为出色',
    capabilities: { coding: 93, math: 92, reasoning: 95, creative: 84, chinese: 88 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 2,
  },
  {
    id: 'fb-lg3',
    modelId: 'kimi-k3',
    modelName: 'Kimi K3',
    vendor: 'Moonshot',
    category: 'llm',
    subcategory: 'general',
    arenaScore: 1486,
    arenaRank: 9,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 11,
    winRate: null,
    voteCount: null,
    contextWindow: '1M',
    maxOutput: null,
    inputPrice: '开源',
    outputPrice: '开源',
    releaseDate: '2026-07-17',
    highlight: '月之暗面 2.8 万亿参数开源模型,国产开源代表',
    capabilities: { coding: 88, math: 85, reasoning: 87, creative: 86, chinese: 93 },
    license: '开源',
    isOverall: false,
    sortOrder: 9,
  },
  // LLM 代码(3)
  {
    id: 'fb-lc1',
    modelId: 'claude-opus-4-7-thinking#coding',
    modelName: 'Claude Opus 4.7 Thinking',
    vendor: 'Anthropic',
    category: 'llm',
    subcategory: 'coding',
    arenaScore: 1567,
    arenaRank: 1,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 5,
    winRate: null,
    voteCount: null,
    contextWindow: '1M',
    maxOutput: '64K',
    inputPrice: '$5',
    outputPrice: '$25',
    releaseDate: '2026-07-12',
    highlight: 'WebDev Arena 编程表现领先,全栈开发能力较为出色',
    capabilities: { coding: 98, math: 90, reasoning: 95, creative: 80, chinese: 85 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 11,
  },
  {
    id: 'fb-lc2',
    modelId: 'qwen3-7-max#coding',
    modelName: 'Qwen3.7 Max',
    vendor: 'Alibaba',
    category: 'llm',
    subcategory: 'coding',
    arenaScore: 1537,
    arenaRank: 7,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 7,
    winRate: null,
    voteCount: null,
    contextWindow: '1M',
    maxOutput: null,
    inputPrice: '¥2',
    outputPrice: '¥6',
    releaseDate: null,
    highlight: '阿里通义千问编程特化,国产编程表现领先',
    capabilities: { coding: 94, math: 88, reasoning: 87, creative: 78, chinese: 92 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 17,
  },
  {
    id: 'fb-lc3',
    modelId: 'glm-5-1#coding',
    modelName: 'GLM-5.1',
    vendor: 'Z.ai',
    category: 'llm',
    subcategory: 'coding',
    arenaScore: 1532,
    arenaRank: 8,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 8,
    winRate: null,
    voteCount: null,
    contextWindow: '128K',
    maxOutput: null,
    inputPrice: '¥3',
    outputPrice: '¥6',
    releaseDate: null,
    highlight: '智谱 GLM 编程版,中文代码注释较为出色',
    capabilities: { coding: 92, math: 85, reasoning: 86, creative: 76, chinese: 94 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 18,
  },
  // LLM 推理(3)
  {
    id: 'fb-lr1',
    modelId: 'claude-fable-5#reasoning',
    modelName: 'Claude Fable 5',
    vendor: 'Anthropic',
    category: 'llm',
    subcategory: 'reasoning',
    arenaScore: 1500,
    arenaRank: 1,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 8,
    winRate: null,
    voteCount: null,
    contextWindow: '1M',
    maxOutput: '128K',
    inputPrice: '$10',
    outputPrice: '$50',
    releaseDate: '2026-07-15',
    highlight: '复杂推理与多步规划能力较为出色',
    capabilities: { coding: 92, math: 93, reasoning: 96, creative: 85, chinese: 89 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 21,
  },
]
