import type { LeaderboardEntry } from '../types'

export const FALLBACK_LEADERBOARD_PART_5: LeaderboardEntry[] = [
  // 嵌入(2)
  {
    id: 'fb-em1',
    modelId: 'text-embedding-3-large',
    modelName: 'Text Embedding 3 Large',
    vendor: 'OpenAI',
    category: 'embedding',
    subcategory: null,
    arenaScore: 1450,
    arenaRank: 1,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 5,
    winRate: null,
    voteCount: null,
    contextWindow: '8K',
    maxOutput: null,
    inputPrice: null,
    outputPrice: null,
    releaseDate: null,
    highlight: 'OpenAI 旗舰嵌入,8192 维,检索精度较高',
    capabilities: { coding: 65, math: 72, reasoning: 68, creative: 60, chinese: 65 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 76,
  },
  {
    id: 'fb-em2',
    modelId: 'bge-m3',
    modelName: 'BGE-M3',
    vendor: 'BAAI',
    category: 'embedding',
    subcategory: null,
    arenaScore: 1390,
    arenaRank: 4,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 8,
    winRate: null,
    voteCount: null,
    contextWindow: null,
    maxOutput: null,
    inputPrice: null,
    outputPrice: null,
    releaseDate: null,
    highlight: '智源开源嵌入,多语言+长文本',
    capabilities: { coding: 63, math: 67, reasoning: 64, creative: 56, chinese: 72 },
    license: '开源',
    isOverall: false,
    sortOrder: 79,
  },
]
