// © 2026 IHUI AI (智汇AI) · 版权所有者: 李春川 (Li Chunchuan) · https://aizhs.top
// Provenance-watermarked. 未授权商用可被溯源追责 (Apache-2.0 须保留本声明与 NOTICE)。
// [IHUI-AI-PROVENANCE]:⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠

import type { LeaderboardEntry } from '../types'

export const FALLBACK_LEADERBOARD_PART_4: LeaderboardEntry[] = [
  // 多模态(3)
  {
    id: 'fb-mm1',
    modelId: 'claude-fable-5',
    modelName: 'Claude Fable 5',
    vendor: 'Anthropic',
    category: 'multimodal',
    subcategory: null,
    arenaScore: 1318,
    arenaRank: 1,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 9,
    winRate: null,
    voteCount: 7411,
    contextWindow: '1M',
    maxOutput: '128K',
    inputPrice: '$10',
    outputPrice: '$50',
    releaseDate: '2026-07-15',
    highlight: '视觉理解+推理双强,图表分析较为出色',
    capabilities: { coding: 90, math: 85, reasoning: 92, creative: 85, chinese: 88 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 51,
  },
  {
    id: 'fb-mm2',
    modelId: 'gemini-3-pro',
    modelName: 'Gemini 3 Pro',
    vendor: 'Google',
    category: 'multimodal',
    subcategory: null,
    arenaScore: 1289,
    arenaRank: 7,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 8,
    winRate: null,
    voteCount: 13183,
    contextWindow: '1M',
    maxOutput: '128K',
    inputPrice: '$2',
    outputPrice: '$12',
    releaseDate: '2026-07-17',
    highlight: '原生多模态,视频理解能力较为出色',
    capabilities: { coding: 86, math: 88, reasoning: 88, creative: 83, chinese: 84 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 57,
  },
  {
    id: 'fb-mm3',
    modelId: 'gpt-5-5',
    modelName: 'GPT-5.5',
    vendor: 'OpenAI',
    category: 'multimodal',
    subcategory: null,
    arenaScore: 1286,
    arenaRank: 9,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 7,
    winRate: null,
    voteCount: 17412,
    contextWindow: '1.1M',
    maxOutput: '128K',
    inputPrice: '$5',
    outputPrice: '$30',
    releaseDate: null,
    highlight: 'OpenAI 多模态旗舰,图文混合理解较为出色',
    capabilities: { coding: 87, math: 86, reasoning: 87, creative: 82, chinese: 83 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 59,
  },
  // Agent(3)
  {
    id: 'fb-ag1',
    modelId: 'claude-fable-5-high',
    modelName: 'Claude Fable 5 High',
    vendor: 'Anthropic',
    category: 'agent',
    subcategory: null,
    arenaScore: 1394,
    arenaRank: 1,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 8,
    winRate: 13.94,
    voteCount: 16059,
    contextWindow: '1M',
    maxOutput: '128K',
    inputPrice: '$10',
    outputPrice: '$50',
    releaseDate: '2026-07-15',
    highlight: 'Agent 净提升 13.94%,复杂任务规划能力较为出色',
    capabilities: { coding: 95, math: 82, reasoning: 94, creative: 78, chinese: 85 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 61,
  },
  {
    id: 'fb-ag2',
    modelId: 'gpt-5-6-sol-xhigh',
    modelName: 'GPT-5.6 Sol xHigh',
    vendor: 'OpenAI',
    category: 'agent',
    subcategory: null,
    arenaScore: 1094,
    arenaRank: 2,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 9,
    winRate: 10.94,
    voteCount: 7881,
    contextWindow: '1.05M',
    maxOutput: '128K',
    inputPrice: '$5',
    outputPrice: '$30',
    releaseDate: '2026-07-09',
    highlight: 'Agent 净提升 10.94%,代码任务自动化较为出色',
    capabilities: { coding: 93, math: 80, reasoning: 90, creative: 72, chinese: 80 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 62,
  },
  {
    id: 'fb-ag3',
    modelId: 'glm-5-2-max',
    modelName: 'GLM-5.2 Max',
    vendor: 'Z.ai',
    category: 'agent',
    subcategory: null,
    arenaScore: 624,
    arenaRank: 9,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 10,
    winRate: 6.24,
    voteCount: null,
    contextWindow: '128K',
    maxOutput: null,
    inputPrice: '¥3',
    outputPrice: '¥6',
    releaseDate: null,
    highlight: '国产 Agent 表现领先,净提升 6.24%',
    capabilities: { coding: 86, math: 75, reasoning: 85, creative: 72, chinese: 90 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 69,
  },
  // 语音(2)
  {
    id: 'fb-au1',
    modelId: 'eleven-multilingual-v2',
    modelName: 'Eleven Multilingual v2',
    vendor: 'ElevenLabs',
    category: 'audio',
    subcategory: null,
    arenaScore: 1420,
    arenaRank: 1,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 6,
    winRate: null,
    voteCount: 50000,
    contextWindow: null,
    maxOutput: null,
    inputPrice: null,
    outputPrice: null,
    releaseDate: null,
    highlight: 'ElevenLabs 旗舰,多语言语音自然度较为出色',
    capabilities: { coding: 30, math: 28, reasoning: 35, creative: 90, chinese: 60 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 71,
  },
  {
    id: 'fb-au2',
    modelId: 'minimax-voice',
    modelName: 'MiniMax Voice',
    vendor: 'MiniMax',
    category: 'audio',
    subcategory: null,
    arenaScore: 1350,
    arenaRank: 5,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 8,
    winRate: null,
    voteCount: 25000,
    contextWindow: null,
    maxOutput: null,
    inputPrice: null,
    outputPrice: null,
    releaseDate: null,
    highlight: '国产语音合成,中文拟真度较为出色',
    capabilities: { coding: 30, math: 28, reasoning: 35, creative: 85, chinese: 88 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 75,
  },
]
// ⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠
