import type { LeaderboardEntry } from '../types'

export const FALLBACK_LEADERBOARD_PART_1: LeaderboardEntry[] = [
  // 总榜(9)
  {
    id: 'fb-o1',
    modelId: 'claude-fable-5',
    modelName: 'Claude Fable 5',
    vendor: 'Anthropic',
    category: 'overall',
    subcategory: null,
    arenaScore: 1507,
    arenaRank: 1,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 7,
    winRate: null,
    voteCount: null,
    contextWindow: '1M',
    maxOutput: '128K',
    inputPrice: '$10',
    outputPrice: '$50',
    releaseDate: '2026-07-15',
    highlight: '总榜排名第 1,LLM 通用表现领先,综合能力较为全面',
    capabilities: { coding: 95, math: 90, reasoning: 94, creative: 88, chinese: 90 },
    license: 'Proprietary',
    isOverall: true,
    sortOrder: 1,
  },
  {
    id: 'fb-o2',
    modelId: 'gpt-image-2-medium',
    modelName: 'GPT Image 2 Medium',
    vendor: 'OpenAI',
    category: 'overall',
    subcategory: null,
    arenaScore: 1500,
    arenaRank: 2,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 5,
    winRate: null,
    voteCount: null,
    contextWindow: null,
    maxOutput: null,
    inputPrice: null,
    outputPrice: null,
    releaseDate: null,
    highlight: '总榜排名第 2,生图表现领先,归一化分 1500',
    capabilities: { coding: 35, math: 30, reasoning: 65, creative: 95, chinese: 70 },
    license: 'Proprietary',
    isOverall: true,
    sortOrder: 2,
  },
  {
    id: 'fb-o3',
    modelId: 'gemini-omni-flash',
    modelName: 'Gemini Omni Flash',
    vendor: 'Google',
    category: 'overall',
    subcategory: null,
    arenaScore: 1527,
    arenaRank: 3,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 13,
    winRate: null,
    voteCount: 5449,
    contextWindow: null,
    maxOutput: null,
    inputPrice: null,
    outputPrice: null,
    releaseDate: null,
    highlight: '总榜排名第 3,视频生成表现领先,运动一致性较为出色',
    capabilities: { coding: 35, math: 30, reasoning: 60, creative: 94, chinese: 65 },
    license: 'Proprietary',
    isOverall: true,
    sortOrder: 3,
  },
  {
    id: 'fb-o4',
    modelId: 'claude-fable-5-high',
    modelName: 'Claude Fable 5 High',
    vendor: 'Anthropic',
    category: 'overall',
    subcategory: null,
    arenaScore: 1394,
    arenaRank: 4,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 8,
    winRate: 13.94,
    voteCount: 16059,
    contextWindow: '1M',
    maxOutput: '128K',
    inputPrice: '$10',
    outputPrice: '$50',
    releaseDate: '2026-07-15',
    highlight: '总榜排名第 4,Agent 表现领先,净提升 13.94%',
    capabilities: { coding: 95, math: 82, reasoning: 94, creative: 78, chinese: 85 },
    license: 'Proprietary',
    isOverall: true,
    sortOrder: 4,
  },
  {
    id: 'fb-o5',
    modelId: 'claude-opus-4-6-thinking',
    modelName: 'Claude Opus 4.6 Thinking',
    vendor: 'Anthropic',
    category: 'overall',
    subcategory: null,
    arenaScore: 1504,
    arenaRank: 5,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 4,
    winRate: null,
    voteCount: null,
    contextWindow: '1M',
    maxOutput: '64K',
    inputPrice: '$5',
    outputPrice: '$25',
    releaseDate: '2026-07-10',
    highlight: '总榜排名第 5,LLM 通用表现稳健,深度推理强项',
    capabilities: { coding: 93, math: 92, reasoning: 95, creative: 84, chinese: 88 },
    license: 'Proprietary',
    isOverall: true,
    sortOrder: 5,
  },
  {
    id: 'fb-o6',
    modelId: 'dreamina-seedance-2-0-720p',
    modelName: 'Dreamina Seedance 2.0 720p',
    vendor: 'Bytedance',
    category: 'overall',
    subcategory: null,
    arenaScore: 1482,
    arenaRank: 6,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 10,
    winRate: null,
    voteCount: 41953,
    contextWindow: null,
    maxOutput: null,
    inputPrice: null,
    outputPrice: null,
    releaseDate: null,
    highlight: '总榜排名第 6,视频表现稳健,国产视频表现领先',
    capabilities: { coding: 32, math: 28, reasoning: 58, creative: 92, chinese: 75 },
    license: 'Proprietary',
    isOverall: true,
    sortOrder: 6,
  },
  {
    id: 'fb-o7',
    modelId: 'eleven-multilingual-v2',
    modelName: 'Eleven Multilingual v2',
    vendor: 'ElevenLabs',
    category: 'overall',
    subcategory: null,
    arenaScore: 1420,
    arenaRank: 7,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 6,
    winRate: null,
    voteCount: 50000,
    contextWindow: null,
    maxOutput: null,
    inputPrice: null,
    outputPrice: null,
    releaseDate: null,
    highlight: '总榜排名第 7,语音表现领先,多语言自然度较为出色',
    capabilities: { coding: 30, math: 28, reasoning: 35, creative: 90, chinese: 60 },
    license: 'Proprietary',
    isOverall: true,
    sortOrder: 7,
  },
  {
    id: 'fb-o8',
    modelId: 'text-embedding-3-large',
    modelName: 'Text Embedding 3 Large',
    vendor: 'OpenAI',
    category: 'overall',
    subcategory: null,
    arenaScore: 1450,
    arenaRank: 8,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 5,
    winRate: null,
    voteCount: null,
    contextWindow: '8K',
    maxOutput: null,
    inputPrice: null,
    outputPrice: null,
    releaseDate: null,
    highlight: '总榜排名第 8,嵌入表现领先,8192 维检索精度较高',
    capabilities: { coding: 65, math: 72, reasoning: 68, creative: 60, chinese: 65 },
    license: 'Proprietary',
    isOverall: true,
    sortOrder: 8,
  },
]
