import type { LeaderboardEntry } from '../types'

export const FALLBACK_LEADERBOARD_PART_3: LeaderboardEntry[] = [
  {
    id: 'fb-lr2',
    modelId: 'kimi-k3#reasoning',
    modelName: 'Kimi K3',
    vendor: 'Moonshot',
    category: 'llm',
    subcategory: 'reasoning',
    arenaScore: 1478,
    arenaRank: 9,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 12,
    winRate: null,
    voteCount: null,
    contextWindow: '1M',
    maxOutput: null,
    inputPrice: '开源',
    outputPrice: '开源',
    releaseDate: '2026-07-17',
    highlight: '国产开源推理旗舰,中文推理较为出色',
    capabilities: { coding: 86, math: 87, reasoning: 89, creative: 84, chinese: 92 },
    license: '开源',
    isOverall: false,
    sortOrder: 29,
  },
  {
    id: 'fb-lr3',
    modelId: 'gpt-5-6-sol-xhigh#reasoning',
    modelName: 'GPT-5.6 Sol xHigh',
    vendor: 'OpenAI',
    category: 'llm',
    subcategory: 'reasoning',
    arenaScore: 1478,
    arenaRank: 10,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 10,
    winRate: null,
    voteCount: null,
    contextWindow: '1.05M',
    maxOutput: '128K',
    inputPrice: '$5',
    outputPrice: '$30',
    releaseDate: '2026-07-09',
    highlight: 'OpenAI 推理模式,数学竞赛级表现',
    capabilities: { coding: 90, math: 90, reasoning: 91, creative: 81, chinese: 82 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 30,
  },
  // 生图(3)
  {
    id: 'fb-im1',
    modelId: 'gpt-image-2-medium',
    modelName: 'GPT Image 2 Medium',
    vendor: 'OpenAI',
    category: 'image',
    subcategory: null,
    arenaScore: 1385,
    arenaRank: 1,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 5,
    winRate: null,
    voteCount: null,
    contextWindow: null,
    maxOutput: null,
    inputPrice: null,
    outputPrice: null,
    releaseDate: null,
    highlight: 'OpenAI 旗舰生图,细节还原与文字渲染较为出色',
    capabilities: { coding: 35, math: 30, reasoning: 65, creative: 95, chinese: 70 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 31,
  },
  {
    id: 'fb-im2',
    modelId: 'reve-2-1',
    modelName: 'Reve 2.1',
    vendor: 'Reve',
    category: 'image',
    subcategory: null,
    arenaScore: 1302,
    arenaRank: 2,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 12,
    winRate: null,
    voteCount: null,
    contextWindow: null,
    maxOutput: null,
    inputPrice: null,
    outputPrice: null,
    releaseDate: null,
    highlight: '新兴生图黑马,风格化表现较为出色',
    capabilities: { coding: 32, math: 28, reasoning: 62, creative: 92, chinese: 68 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 32,
  },
  {
    id: 'fb-im3',
    modelId: 'muse-image',
    modelName: 'Muse Image',
    vendor: 'Meta',
    category: 'image',
    subcategory: null,
    arenaScore: 1280,
    arenaRank: 3,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 8,
    winRate: null,
    voteCount: null,
    contextWindow: null,
    maxOutput: null,
    inputPrice: null,
    outputPrice: null,
    releaseDate: null,
    highlight: 'Meta 开源生图,编辑能力较为灵活',
    capabilities: { coding: 34, math: 29, reasoning: 63, creative: 90, chinese: 66 },
    license: '开源',
    isOverall: false,
    sortOrder: 33,
  },
  // 视频(3)
  {
    id: 'fb-vi1',
    modelId: 'gemini-omni-flash',
    modelName: 'Gemini Omni Flash',
    vendor: 'Google',
    category: 'video',
    subcategory: null,
    arenaScore: 1527,
    arenaRank: 1,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 13,
    winRate: null,
    voteCount: 5449,
    contextWindow: null,
    maxOutput: null,
    inputPrice: null,
    outputPrice: null,
    releaseDate: null,
    highlight: 'Google 全能视频生成,运动一致性较为出色',
    capabilities: { coding: 35, math: 30, reasoning: 60, creative: 94, chinese: 65 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 41,
  },
  {
    id: 'fb-vi2',
    modelId: 'dreamina-seedance-2-0-720p',
    modelName: 'Dreamina Seedance 2.0 720p',
    vendor: 'Bytedance',
    category: 'video',
    subcategory: null,
    arenaScore: 1482,
    arenaRank: 2,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 10,
    winRate: null,
    voteCount: 41953,
    contextWindow: null,
    maxOutput: null,
    inputPrice: null,
    outputPrice: null,
    releaseDate: null,
    highlight: '字节梦境 2.0,国产视频表现领先,720p 画质',
    capabilities: { coding: 32, math: 28, reasoning: 58, creative: 92, chinese: 75 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 42,
  },
  {
    id: 'fb-vi3',
    modelId: 'sora-2-pro',
    modelName: 'Sora 2 Pro',
    vendor: 'OpenAI',
    category: 'video',
    subcategory: null,
    arenaScore: 1366,
    arenaRank: 5,
    rankDelta: null,
    rankSpreadLow: null,
    rankSpreadHigh: null,
    scoreCi: 8,
    winRate: null,
    voteCount: 39773,
    contextWindow: null,
    maxOutput: null,
    inputPrice: null,
    outputPrice: null,
    releaseDate: null,
    highlight: 'OpenAI 视频旗舰,物理模拟较为逼真',
    capabilities: { coding: 36, math: 32, reasoning: 62, creative: 93, chinese: 66 },
    license: 'Proprietary',
    isOverall: false,
    sortOrder: 45,
  },
]
