/* tslint:disable */
/* eslint-disable */
/**
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type RuleParamCreate,
    RuleParamCreateFromJSON,
    RuleParamCreateToJSON,
} from '../models/RuleParamCreate';
import {
    type RuleParamUpdate,
    RuleParamUpdateFromJSON,
    RuleParamUpdateToJSON,
} from '../models/RuleParamUpdate';

export interface CreateRuleParamApiV1PostRequest {
    ruleParamCreate: RuleParamCreate;
}

export interface DeleteRuleParamsApiV1ItemIdsDeleteRequest {
    itemIds: string;
}

export interface GetRuleParamApiV1ItemIdGetRequest {
    itemId: number;
}

export interface ListRuleParamsApiV1ListGetRequest {
    page?: number;
    limit?: number;
    ruleId?: number | null;
}

export interface UpdateRuleParamApiV1PutRequest {
    ruleParamUpdate: RuleParamUpdate;
}

/**
 * 
 */
export class AgentRuleParamsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createRuleParamApiV1Post without sending the request
     */
    async createRuleParamApiV1PostRequestOpts(requestParameters: CreateRuleParamApiV1PostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ruleParamCreate'] == null) {
            throw new runtime.RequiredError(
                'ruleParamCreate',
                'Required parameter "ruleParamCreate" was null or undefined when calling createRuleParamApiV1Post().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RuleParamCreateToJSON(requestParameters['ruleParamCreate']),
        };
    }

    /**
     * Create rule param
     */
    async createRuleParamApiV1PostRaw(requestParameters: CreateRuleParamApiV1PostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.createRuleParamApiV1PostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create rule param
     */
    async createRuleParamApiV1Post(requestParameters: CreateRuleParamApiV1PostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createRuleParamApiV1PostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteRuleParamsApiV1ItemIdsDelete without sending the request
     */
    async deleteRuleParamsApiV1ItemIdsDeleteRequestOpts(requestParameters: DeleteRuleParamsApiV1ItemIdsDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemIds'] == null) {
            throw new runtime.RequiredError(
                'itemIds',
                'Required parameter "itemIds" was null or undefined when calling deleteRuleParamsApiV1ItemIdsDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/{item_ids}`;
        urlPath = urlPath.replace('{item_ids}', encodeURIComponent(String(requestParameters['itemIds'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete rule params
     */
    async deleteRuleParamsApiV1ItemIdsDeleteRaw(requestParameters: DeleteRuleParamsApiV1ItemIdsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.deleteRuleParamsApiV1ItemIdsDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete rule params
     */
    async deleteRuleParamsApiV1ItemIdsDelete(requestParameters: DeleteRuleParamsApiV1ItemIdsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteRuleParamsApiV1ItemIdsDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRuleParamApiV1ItemIdGet without sending the request
     */
    async getRuleParamApiV1ItemIdGetRequestOpts(requestParameters: GetRuleParamApiV1ItemIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling getRuleParamApiV1ItemIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get rule param detail
     */
    async getRuleParamApiV1ItemIdGetRaw(requestParameters: GetRuleParamApiV1ItemIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getRuleParamApiV1ItemIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get rule param detail
     */
    async getRuleParamApiV1ItemIdGet(requestParameters: GetRuleParamApiV1ItemIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getRuleParamApiV1ItemIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRuleParamsApiV1ListGet without sending the request
     */
    async listRuleParamsApiV1ListGetRequestOpts(requestParameters: ListRuleParamsApiV1ListGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['ruleId'] != null) {
            queryParameters['rule_id'] = requestParameters['ruleId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/list`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List rule params
     */
    async listRuleParamsApiV1ListGetRaw(requestParameters: ListRuleParamsApiV1ListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.listRuleParamsApiV1ListGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List rule params
     */
    async listRuleParamsApiV1ListGet(requestParameters: ListRuleParamsApiV1ListGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listRuleParamsApiV1ListGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateRuleParamApiV1Put without sending the request
     */
    async updateRuleParamApiV1PutRequestOpts(requestParameters: UpdateRuleParamApiV1PutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ruleParamUpdate'] == null) {
            throw new runtime.RequiredError(
                'ruleParamUpdate',
                'Required parameter "ruleParamUpdate" was null or undefined when calling updateRuleParamApiV1Put().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RuleParamUpdateToJSON(requestParameters['ruleParamUpdate']),
        };
    }

    /**
     * Update rule param
     */
    async updateRuleParamApiV1PutRaw(requestParameters: UpdateRuleParamApiV1PutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.updateRuleParamApiV1PutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update rule param
     */
    async updateRuleParamApiV1Put(requestParameters: UpdateRuleParamApiV1PutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateRuleParamApiV1PutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
