/* tslint:disable */
/* eslint-disable */
/**
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AppApiV1AiDashscopeRouteImageGenerateBody,
    AppApiV1AiDashscopeRouteImageGenerateBodyFromJSON,
    AppApiV1AiDashscopeRouteImageGenerateBodyToJSON,
} from '../models/AppApiV1AiDashscopeRouteImageGenerateBody';
import {
    type AudioRecognizeRequest,
    AudioRecognizeRequestFromJSON,
    AudioRecognizeRequestToJSON,
} from '../models/AudioRecognizeRequest';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type ImageEditBody,
    ImageEditBodyFromJSON,
    ImageEditBodyToJSON,
} from '../models/ImageEditBody';
import {
    type ImageToImageBody,
    ImageToImageBodyFromJSON,
    ImageToImageBodyToJSON,
} from '../models/ImageToImageBody';
import {
    type SimpleEditBody,
    SimpleEditBodyFromJSON,
    SimpleEditBodyToJSON,
} from '../models/SimpleEditBody';
import {
    type VideoSynthesisRequest,
    VideoSynthesisRequestFromJSON,
    VideoSynthesisRequestToJSON,
} from '../models/VideoSynthesisRequest';
import {
    type VisionChatRequest,
    VisionChatRequestFromJSON,
    VisionChatRequestToJSON,
} from '../models/VisionChatRequest';

export interface AudioRecognizeApiV1AiDashscopeAudioRecognizePostRequest {
    audioRecognizeRequest: AudioRecognizeRequest;
}

export interface DashscopeChatApiV1AiDashscopeChatPostRequest {
    message: string;
    model?: string;
}

export interface DashscopeStreamApiV1AiDashscopeChatStreamPostRequest {
    message: string;
    model?: string;
}

export interface ImageEditApiV1AiDashscopeImageEditPostRequest {
    imageEditBody: ImageEditBody;
}

export interface ImageEditSimpleApiV1AiDashscopeImageEditSimplePostRequest {
    simpleEditBody: SimpleEditBody;
}

export interface ImageGenerateApiV1AiDashscopeImageGenerateModelPostRequest {
    model: string;
    appApiV1AiDashscopeRouteImageGenerateBody: AppApiV1AiDashscopeRouteImageGenerateBody;
}

export interface ImageTaskStatusApiV1AiDashscopeImageTaskTaskIdGetRequest {
    taskId: string;
}

export interface ImageToImageApiV1AiDashscopeImageToImagePostRequest {
    imageToImageBody: ImageToImageBody;
}

export interface VideoSynthesisApiV1AiDashscopeVideoSynthesisPostRequest {
    videoSynthesisRequest: VideoSynthesisRequest;
}

export interface VideoTaskStatusApiV1AiDashscopeVideoTasksTaskIdGetRequest {
    taskId: string;
}

export interface VisionChatApiV1AiDashscopeVisionChatPostRequest {
    visionChatRequest: VisionChatRequest;
}

/**
 * 
 */
export class AIDashScopeApi extends runtime.BaseAPI {

    /**
     * Creates request options for audioModelsApiV1AiDashscopeAudioModelsGet without sending the request
     */
    async audioModelsApiV1AiDashscopeAudioModelsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/ai/dashscope/audio/models`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return the list of supported audio recognition models.
     * List supported ASR models
     */
    async audioModelsApiV1AiDashscopeAudioModelsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.audioModelsApiV1AiDashscopeAudioModelsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Return the list of supported audio recognition models.
     * List supported ASR models
     */
    async audioModelsApiV1AiDashscopeAudioModelsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.audioModelsApiV1AiDashscopeAudioModelsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for audioRecognizeApiV1AiDashscopeAudioRecognizePost without sending the request
     */
    async audioRecognizeApiV1AiDashscopeAudioRecognizePostRequestOpts(requestParameters: AudioRecognizeApiV1AiDashscopeAudioRecognizePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['audioRecognizeRequest'] == null) {
            throw new runtime.RequiredError(
                'audioRecognizeRequest',
                'Required parameter "audioRecognizeRequest" was null or undefined when calling audioRecognizeApiV1AiDashscopeAudioRecognizePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/ai/dashscope/audio/recognize`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AudioRecognizeRequestToJSON(requestParameters['audioRecognizeRequest']),
        };
    }

    /**
     * Recognise speech in audio via DashScope MultiModalConversation ASR.  Uses the DashScope multi-modal-generation HTTP endpoint. Includes token balance check, cost deduction, and conversation recording.
     * Audio speech recognition
     */
    async audioRecognizeApiV1AiDashscopeAudioRecognizePostRaw(requestParameters: AudioRecognizeApiV1AiDashscopeAudioRecognizePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.audioRecognizeApiV1AiDashscopeAudioRecognizePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Recognise speech in audio via DashScope MultiModalConversation ASR.  Uses the DashScope multi-modal-generation HTTP endpoint. Includes token balance check, cost deduction, and conversation recording.
     * Audio speech recognition
     */
    async audioRecognizeApiV1AiDashscopeAudioRecognizePost(requestParameters: AudioRecognizeApiV1AiDashscopeAudioRecognizePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.audioRecognizeApiV1AiDashscopeAudioRecognizePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for dashscopeChatApiV1AiDashscopeChatPost without sending the request
     */
    async dashscopeChatApiV1AiDashscopeChatPostRequestOpts(requestParameters: DashscopeChatApiV1AiDashscopeChatPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['message'] == null) {
            throw new runtime.RequiredError(
                'message',
                'Required parameter "message" was null or undefined when calling dashscopeChatApiV1AiDashscopeChatPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['message'] != null) {
            queryParameters['message'] = requestParameters['message'];
        }

        if (requestParameters['model'] != null) {
            queryParameters['model'] = requestParameters['model'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/ai/dashscope/chat`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * DashScope chat completion
     */
    async dashscopeChatApiV1AiDashscopeChatPostRaw(requestParameters: DashscopeChatApiV1AiDashscopeChatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.dashscopeChatApiV1AiDashscopeChatPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * DashScope chat completion
     */
    async dashscopeChatApiV1AiDashscopeChatPost(requestParameters: DashscopeChatApiV1AiDashscopeChatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.dashscopeChatApiV1AiDashscopeChatPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for dashscopeStreamApiV1AiDashscopeChatStreamPost without sending the request
     */
    async dashscopeStreamApiV1AiDashscopeChatStreamPostRequestOpts(requestParameters: DashscopeStreamApiV1AiDashscopeChatStreamPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['message'] == null) {
            throw new runtime.RequiredError(
                'message',
                'Required parameter "message" was null or undefined when calling dashscopeStreamApiV1AiDashscopeChatStreamPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['message'] != null) {
            queryParameters['message'] = requestParameters['message'];
        }

        if (requestParameters['model'] != null) {
            queryParameters['model'] = requestParameters['model'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/ai/dashscope/chat/stream`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * DashScope streaming chat
     */
    async dashscopeStreamApiV1AiDashscopeChatStreamPostRaw(requestParameters: DashscopeStreamApiV1AiDashscopeChatStreamPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.dashscopeStreamApiV1AiDashscopeChatStreamPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * DashScope streaming chat
     */
    async dashscopeStreamApiV1AiDashscopeChatStreamPost(requestParameters: DashscopeStreamApiV1AiDashscopeChatStreamPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.dashscopeStreamApiV1AiDashscopeChatStreamPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for imageEditApiV1AiDashscopeImageEditPost without sending the request
     */
    async imageEditApiV1AiDashscopeImageEditPostRequestOpts(requestParameters: ImageEditApiV1AiDashscopeImageEditPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['imageEditBody'] == null) {
            throw new runtime.RequiredError(
                'imageEditBody',
                'Required parameter "imageEditBody" was null or undefined when calling imageEditApiV1AiDashscopeImageEditPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/ai/dashscope/image/edit`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImageEditBodyToJSON(requestParameters['imageEditBody']),
        };
    }

    /**
     * Edit an image using a mask and prompt.  Returns task_id for async models.  For synchronous models (e.g. wan2.1-image-edit) the result image URL is returned directly.
     * DashScope image editing (standard)
     */
    async imageEditApiV1AiDashscopeImageEditPostRaw(requestParameters: ImageEditApiV1AiDashscopeImageEditPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.imageEditApiV1AiDashscopeImageEditPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Edit an image using a mask and prompt.  Returns task_id for async models.  For synchronous models (e.g. wan2.1-image-edit) the result image URL is returned directly.
     * DashScope image editing (standard)
     */
    async imageEditApiV1AiDashscopeImageEditPost(requestParameters: ImageEditApiV1AiDashscopeImageEditPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.imageEditApiV1AiDashscopeImageEditPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for imageEditSimpleApiV1AiDashscopeImageEditSimplePost without sending the request
     */
    async imageEditSimpleApiV1AiDashscopeImageEditSimplePostRequestOpts(requestParameters: ImageEditSimpleApiV1AiDashscopeImageEditSimplePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['simpleEditBody'] == null) {
            throw new runtime.RequiredError(
                'simpleEditBody',
                'Required parameter "simpleEditBody" was null or undefined when calling imageEditSimpleApiV1AiDashscopeImageEditSimplePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/ai/dashscope/image/edit/simple`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SimpleEditBodyToJSON(requestParameters['simpleEditBody']),
        };
    }

    /**
     * Simple image editing using qwen-image-edit model (background removal, style transfer, etc.).
     * Simple DashScope image editing
     */
    async imageEditSimpleApiV1AiDashscopeImageEditSimplePostRaw(requestParameters: ImageEditSimpleApiV1AiDashscopeImageEditSimplePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.imageEditSimpleApiV1AiDashscopeImageEditSimplePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Simple image editing using qwen-image-edit model (background removal, style transfer, etc.).
     * Simple DashScope image editing
     */
    async imageEditSimpleApiV1AiDashscopeImageEditSimplePost(requestParameters: ImageEditSimpleApiV1AiDashscopeImageEditSimplePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.imageEditSimpleApiV1AiDashscopeImageEditSimplePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for imageGenerateApiV1AiDashscopeImageGenerateModelPost without sending the request
     */
    async imageGenerateApiV1AiDashscopeImageGenerateModelPostRequestOpts(requestParameters: ImageGenerateApiV1AiDashscopeImageGenerateModelPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['model'] == null) {
            throw new runtime.RequiredError(
                'model',
                'Required parameter "model" was null or undefined when calling imageGenerateApiV1AiDashscopeImageGenerateModelPost().'
            );
        }

        if (requestParameters['appApiV1AiDashscopeRouteImageGenerateBody'] == null) {
            throw new runtime.RequiredError(
                'appApiV1AiDashscopeRouteImageGenerateBody',
                'Required parameter "appApiV1AiDashscopeRouteImageGenerateBody" was null or undefined when calling imageGenerateApiV1AiDashscopeImageGenerateModelPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/ai/dashscope/image/generate/{model}`;
        urlPath = urlPath.replace('{model}', encodeURIComponent(String(requestParameters['model'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AppApiV1AiDashscopeRouteImageGenerateBodyToJSON(requestParameters['appApiV1AiDashscopeRouteImageGenerateBody']),
        };
    }

    /**
     * Submit an async text-to-image task.  When *sync=false* (default) only ``task_id`` is returned; poll with ``GET /image/task/{task_id}``. When *sync=true* the endpoint polls until the task finishes and returns the image URL(s) directly.
     * DashScope image generation
     */
    async imageGenerateApiV1AiDashscopeImageGenerateModelPostRaw(requestParameters: ImageGenerateApiV1AiDashscopeImageGenerateModelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.imageGenerateApiV1AiDashscopeImageGenerateModelPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Submit an async text-to-image task.  When *sync=false* (default) only ``task_id`` is returned; poll with ``GET /image/task/{task_id}``. When *sync=true* the endpoint polls until the task finishes and returns the image URL(s) directly.
     * DashScope image generation
     */
    async imageGenerateApiV1AiDashscopeImageGenerateModelPost(requestParameters: ImageGenerateApiV1AiDashscopeImageGenerateModelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.imageGenerateApiV1AiDashscopeImageGenerateModelPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for imageTaskStatusApiV1AiDashscopeImageTaskTaskIdGet without sending the request
     */
    async imageTaskStatusApiV1AiDashscopeImageTaskTaskIdGetRequestOpts(requestParameters: ImageTaskStatusApiV1AiDashscopeImageTaskTaskIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling imageTaskStatusApiV1AiDashscopeImageTaskTaskIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/ai/dashscope/image/task/{task_id}`;
        urlPath = urlPath.replace('{task_id}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Poll a DashScope async task; returns status and image URLs when SUCCEEDED.
     * Query image generation task status
     */
    async imageTaskStatusApiV1AiDashscopeImageTaskTaskIdGetRaw(requestParameters: ImageTaskStatusApiV1AiDashscopeImageTaskTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.imageTaskStatusApiV1AiDashscopeImageTaskTaskIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Poll a DashScope async task; returns status and image URLs when SUCCEEDED.
     * Query image generation task status
     */
    async imageTaskStatusApiV1AiDashscopeImageTaskTaskIdGet(requestParameters: ImageTaskStatusApiV1AiDashscopeImageTaskTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.imageTaskStatusApiV1AiDashscopeImageTaskTaskIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for imageToImageApiV1AiDashscopeImageToImagePost without sending the request
     */
    async imageToImageApiV1AiDashscopeImageToImagePostRequestOpts(requestParameters: ImageToImageApiV1AiDashscopeImageToImagePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['imageToImageBody'] == null) {
            throw new runtime.RequiredError(
                'imageToImageBody',
                'Required parameter "imageToImageBody" was null or undefined when calling imageToImageApiV1AiDashscopeImageToImagePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/ai/dashscope/image-to-image`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImageToImageBodyToJSON(requestParameters['imageToImageBody']),
        };
    }

    /**
     * Transform an image guided by a text prompt. Returns task_id for async models.
     * DashScope image-to-image
     */
    async imageToImageApiV1AiDashscopeImageToImagePostRaw(requestParameters: ImageToImageApiV1AiDashscopeImageToImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.imageToImageApiV1AiDashscopeImageToImagePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Transform an image guided by a text prompt. Returns task_id for async models.
     * DashScope image-to-image
     */
    async imageToImageApiV1AiDashscopeImageToImagePost(requestParameters: ImageToImageApiV1AiDashscopeImageToImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.imageToImageApiV1AiDashscopeImageToImagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videoSynthesisApiV1AiDashscopeVideoSynthesisPost without sending the request
     */
    async videoSynthesisApiV1AiDashscopeVideoSynthesisPostRequestOpts(requestParameters: VideoSynthesisApiV1AiDashscopeVideoSynthesisPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoSynthesisRequest'] == null) {
            throw new runtime.RequiredError(
                'videoSynthesisRequest',
                'Required parameter "videoSynthesisRequest" was null or undefined when calling videoSynthesisApiV1AiDashscopeVideoSynthesisPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/ai/dashscope/video/synthesis`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VideoSynthesisRequestToJSON(requestParameters['videoSynthesisRequest']),
        };
    }

    /**
     * Submit an async video generation task to DashScope.  Uses the ``video_generation`` HTTP endpoint with ``X-DashScope-Async``. Returns a ``task_id``; poll with ``GET /video/tasks/{task_id}``.
     * Submit video synthesis task
     */
    async videoSynthesisApiV1AiDashscopeVideoSynthesisPostRaw(requestParameters: VideoSynthesisApiV1AiDashscopeVideoSynthesisPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.videoSynthesisApiV1AiDashscopeVideoSynthesisPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Submit an async video generation task to DashScope.  Uses the ``video_generation`` HTTP endpoint with ``X-DashScope-Async``. Returns a ``task_id``; poll with ``GET /video/tasks/{task_id}``.
     * Submit video synthesis task
     */
    async videoSynthesisApiV1AiDashscopeVideoSynthesisPost(requestParameters: VideoSynthesisApiV1AiDashscopeVideoSynthesisPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.videoSynthesisApiV1AiDashscopeVideoSynthesisPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videoTaskStatusApiV1AiDashscopeVideoTasksTaskIdGet without sending the request
     */
    async videoTaskStatusApiV1AiDashscopeVideoTasksTaskIdGetRequestOpts(requestParameters: VideoTaskStatusApiV1AiDashscopeVideoTasksTaskIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling videoTaskStatusApiV1AiDashscopeVideoTasksTaskIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/ai/dashscope/video/tasks/{task_id}`;
        urlPath = urlPath.replace('{task_id}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Query the status / result of an async video synthesis task.
     * Query video synthesis task status
     */
    async videoTaskStatusApiV1AiDashscopeVideoTasksTaskIdGetRaw(requestParameters: VideoTaskStatusApiV1AiDashscopeVideoTasksTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.videoTaskStatusApiV1AiDashscopeVideoTasksTaskIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Query the status / result of an async video synthesis task.
     * Query video synthesis task status
     */
    async videoTaskStatusApiV1AiDashscopeVideoTasksTaskIdGet(requestParameters: VideoTaskStatusApiV1AiDashscopeVideoTasksTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.videoTaskStatusApiV1AiDashscopeVideoTasksTaskIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for visionChatApiV1AiDashscopeVisionChatPost without sending the request
     */
    async visionChatApiV1AiDashscopeVisionChatPostRequestOpts(requestParameters: VisionChatApiV1AiDashscopeVisionChatPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['visionChatRequest'] == null) {
            throw new runtime.RequiredError(
                'visionChatRequest',
                'Required parameter "visionChatRequest" was null or undefined when calling visionChatApiV1AiDashscopeVisionChatPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/ai/dashscope/vision/chat`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VisionChatRequestToJSON(requestParameters['visionChatRequest']),
        };
    }

    /**
     * Chat with images + text via DashScope MultiModalConversation.  Supports models like ``qwen-vl-plus``, ``qwen-vl-max``, ``qwen-vl-plus-latest``.
     * Vision multi-modal chat
     */
    async visionChatApiV1AiDashscopeVisionChatPostRaw(requestParameters: VisionChatApiV1AiDashscopeVisionChatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.visionChatApiV1AiDashscopeVisionChatPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Chat with images + text via DashScope MultiModalConversation.  Supports models like ``qwen-vl-plus``, ``qwen-vl-max``, ``qwen-vl-plus-latest``.
     * Vision multi-modal chat
     */
    async visionChatApiV1AiDashscopeVisionChatPost(requestParameters: VisionChatApiV1AiDashscopeVisionChatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.visionChatApiV1AiDashscopeVisionChatPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
