/* tslint:disable */
/* eslint-disable */
/**
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface DeepseekChatApiV1ChatChatPostRequest {
    message: string;
    model?: string;
}

export interface DeepseekChatStreamApiV1ChatChatStreamPostRequest {
    message: string;
    model?: string;
}

/**
 * 
 */
export class DeepSeekChatApi extends runtime.BaseAPI {

    /**
     * Creates request options for deepseekChatApiV1ChatChatPost without sending the request
     */
    async deepseekChatApiV1ChatChatPostRequestOpts(requestParameters: DeepseekChatApiV1ChatChatPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['message'] == null) {
            throw new runtime.RequiredError(
                'message',
                'Required parameter "message" was null or undefined when calling deepseekChatApiV1ChatChatPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['model'] != null) {
            queryParameters['model'] = requestParameters['model'];
        }

        if (requestParameters['message'] != null) {
            queryParameters['message'] = requestParameters['message'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/chat/chat`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * DeepSeek 同步聊天
     */
    async deepseekChatApiV1ChatChatPostRaw(requestParameters: DeepseekChatApiV1ChatChatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.deepseekChatApiV1ChatChatPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * DeepSeek 同步聊天
     */
    async deepseekChatApiV1ChatChatPost(requestParameters: DeepseekChatApiV1ChatChatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deepseekChatApiV1ChatChatPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deepseekChatStreamApiV1ChatChatStreamPost without sending the request
     */
    async deepseekChatStreamApiV1ChatChatStreamPostRequestOpts(requestParameters: DeepseekChatStreamApiV1ChatChatStreamPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['message'] == null) {
            throw new runtime.RequiredError(
                'message',
                'Required parameter "message" was null or undefined when calling deepseekChatStreamApiV1ChatChatStreamPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['model'] != null) {
            queryParameters['model'] = requestParameters['model'];
        }

        if (requestParameters['message'] != null) {
            queryParameters['message'] = requestParameters['message'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/chat/chat/stream`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * DeepSeek 流式聊天（SSE）
     */
    async deepseekChatStreamApiV1ChatChatStreamPostRaw(requestParameters: DeepseekChatStreamApiV1ChatChatStreamPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.deepseekChatStreamApiV1ChatChatStreamPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * DeepSeek 流式聊天（SSE）
     */
    async deepseekChatStreamApiV1ChatChatStreamPost(requestParameters: DeepseekChatStreamApiV1ChatChatStreamPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deepseekChatStreamApiV1ChatChatStreamPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
