/* tslint:disable */
/* eslint-disable */
/**
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface AddContextApiV1UserAgentContextPostRequest {
    agentId: string;
    sessionId: string;
    role: string;
    content: string;
    contentType?: string;
    tokens?: number;
    model?: string | null;
}

export interface AddContextApiV1UserAgentContextPost0Request {
    agentId: string;
    sessionId: string;
    role: string;
    content: string;
    contentType?: string;
    tokens?: number;
    model?: string | null;
}

export interface ClearContextApiV1UserAgentContextDeleteRequest {
    agentId: string;
    sessionId?: string | null;
}

export interface ClearContextApiV1UserAgentContextDelete0Request {
    agentId: string;
    sessionId?: string | null;
}

export interface ListContextApiV1UserAgentContextListGetRequest {
    agentId: string;
    sessionId?: string | null;
    limit?: number;
}

export interface ListContextApiV1UserAgentContextListGet0Request {
    agentId: string;
    sessionId?: string | null;
    limit?: number;
}

export interface ListSummariesApiV1UserAgentContextSummaryListGetRequest {
    agentId: string;
    limit?: number;
}

export interface ListSummariesApiV1UserAgentContextSummaryListGet0Request {
    agentId: string;
    limit?: number;
}

export interface SummarizeContextApiV1UserAgentContextSummaryPostRequest {
    agentId: string;
    summary: string;
    sessionId?: string | null;
    startId?: number;
    endId?: number;
    tokens?: number;
}

export interface SummarizeContextApiV1UserAgentContextSummaryPost0Request {
    agentId: string;
    summary: string;
    sessionId?: string | null;
    startId?: number;
    endId?: number;
    tokens?: number;
}

/**
 * 
 */
export class UserAgentContextApi extends runtime.BaseAPI {

    /**
     * Creates request options for addContextApiV1UserAgentContextPost without sending the request
     */
    async addContextApiV1UserAgentContextPostRequestOpts(requestParameters: AddContextApiV1UserAgentContextPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling addContextApiV1UserAgentContextPost().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling addContextApiV1UserAgentContextPost().'
            );
        }

        if (requestParameters['role'] == null) {
            throw new runtime.RequiredError(
                'role',
                'Required parameter "role" was null or undefined when calling addContextApiV1UserAgentContextPost().'
            );
        }

        if (requestParameters['content'] == null) {
            throw new runtime.RequiredError(
                'content',
                'Required parameter "content" was null or undefined when calling addContextApiV1UserAgentContextPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['agentId'] != null) {
            queryParameters['agent_id'] = requestParameters['agentId'];
        }

        if (requestParameters['sessionId'] != null) {
            queryParameters['session_id'] = requestParameters['sessionId'];
        }

        if (requestParameters['role'] != null) {
            queryParameters['role'] = requestParameters['role'];
        }

        if (requestParameters['content'] != null) {
            queryParameters['content'] = requestParameters['content'];
        }

        if (requestParameters['contentType'] != null) {
            queryParameters['content_type'] = requestParameters['contentType'];
        }

        if (requestParameters['tokens'] != null) {
            queryParameters['tokens'] = requestParameters['tokens'];
        }

        if (requestParameters['model'] != null) {
            queryParameters['model'] = requestParameters['model'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/user-agent-context`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 添加上下文消息
     */
    async addContextApiV1UserAgentContextPostRaw(requestParameters: AddContextApiV1UserAgentContextPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.addContextApiV1UserAgentContextPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 添加上下文消息
     */
    async addContextApiV1UserAgentContextPost(requestParameters: AddContextApiV1UserAgentContextPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.addContextApiV1UserAgentContextPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for addContextApiV1UserAgentContextPost_1 without sending the request
     */
    async addContextApiV1UserAgentContextPost_1RequestOpts(requestParameters: AddContextApiV1UserAgentContextPost0Request): Promise<runtime.RequestOpts> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling addContextApiV1UserAgentContextPost_1().'
            );
        }

        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling addContextApiV1UserAgentContextPost_1().'
            );
        }

        if (requestParameters['role'] == null) {
            throw new runtime.RequiredError(
                'role',
                'Required parameter "role" was null or undefined when calling addContextApiV1UserAgentContextPost_1().'
            );
        }

        if (requestParameters['content'] == null) {
            throw new runtime.RequiredError(
                'content',
                'Required parameter "content" was null or undefined when calling addContextApiV1UserAgentContextPost_1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['agentId'] != null) {
            queryParameters['agent_id'] = requestParameters['agentId'];
        }

        if (requestParameters['sessionId'] != null) {
            queryParameters['session_id'] = requestParameters['sessionId'];
        }

        if (requestParameters['role'] != null) {
            queryParameters['role'] = requestParameters['role'];
        }

        if (requestParameters['content'] != null) {
            queryParameters['content'] = requestParameters['content'];
        }

        if (requestParameters['contentType'] != null) {
            queryParameters['content_type'] = requestParameters['contentType'];
        }

        if (requestParameters['tokens'] != null) {
            queryParameters['tokens'] = requestParameters['tokens'];
        }

        if (requestParameters['model'] != null) {
            queryParameters['model'] = requestParameters['model'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/user-agent-context`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 添加上下文消息
     */
    async addContextApiV1UserAgentContextPost_1Raw(requestParameters: AddContextApiV1UserAgentContextPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.addContextApiV1UserAgentContextPost_1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 添加上下文消息
     */
    async addContextApiV1UserAgentContextPost_1(requestParameters: AddContextApiV1UserAgentContextPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.addContextApiV1UserAgentContextPost_1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for clearContextApiV1UserAgentContextDelete without sending the request
     */
    async clearContextApiV1UserAgentContextDeleteRequestOpts(requestParameters: ClearContextApiV1UserAgentContextDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling clearContextApiV1UserAgentContextDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['agentId'] != null) {
            queryParameters['agent_id'] = requestParameters['agentId'];
        }

        if (requestParameters['sessionId'] != null) {
            queryParameters['session_id'] = requestParameters['sessionId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/user-agent-context`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 清空上下文
     */
    async clearContextApiV1UserAgentContextDeleteRaw(requestParameters: ClearContextApiV1UserAgentContextDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.clearContextApiV1UserAgentContextDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 清空上下文
     */
    async clearContextApiV1UserAgentContextDelete(requestParameters: ClearContextApiV1UserAgentContextDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.clearContextApiV1UserAgentContextDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for clearContextApiV1UserAgentContextDelete_2 without sending the request
     */
    async clearContextApiV1UserAgentContextDelete_2RequestOpts(requestParameters: ClearContextApiV1UserAgentContextDelete0Request): Promise<runtime.RequestOpts> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling clearContextApiV1UserAgentContextDelete_2().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['agentId'] != null) {
            queryParameters['agent_id'] = requestParameters['agentId'];
        }

        if (requestParameters['sessionId'] != null) {
            queryParameters['session_id'] = requestParameters['sessionId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/user-agent-context`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 清空上下文
     */
    async clearContextApiV1UserAgentContextDelete_2Raw(requestParameters: ClearContextApiV1UserAgentContextDelete0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.clearContextApiV1UserAgentContextDelete_2RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 清空上下文
     */
    async clearContextApiV1UserAgentContextDelete_2(requestParameters: ClearContextApiV1UserAgentContextDelete0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.clearContextApiV1UserAgentContextDelete_2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listContextApiV1UserAgentContextListGet without sending the request
     */
    async listContextApiV1UserAgentContextListGetRequestOpts(requestParameters: ListContextApiV1UserAgentContextListGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling listContextApiV1UserAgentContextListGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['agentId'] != null) {
            queryParameters['agent_id'] = requestParameters['agentId'];
        }

        if (requestParameters['sessionId'] != null) {
            queryParameters['session_id'] = requestParameters['sessionId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/user-agent-context/list`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 获取上下文
     */
    async listContextApiV1UserAgentContextListGetRaw(requestParameters: ListContextApiV1UserAgentContextListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.listContextApiV1UserAgentContextListGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 获取上下文
     */
    async listContextApiV1UserAgentContextListGet(requestParameters: ListContextApiV1UserAgentContextListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listContextApiV1UserAgentContextListGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listContextApiV1UserAgentContextListGet_3 without sending the request
     */
    async listContextApiV1UserAgentContextListGet_3RequestOpts(requestParameters: ListContextApiV1UserAgentContextListGet0Request): Promise<runtime.RequestOpts> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling listContextApiV1UserAgentContextListGet_3().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['agentId'] != null) {
            queryParameters['agent_id'] = requestParameters['agentId'];
        }

        if (requestParameters['sessionId'] != null) {
            queryParameters['session_id'] = requestParameters['sessionId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/user-agent-context/list`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 获取上下文
     */
    async listContextApiV1UserAgentContextListGet_3Raw(requestParameters: ListContextApiV1UserAgentContextListGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.listContextApiV1UserAgentContextListGet_3RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 获取上下文
     */
    async listContextApiV1UserAgentContextListGet_3(requestParameters: ListContextApiV1UserAgentContextListGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listContextApiV1UserAgentContextListGet_3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSummariesApiV1UserAgentContextSummaryListGet without sending the request
     */
    async listSummariesApiV1UserAgentContextSummaryListGetRequestOpts(requestParameters: ListSummariesApiV1UserAgentContextSummaryListGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling listSummariesApiV1UserAgentContextSummaryListGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['agentId'] != null) {
            queryParameters['agent_id'] = requestParameters['agentId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/user-agent-context/summary/list`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 总结列表
     */
    async listSummariesApiV1UserAgentContextSummaryListGetRaw(requestParameters: ListSummariesApiV1UserAgentContextSummaryListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.listSummariesApiV1UserAgentContextSummaryListGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 总结列表
     */
    async listSummariesApiV1UserAgentContextSummaryListGet(requestParameters: ListSummariesApiV1UserAgentContextSummaryListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listSummariesApiV1UserAgentContextSummaryListGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSummariesApiV1UserAgentContextSummaryListGet_4 without sending the request
     */
    async listSummariesApiV1UserAgentContextSummaryListGet_4RequestOpts(requestParameters: ListSummariesApiV1UserAgentContextSummaryListGet0Request): Promise<runtime.RequestOpts> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling listSummariesApiV1UserAgentContextSummaryListGet_4().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['agentId'] != null) {
            queryParameters['agent_id'] = requestParameters['agentId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/user-agent-context/summary/list`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 总结列表
     */
    async listSummariesApiV1UserAgentContextSummaryListGet_4Raw(requestParameters: ListSummariesApiV1UserAgentContextSummaryListGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.listSummariesApiV1UserAgentContextSummaryListGet_4RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 总结列表
     */
    async listSummariesApiV1UserAgentContextSummaryListGet_4(requestParameters: ListSummariesApiV1UserAgentContextSummaryListGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listSummariesApiV1UserAgentContextSummaryListGet_4Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for summarizeContextApiV1UserAgentContextSummaryPost without sending the request
     */
    async summarizeContextApiV1UserAgentContextSummaryPostRequestOpts(requestParameters: SummarizeContextApiV1UserAgentContextSummaryPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling summarizeContextApiV1UserAgentContextSummaryPost().'
            );
        }

        if (requestParameters['summary'] == null) {
            throw new runtime.RequiredError(
                'summary',
                'Required parameter "summary" was null or undefined when calling summarizeContextApiV1UserAgentContextSummaryPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['agentId'] != null) {
            queryParameters['agent_id'] = requestParameters['agentId'];
        }

        if (requestParameters['sessionId'] != null) {
            queryParameters['session_id'] = requestParameters['sessionId'];
        }

        if (requestParameters['summary'] != null) {
            queryParameters['summary'] = requestParameters['summary'];
        }

        if (requestParameters['startId'] != null) {
            queryParameters['start_id'] = requestParameters['startId'];
        }

        if (requestParameters['endId'] != null) {
            queryParameters['end_id'] = requestParameters['endId'];
        }

        if (requestParameters['tokens'] != null) {
            queryParameters['tokens'] = requestParameters['tokens'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/user-agent-context/summary`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 总结上下文
     */
    async summarizeContextApiV1UserAgentContextSummaryPostRaw(requestParameters: SummarizeContextApiV1UserAgentContextSummaryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.summarizeContextApiV1UserAgentContextSummaryPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 总结上下文
     */
    async summarizeContextApiV1UserAgentContextSummaryPost(requestParameters: SummarizeContextApiV1UserAgentContextSummaryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.summarizeContextApiV1UserAgentContextSummaryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for summarizeContextApiV1UserAgentContextSummaryPost_5 without sending the request
     */
    async summarizeContextApiV1UserAgentContextSummaryPost_5RequestOpts(requestParameters: SummarizeContextApiV1UserAgentContextSummaryPost0Request): Promise<runtime.RequestOpts> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling summarizeContextApiV1UserAgentContextSummaryPost_5().'
            );
        }

        if (requestParameters['summary'] == null) {
            throw new runtime.RequiredError(
                'summary',
                'Required parameter "summary" was null or undefined when calling summarizeContextApiV1UserAgentContextSummaryPost_5().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['agentId'] != null) {
            queryParameters['agent_id'] = requestParameters['agentId'];
        }

        if (requestParameters['sessionId'] != null) {
            queryParameters['session_id'] = requestParameters['sessionId'];
        }

        if (requestParameters['summary'] != null) {
            queryParameters['summary'] = requestParameters['summary'];
        }

        if (requestParameters['startId'] != null) {
            queryParameters['start_id'] = requestParameters['startId'];
        }

        if (requestParameters['endId'] != null) {
            queryParameters['end_id'] = requestParameters['endId'];
        }

        if (requestParameters['tokens'] != null) {
            queryParameters['tokens'] = requestParameters['tokens'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/user-agent-context/summary`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 总结上下文
     */
    async summarizeContextApiV1UserAgentContextSummaryPost_5Raw(requestParameters: SummarizeContextApiV1UserAgentContextSummaryPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.summarizeContextApiV1UserAgentContextSummaryPost_5RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * 总结上下文
     */
    async summarizeContextApiV1UserAgentContextSummaryPost_5(requestParameters: SummarizeContextApiV1UserAgentContextSummaryPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.summarizeContextApiV1UserAgentContextSummaryPost_5Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
