/*
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.ChatCreateBody;
import org.openapitools.client.model.ChatMarkBody;
import org.openapitools.client.model.ChatQueryBody;
import org.openapitools.client.model.HTTPValidationError;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ChatHistoryApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ChatHistoryApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ChatHistoryApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createChatApiV1ChatCreatePost
     * @param chatCreateBody  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createChatApiV1ChatCreatePostCall(@javax.annotation.Nonnull ChatCreateBody chatCreateBody, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = chatCreateBody;

        // create path and map variables
        String localVarPath = "/api/v1/chat/create";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "HTTPBearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createChatApiV1ChatCreatePostValidateBeforeCall(@javax.annotation.Nonnull ChatCreateBody chatCreateBody, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'chatCreateBody' is set
        if (chatCreateBody == null) {
            throw new ApiException("Missing the required parameter 'chatCreateBody' when calling createChatApiV1ChatCreatePost(Async)");
        }

        return createChatApiV1ChatCreatePostCall(chatCreateBody, _callback);

    }

    /**
     * Create a chat record
     * Create a new user-model chat record.
     * @param chatCreateBody  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object createChatApiV1ChatCreatePost(@javax.annotation.Nonnull ChatCreateBody chatCreateBody) throws ApiException {
        ApiResponse<Object> localVarResp = createChatApiV1ChatCreatePostWithHttpInfo(chatCreateBody);
        return localVarResp.getData();
    }

    /**
     * Create a chat record
     * Create a new user-model chat record.
     * @param chatCreateBody  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> createChatApiV1ChatCreatePostWithHttpInfo(@javax.annotation.Nonnull ChatCreateBody chatCreateBody) throws ApiException {
        okhttp3.Call localVarCall = createChatApiV1ChatCreatePostValidateBeforeCall(chatCreateBody, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a chat record (asynchronously)
     * Create a new user-model chat record.
     * @param chatCreateBody  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createChatApiV1ChatCreatePostAsync(@javax.annotation.Nonnull ChatCreateBody chatCreateBody, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = createChatApiV1ChatCreatePostValidateBeforeCall(chatCreateBody, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteChatApiV1ChatChatIdDelete
     * @param chatId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteChatApiV1ChatChatIdDeleteCall(@javax.annotation.Nonnull Integer chatId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/chat/{chat_id}"
            .replace("{" + "chat_id" + "}", localVarApiClient.escapeString(chatId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "HTTPBearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteChatApiV1ChatChatIdDeleteValidateBeforeCall(@javax.annotation.Nonnull Integer chatId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'chatId' is set
        if (chatId == null) {
            throw new ApiException("Missing the required parameter 'chatId' when calling deleteChatApiV1ChatChatIdDelete(Async)");
        }

        return deleteChatApiV1ChatChatIdDeleteCall(chatId, _callback);

    }

    /**
     * Delete a chat record
     * Delete a chat record owned by the authenticated user.
     * @param chatId  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object deleteChatApiV1ChatChatIdDelete(@javax.annotation.Nonnull Integer chatId) throws ApiException {
        ApiResponse<Object> localVarResp = deleteChatApiV1ChatChatIdDeleteWithHttpInfo(chatId);
        return localVarResp.getData();
    }

    /**
     * Delete a chat record
     * Delete a chat record owned by the authenticated user.
     * @param chatId  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> deleteChatApiV1ChatChatIdDeleteWithHttpInfo(@javax.annotation.Nonnull Integer chatId) throws ApiException {
        okhttp3.Call localVarCall = deleteChatApiV1ChatChatIdDeleteValidateBeforeCall(chatId, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete a chat record (asynchronously)
     * Delete a chat record owned by the authenticated user.
     * @param chatId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteChatApiV1ChatChatIdDeleteAsync(@javax.annotation.Nonnull Integer chatId, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteChatApiV1ChatChatIdDeleteValidateBeforeCall(chatId, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for queryChatsApiV1ChatQueryPost
     * @param chatQueryBody  (required)
     * @param page  (optional, default to 1)
     * @param limit  (optional, default to 20)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call queryChatsApiV1ChatQueryPostCall(@javax.annotation.Nonnull ChatQueryBody chatQueryBody, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = chatQueryBody;

        // create path and map variables
        String localVarPath = "/api/v1/chat/query";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "HTTPBearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call queryChatsApiV1ChatQueryPostValidateBeforeCall(@javax.annotation.Nonnull ChatQueryBody chatQueryBody, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'chatQueryBody' is set
        if (chatQueryBody == null) {
            throw new ApiException("Missing the required parameter 'chatQueryBody' when calling queryChatsApiV1ChatQueryPost(Async)");
        }

        return queryChatsApiV1ChatQueryPostCall(chatQueryBody, page, limit, _callback);

    }

    /**
     * Query chat records
     * Query chat records for the authenticated user, optionally filtered by model_name. Joins with zhs_ai_model_info to include model source and icon.
     * @param chatQueryBody  (required)
     * @param page  (optional, default to 1)
     * @param limit  (optional, default to 20)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object queryChatsApiV1ChatQueryPost(@javax.annotation.Nonnull ChatQueryBody chatQueryBody, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit) throws ApiException {
        ApiResponse<Object> localVarResp = queryChatsApiV1ChatQueryPostWithHttpInfo(chatQueryBody, page, limit);
        return localVarResp.getData();
    }

    /**
     * Query chat records
     * Query chat records for the authenticated user, optionally filtered by model_name. Joins with zhs_ai_model_info to include model source and icon.
     * @param chatQueryBody  (required)
     * @param page  (optional, default to 1)
     * @param limit  (optional, default to 20)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> queryChatsApiV1ChatQueryPostWithHttpInfo(@javax.annotation.Nonnull ChatQueryBody chatQueryBody, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit) throws ApiException {
        okhttp3.Call localVarCall = queryChatsApiV1ChatQueryPostValidateBeforeCall(chatQueryBody, page, limit, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Query chat records (asynchronously)
     * Query chat records for the authenticated user, optionally filtered by model_name. Joins with zhs_ai_model_info to include model source and icon.
     * @param chatQueryBody  (required)
     * @param page  (optional, default to 1)
     * @param limit  (optional, default to 20)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call queryChatsApiV1ChatQueryPostAsync(@javax.annotation.Nonnull ChatQueryBody chatQueryBody, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = queryChatsApiV1ChatQueryPostValidateBeforeCall(chatQueryBody, page, limit, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateChatMarkApiV1ChatChatIdMarkPut
     * @param chatId  (required)
     * @param chatMarkBody  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateChatMarkApiV1ChatChatIdMarkPutCall(@javax.annotation.Nonnull Integer chatId, @javax.annotation.Nonnull ChatMarkBody chatMarkBody, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = chatMarkBody;

        // create path and map variables
        String localVarPath = "/api/v1/chat/{chat_id}/mark"
            .replace("{" + "chat_id" + "}", localVarApiClient.escapeString(chatId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "HTTPBearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateChatMarkApiV1ChatChatIdMarkPutValidateBeforeCall(@javax.annotation.Nonnull Integer chatId, @javax.annotation.Nonnull ChatMarkBody chatMarkBody, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'chatId' is set
        if (chatId == null) {
            throw new ApiException("Missing the required parameter 'chatId' when calling updateChatMarkApiV1ChatChatIdMarkPut(Async)");
        }

        // verify the required parameter 'chatMarkBody' is set
        if (chatMarkBody == null) {
            throw new ApiException("Missing the required parameter 'chatMarkBody' when calling updateChatMarkApiV1ChatChatIdMarkPut(Async)");
        }

        return updateChatMarkApiV1ChatChatIdMarkPutCall(chatId, chatMarkBody, _callback);

    }

    /**
     * Update chat mark/label
     * Update the mark (label/summary) of a chat record owned by the user.
     * @param chatId  (required)
     * @param chatMarkBody  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object updateChatMarkApiV1ChatChatIdMarkPut(@javax.annotation.Nonnull Integer chatId, @javax.annotation.Nonnull ChatMarkBody chatMarkBody) throws ApiException {
        ApiResponse<Object> localVarResp = updateChatMarkApiV1ChatChatIdMarkPutWithHttpInfo(chatId, chatMarkBody);
        return localVarResp.getData();
    }

    /**
     * Update chat mark/label
     * Update the mark (label/summary) of a chat record owned by the user.
     * @param chatId  (required)
     * @param chatMarkBody  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> updateChatMarkApiV1ChatChatIdMarkPutWithHttpInfo(@javax.annotation.Nonnull Integer chatId, @javax.annotation.Nonnull ChatMarkBody chatMarkBody) throws ApiException {
        okhttp3.Call localVarCall = updateChatMarkApiV1ChatChatIdMarkPutValidateBeforeCall(chatId, chatMarkBody, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update chat mark/label (asynchronously)
     * Update the mark (label/summary) of a chat record owned by the user.
     * @param chatId  (required)
     * @param chatMarkBody  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateChatMarkApiV1ChatChatIdMarkPutAsync(@javax.annotation.Nonnull Integer chatId, @javax.annotation.Nonnull ChatMarkBody chatMarkBody, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateChatMarkApiV1ChatChatIdMarkPutValidateBeforeCall(chatId, chatMarkBody, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
