'use client' import * as React from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useTranslations } from 'next-intl'
import { CheckCircle2, Loader2, RotateCw, UserPlus } from 'lucide-react' import { fetchApi } from '@/lib/api'
import { Button, Card, CardContent, Input, Label } from '@ihui/ui-react'
import { toast } from '@/components/common/Toaster'
import { BackButton } from '@/components/common' interface ReferrerInfo { referrerName: string | null referrerCode: string | null code: string
} async function api<T>(url: string, options?: RequestInit): Promise<T> { const r = await fetchApi<T>(url, options) if (!r.success) throw new Error(r.error) return r.data
} export default function ReferrerPage() { const t = useTranslations('referrer') const qc = useQueryClient() const [code, setCode] = React.useState('') const q = useQuery({ queryKey: ['user', 'referrer'], queryFn: () => api<ReferrerInfo>('/user/referrer'), }) const bindQ = useMutation({ mutationFn: (inviteCode: string) => api<unknown>('/user/referrer', { method: 'POST', body: JSON.stringify({ code: inviteCode }) }), onSuccess: () => { toast.success(t('bindSuccess')) setCode('') void qc.invalidateQueries({ queryKey: ['user', 'referrer'] }) }, onError: (e: Error) => { toast.error(e.message || t('bindFailed')) }, }) const info = q.data return ( <div className="mx-auto w-full max-w-md "> <div className="mb-4 flex items-center justify-between"> <BackButton fallbackHref="/distribution" /> <h1 className="text-lg font-medium">{t('title')}</h1> <div className="w-10" /> </div> {q.isLoading ? ( <div className="flex items-center justify-center text-muted-foreground"> <Loader2 className="mr-2 h-5 w-5 shrink-0 animate-spin" /> <span>{t('loading')}</span> </div> ) : q.isError ? ( <div className="rounded-md border border-border bg-card p-6 text-center"> <p className="mb-3 text-sm text-muted-foreground">{t('loadFailed')}</p> <Button variant="outline" size="sm" onClick={() => void q.refetch()}> <RotateCw className="mr-2 h-4 w-4" /> {t('retry')} </Button> </div> ) : info ? ( <div className="space-y-4"> <Card> <CardContent className="p-4"> <h3 className="mb-2 text-sm font-medium">{t('myReferrer')}</h3> {info.referrerName ? ( <div className="flex items-center gap-2 text-sm"> <CheckCircle2 className="h-4 w-4 text-green-600" /> <span> {info.referrerName} {info.referrerCode ? ` (${info.referrerCode})` : ''} </span> </div> ) : ( <p className="text-sm text-muted-foreground">{t('noReferrer')}</p> )} <p className="mt-3 text-xs text-muted-foreground"> {t('myInviteCode')}: {info.code} </p> </CardContent> </Card> {!info.referrerName && ( <Card> <CardContent className="space-y-3 p-4"> <h3 className="text-sm font-medium">{t('bindTitle')}</h3> <div className="space-y-1.5"> <Label htmlFor="invite-code">{t('codeLabel')}</Label> <Input id="invite-code" value={code} onChange={(e) => setCode(e.target.value)} placeholder={t('codePlaceholder')} maxLength={32} /> </div> <Button className="w-full" disabled={bindQ.isPending || !code.trim()} onClick={() => bindQ.mutate(code.trim())} > {bindQ.isPending ? ( <Loader2 className="mr-2 h-4 w-4 animate-spin" /> ) : ( <UserPlus className="mr-2 h-4 w-4" /> )} {t('bindBtn')} </Button> </CardContent> </Card> )} </div> ) : null} </div> )
}
