// © 2026 IHUI AI (智汇AI) · 版权所有者: 李春川 (Li Chunchuan) · https://aizhs.top
// Provenance-watermarked. 未授权商用可被溯源追责 (Apache-2.0 须保留本声明与 NOTICE)。
// [IHUI-AI-PROVENANCE]:⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠

// AUTO-GENERATED by scripts/resolve-desktop-download.mjs — 请勿手动编辑
// 数据源:GitHub Releases 最新 desktop-v* release 资产(发版后由 CI 自动刷新)
export interface DesktopFeedAsset {
  href: string
  sizeBytes: number
  format: string
  arch: string
  /** Tauri 更新器签名(release 未附 .sig 资产时为空串 → 更新器判定无效) */
  signature: string
}

/** Tauri updater 平台条目:url 必须是 GitHub/Gitee 资产直链,signature 非空 */
export interface DesktopFeedUpdaterEntry {
  url: string
  signature: string
}

export interface DesktopFeed {
  version: string
  releaseDate: string
  githubReleasesUrl: string
  resolvedFromTag: string
  resolvedAt: string
  assets: DesktopFeedAsset[]
  /**
   * Tauri updater feed 的 platforms 映射(键:windows-x86_64 / linux-x86_64 /
   * darwin-x86_64 / darwin-aarch64;缺签名/host 不可达的平台不出现)。
   * 历史快照无此字段(route 有 windows 兜底派生)。
   */
  updaterPlatforms?: Record<string, DesktopFeedUpdaterEntry>
}

export const DESKTOP_FEED: DesktopFeed = {
  version: '0.1.50',
  releaseDate: '2026-09-28',
  githubReleasesUrl: 'https://gitee.com/JLSLSSZWHYXGS_0/IHUI-AI/releases',
  resolvedFromTag: 'desktop-v0.1.50',
  resolvedAt: '2026-09-28T04:53:33.089Z',
  assets: [
    { href: 'https://gitee.com/JLSLSSZWHYXGS_0/IHUI-AI/releases/download/desktop-v0.1.50/AI_0.1.50_x64-setup.exe', sizeBytes: 7583902, format: 'Windows NSIS exe', arch: 'x64', signature: 'dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVRSTI3R2lmdWJYdGZWakl1T2gxSUFwb1BVaUtDOGZSZmRzQnVyZCs5NVFpbWx2OTFZWmRxUFBMSGc5dzJvZTFRSXJqeWVJaitPM3JpMHMra3UrM1BvakRNdkJ0ZWFvekF3PQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzkwNTY5Nzg5CWZpbGU65pm65rGHQUlfMC4xLjUwX3g2NC1zZXR1cC5leGUKOENUZG1hdlh1cXlLc1hJblBRbTBXRm9CMkdvWnhQeGVpbU1tc2ZDYnAxdGx5dGg2RUI3T05GcnY1azJuQjNxYTI1blB6MTRBODl4d1hpajhOTjlpQ2c9PQo=' },
    { href: 'https://github.com/IHUI-INF-AI/IHUI-AI/releases/download/desktop-v0.1.50/AI_0.1.50_universal.dmg', sizeBytes: 11205529, format: 'macOS DMG', arch: 'x64', signature: '' },
    { href: 'https://github.com/IHUI-INF-AI/IHUI-AI/releases/download/desktop-v0.1.50/AI_0.1.50_amd64.AppImage', sizeBytes: 81975800, format: 'Linux AppImage', arch: 'amd64', signature: 'dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVRSTI3R2lmdWJYdFRMZVg1eWpocFpvbzM0eHhZMFEvMWZGV3Vyd2JtNnRwL1BUditvZGJ2b0txaEFoeG1EOXZpYmZvZFFTSWpaRmFhc011ZkdOUWIrOVhnelBhYk11YlFnPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzkwNTcwMjA3CWZpbGU65pm65rGHQUlfMC4xLjUwX2FtZDY0LkFwcEltYWdlClZTK0VpZjBMWUF6V3hDbjBObGNGRVJkczlTd1o1Sklxcm4zaWFHU1p0YXR2NVNEdm9QVW1ucHlBYmdJV1ZuSjA0Y1lqdlFYdGx6REl5c2h0eGpvWkNRPT0K' },
    { href: 'https://github.com/IHUI-INF-AI/IHUI-AI/releases/download/desktop-v0.1.50/AI_0.1.50_amd64.deb', sizeBytes: 6731436, format: 'Linux DEB', arch: 'amd64', signature: 'dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVRSTI3R2lmdWJYdFErUWtVajJuSjZsRHpjVUV6S2J2bU84RzdHZGY5L2pCaWpORHNxeW9oTWVEUmtqZk5EbUN4NGFFblROZXNjV3pSSkNVUmVyTlVscXFxWURzcTNrbEFBPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzkwNTcwMjA3CWZpbGU65pm65rGHQUlfMC4xLjUwX2FtZDY0LmRlYgpsWVE1TnVVRm9Oa0VmN0pzYnErNVZmN2x0Qmc0cERFdC9wVjB2YlI4bng0T3FxTUpRZTBhWHNSVlVuZE5nYUNNeStRUDdhZUlNZWZoRUp2T2YwNWhBZz09Cg==' },
  ],
  updaterPlatforms: {
    'windows-x86_64': { url: 'https://gitee.com/JLSLSSZWHYXGS_0/IHUI-AI/releases/download/desktop-v0.1.50/AI_0.1.50_x64-setup.exe', signature: 'dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVRSTI3R2lmdWJYdGZWakl1T2gxSUFwb1BVaUtDOGZSZmRzQnVyZCs5NVFpbWx2OTFZWmRxUFBMSGc5dzJvZTFRSXJqeWVJaitPM3JpMHMra3UrM1BvakRNdkJ0ZWFvekF3PQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzkwNTY5Nzg5CWZpbGU65pm65rGHQUlfMC4xLjUwX3g2NC1zZXR1cC5leGUKOENUZG1hdlh1cXlLc1hJblBRbTBXRm9CMkdvWnhQeGVpbU1tc2ZDYnAxdGx5dGg2RUI3T05GcnY1azJuQjNxYTI1blB6MTRBODl4d1hpajhOTjlpQ2c9PQo=' },
    'linux-x86_64': { url: 'https://github.com/IHUI-INF-AI/IHUI-AI/releases/download/desktop-v0.1.50/AI_0.1.50_amd64.AppImage', signature: 'dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVRSTI3R2lmdWJYdFRMZVg1eWpocFpvbzM0eHhZMFEvMWZGV3Vyd2JtNnRwL1BUditvZGJ2b0txaEFoeG1EOXZpYmZvZFFTSWpaRmFhc011ZkdOUWIrOVhnelBhYk11YlFnPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzkwNTcwMjA3CWZpbGU65pm65rGHQUlfMC4xLjUwX2FtZDY0LkFwcEltYWdlClZTK0VpZjBMWUF6V3hDbjBObGNGRVJkczlTd1o1Sklxcm4zaWFHU1p0YXR2NVNEdm9QVW1ucHlBYmdJV1ZuSjA0Y1lqdlFYdGx6REl5c2h0eGpvWkNRPT0K' },
    'darwin-x86_64': { url: 'https://github.com/IHUI-INF-AI/IHUI-AI/releases/download/desktop-v0.1.50/AI_universal.app.tar.gz', signature: 'dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVRSTI3R2lmdWJYdFVjUzBLVm9SZ0ZMQ1k1RGRoekxhNndqVThTNng5UDhSNWdFektnRlJFaUJYOVdxVklXWHI4RHRQanYvelU1anN1alB3TDhodllRRVljZXZSK3NZNlFjPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzkwNTY5OTk0CWZpbGU65pm65rGHQUkuYXBwLnRhci5negpLaEJXZUF2RlJIOElNdG1SK2t4R2lMRS9kRWtiWHVsY0xUN2NZVmdLNi9ydVhybG5mTHlBdHN1T3JhT0ZCZ2g1YVVWZ3p5YkFlUlhJKzhGN0VlbWlBZz09Cg==' },
    'darwin-aarch64': { url: 'https://github.com/IHUI-INF-AI/IHUI-AI/releases/download/desktop-v0.1.50/AI_universal.app.tar.gz', signature: 'dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVRSTI3R2lmdWJYdFVjUzBLVm9SZ0ZMQ1k1RGRoekxhNndqVThTNng5UDhSNWdFektnRlJFaUJYOVdxVklXWHI4RHRQanYvelU1anN1alB3TDhodllRRVljZXZSK3NZNlFjPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzkwNTY5OTk0CWZpbGU65pm65rGHQUkuYXBwLnRhci5negpLaEJXZUF2RlJIOElNdG1SK2t4R2lMRS9kRWtiWHVsY0xUN2NZVmdLNi9ydVhybG5mTHlBdHN1T3JhT0ZCZ2g1YVVWZ3p5YkFlUlhJKzhGN0VlbWlBZz09Cg==' },
  },
}
// ⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠
