/**
 * 插件市场数据源(2026-07-22 重构,扩充至 24 内置 + 50 市场)
 *
 * 三类元数据:
 *  - category: 用于分类筛选(all/builtin/mcp/agent/workflow/tool/model/market/ide/knowledge/creation)
 *  - tags:     展示用标签 chip
 *  - vendor:   lobehub 厂商 code(小写),用于 BrandIcon 渲染官方矢量图标
 *
 * 图标策略:
 *  - 项目插件: lucide-react(与侧边栏视觉一致)
 *  - 市场插件: 优先 BrandIcon(@lobehub/icons),未收录用 lucide 兜底
 */

import {
  Cable,
  Bot,
  Workflow,
  Sparkles,
  Wrench,
  Image as ImageIcon,
  Code,
  Globe,
  Boxes,
  Link2,
  MousePointer2,
  Server,
  Rocket,
  Terminal,
  Send,
  Network,
  BookOpen,
  Database,
  FileText,
  BarChart3,
  ShieldCheck,
  Building2,
  Palette,
  Layers,
  Cpu,
  Zap,
  Star,
  Store,
  type LucideIcon,
} from 'lucide-react'

export type PluginCategory =
  | 'builtin'
  | 'mcp'
  | 'agent'
  | 'workflow'
  | 'tool'
  | 'model'
  | 'market'
  | 'ide'
  | 'knowledge'
  | 'creation'

export interface ProjectPlugin {
  id: string
  name: string
  description: string
  href: string
  icon: LucideIcon
  tags: string[]
  category: PluginCategory
}

export interface MarketPlugin {
  id: string
  name: string
  description: string
  url: string
  /** lobehub 厂商代码(小写),用于 BrandIcon;为空则用 fallbackIcon */
  vendor?: string
  fallbackIcon: LucideIcon
  tags: string[]
  category: PluginCategory
  free?: boolean
  official?: boolean
}

/** 本项目已集成的插件能力(24 项,对应 (main) 路由组下已有页面) */
export const PROJECT_PLUGINS: ProjectPlugin[] = [
  {
    id: 'mcp-projects',
    name: 'MCP 项目',
    description: 'Model Context Protocol 服务器管理,让 AI 调用外部工具与数据源',
    href: '/mcp-projects',
    icon: Cable,
    tags: ['MCP', '工具调用'],
    category: 'mcp',
  },
  {
    id: 'agents',
    name: 'AI 智能体',
    description: '创建与管理自定义 AI Agent,支持多模型编排与工具组合',
    href: '/agents',
    icon: Bot,
    tags: ['Agent', '多模型'],
    category: 'agent',
  },
  {
    id: 'workflows',
    name: '工作流',
    description: '可视化工作流编排,串联 AI 节点 / API 调用 / 条件分支',
    href: '/workflows',
    icon: Workflow,
    tags: ['工作流', '编排'],
    category: 'workflow',
  },
  {
    id: 'skills',
    name: 'AI 技能',
    description: '平台技能市场,管理与配置 AI 模型可调用的技能模板',
    href: '/models/skills',
    icon: Sparkles,
    tags: ['技能', '模板'],
    category: 'tool',
  },
  {
    id: 'tools',
    name: 'AI 工具',
    description: '在线 AI 工具集合,涵盖 PDF 处理 / 文档转换 / 文本分析等',
    href: '/tools',
    icon: Wrench,
    tags: ['工具', '在线'],
    category: 'tool',
  },
  {
    id: 'image-gen',
    name: '图像生成',
    description: 'AI 图像生成能力,支持文生图 / 图生图 / 多模型切换',
    href: '/image-gen',
    icon: ImageIcon,
    tags: ['图像', '生成'],
    category: 'creation',
  },
  {
    id: 'ai-generation',
    name: 'AI 创作',
    description: 'AI 内容创作中心,文案 / 脚本 / 小说 / 营销内容一键生成',
    href: '/ai-generation',
    icon: Sparkles,
    tags: ['创作', '内容'],
    category: 'creation',
  },
  {
    id: 'api-test',
    name: 'API 测试',
    description: '在线 API 调试与测试工具,支持参数配置 / 历史记录 / 结果对比',
    href: '/api-test',
    icon: Code,
    tags: ['API', '调试'],
    category: 'tool',
  },
  {
    id: 'ai-world',
    name: 'AI 世界',
    description: 'AI 应用探索中心,热门 AI 应用 / 智能创作 / 场景化体验',
    href: '/ai-world',
    icon: Globe,
    tags: ['应用', '探索'],
    category: 'creation',
  },
  {
    id: 'knowledge-graph',
    name: '知识图谱',
    description: '构建与管理知识图谱,实体关系可视化 / 图谱推理 / 关联查询',
    href: '/knowledge-graph',
    icon: Network,
    tags: ['图谱', '知识'],
    category: 'knowledge',
  },
  {
    id: 'knowledge-base',
    name: '知识库',
    description: '企业知识库管理,文档上传 / 分 chunk / 向量化 / 检索召回',
    href: '/knowledge-base',
    icon: BookOpen,
    tags: ['知识库', '向量'],
    category: 'knowledge',
  },
  {
    id: 'knowledge-rag',
    name: '知识检索 RAG',
    description: 'RAG 检索增强生成,文档问答 / 语义检索 / 引用溯源',
    href: '/knowledge-rag',
    icon: Database,
    tags: ['RAG', '检索'],
    category: 'knowledge',
  },
  {
    id: 'docs',
    name: '文档中心',
    description: '项目文档与 API 参考手册,开发者必读 / 接口契约 / 架构说明',
    href: '/docs',
    icon: FileText,
    tags: ['文档', 'API'],
    category: 'knowledge',
  },
  {
    id: 'publish',
    name: '多平台发布',
    description: '一键多平台发布工具,支持 md / docx / html / pdf / 图片 / 视频 → 14 平台',
    href: '/publish',
    icon: Send,
    tags: ['发布', '多平台'],
    category: 'creation',
  },
  {
    id: 'articles',
    name: '文章',
    description: '长文创作与管理,支持 Markdown / 富文本 / 草稿 / 发布工作流',
    href: '/articles',
    icon: FileText,
    tags: ['文章', 'Markdown'],
    category: 'creation',
  },
  {
    id: 'models',
    name: '模型市场',
    description: '50+ 主流大模型市场,OpenAI / Anthropic / Google / 国产模型一网打尽',
    href: '/models',
    icon: Cpu,
    tags: ['模型', '市场'],
    category: 'model',
  },
  {
    id: 'developer',
    name: '开发者中心',
    description: '开发者工具集,API Key 管理 / Webhook / 调试 / 日志 / 监控',
    href: '/developer',
    icon: Terminal,
    tags: ['开发', 'API Key'],
    category: 'ide',
  },
  {
    id: 'n8n-agents',
    name: 'n8n Agents',
    description: 'n8n 工作流 Agent 集成,可视化编排 + AI 节点 + 自动化触发',
    href: '/n8n-agents',
    icon: Workflow,
    tags: ['n8n', '自动化'],
    category: 'workflow',
  },
  {
    id: 'openclaw',
    name: 'OpenClaw',
    description: '开源 AI Agent 平台,多智能体协作 / 工具调用 / 工作流编排',
    href: '/openclaw',
    icon: Rocket,
    tags: ['开源', 'Agent'],
    category: 'agent',
  },
  {
    id: 'dashboard',
    name: '数据看板',
    description: '平台运营数据看板,用户 / 收入 / 调用量 / 模型分布实时可视化',
    href: '/dashboard',
    icon: BarChart3,
    tags: ['数据', '看板'],
    category: 'tool',
  },
  {
    id: 'bi-dashboard',
    name: 'BI 仪表板',
    description: '商业智能仪表板,多维度数据分析 / 自定义图表 / 导出报表',
    href: '/bi-dashboard',
    icon: BarChart3,
    tags: ['BI', '报表'],
    category: 'tool',
  },
  {
    id: 'security-audit',
    name: '安全审计',
    description: '平台安全审计中心,API Key 泄露检测 / 权限审查 / 操作日志',
    href: '/security-audit',
    icon: ShieldCheck,
    tags: ['安全', '审计'],
    category: 'tool',
  },
  {
    id: 'enterprise',
    name: '企业版',
    description: '企业级能力,SSO 单点登录 / 组织架构 / 配额管理 / 私有部署',
    href: '/enterprise',
    icon: Building2,
    tags: ['企业', 'SSO'],
    category: 'tool',
  },
  {
    id: 'design-system',
    name: '设计系统',
    description: 'UI 设计系统文档,组件库 / 色彩 token / 图标 / 间距规范',
    href: '/design-system',
    icon: Palette,
    tags: ['设计', 'UI'],
    category: 'tool',
  },
]

/** 全网主流 AI 插件 / 脚本 / MCP 市场(50 项,2026-07 联网搜索) */
export const MARKET_PLUGINS: MarketPlugin[] = [
  // === 大模型厂商官方市场 ===
  {
    id: 'gpt-store',
    name: 'OpenAI GPT Store',
    description: 'OpenAI 官方 GPTs 市场,百万级自定义 GPT 机器人,涵盖工作 / 学习 / 生活',
    url: 'https://chatgpt.com/gpts',
    vendor: 'openai',
    fallbackIcon: Store,
    tags: ['GPTs', '官方'],
    category: 'market',
    free: true,
    official: true,
  },
  {
    id: 'claude-skills',
    name: 'Anthropic Claude',
    description: 'Claude 官方技能与工具市场,Artifacts / Computer Use / MCP 原生支持',
    url: 'https://anthropic.com/claude',
    vendor: 'anthropic',
    fallbackIcon: Star,
    tags: ['Claude', '官方'],
    category: 'market',
    official: true,
  },
  {
    id: 'gemini-gems',
    name: 'Google Gemini Gems',
    description: 'Google Gemini 官方定制 Gems 市场,个性化 AI 助手 / 多模态 / 原生多语言',
    url: 'https://gemini.google.com',
    vendor: 'google',
    fallbackIcon: Star,
    tags: ['Gemini', '官方'],
    category: 'market',
    free: true,
    official: true,
  },
  {
    id: 'grok',
    name: 'xAI Grok',
    description: 'Elon Musk 的 xAI 公司 Grok 模型,实时信息 / 幽默风格 / X 平台深度集成',
    url: 'https://x.ai',
    vendor: 'xai',
    fallbackIcon: Zap,
    tags: ['Grok', 'xAI'],
    category: 'market',
    official: true,
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    description: '欧洲 Mistral AI 开源模型平台,Mixtral / Codestral / 函数调用原生支持',
    url: 'https://mistral.ai',
    vendor: 'mistral',
    fallbackIcon: Star,
    tags: ['Mistral', '开源'],
    category: 'market',
    official: true,
  },
  {
    id: 'cohere',
    name: 'Cohere',
    description: 'Cohere 企业级 LLM 平台,Command R+ / Rerank / Embed 多模型协同',
    url: 'https://cohere.com',
    vendor: 'cohere',
    fallbackIcon: Star,
    tags: ['Cohere', '企业'],
    category: 'market',
    official: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    description: 'Perplexity AI 搜索引擎,实时联网 / 引用溯源 / Pro 模型多选',
    url: 'https://perplexity.ai',
    vendor: 'perplexity',
    fallbackIcon: Star,
    tags: ['搜索', '联网'],
    category: 'market',
    official: true,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek 深度求索',
    description: 'DeepSeek 开源大模型,V3 / R1 推理模型 / 极低价格 / 代码能力领先',
    url: 'https://deepseek.com',
    vendor: 'deepseek',
    fallbackIcon: Star,
    tags: ['DeepSeek', '开源'],
    category: 'market',
    free: true,
    official: true,
  },
  {
    id: 'qwen',
    name: '阿里通义千问',
    description: '阿里巴巴通义千问模型市场,Qwen 系列 / 开源闭源双线 / 多模态',
    url: 'https://qwen.com',
    vendor: 'qwen',
    fallbackIcon: Star,
    tags: ['Qwen', '阿里'],
    category: 'market',
    free: true,
    official: true,
  },
  {
    id: 'zhipu',
    name: '智谱 GLM',
    description: '智谱 AI GLM 系列模型市场,GLM-4 / CogVideoX / 开源 ChatGLM',
    url: 'https://open.bigmodel.cn',
    vendor: 'zhipu',
    fallbackIcon: Star,
    tags: ['GLM', '智谱'],
    category: 'market',
    official: true,
  },
  {
    id: 'moonshot',
    name: '月之暗面 Kimi',
    description: 'Moonshot AI Kimi 模型,超长上下文 / 文档解析 / 联网搜索',
    url: 'https://kimi.moonshot.cn',
    vendor: 'moonshot',
    fallbackIcon: Star,
    tags: ['Kimi', '长上下文'],
    category: 'market',
    official: true,
  },
  {
    id: 'doubao',
    name: '字节豆包',
    description: '字节跳动豆包大模型,火山引擎方舟平台 / 多模态 / 低价调用',
    url: 'https://volcengine.com/product/doubao',
    vendor: 'doubao',
    fallbackIcon: Star,
    tags: ['豆包', '字跳'],
    category: 'market',
    official: true,
  },
  {
    id: 'baidu-ernie',
    name: '百度文心',
    description: '百度文心一言 / ERNIE 模型市场,千帆平台 / 知识增强 / 产业级',
    url: 'https://yiyan.baidu.com',
    vendor: 'baidu',
    fallbackIcon: Star,
    tags: ['文心', '百度'],
    category: 'market',
    official: true,
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    description: 'MiniMax 大模型平台,abab 系列 / 语音合成 / 视频生成全栈',
    url: 'https://minimaxi.com',
    vendor: 'minimax',
    fallbackIcon: Star,
    tags: ['MiniMax', '多模态'],
    category: 'market',
    official: true,
  },
  {
    id: 'hunyuan',
    name: '腾讯混元',
    description: '腾讯混元大模型,多模态 / 长文本 / 微信生态深度集成',
    url: 'https://hunyuan.tencent.com',
    vendor: 'hunyuan',
    fallbackIcon: Star,
    tags: ['混元', '腾讯'],
    category: 'market',
    official: true,
  },
  {
    id: 'yi',
    name: '零一万物 Yi',
    description: '李开复零一万物 Yi 系列模型,开源 / 闭源 / 长上下文',
    url: 'https://lingyiwanwu.com',
    vendor: 'yi',
    fallbackIcon: Star,
    tags: ['Yi', '零一'],
    category: 'market',
    official: true,
  },
  {
    id: 'spark',
    name: '讯飞星火',
    description: '科大讯飞星火大模型,语音交互 / 教育场景 / 国产自主',
    url: 'https://xinghuo.xfyun.cn',
    vendor: 'spark',
    fallbackIcon: Star,
    tags: ['星火', '讯飞'],
    category: 'market',
    official: true,
  },
  {
    id: 'baichuan',
    name: '百川智能',
    description: '王小川百川大模型,Baichuan 系列 / 搜索增强 / 医疗垂类',
    url: 'https://baichuan-ai.com',
    vendor: 'baichuan',
    fallbackIcon: Star,
    tags: ['百川', '搜索'],
    category: 'market',
    official: true,
  },

  // === AI 应用开发平台 ===
  {
    id: 'coze',
    name: 'Coze 扣子',
    description: '字节跳动 AI Bot 开发平台,可视化编排 / 插件市场 / 知识库 / 工作流',
    url: 'https://www.coze.com',
    vendor: 'coze',
    fallbackIcon: Bot,
    tags: ['Bot', '字跳'],
    category: 'market',
    free: true,
    official: true,
  },
  {
    id: 'dify',
    name: 'Dify',
    description: 'Dify 开源 LLM 应用开发平台,工具 / 模型 / Agent 模板社区',
    url: 'https://dify.ai/marketplace',
    fallbackIcon: Boxes,
    tags: ['开源', 'LLMOps'],
    category: 'market',
    free: true,
  },
  {
    id: 'huggingface-spaces',
    name: 'Hugging Face Spaces',
    description: 'Hugging Face 模型演示空间,数十万 AI 应用 / Demo / 模型在线体验',
    url: 'https://huggingface.co/spaces',
    vendor: 'huggingface',
    fallbackIcon: Boxes,
    tags: ['Demo', '开源'],
    category: 'market',
    free: true,
    official: true,
  },
  {
    id: 'poe',
    name: 'Poe',
    description: 'Quora 旗下 Poe AI 平台,聚合 100+ 顶级模型 / 自定义 Bot / 一键创建',
    url: 'https://poe.com',
    fallbackIcon: Star,
    tags: ['聚合', 'Bot'],
    category: 'market',
    official: true,
  },
  {
    id: 'character-ai',
    name: 'Character.AI',
    description: 'Character.AI 角色对话平台,百万级 AI 角色 / 个性化 / 沉浸式',
    url: 'https://character.ai',
    fallbackIcon: Bot,
    tags: ['角色', '对话'],
    category: 'market',
    free: true,
  },
  {
    id: 'openwebui',
    name: 'OpenWebUI',
    description: '开源 AI Web UI,兼容 Ollama / OpenAI,内置工具 / 函数 / 知识库插件',
    url: 'https://openwebui.com',
    vendor: 'openwebui',
    fallbackIcon: Globe,
    tags: ['开源', 'Ollama'],
    category: 'market',
    free: true,
  },
  {
    id: 'lobehub-plugins',
    name: 'LobeHub Plugins',
    description: 'LobeChat 插件市场,数百个 AI 工具插件,搜索 / 联网 / 多模态',
    url: 'https://lobehub.com/plugins',
    fallbackIcon: Boxes,
    tags: ['插件', 'LobeChat'],
    category: 'market',
    free: true,
  },
  {
    id: 'flowise',
    name: 'Flowise',
    description: '开源无代码 LLM 应用构建器,拖拽式编排 / LangChain 可视化 / 自托管',
    url: 'https://flowiseai.com',
    fallbackIcon: Workflow,
    tags: ['无代码', '开源'],
    category: 'market',
    free: true,
  },
  {
    id: 'langflow',
    name: 'Langflow',
    description: 'DataStax 旗下开源 LangChain 可视化编排工具,拖拽构建 / 多模型',
    url: 'https://langflow.org',
    fallbackIcon: Workflow,
    tags: ['可视化', '开源'],
    category: 'market',
    free: true,
  },
  {
    id: 'anythingllm',
    name: 'AnythingLLM',
    description: '开源私有化 RAG 框架,文档问答 / 多用户 / 工作空间 / 自托管',
    url: 'https://anythingllm.com',
    fallbackIcon: Boxes,
    tags: ['RAG', '自托管'],
    category: 'market',
    free: true,
  },
  {
    id: 'privategpt',
    name: 'PrivateGPT',
    description: '开源私有化 LLM 框架,本地推理 / 文档问答 / 零数据泄露',
    url: 'https://privategpt.dev',
    fallbackIcon: ShieldCheck,
    tags: ['私有化', '本地'],
    category: 'market',
    free: true,
  },
  {
    id: 'quivr',
    name: 'Quivr',
    description: '开源 generative AI 第二大脑,知识库 / 多模型 / 团队协作',
    url: 'https://quivr.ai',
    fallbackIcon: Database,
    tags: ['第二大脑', '开源'],
    category: 'market',
    free: true,
  },

  // === 开发工具 / IDE 扩展 ===
  {
    id: 'cursor',
    name: 'Cursor',
    description: 'Cursor AI 代码编辑器,扩展市场 / MCP 集成 / 规则文件 / Agent 模式',
    url: 'https://cursor.com',
    fallbackIcon: MousePointer2,
    tags: ['IDE', '代码'],
    category: 'ide',
    official: true,
  },
  {
    id: 'vscode-marketplace',
    name: 'VSCode Marketplace',
    description: 'Visual Studio Code 扩展市场,AI 类扩展涵盖 Copilot / Continue / Cline',
    url: 'https://marketplace.visualstudio.com',
    vendor: 'microsoft',
    fallbackIcon: Code,
    tags: ['IDE', '微软'],
    category: 'ide',
    free: true,
    official: true,
  },
  {
    id: 'github-models',
    name: 'GitHub Models',
    description: 'GitHub 官方模型市场,免费体验主流 LLM,集成 Codespaces / Copilot',
    url: 'https://github.com/models',
    vendor: 'githubcopilot',
    fallbackIcon: Code,
    tags: ['模型', 'GitHub'],
    category: 'ide',
    free: true,
    official: true,
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    description: 'GitHub 官方 AI 编程助手,Copilot Chat / Agent / PR Review / 多 IDE 支持',
    url: 'https://github.com/features/copilot',
    vendor: 'githubcopilot',
    fallbackIcon: Code,
    tags: ['Copilot', '编程'],
    category: 'ide',
    official: true,
  },
  {
    id: 'cline',
    name: 'Cline',
    description: '开源 AI 编程 Agent,VSCode 扩展,支持 MCP / 自定义工具 / 浏览器控制',
    url: 'https://cline.bot',
    fallbackIcon: Terminal,
    tags: ['Agent', 'VSCode'],
    category: 'ide',
    free: true,
  },
  {
    id: 'continue',
    name: 'Continue',
    description: '开源 AI 编程助手,VSCode / JetBrains,自定义模型 / 代码补全 / Chat',
    url: 'https://continue.dev',
    fallbackIcon: Code,
    tags: ['开源', '补全'],
    category: 'ide',
    free: true,
  },
  {
    id: 'replit-agent',
    name: 'Replit Agent',
    description: 'Replit AI 编程 Agent 平台,云端开发环境 + Agent 商店 + 一键部署',
    url: 'https://replit.com',
    vendor: 'replit',
    fallbackIcon: Terminal,
    tags: ['IDE', '云端'],
    category: 'ide',
    official: true,
  },

  // === 协议 / 注册中心 / 模型聚合 ===
  {
    id: 'mcp-registry',
    name: 'MCP Registry',
    description: 'Model Context Protocol 官方服务器注册表,10000+ MCP Server 跨客户端复用',
    url: 'https://modelcontextprotocol.io',
    vendor: 'anthropic',
    fallbackIcon: Server,
    tags: ['MCP', '协议'],
    category: 'mcp',
    free: true,
    official: true,
  },
  {
    id: 'smithery',
    name: 'Smithery MCP',
    description: 'Smithery MCP Server 注册中心,一键安装 / 运行 / 管理 MCP 服务器',
    url: 'https://smithery.ai',
    fallbackIcon: Server,
    tags: ['MCP', '注册中心'],
    category: 'mcp',
    free: true,
  },
  {
    id: 'langchain-hub',
    name: 'LangChain Hub',
    description: 'LangChain 官方 Prompt / Agent / Tool 仓库,LangGraph 工作流模板社区',
    url: 'https://smith.langchain.com/hub',
    fallbackIcon: Link2,
    tags: ['Prompt', 'Tool'],
    category: 'market',
    free: true,
    official: true,
  },
  {
    id: 'langgraph',
    name: 'LangGraph Studio',
    description: 'LangGraph 官方可视化 Agent 编排与调试工具,状态图 / 断点 / 回放',
    url: 'https://langchain.com/langgraph',
    fallbackIcon: Workflow,
    tags: ['LangGraph', '编排'],
    category: 'market',
    official: true,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    description: '统一 LLM API 路由,300+ 模型聚合,内置函数调用 / 工具 / 结构化输出',
    url: 'https://openrouter.ai',
    vendor: 'openrouter',
    fallbackIcon: Link2,
    tags: ['API', '聚合'],
    category: 'model',
    free: true,
    official: true,
  },
  {
    id: 'together-ai',
    name: 'Together AI',
    description: 'Together AI 推理平台,开源模型加速 / Fine-tune / Embedding / 重排',
    url: 'https://together.ai',
    vendor: 'together',
    fallbackIcon: Cpu,
    tags: ['推理', '开源'],
    category: 'model',
    official: true,
  },
  {
    id: 'fireworks-ai',
    name: 'Fireworks AI',
    description: 'Fireworks AI 高速推理平台,开源模型 / serverless / 函数调用',
    url: 'https://fireworks.ai',
    vendor: 'fireworks',
    fallbackIcon: Zap,
    tags: ['推理', 'serverless'],
    category: 'model',
    official: true,
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'Groq 超低延迟推理平台,LPU 芯片 / 开源模型 / 毫秒级响应',
    url: 'https://groq.com',
    vendor: 'groq',
    fallbackIcon: Zap,
    tags: ['推理', 'LPU'],
    category: 'model',
    free: true,
    official: true,
  },
  {
    id: 'replicate',
    name: 'Replicate',
    description: 'Replicate 模型运行平台,开源模型 / API 调用 / 一键部署 / 图片视频生成',
    url: 'https://replicate.com',
    vendor: 'replicate',
    fallbackIcon: Layers,
    tags: ['模型', '部署'],
    category: 'model',
    official: true,
  },
  {
    id: 'huggingface-models',
    name: 'Hugging Face Models',
    description: 'Hugging Face 模型仓库,百万级开源模型 / 权重下载 / Inference API',
    url: 'https://huggingface.co/models',
    vendor: 'huggingface',
    fallbackIcon: Cpu,
    tags: ['模型', '开源'],
    category: 'model',
    free: true,
    official: true,
  },
  {
    id: 'ollama',
    name: 'Ollama',
    description: 'Ollama 本地大模型运行框架,一行命令跑 Llama / Qwen / DeepSeek / 离线',
    url: 'https://ollama.com',
    vendor: 'ollama',
    fallbackIcon: Cpu,
    tags: ['本地', '开源'],
    category: 'model',
    free: true,
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    description: 'Cerebras 超快推理平台,Wafer-Scale Engine / 极速 token 生成',
    url: 'https://cerebras.ai',
    vendor: 'cerebras',
    fallbackIcon: Cpu,
    tags: ['推理', '极速'],
    category: 'model',
    official: true,
  },
  {
    id: 'sambanova',
    name: 'SambaNova',
    description: 'SambaNova AI 推理平台,RDU 芯片 / 开源模型 / 企业级部署',
    url: 'https://sambanova.ai',
    vendor: 'sambanova',
    fallbackIcon: Cpu,
    tags: ['推理', '企业'],
    category: 'model',
    official: true,
  },

  // === 自动化 / 工作流平台 ===
  {
    id: 'n8n-templates',
    name: 'n8n Templates',
    description: 'n8n 工作流自动化平台模板市场,数千个 AI 工作流模板一键导入',
    url: 'https://n8n.io/templates',
    fallbackIcon: Workflow,
    tags: ['工作流', '自动化'],
    category: 'workflow',
    free: true,
  },
  {
    id: 'make-com',
    name: 'Make.com',
    description: 'Make 可视化自动化平台,1500+ 应用集成 / AI 节点 / 场景化模板',
    url: 'https://make.com',
    fallbackIcon: Workflow,
    tags: ['自动化', '集成'],
    category: 'workflow',
    official: true,
  },
  {
    id: 'zapier-ai',
    name: 'Zapier AI Actions',
    description: 'Zapier AI Actions 市场,7000+ 应用集成 / AI 中央 / Agent 自动化',
    url: 'https://zapier.com/ai',
    fallbackIcon: Zap,
    tags: ['自动化', 'AI'],
    category: 'workflow',
    official: true,
  },
  {
    id: 'pipedream',
    name: 'Pipedream',
    description: 'Pipedream 开发者自动化平台,2600+ 应用 / 代码 + 无代码 / AI 工作流',
    url: 'https://pipedream.com',
    fallbackIcon: Workflow,
    tags: ['自动化', '开发者'],
    category: 'workflow',
    free: true,
  },

  // === 云厂商 AI 平台 ===
  {
    id: 'aws-bedrock',
    name: 'AWS Bedrock',
    description: 'Amazon Bedrock 托管 LLM 服务,多模型 / Knowledge Base / Agent / Guardrails',
    url: 'https://aws.amazon.com/bedrock',
    vendor: 'bedrock',
    fallbackIcon: Building2,
    tags: ['AWS', '云'],
    category: 'market',
    official: true,
  },
  {
    id: 'azure-ai',
    name: 'Azure AI Foundry',
    description: 'Microsoft Azure AI Foundry 模型目录,OpenAI / 开源模型 / 多模态 / 企业级',
    url: 'https://ai.azure.com',
    vendor: 'azureai',
    fallbackIcon: Building2,
    tags: ['Azure', '云'],
    category: 'market',
    official: true,
  },
  {
    id: 'vertex-ai',
    name: 'Vertex AI Agent Builder',
    description: 'Google Cloud Vertex AI Agent Builder,企业级 Agent / RAG / 模型花园',
    url: 'https://cloud.google.com/vertex-ai',
    vendor: 'vertexai',
    fallbackIcon: Building2,
    tags: ['GCP', 'Agent'],
    category: 'market',
    official: true,
  },
  {
    id: 'copilot-studio',
    name: 'Microsoft Copilot Studio',
    description: 'Microsoft Copilot Studio 低代码 Agent 构建平台,深度集成 M365 生态',
    url: 'https://copilotstudio.microsoft.com',
    vendor: 'microsoft',
    fallbackIcon: Bot,
    tags: ['微软', 'Copilot'],
    category: 'market',
    official: true,
  },
  {
    id: 'siliconcloud',
    name: '硅基流动 SiliconCloud',
    description: 'SiliconCloud 国产模型聚合推理平台,开源模型 / 极低价格 / 高并发',
    url: 'https://siliconflow.cn',
    vendor: 'siliconcloud',
    fallbackIcon: Cpu,
    tags: ['推理', '国产'],
    category: 'model',
    free: true,
  },
  {
    id: 'modelscope',
    name: 'ModelScope 魔搭',
    description: '阿里达摩院 ModelScope 模型社区,国产开源模型 / Demo / 数据集',
    url: 'https://modelscope.cn',
    vendor: 'modelscope',
    fallbackIcon: Cpu,
    tags: ['模型', '阿里'],
    category: 'model',
    free: true,
    official: true,
  },
  {
    id: 'volcengine',
    name: '火山方舟',
    description: '字节跳动火山引擎方舟大模型平台,豆包 / 多模型 / 精调 / 推理加速',
    url: 'https://volcengine.com/product/ark',
    vendor: 'volcengine',
    fallbackIcon: Cpu,
    tags: ['火山', '字跳'],
    category: 'model',
    official: true,
  },
  {
    id: 'bailian',
    name: '阿里百炼',
    description: '阿里云百炼大模型平台,通义系列 / 精调 / RAG / Agent 一站式',
    url: 'https://bailian.console.aliyun.com',
    vendor: 'bailian',
    fallbackIcon: Cpu,
    tags: ['百炼', '阿里'],
    category: 'model',
    official: true,
  },
]
