// © 2026 IHUI AI (智汇AI) · 版权所有者: 李春川 (Li Chunchuan) · https://aizhs.top
// Provenance-watermarked. 未授权商用可被溯源追责 (Apache-2.0 须保留本声明与 NOTICE)。
// [IHUI-AI-PROVENANCE]:⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠

// GENERATED FILE — DO NOT EDIT. 由 apps/mobile-rn/scripts/generate-ui-routes.mjs 生成(pnpm gen:ui-routes)
// 数据源:RootNavigator.tsx 已登录分支的 <RootStack.Screen name/> + <MainTabs.Screen name/>
//        + RootStackParamList 必填参数键 + navigation/linking.ts 的 :param 模式。
// 改路由请改 RootNavigator.tsx 后重新生成。

/** AI 可导航 Screen 条目:name 是 react-navigation 的 screen name(不是 URL 路径) */
export interface RnUiRouteEntry {
  /** Screen name,如 'Wallet';navigate 白名单就是它 */
  name: string
  /** 是否 Main(Bottom Tabs)的子 tab:true 必须走 navigate('Main', { screen: name }) */
  tab: boolean
  /** 该 Screen 的参数类型里是否存在必填键(必填页缺参数时注册表按此报错并点名缺哪个键) */
  requiresParams: boolean
  /** requiresParams 的具体键名,如 ["id"];给 AI 的报错文案用,避免它反复试错 */
  requiredParams: string[]
}

/** 全量白名单:前 199 条是已登录分支 RootStack.Screen,后 5 条是 Main Tab */
export const RN_UI_ROUTES: readonly RnUiRouteEntry[] = [
  { name: 'Main', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Home', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Chat', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'OrderRefund', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Payment', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Vip', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AIMultimodal', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'CourseEnroll', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'LivePlayback', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Note', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'StudyRecord', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Exam', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'CourseFilter', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'LiveList', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Coupon', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'PointsMall', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'PointsRecord', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'TaskCenter', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'CheckIn', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Ranking', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Promote', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Distribution', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Team', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Withdraw', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'BankCard', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'RealNameAuth', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'IdentityVerify', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'SecuritySettings', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Privacy', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Agreement', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'About', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Help', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Feedback', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'CustomerService', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Announcement', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Activity', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Promotion', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Referrer', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Invite', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'QrCode', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'NotificationSettings', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AgentReviewList', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AgentStat', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AgentSetting', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Carte', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'ApiSettings', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'ModelEdit', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'CourseAnnex', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'CourseResource', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'CourseQAList', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'CourseQAAsk', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'LivePreview', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'LivePlaybackList', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'OrderLog', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'OrderTrack', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'RefundDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'RefundHistory', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'PointRule', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'PointHistory', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'VipLevel', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'VipBenefit', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'VipCompare', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'CertList', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'CertApply', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'MessageSystem', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'MessageDirect', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'MessageGroup', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AnnouncementDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'FeedbackHistory', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'FeedbackDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'SettingsAccount', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'OrderDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'CourseChapter', tab: false, requiresParams: true, requiredParams: ['courseId'] },
  { name: 'CourseComment', tab: false, requiresParams: true, requiredParams: ['courseId'] },
  { name: 'CourseCatalog', tab: false, requiresParams: true, requiredParams: ['courseId'] },
  { name: 'LiveChat', tab: false, requiresParams: true, requiredParams: ['liveId'] },
  { name: 'LiveHost', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'ChangePhone', tab: false, requiresParams: true, requiredParams: ['uuid'] },
  { name: 'Income', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AgentDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'AgentChat', tab: false, requiresParams: true, requiredParams: ['agentId', 'name'] },
  { name: 'AgentMarket', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AgentCreate', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'ArticleDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'ArticleList', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'PostDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'PostCreate', tab: false, requiresParams: true, requiredParams: ['name'] },
  { name: 'CircleDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'CircleCreate', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'CircleMember', tab: false, requiresParams: true, requiredParams: ['circleId'] },
  { name: 'CircleChat', tab: false, requiresParams: true, requiredParams: ['circleId', 'name'] },
  { name: 'AskDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'AskCreate', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AskList', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'NoteDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'NoteCreate', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'NoteList', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'StudyPlan', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'StudyProgress', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'ExamResult', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'ExamHistory', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'ExamQuestion', tab: false, requiresParams: true, requiredParams: ['examId'] },
  { name: 'CertDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'CertVerify', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'MessageDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'MessageChat', tab: false, requiresParams: true, requiredParams: ['peerId', 'name'] },
  { name: 'NotificationList', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Search', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'History', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Bookmark', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Share', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'SharedDemo', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Recharge', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AigcCover', tab: false, requiresParams: true, requiredParams: ['id', 'title'] },
  { name: 'AigcPublish', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Learn', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'News', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Plaza', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'CoursePlanet', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'LearnDevelop', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'StudyIndex', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'KnowledgePlanet', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AccountCancel', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'BusinessLicense', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'IcpRecord', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'ModelRecord', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'UsageRules', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AppPermission', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'TokenValue', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AiGroup', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AiAssistant', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AigcList', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'ModelPlaza', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Developer', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'BusinessCard', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Recruitment', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'VipTrader', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'DevEnter', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'N8nModel', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'ModelIncome', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AiCareer', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Assistant', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'ChangePwd', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'TopupSuccess', tab: false, requiresParams: true, requiredParams: ['amount', 'orderId'] },
  { name: 'TopupFail', tab: false, requiresParams: false, requiredParams: [] },
  {
    name: 'CategoryDetail',
    tab: false,
    requiresParams: true,
    requiredParams: ['categoryId', 'title'],
  },
  { name: 'RankingDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'TeamDetail', tab: false, requiresParams: true, requiredParams: ['memberId'] },
  { name: 'DistributionOrderList', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'EarnCommission', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'StudyPublish', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AiAssistantN8n', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'MoreCourse', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'DevEnterCover', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'PlazaCover', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'SetNeed', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'SubPackageIndex', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AppTopup', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'KnowledgeBase', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'KnowledgeCreate', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'KnowledgeDoc', tab: false, requiresParams: true, requiredParams: ['id', 'title'] },
  { name: 'AiSkill', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AiSkillDetail', tab: false, requiresParams: true, requiredParams: ['id', 'name'] },
  { name: 'Memory', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'AiWorld', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Publish', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'ImageGenHistory', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'ImageGenCreate', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Spec', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'SelfMedia', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Context', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'PdfTools', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'WebView', tab: false, requiresParams: true, requiredParams: ['url'] },
  { name: 'ChatTools', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'WebPortal', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'KnowledgeRag', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Subagents', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'ConversationImport', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'CourseDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  {
    name: 'VideoPlayer',
    tab: false,
    requiresParams: true,
    requiredParams: ['courseId', 'lessonId'],
  },
  { name: 'LiveDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'Order', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Wallet', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Settings', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Favorites', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Favorite', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Follow', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Subscriptions', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Certificate', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'MessageCenter', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'ProfileEdit', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'Agent', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'TeacherList', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'TeacherDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'Cart', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'PayResult', tab: false, requiresParams: true, requiredParams: ['orderNo'] },
  { name: 'TopicList', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'TopicDetail', tab: false, requiresParams: true, requiredParams: ['id'] },
  { name: 'CircleIndex', tab: false, requiresParams: false, requiredParams: [] },
  { name: 'HomeMain', tab: true, requiresParams: false, requiredParams: [] },
  { name: 'CourseMain', tab: true, requiresParams: false, requiredParams: [] },
  { name: 'AiMain', tab: true, requiresParams: false, requiredParams: [] },
  { name: 'LiveMain', tab: true, requiresParams: false, requiredParams: [] },
  { name: 'ProfileMain', tab: true, requiresParams: false, requiredParams: [] },
]

// ⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠
