import type { CompetitorConfig } from '../types'

export const COMPETITORS_PART_6: Partial<Record<CompetitorConfig['id'], CompetitorConfig>> = {
  'qwen-platform': {
    id: 'qwen-platform',
    name: 'Tongyi Qianwen / 通义千问',
    tagline: '通义千问是阿里大模型平台;IHUI AI 跨 30+ 模型中立 + Agent 市场化',
    verdict:
      '如果只用通义千问模型 API,阿里平台够用;如果需要跨模型调度 + Agent 编排 + 六端分发 + 团队协作,IHUI AI 是更完整方案。',
    rows: [
      {
        dimension: '定位',
        ihui: '全栈 AI 操作系统',
        competitor: '阿里大模型平台',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端',
        competitorDetail: '模型 API + 阿里云集成',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'Web + API',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '需自行开发客户端',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '部分开源(Qwen 模型)',
        ihuiDetail: '平台完全开源',
        competitorDetail: '模型开源,平台闭源',
      },
      {
        dimension: '私有化部署',
        ihui: '完整支持',
        competitor: '受限',
        ihuiDetail: 'Docker Compose + K8s',
        competitorDetail: '需阿里云灵积 API 或自部署 Qwen',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: 'API 调用',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '需自己写编排逻辑',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 多格式',
        competitor: '需自建',
        ihuiDetail: '向量 + BM25 + 知识图谱',
        competitorDetail: '需对接阿里云向量检索',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型中立',
        competitor: '仅通义系列',
        ihuiDetail: '跨厂商 + 自动 fallback',
        competitorDetail: 'Qwen-Max/Plus/Turbo',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '阿里云 RAM',
        ihuiDetail: '多租户工作区',
        competitorDetail: '依赖阿里云权限',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '按 token 计费',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '云版按量,无统一积分',
      },
    ],
  },
  'kimi-platform': {
    id: 'kimi-platform',
    name: 'Kimi / 月之暗面',
    tagline: 'Kimi 在长文本对话方面有特色;IHUI AI 是全栈 Agent 操作系统(含 Kimi 模型)',
    verdict:
      '如果只需要长文本阅读/对话,Kimi 体验较好;如果需要构建 Agent 产品 + 知识库 + 跨端分发 + 团队协作,IHUI AI 是更完整方案(且可接入 Kimi 模型)。',
    rows: [
      {
        dimension: '定位',
        ihui: '全栈 AI 操作系统',
        competitor: '长文本 AI 助手',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端',
        competitorDetail: '200 万字长文本对话',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'Web + APP',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: 'Web + 移动 APP',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '闭源',
        ihuiDetail: '完全开源可商用',
        competitorDetail: '闭源 SaaS',
      },
      {
        dimension: '私有化部署',
        ihui: '完整支持',
        competitor: '不支持',
        ihuiDetail: 'Docker Compose + K8s',
        competitorDetail: '仅 Kimi 云端',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: '基础对话',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '无 Agent 编排',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 多格式',
        competitor: '文件上传对话',
        ihuiDetail: '向量 + BM25 + 知识图谱',
        competitorDetail: '临时文件解析,无持久化知识库',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型(含 Kimi)',
        competitor: '仅 Kimi',
        ihuiDetail: '可接入 Kimi + GPT + Claude 等',
        competitorDetail: '锁定 Moonshot 模型',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '个人账号',
        ihuiDetail: '多租户企业级',
        competitorDetail: '无企业协作',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '免费 + Pro ¥X/月',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '按 token 计费',
      },
    ],
  },
  doubao: {
    id: 'doubao',
    name: 'Doubao / 豆包',
    tagline: '豆包是字节 C 端 AI 助手;IHUI AI 是企业级开源 Agent 平台',
    verdict:
      '如果个人日常问答/创作,豆包免费好用;如果企业需要私有化部署 + 数据主权 + Agent 编排 + 跨端分发,IHUI AI 是更合适的选择。',
    rows: [
      {
        dimension: '定位',
        ihui: '企业级 Agent 操作系统',
        competitor: 'C 端 AI 助手',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端',
        competitorDetail: '日常对话 + 创作 + 抖音生态',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'Web + APP',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '字节系 APP 为主',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '闭源',
        ihuiDetail: '完全开源可商用',
        competitorDetail: '闭源 SaaS',
      },
      {
        dimension: '私有化部署',
        ihui: '完整支持',
        competitor: '不支持',
        ihuiDetail: 'Docker Compose + K8s',
        competitorDetail: '仅字节云',
      },
      {
        dimension: '数据主权',
        ihui: '自托管 100% 数据自有',
        competitor: '字节云托管',
        ihuiDetail: '数据不出域',
        competitorDetail: '数据由字节掌控',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: '基础对话 + 扣子集成',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '需配合扣子平台',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型中立',
        competitor: '仅豆包系列',
        ihuiDetail: '跨厂商 + 自动 fallback',
        competitorDetail: '豆包 Pro/Lite/Function call',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '个人账号',
        ihuiDetail: '多租户企业级',
        competitorDetail: '无企业协作',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '免费',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '免费但有调用上限',
      },
    ],
  },
}
