import type { CompetitorConfig } from '../types'

export const COMPETITORS_PART_10: Partial<Record<CompetitorConfig['id'], CompetitorConfig>> = {
  // 2026-07-26 阶段 9 新增:AI 编程助手 8 个(2025-2026 现象级,搜索量极高)
  'claude-code': {
    id: 'claude-code',
    name: 'Claude Code',
    tagline: 'Claude Code 是终端内 AI 编程助手;IHUI AI 是含代码 Agent 的全栈 AI 操作系统',
    verdict:
      '如果你的团队主要在终端写代码且只用 Claude 模型,Claude Code 体验流畅;如果你需要 Agent 市场 + 知识库 RAG + 六端分发 + 多模型调度 + 团队协作 + 私有化部署,IHUI AI 是更完整的企业级方案。',
    rows: [
      {
        dimension: '定位',
        ihui: '六端同源全栈 AI 操作系统',
        competitor: '终端内 AI 编程助手',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端分发',
        competitorDetail: '专注 CLI 内代码生成与编辑',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'CLI only',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '仅命令行,无 GUI 客户端',
      },
      {
        dimension: 'Agent 市场',
        ihui: true,
        competitor: false,
        ihuiDetail: '200+ 模板 + 创作者分成 + 一键 fork',
        competitorDetail: '无 Agent 市场概念',
      },
      {
        dimension: '知识库 RAG',
        ihui: true,
        competitor: '代码上下文为主',
        ihuiDetail: '向量 + BM25 + 知识图谱,企业私有知识库',
        competitorDetail: '依赖本地代码仓库上下文',
      },
      {
        dimension: '多模型调度',
        ihui: true,
        competitor: false,
        ihuiDetail: '30+ 模型统一调度 + 自动 fallback + 成本路由',
        competitorDetail: '仅 Claude 系列模型(Anthropic)',
      },
      {
        dimension: 'MCP 工具协议',
        ihui: true,
        competitor: true,
        ihuiDetail: '原生 MCP,100+ 预置 Server',
        competitorDetail: 'Claude Code 原生支持 MCP',
      },
      {
        dimension: '工作流编排',
        ihui: true,
        competitor: false,
        ihuiDetail: 'n8n 风格节点画布 + 触发器 + 条件分支',
        competitorDetail: '无工作流编排能力',
      },
      {
        dimension: '团队协作',
        ihui: true,
        competitor: '基础',
        ihuiDetail: '多租户 + RBAC + 审计日志 + SSO',
        competitorDetail: '个人 API Key,无企业协作',
      },
      {
        dimension: '私有化部署',
        ihui: true,
        competitor: false,
        ihuiDetail: 'Apache 2.0 + Docker Compose + K8s',
        competitorDetail: '闭源 SaaS,数据过 Anthropic',
      },
      {
        dimension: '编程语言支持',
        ihui: '全栈代码 Agent(多语言)',
        competitor: '多语言(主流)',
        ihuiDetail: '代码 Agent 是六端之一,支持多语言',
        competitorDetail: 'Python/JS/TS/Go/Rust 等主流语言',
      },
      {
        dimension: 'IDE 集成',
        ihui: '六端含 CLI + 扩展',
        competitor: '终端 + IDE 适配',
        ihuiDetail: 'CLI 端 + 浏览器扩展端原生集成',
        competitorDetail: '通过 MCP 与 VS Code/JetBrains 联动',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '$20/月起(Pro)',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '按订阅计费,无自托管',
      },
    ],
  },
  cursor: {
    id: 'cursor',
    name: 'Cursor',
    tagline: 'Cursor 是 AI IDE(代码补全 + Chat);IHUI AI 是含代码 Agent 的全栈操作系统',
    verdict:
      '如果你是个人开发者专注写代码,Cursor IDE 体验优秀;如果企业需要 Agent 市场 + 知识库 RAG + 六端分发 + 团队协作 + 私有化,IHUI AI 是更完整方案(且 IHUI CLI 端同样支持代码生成)。',
    rows: [
      {
        dimension: '定位',
        ihui: '六端同源全栈 AI 操作系统',
        competitor: 'AI 优先 IDE(VS Code fork)',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端分发',
        competitorDetail: '专注代码补全 + Chat + Agent',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: '桌面 IDE only',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: 'macOS/Windows/Linux 桌面应用',
      },
      {
        dimension: 'Agent 市场',
        ihui: true,
        competitor: false,
        ihuiDetail: '200+ 模板 + 创作者分成 + 一键 fork',
        competitorDetail: '无 Agent 市场概念',
      },
      {
        dimension: '知识库 RAG',
        ihui: true,
        competitor: '代码库索引',
        ihuiDetail: '向量 + BM25 + 知识图谱,企业私有知识库',
        competitorDetail: '专注本地代码索引(@codebase)',
      },
      {
        dimension: '多模型调度',
        ihui: true,
        competitor: true,
        ihuiDetail: '30+ 模型统一调度 + 自动 fallback + 成本路由',
        competitorDetail: '支持 Claude/GPT/Gemini 等主流模型',
      },
      {
        dimension: 'MCP 工具协议',
        ihui: true,
        competitor: true,
        ihuiDetail: '原生 MCP,100+ 预置 Server',
        competitorDetail: 'Cursor 0.42+ 原生支持 MCP',
      },
      {
        dimension: '工作流编排',
        ihui: true,
        competitor: false,
        ihuiDetail: 'n8n 风格节点画布 + 触发器 + 条件分支',
        competitorDetail: '无工作流编排能力',
      },
      {
        dimension: '团队协作',
        ihui: true,
        competitor: '基础',
        ihuiDetail: '多租户 + RBAC + 审计日志 + SSO',
        competitorDetail: 'Cursor Pro/Teams 基础团队功能',
      },
      {
        dimension: '私有化部署',
        ihui: true,
        competitor: false,
        ihuiDetail: 'Apache 2.0 + Docker Compose + K8s',
        competitorDetail: '闭源 SaaS,数据过 Cursor 云',
      },
      {
        dimension: '编程语言支持',
        ihui: '全栈代码 Agent(多语言)',
        competitor: '多语言(全栈)',
        ihuiDetail: '代码 Agent 是六端之一,支持多语言',
        competitorDetail: 'Python/JS/TS/Go/Rust/Java 等',
      },
      {
        dimension: 'IDE 集成',
        ihui: '六端含 CLI + 扩展',
        competitor: '原生 IDE',
        ihuiDetail: 'CLI 端 + 浏览器扩展端原生集成',
        competitorDetail: 'Cursor 本身即 IDE,体验较为完善',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '$20/月起(Pro)',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '按订阅计费,无自托管',
      },
    ],
  },
  'github-copilot': {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    tagline: 'GitHub Copilot 是老牌 AI 编程助手;IHUI AI 是含代码 Agent 的全栈操作系统',
    verdict:
      '如果你的团队已深度使用 GitHub + VS Code 生态,GitHub Copilot 集成较自然;如果需要 Agent 编排 + 知识库 + 工作流 + 六端分发 + 私有化部署,IHUI AI 是更完整的企业级方案。',
    rows: [
      {
        dimension: '定位',
        ihui: '六端同源全栈 AI 操作系统',
        competitor: 'AI 编程助手(IDE 插件)',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端分发',
        competitorDetail: '专注代码补全 + Chat + Workspace',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'IDE 插件 only',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: 'VS Code/JetBrains/Visual Studio/Neovim',
      },
      {
        dimension: 'Agent 市场',
        ihui: true,
        competitor: false,
        ihuiDetail: '200+ 模板 + 创作者分成 + 一键 fork',
        competitorDetail: '无 Agent 市场概念',
      },
      {
        dimension: '知识库 RAG',
        ihui: true,
        competitor: '代码库 + GitHub 仓库',
        ihuiDetail: '向量 + BM25 + 知识图谱,企业私有知识库',
        competitorDetail: '@workspace 索引 GitHub 仓库',
      },
      {
        dimension: '多模型调度',
        ihui: true,
        competitor: '部分',
        ihuiDetail: '30+ 模型统一调度 + 自动 fallback',
        competitorDetail: 'GPT/Claude/Gemini 有限选择',
      },
      {
        dimension: 'MCP 工具协议',
        ihui: true,
        competitor: true,
        ihuiDetail: '原生 MCP,100+ 预置 Server',
        competitorDetail: 'Copilot 2025 起支持 MCP',
      },
      {
        dimension: '工作流编排',
        ihui: true,
        competitor: false,
        ihuiDetail: 'n8n 风格节点画布 + 触发器 + 条件分支',
        competitorDetail: '无工作流编排能力',
      },
      {
        dimension: '团队协作',
        ihui: true,
        competitor: '基础',
        ihuiDetail: '多租户 + RBAC + 审计日志 + SSO',
        competitorDetail: 'Copilot Business/Enterprise 席位',
      },
      {
        dimension: '私有化部署',
        ihui: true,
        competitor: false,
        ihuiDetail: 'Apache 2.0 + Docker Compose + K8s',
        competitorDetail: '闭源 SaaS,数据过 GitHub 云',
      },
      {
        dimension: '编程语言支持',
        ihui: '全栈代码 Agent(多语言)',
        competitor: '多语言(全栈)',
        ihuiDetail: '代码 Agent 是六端之一,支持多语言',
        competitorDetail: '20+ 主流编程语言',
      },
      {
        dimension: 'IDE 集成',
        ihui: '六端含 CLI + 扩展',
        competitor: '原生 IDE 集成',
        ihuiDetail: 'CLI 端 + 浏览器扩展端原生集成',
        competitorDetail: 'VS Code/JetBrains 深度集成',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '$10/月起(Business)',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '按席位计费,无自托管',
      },
    ],
  },
}
