import type { CompetitorConfig } from '../types'

export const COMPETITORS_PART_11: Partial<Record<CompetitorConfig['id'], CompetitorConfig>> = {
  windsurf: {
    id: 'windsurf',
    name: 'Windsurf',
    tagline: 'Windsurf 是 Codeium 出品 AI IDE;IHUI AI 是含代码 Agent 的全栈操作系统',
    verdict:
      '如果你喜欢 Codeium 风格的 AI IDE 体验,Windsurf 流畅;如果企业需要 Agent 市场 + 知识库 + 工作流 + 六端分发 + 私有化部署,IHUI AI 是更完整方案。',
    rows: [
      {
        dimension: '定位',
        ihui: '六端同源全栈 AI 操作系统',
        competitor: 'AI 优先 IDE(Codeium 出品)',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端分发',
        competitorDetail: '专注代码补全 + Cascade Agent',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: '桌面 IDE only',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: 'macOS/Windows/Linux 桌面应用',
      },
      {
        dimension: 'Agent 市场',
        ihui: true,
        competitor: false,
        ihuiDetail: '200+ 模板 + 创作者分成 + 一键 fork',
        competitorDetail: '无 Agent 市场概念',
      },
      {
        dimension: '知识库 RAG',
        ihui: true,
        competitor: '代码库索引',
        ihuiDetail: '向量 + BM25 + 知识图谱,企业私有知识库',
        competitorDetail: '专注本地代码索引',
      },
      {
        dimension: '多模型调度',
        ihui: true,
        competitor: true,
        ihuiDetail: '30+ 模型统一调度 + 自动 fallback',
        competitorDetail: '支持 Claude/GPT/Gemini 等',
      },
      {
        dimension: 'MCP 工具协议',
        ihui: true,
        competitor: true,
        ihuiDetail: '原生 MCP,100+ 预置 Server',
        competitorDetail: 'Windsurf 原生支持 MCP',
      },
      {
        dimension: '工作流编排',
        ihui: true,
        competitor: false,
        ihuiDetail: 'n8n 风格节点画布 + 触发器 + 条件分支',
        competitorDetail: '无工作流编排能力',
      },
      {
        dimension: '团队协作',
        ihui: true,
        competitor: '基础',
        ihuiDetail: '多租户 + RBAC + 审计日志 + SSO',
        competitorDetail: 'Windsurf Teams 基础团队功能',
      },
      {
        dimension: '私有化部署',
        ihui: true,
        competitor: false,
        ihuiDetail: 'Apache 2.0 + Docker Compose + K8s',
        competitorDetail: '闭源 SaaS,数据过 Codeium 云',
      },
      {
        dimension: '编程语言支持',
        ihui: '全栈代码 Agent(多语言)',
        competitor: '多语言(全栈)',
        ihuiDetail: '代码 Agent 是六端之一,支持多语言',
        competitorDetail: '40+ 编程语言',
      },
      {
        dimension: 'IDE 集成',
        ihui: '六端含 CLI + 扩展',
        competitor: '原生 IDE',
        ihuiDetail: 'CLI 端 + 浏览器扩展端原生集成',
        competitorDetail: 'Windsurf 本身即 IDE',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '$15/月起(Pro)',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '按订阅计费,无自托管',
      },
    ],
  },
  'bolt-new': {
    id: 'bolt-new',
    name: 'Bolt.new',
    tagline: 'Bolt.new 是浏览器内全栈应用生成;IHUI AI 是含代码 Agent 的全栈操作系统',
    verdict:
      '如果你需要快速原型生成全栈 Web 应用,Bolt.new 体验流畅;如果企业需要 Agent 市场 + 知识库 + 工作流 + 六端分发 + 团队协作 + 私有化,IHUI AI 是更完整方案。',
    rows: [
      {
        dimension: '定位',
        ihui: '六端同源全栈 AI 操作系统',
        competitor: '浏览器内全栈应用生成',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端分发',
        competitorDetail: '专注 prompt → 全栈应用一键生成',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'Web only',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '仅 Web 应用(StackBlitz WebContainer)',
      },
      {
        dimension: 'Agent 市场',
        ihui: true,
        competitor: false,
        ihuiDetail: '200+ 模板 + 创作者分成 + 一键 fork',
        competitorDetail: '无 Agent 市场概念',
      },
      {
        dimension: '知识库 RAG',
        ihui: true,
        competitor: false,
        ihuiDetail: '向量 + BM25 + 知识图谱,企业私有知识库',
        competitorDetail: '无知识库 RAG 能力',
      },
      {
        dimension: '多模型调度',
        ihui: true,
        competitor: true,
        ihuiDetail: '30+ 模型统一调度 + 自动 fallback',
        competitorDetail: '支持 Claude/GPT 等(有限选择)',
      },
      {
        dimension: 'MCP 工具协议',
        ihui: true,
        competitor: false,
        ihuiDetail: '原生 MCP,100+ 预置 Server',
        competitorDetail: '不支持 MCP 协议',
      },
      {
        dimension: '工作流编排',
        ihui: true,
        competitor: false,
        ihuiDetail: 'n8n 风格节点画布 + 触发器 + 条件分支',
        competitorDetail: '无工作流编排能力',
      },
      {
        dimension: '团队协作',
        ihui: true,
        competitor: '基础',
        ihuiDetail: '多租户 + RBAC + 审计日志 + SSO',
        competitorDetail: '基础项目分享,无企业协作',
      },
      {
        dimension: '私有化部署',
        ihui: true,
        competitor: false,
        ihuiDetail: 'Apache 2.0 + Docker Compose + K8s',
        competitorDetail: '闭源 SaaS,数据过 StackBlitz 云',
      },
      {
        dimension: '编程语言支持',
        ihui: '全栈代码 Agent(多语言)',
        competitor: 'JS/TS 全栈为主',
        ihuiDetail: '代码 Agent 是六端之一,支持多语言',
        competitorDetail: '专注 JavaScript/TypeScript 全栈',
      },
      {
        dimension: 'IDE 集成',
        ihui: '六端含 CLI + 扩展',
        competitor: '浏览器内 IDE',
        ihuiDetail: 'CLI 端 + 浏览器扩展端原生集成',
        competitorDetail: 'StackBlitz WebContainer 在线 IDE',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '$20/月起(Pro)',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '按 token + 订阅计费',
      },
    ],
  },
  'replit-agent': {
    id: 'replit-agent',
    name: 'Replit Agent',
    tagline: 'Replit Agent 是云端 IDE + AI Agent;IHUI AI 是含代码 Agent 的全栈操作系统',
    verdict:
      '如果你需要云端协作开发 + 一键部署,Replit Agent 体验流畅;如果企业需要 Agent 市场 + 知识库 + 工作流 + 六端分发 + 私有化 + 团队协作,IHUI AI 是更完整方案。',
    rows: [
      {
        dimension: '定位',
        ihui: '六端同源全栈 AI 操作系统',
        competitor: '云端 IDE + AI Agent',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端分发',
        competitorDetail: '专注云端开发 + 部署 + AI Agent',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'Web + 移动 APP',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: 'Web IDE + iOS/Android APP',
      },
      {
        dimension: 'Agent 市场',
        ihui: true,
        competitor: false,
        ihuiDetail: '200+ 模板 + 创作者分成 + 一键 fork',
        competitorDetail: '无 Agent 市场概念',
      },
      {
        dimension: '知识库 RAG',
        ihui: true,
        competitor: false,
        ihuiDetail: '向量 + BM25 + 知识图谱,企业私有知识库',
        competitorDetail: '无知识库 RAG 能力',
      },
      {
        dimension: '多模型调度',
        ihui: true,
        competitor: true,
        ihuiDetail: '30+ 模型统一调度 + 自动 fallback',
        competitorDetail: '支持 Claude/GPT 等(有限选择)',
      },
      {
        dimension: 'MCP 工具协议',
        ihui: true,
        competitor: '部分',
        ihuiDetail: '原生 MCP,100+ 预置 Server',
        competitorDetail: '通过工具调用支持有限 MCP',
      },
      {
        dimension: '工作流编排',
        ihui: true,
        competitor: false,
        ihuiDetail: 'n8n 风格节点画布 + 触发器 + 条件分支',
        competitorDetail: '无工作流编排能力',
      },
      {
        dimension: '团队协作',
        ihui: true,
        competitor: '基础',
        ihuiDetail: '多租户 + RBAC + 审计日志 + SSO',
        competitorDetail: 'Replit Teams 基础协作',
      },
      {
        dimension: '私有化部署',
        ihui: true,
        competitor: false,
        ihuiDetail: 'Apache 2.0 + Docker Compose + K8s',
        competitorDetail: '闭源 SaaS,数据过 Replit 云',
      },
      {
        dimension: '编程语言支持',
        ihui: '全栈代码 Agent(多语言)',
        competitor: '多语言(全栈)',
        ihuiDetail: '代码 Agent 是六端之一,支持多语言',
        competitorDetail: '50+ 编程语言',
      },
      {
        dimension: 'IDE 集成',
        ihui: '六端含 CLI + 扩展',
        competitor: '云端 IDE',
        ihuiDetail: 'CLI 端 + 浏览器扩展端原生集成',
        competitorDetail: 'Replit 云端 IDE 原生体验',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '$25/月起(Core)',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '按订阅 + 计算资源计费',
      },
    ],
  },
}
