import type { CompetitorConfig } from '../types'

export const COMPETITORS_PART_8: Partial<Record<CompetitorConfig['id'], CompetitorConfig>> = {
  minimax: {
    id: 'minimax',
    name: 'MiniMax',
    tagline: 'MiniMax 是多模态大模型 API;IHUI AI 含 MiniMax + Agent 编排 + 六端',
    verdict:
      '如果只需多模态模型 API(文本/语音/视频),MiniMax 直接够用;如果需要 Agent 编排 + 知识库 + 工作流 + 六端分发 + 团队协作,IHUI AI 是更完整方案。',
    rows: [
      {
        dimension: '定位',
        ihui: '全栈 AI 操作系统',
        competitor: '多模态大模型 API',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端',
        competitorDetail: 'abab 系列 + 语音/视频',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'API + 海螺 AI',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: 'API + 海螺 APP',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '闭源',
        ihuiDetail: '完全开源可商用',
        competitorDetail: '闭源 API',
      },
      {
        dimension: '私有化部署',
        ihui: '完整支持',
        competitor: '不支持',
        ihuiDetail: 'Docker Compose + K8s',
        competitorDetail: '仅 MiniMax 云端',
      },
      {
        dimension: '多模态',
        ihui: '可对接 MiniMax/百度/字节',
        competitor: '原生支持',
        ihuiDetail: '灵活对接多家',
        competitorDetail: '文本/语音/视频原生',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: 'API 调用',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '需自己写编排',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型(含 MiniMax)',
        competitor: '仅 MiniMax',
        ihuiDetail: 'MiniMax + GPT + Claude + Qwen',
        competitorDetail: 'abab6 / abab5.5 / 语音',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: 'API Key',
        ihuiDetail: '多租户企业级',
        competitorDetail: '基础 Key 管理',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '按 token 计费',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '按量计费',
      },
    ],
  },
  // 2026-07-26 阶段 8 新增:国际 SaaS 6 个(海外 AI 检索长尾)
  'zapier-ai': {
    id: 'zapier-ai',
    name: 'Zapier AI Actions',
    tagline: 'Zapier 偏自动化集成;IHUI AI 在工作流上叠加 LLM + Agent + 六端',
    verdict:
      '如果只需连接 SaaS 工具做自动化,Zapier 集成生态较丰富;如果需要 LLM/Agent 作为工作流核心 + 知识库 + 六端分发 + 团队协作,IHUI AI 是更 AI-native 的选择。',
    rows: [
      {
        dimension: '定位',
        ihui: 'AI 优先的全栈操作系统',
        competitor: '自动化集成平台',
        ihuiDetail: 'LLM/Agent 是一等公民',
        competitorDetail: '7000+ SaaS 集成,LLM 是节点',
      },
      {
        dimension: 'AI 能力',
        ihui: '原生 AI 优先',
        competitor: 'AI Actions(中央编排)',
        ihuiDetail: 'Agent + 知识库 + 工作流一体',
        competitorDetail: '通过 Zapier Central 调用 LLM',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: '基础 AI Actions',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '预置 AI Action 模板',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 多格式',
        competitor: '需对接外部',
        ihuiDetail: '向量 + BM25 + 知识图谱',
        competitorDetail: '通过 Zapier 接 Vector DB',
      },
      {
        dimension: '客户端',
        ihui: '6 端同源',
        competitor: 'Web + API',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: 'Web + Zapier 集成',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '闭源 SaaS',
        ihuiDetail: '完全开源可商用',
        competitorDetail: '闭源,无自托管',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '团队账户',
        ihuiDetail: '多租户企业级',
        competitorDetail: '基础团队协作',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '$19.99/月起',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '按任务数计费',
      },
    ],
  },
  make: {
    id: 'make',
    name: 'Make.com',
    tagline: 'Make.com 是可视化自动化;IHUI AI 是 AI 优先的全栈操作系统',
    verdict:
      '如果需要可视化自动化连接 SaaS,Make 体验优秀;如果需要 LLM/Agent 为核心 + 知识库 + 六端分发 + 私有化,IHUI AI 是更 AI-native 的选择。',
    rows: [
      {
        dimension: '定位',
        ihui: 'AI 优先全栈操作系统',
        competitor: '可视化自动化平台',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端',
        competitorDetail: '拖拽场景 + 1800+ app',
      },
      {
        dimension: 'AI 能力',
        ihui: '原生 AI 优先',
        competitor: 'AI 模块(OpenAI 等)',
        ihuiDetail: 'LLM/Agent 是核心',
        competitorDetail: 'AI 作为模块之一',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: '可视化场景',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '场景模板库',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 多格式',
        competitor: '需对接外部',
        ihuiDetail: '向量 + BM25 + 知识图谱',
        competitorDetail: '接 Pinecone/Weaviate',
      },
      {
        dimension: '客户端',
        ihui: '6 端同源',
        competitor: 'Web + API',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: 'Web + Make API',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '闭源 SaaS',
        ihuiDetail: '完全开源可商用',
        competitorDetail: '闭源,无自托管',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '团队 + 角色',
        ihuiDetail: '多租户企业级',
        competitorDetail: '基础团队协作',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '$9/月起',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '按操作数计费',
      },
    ],
  },
}
