import type { CompetitorConfig } from '../types'

export const COMPETITORS_PART_5: Partial<Record<CompetitorConfig['id'], CompetitorConfig>> = {
  flowise: {
    id: 'flowise',
    name: 'Flowise',
    tagline: 'Flowise 是可视化 LangChain;IHUI AI 是含可视化 + 市场的全栈操作系统',
    verdict:
      '如果你只需要可视化拖拽 LLM 流程,Flowise 轻量;如果需要 Agent 市场 + 跨端 + 团队协作 + 私有化,IHUI AI 更完整。',
    rows: [
      {
        dimension: '定位',
        ihui: '全栈 AI 操作系统',
        competitor: '可视化 LLM 应用构建',
        ihuiDetail: '含市场 + 跨端 + 协作',
        competitorDetail: '专注拖拽流程',
      },
      {
        dimension: '产品形态',
        ihui: '完整 OS(6 端 + 后端 + DB)',
        competitor: 'Web 应用',
        ihuiDetail: '开箱即用 6 端',
        competitorDetail: '仅 Web',
      },
      {
        dimension: 'Agent 市场',
        ihui: '200+ 模板 + 创作者分成',
        competitor: '模板库(社区)',
        ihuiDetail: '一键 fork 商用',
        competitorDetail: '需自己改造',
      },
      {
        dimension: '客户端',
        ihui: '6 端同源',
        competitor: 'Web only',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '仅 Web 应用',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 30+ 数据源',
        competitor: '基础 RAG 节点',
        ihuiDetail: '向量 + BM25 + 知识图谱',
        competitorDetail: '需自己配',
      },
      {
        dimension: 'MCP',
        ihui: '原生 + 100+ 预置',
        competitor: '需适配',
        ihuiDetail: '标准 MCP 生态',
        competitorDetail: '自己包装',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型 + 统一计费',
        competitor: '多模型',
        ihuiDetail: '统一积分 + 成本路由',
        competitorDetail: '需分别配凭证',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '基础多用户',
        ihuiDetail: '多租户企业级',
        competitorDetail: '简单权限',
      },
      {
        dimension: '工作流',
        ihui: 'n8n 风格画布 + 触发器',
        competitor: 'LangChain 拖拽',
        ihuiDetail: '业务人员可上手',
        competitorDetail: '需懂 LangChain',
      },
      {
        dimension: '私有化',
        ihui: 'Apache 2.0',
        competitor: 'Apache 2.0',
        ihuiDetail: 'Docker/K8s 一键',
        competitorDetail: 'Docker 部署',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '免费(开源)',
        ihuiDetail: '云版统一积分',
        competitorDetail: '自己承担 LLM 成本',
      },
    ],
  },
  typebot: {
    id: 'typebot',
    name: 'Typebot',
    tagline: 'Typebot 是开源聊天机器人构建器;IHUI AI 是含聊天 + Agent + RAG 的全栈操作系统',
    verdict:
      '如果你只需要可视化聊天机器人(表单/问卷),Typebot 专业;如果需要 AI Agent + 知识库 + 工作流 + 跨端,IHUI AI 更完整。',
    rows: [
      {
        dimension: '定位',
        ihui: '全栈 AI 操作系统',
        competitor: '聊天机器人构建器',
        ihuiDetail: '含 Agent + RAG + 工作流',
        competitorDetail: '专注聊天流程',
      },
      {
        dimension: '产品形态',
        ihui: '完整 OS(6 端 + 后端 + DB)',
        competitor: 'Web 应用',
        ihuiDetail: '开箱即用 6 端',
        competitorDetail: '仅 Web + 嵌入',
      },
      {
        dimension: 'AI 能力',
        ihui: 'Agent + RAG + 工作流',
        competitor: '聊天流程 + LLM 节点',
        ihuiDetail: '完整 AI 栈',
        competitorDetail: 'LLM 是节点之一',
      },
      {
        dimension: 'Agent 市场',
        ihui: '200+ 模板 + 创作者分成',
        competitor: '模板库',
        ihuiDetail: '一键 fork 商用',
        competitorDetail: '需自己改造',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 30+ 数据源',
        competitor: '基础',
        ihuiDetail: '向量 + BM25 + 知识图谱',
        competitorDetail: '需自己接',
      },
      {
        dimension: '客户端',
        ihui: '6 端同源',
        competitor: 'Web + 嵌入',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: 'Web + iframe',
      },
      {
        dimension: 'MCP',
        ihui: '原生 + 100+ 预置',
        competitor: '需适配',
        ihuiDetail: '标准 MCP 生态',
        competitorDetail: '自己包装',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型 + 统一计费',
        competitor: '多模型',
        ihuiDetail: '统一积分 + 成本路由',
        competitorDetail: '需分别配凭证',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '多工作区',
        ihuiDetail: '多租户企业级',
        competitorDetail: '基础协作',
      },
      {
        dimension: '私有化',
        ihui: 'Apache 2.0',
        competitor: 'AGPL',
        ihuiDetail: 'Docker/K8s 一键',
        competitorDetail: 'Docker 部署',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '免费(自托管)',
        ihuiDetail: '云版统一积分',
        competitorDetail: '云版按对话计费',
      },
    ],
  },
  // 2026-07-26 阶段 8 新增:国内 AI 平台 8 个(高频搜索长尾)
  ernie: {
    id: 'ernie',
    name: 'ERNIE Bot / 文心一言',
    tagline: '文心一言是百度 C 端 AI 助手;IHUI AI 是企业级 Agent 操作系统',
    verdict:
      '如果只是个人问答对话,文心一言够用;如果企业需要构建专属 Agent + 私有知识库 + 跨端分发 + 团队协作,IHUI AI 是更系统化的选择。',
    rows: [
      {
        dimension: '定位',
        ihui: '企业级 Agent 操作系统',
        competitor: 'C 端通用 AI 助手',
        ihuiDetail: 'Agent 市场 + 知识库 + 工作流 + 六端分发',
        competitorDetail: '问答对话 + 百度生态集成',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'Web + APP + 小程序',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '百度系 APP 为主',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '闭源',
        ihuiDetail: '完全开源可商用可审计',
        competitorDetail: '闭源 SaaS,无法自托管',
      },
      {
        dimension: '私有化部署',
        ihui: '完整支持',
        competitor: '不支持',
        ihuiDetail: 'Docker Compose + K8s 离线部署',
        competitorDetail: '仅百度云端',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化拖拽 + 200+ 模板',
        competitor: '基础对话 + 插件',
        ihuiDetail: 'Agent 市场 + 一键 fork + 创作者分成',
        competitorDetail: '插件生态,无 Agent 市场',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 向量/BM25/知识图谱',
        competitor: '百度搜索集成',
        ihuiDetail: '企业私有知识库,数据不出域',
        competitorDetail: '依赖百度搜索,无私有知识库',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型中立',
        competitor: '仅 ERNIE 系列',
        ihuiDetail: 'GPT/Claude/Gemini/Qwen/DeepSeek/ERNIE 等',
        competitorDetail: 'ERNIE 4.0 / Speed / Lite',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '个人账号',
        ihuiDetail: '多租户 + 积分共享 + 审计日志',
        competitorDetail: '无企业协作功能',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '免费 + Pro ¥49.9/月',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '按 token 计费,无自托管',
      },
    ],
  },
}
