import type { CompetitorConfig } from '../types'

export const COMPETITORS_PART_12: Partial<Record<CompetitorConfig['id'], CompetitorConfig>> = {
  lovable: {
    id: 'lovable',
    name: 'Lovable',
    tagline: 'Lovable 是全栈应用生成(prompt → 应用);IHUI AI 是含代码 Agent 的全栈操作系统',
    verdict:
      '如果你需要快速生成全栈 Web 应用(类似 Bolt.new),Lovable 体验流畅;如果企业需要 Agent 市场 + 知识库 + 工作流 + 六端分发 + 私有化 + 团队协作,IHUI AI 是更完整方案。',
    rows: [
      {
        dimension: '定位',
        ihui: '六端同源全栈 AI 操作系统',
        competitor: '全栈应用生成(prompt → 应用)',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端分发',
        competitorDetail: '专注 prompt → 全栈 Web 应用一键生成',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'Web only',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '仅 Web 应用生成',
      },
      {
        dimension: 'Agent 市场',
        ihui: true,
        competitor: false,
        ihuiDetail: '200+ 模板 + 创作者分成 + 一键 fork',
        competitorDetail: '无 Agent 市场概念',
      },
      {
        dimension: '知识库 RAG',
        ihui: true,
        competitor: false,
        ihuiDetail: '向量 + BM25 + 知识图谱,企业私有知识库',
        competitorDetail: '无知识库 RAG 能力',
      },
      {
        dimension: '多模型调度',
        ihui: true,
        competitor: true,
        ihuiDetail: '30+ 模型统一调度 + 自动 fallback',
        competitorDetail: '支持 Claude/GPT 等(有限选择)',
      },
      {
        dimension: 'MCP 工具协议',
        ihui: true,
        competitor: false,
        ihuiDetail: '原生 MCP,100+ 预置 Server',
        competitorDetail: '不支持 MCP 协议',
      },
      {
        dimension: '工作流编排',
        ihui: true,
        competitor: false,
        ihuiDetail: 'n8n 风格节点画布 + 触发器 + 条件分支',
        competitorDetail: '无工作流编排能力',
      },
      {
        dimension: '团队协作',
        ihui: true,
        competitor: '基础',
        ihuiDetail: '多租户 + RBAC + 审计日志 + SSO',
        competitorDetail: '基础项目分享,无企业协作',
      },
      {
        dimension: '私有化部署',
        ihui: true,
        competitor: false,
        ihuiDetail: 'Apache 2.0 + Docker Compose + K8s',
        competitorDetail: '闭源 SaaS,数据过 Lovable 云',
      },
      {
        dimension: '编程语言支持',
        ihui: '全栈代码 Agent(多语言)',
        competitor: 'JS/TS 全栈为主',
        ihuiDetail: '代码 Agent 是六端之一,支持多语言',
        competitorDetail: '专注 JavaScript/TypeScript 全栈',
      },
      {
        dimension: 'IDE 集成',
        ihui: '六端含 CLI + 扩展',
        competitor: '在线编辑器',
        ihuiDetail: 'CLI 端 + 浏览器扩展端原生集成',
        competitorDetail: 'Web IDE + GitHub 集成',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '$25/月起(Pro)',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '按 token + 订阅计费',
      },
    ],
  },
  'v0-dev': {
    id: 'v0-dev',
    name: 'v0.dev',
    tagline: 'v0.dev 是 Vercel UI 组件生成;IHUI AI 是含代码 Agent 的全栈操作系统',
    verdict:
      '如果你只需要生成 Next.js + Tailwind UI 组件,v0.dev 体验流畅;如果企业需要后端 + Agent 市场 + 知识库 + 工作流 + 六端分发 + 团队协作,IHUI AI 是更完整方案。',
    rows: [
      {
        dimension: '定位',
        ihui: '六端同源全栈 AI 操作系统',
        competitor: 'UI 组件生成(Next.js + Tailwind)',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端分发',
        competitorDetail: '专注前端 UI 组件生成',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'Web only',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '仅 Web UI 生成',
      },
      {
        dimension: 'Agent 市场',
        ihui: true,
        competitor: false,
        ihuiDetail: '200+ 模板 + 创作者分成 + 一键 fork',
        competitorDetail: '无 Agent 市场概念',
      },
      {
        dimension: '知识库 RAG',
        ihui: true,
        competitor: false,
        ihuiDetail: '向量 + BM25 + 知识图谱,企业私有知识库',
        competitorDetail: '无知识库 RAG 能力',
      },
      {
        dimension: '多模型调度',
        ihui: true,
        competitor: '部分',
        ihuiDetail: '30+ 模型统一调度 + 自动 fallback',
        competitorDetail: '主要使用 OpenAI + Anthropic',
      },
      {
        dimension: 'MCP 工具协议',
        ihui: true,
        competitor: false,
        ihuiDetail: '原生 MCP,100+ 预置 Server',
        competitorDetail: '不支持 MCP 协议',
      },
      {
        dimension: '工作流编排',
        ihui: true,
        competitor: false,
        ihuiDetail: 'n8n 风格节点画布 + 触发器 + 条件分支',
        competitorDetail: '无工作流编排能力',
      },
      {
        dimension: '团队协作',
        ihui: true,
        competitor: '基础',
        ihuiDetail: '多租户 + RBAC + 审计日志 + SSO',
        competitorDetail: 'Vercel 账户基础协作',
      },
      {
        dimension: '私有化部署',
        ihui: true,
        competitor: false,
        ihuiDetail: 'Apache 2.0 + Docker Compose + K8s',
        competitorDetail: '闭源 SaaS,数据过 Vercel 云',
      },
      {
        dimension: '后端能力',
        ihui: '完整后端 + 数据库 + API',
        competitor: '仅前端 UI',
        ihuiDetail: 'Fastify 5 + Drizzle ORM + PostgreSQL',
        competitorDetail: '只生成 React/Next.js 前端组件',
      },
      {
        dimension: 'IDE 集成',
        ihui: '六端含 CLI + 扩展',
        competitor: '在线编辑器 + Vercel',
        ihuiDetail: 'CLI 端 + 浏览器扩展端原生集成',
        competitorDetail: 'Web 编辑器 + Vercel 平台部署',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '$20/月起(Premium)',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '按订阅 + credit 计费',
      },
    ],
  },
}
