import type { CompetitorConfig } from '../types'

export const COMPETITORS_PART_4: Partial<Record<CompetitorConfig['id'], CompetitorConfig>> = {
  // 2026-07-26 阶段 7 新增:5 个长尾对比页(开源生态扩展)
  autogen: {
    id: 'autogen',
    name: 'Microsoft AutoGen',
    tagline: 'AutoGen 是多 Agent 代码框架;IHUI AI 是完整生产就绪操作系统',
    verdict:
      '如果你是研究员/工程师想精细控制多 Agent 对话,AutoGen 灵活;如果需要生产就绪 UI、Agent 市场、跨端分发、私有化,IHUI AI 是更优选择。',
    rows: [
      {
        dimension: '产品形态',
        ihui: '完整 OS(UI + 后端 + DB)',
        competitor: 'Python SDK',
        ihuiDetail: '开箱即用',
        competitorDetail: '需自建前后端',
      },
      {
        dimension: '多 Agent 协作',
        ihui: '可视化 + 代码双模式',
        competitor: '代码编排(GroupChat',
        ihuiDetail: '业务人员也能用',
        competitorDetail: 'AssistantAgent 编程式',
      },
      {
        dimension: 'Agent 市场',
        ihui: '200+ 模板 + 创作者分成',
        competitor: '无',
        ihuiDetail: '一键 fork 商用',
        competitorDetail: '需自己写',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 30+ 数据源',
        competitor: '需自己接',
        ihuiDetail: '向量 + BM25 + 知识图谱',
        competitorDetail: '配 LlamaIndex 等',
      },
      {
        dimension: '客户端',
        ihui: '6 端同源',
        competitor: 'SDK 调用',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '自己写前端',
      },
      {
        dimension: 'MCP 协议',
        ihui: '原生 + 100+ 预置',
        competitor: '需适配',
        ihuiDetail: '标准 MCP 生态',
        competitorDetail: '自己包装工具',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '无',
        ihuiDetail: '多租户企业级',
        competitorDetail: '需自建',
      },
      {
        dimension: '私有化',
        ihui: 'Apache 2.0 + 完整文档',
        competitor: 'MIT + 自托管',
        ihuiDetail: 'Docker/K8s 一键部署',
        competitorDetail: '需自己搭',
      },
      {
        dimension: '工作流',
        ihui: '可视化画布',
        competitor: '代码对话',
        ihuiDetail: '触发器 + 条件分支',
        competitorDetail: 'Agent 间消息传递',
      },
      {
        dimension: '监控',
        ihui: '内置 + 仪表盘',
        competitor: '基础日志',
        ihuiDetail: 'Agent 性能 + 成本',
        competitorDetail: '需自己接',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '免费(MIT)',
        ihuiDetail: '云版统一积分',
        competitorDetail: '自己承担 LLM 成本',
      },
    ],
  },
  crewai: {
    id: 'crewai',
    name: 'CrewAI',
    tagline: 'CrewAI 是角色扮演多 Agent 框架;IHUI AI 是全栈 AI 操作系统',
    verdict:
      '如果你喜欢"角色分工"模式快速原型,CrewAI 简洁;如果需要生产级 UI、Agent 市场、跨端、团队协作,IHUI AI 更完整。',
    rows: [
      {
        dimension: '产品形态',
        ihui: '完整 OS(UI + 后端 + DB)',
        competitor: 'Python SDK',
        ihuiDetail: '开箱即用',
        competitorDetail: '需自建前后端',
      },
      {
        dimension: 'Agent 协作模式',
        ihui: '可视化 + 代码 + 角色',
        competitor: '角色扮演(Role-Playing',
        ihuiDetail: '多种编排方式',
        competitorDetail: 'Agent 角色分工',
      },
      {
        dimension: 'Agent 市场',
        ihui: '200+ 模板 + 创作者分成',
        competitor: '无',
        ihuiDetail: '一键 fork 商用',
        competitorDetail: '需自己写',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 多格式',
        competitor: '需自己接',
        ihuiDetail: '向量 + BM25',
        competitorDetail: '配外部工具',
      },
      {
        dimension: '客户端',
        ihui: '6 端同源',
        competitor: 'SDK',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '自己写前端',
      },
      {
        dimension: 'MCP',
        ihui: '原生 + 100+ 预置',
        competitor: '需适配',
        ihuiDetail: '标准 MCP 生态',
        competitorDetail: '自己包装工具',
      },
      {
        dimension: '工作流',
        ihui: '可视化画布',
        competitor: '代码流程',
        ihuiDetail: '触发器 + 条件分支',
        competitorDetail: 'Process 编程式',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '无',
        ihuiDetail: '多租户企业级',
        competitorDetail: '需自建',
      },
      {
        dimension: '监控',
        ihui: '内置 + 仪表盘',
        competitor: '基础',
        ihuiDetail: 'Agent 性能 + 成本',
        competitorDetail: '需自己接',
      },
      {
        dimension: '私有化',
        ihui: 'Apache 2.0 + 完整文档',
        competitor: 'MIT',
        ihuiDetail: 'Docker/K8s 一键',
        competitorDetail: '自己搭',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '免费(MIT)',
        ihuiDetail: '云版统一积分',
        competitorDetail: '自己承担 LLM 成本',
      },
    ],
  },
  llamaindex: {
    id: 'llamaindex',
    name: 'LlamaIndex',
    tagline: 'LlamaIndex 是数据连接 + RAG 框架;IHUI AI 是含 RAG 的全栈操作系统',
    verdict:
      '如果你只需要 RAG 数据管道,LlamaIndex 专业;如果需要 RAG + Agent + 工作流 + 跨端 + 团队协作,IHUI AI 更完整。',
    rows: [
      {
        dimension: '定位',
        ihui: '全栈 AI 操作系统',
        competitor: '数据连接 + RAG 框架',
        ihuiDetail: 'RAG 是组件之一',
        competitorDetail: '专注数据摄入 + 检索',
      },
      {
        dimension: '产品形态',
        ihui: '完整 OS(UI + 后端 + DB)',
        competitor: 'Python/TS SDK',
        ihuiDetail: '开箱即用',
        competitorDetail: '需自建前后端',
      },
      {
        dimension: 'RAG 能力',
        ihui: '向量 + BM25 + 知识图谱',
        competitor: '专业 + 丰富索引',
        ihuiDetail: '中文友好',
        competitorDetail: '索引类型多但需配置',
      },
      {
        dimension: 'Agent 市场',
        ihui: '200+ 模板',
        competitor: '无',
        ihuiDetail: '一键 fork 商用',
        competitorDetail: '需自己写',
      },
      {
        dimension: '工作流',
        ihui: '可视化画布',
        competitor: '代码编排',
        ihuiDetail: '业务人员可上手',
        competitorDetail: 'Workflow 编程式',
      },
      {
        dimension: '客户端',
        ihui: '6 端同源',
        competitor: 'SDK',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '自己写前端',
      },
      {
        dimension: 'MCP',
        ihui: '原生 + 100+ 预置',
        competitor: '需适配',
        ihuiDetail: '标准 MCP 生态',
        competitorDetail: '自己包装工具',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '无',
        ihuiDetail: '多租户企业级',
        competitorDetail: '需自建',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型 + 统一计费',
        competitor: '多模型 LlamaIndex',
        ihuiDetail: '统一积分 + 成本路由',
        competitorDetail: '需分别配凭证',
      },
      {
        dimension: '私有化',
        ihui: 'Apache 2.0',
        competitor: 'MIT',
        ihuiDetail: 'Docker/K8s 一键',
        competitorDetail: '自己搭',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '免费(MIT)',
        ihuiDetail: '云版统一积分',
        competitorDetail: '自己承担 LLM 成本',
      },
    ],
  },
}
