import type { CompetitorConfig } from '../types'

export const COMPETITORS_PART_7: Partial<Record<CompetitorConfig['id'], CompetitorConfig>> = {
  'deepseek-platform': {
    id: 'deepseek-platform',
    name: 'DeepSeek Platform',
    tagline: 'DeepSeek 是推理模型 API;IHUI AI 含 DeepSeek + 30+ 模型 + Agent 编排',
    verdict:
      '如果只需调用 DeepSeek API,官方平台较直接;如果需要 Agent 编排 + 知识库 + 工作流 + 六端分发 + 团队协作,IHUI AI 是更完整方案(且原生支持 DeepSeek 模型)。',
    rows: [
      {
        dimension: '定位',
        ihui: '全栈 AI 操作系统',
        competitor: '大模型 API 平台',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端',
        competitorDetail: 'V3/R1/Reasoner API',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'API only',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '需自行开发客户端',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '模型 MIT(平台闭源)',
        ihuiDetail: '平台完全开源',
        competitorDetail: '模型权重开源,平台闭源',
      },
      {
        dimension: '私有化部署',
        ihui: '完整支持',
        competitor: '模型可自部署',
        ihuiDetail: 'Docker Compose + K8s',
        competitorDetail: '需自部署 DeepSeek 模型 + 自建平台',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: 'API 调用',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '需自己写编排',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 多格式',
        competitor: '需自建',
        ihuiDetail: '向量 + BM25 + 知识图谱',
        competitorDetail: '需对接外部向量库',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型(含 DeepSeek)',
        competitor: '仅 DeepSeek',
        ihuiDetail: 'DeepSeek + GPT + Claude + Qwen 等',
        competitorDetail: 'V3 / R1 / Reasoner',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: 'API Key 管理',
        ihuiDetail: '多租户企业级',
        competitorDetail: '基础 Key 管理',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '按 token 计费(极低)',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: 'API 极低价,但需自建平台',
      },
    ],
  },
  zhipu: {
    id: 'zhipu',
    name: 'Zhipu Qingyan / 智谱清言',
    tagline: '智谱清言是 GLM 模型应用;IHUI AI 跨模型 + Agent 市场 + 六端分发',
    verdict:
      '如果只用 GLM 系列模型,智谱清言够用;如果需要跨模型调度 + Agent 编排 + 六端分发 + 团队协作,IHUI AI 是更完整方案(且原生支持 GLM 模型)。',
    rows: [
      {
        dimension: '定位',
        ihui: '全栈 AI 操作系统',
        competitor: 'GLM 模型应用平台',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端',
        competitorDetail: 'GLM-4 + 智能体 + 阿里云集成',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'Web + APP',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: 'Web + 移动 APP',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '部分开源(GLM 模型)',
        ihuiDetail: '平台完全开源',
        competitorDetail: 'GLM 模型部分开源,平台闭源',
      },
      {
        dimension: '私有化部署',
        ihui: '完整支持',
        competitor: '受限',
        ihuiDetail: 'Docker Compose + K8s',
        competitorDetail: '需自部署 GLM 模型 + 自建平台',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: '智谱智能体',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '智谱智能体平台',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 多格式',
        competitor: '需自建',
        ihuiDetail: '向量 + BM25 + 知识图谱',
        competitorDetail: '需对接外部向量库',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型(含 GLM)',
        competitor: '仅 GLM 系列',
        ihuiDetail: 'GLM + GPT + Claude + Qwen 等',
        competitorDetail: 'GLM-4 / GLM-4-Plus / GLM-4V',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '个人 + 团队空间',
        ihuiDetail: '多租户企业级',
        competitorDetail: '基础团队功能',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '免费 + 按量',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: 'GLM-4 按量计费',
      },
    ],
  },
  spark: {
    id: 'spark',
    name: 'iFlytek Spark / 讯飞星火',
    tagline: '星火偏教育/语音 AI;IHUI AI 是全栈 Agent 操作系统跨行业',
    verdict:
      '如果业务聚焦教育/语音交互,讯飞星火生态成熟;如果需要跨行业 Agent 编排 + 六端分发 + 私有化 + 团队协作,IHUI AI 是更通用方案。',
    rows: [
      {
        dimension: '定位',
        ihui: '全栈 AI 操作系统',
        competitor: '教育/语音 AI 平台',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端',
        competitorDetail: '星火大模型 + 讯飞语音 + 教育',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'Web + APP + 硬件',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '讯飞硬件 + APP',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '闭源',
        ihuiDetail: '完全开源可商用',
        competitorDetail: '闭源 SaaS',
      },
      {
        dimension: '私有化部署',
        ihui: '完整支持',
        competitor: '企业版支持',
        ihuiDetail: 'Docker Compose + K8s',
        competitorDetail: '讯飞企业版(付费)',
      },
      {
        dimension: '语音能力',
        ihui: '可对接讯飞/百度/Whisper',
        competitor: '原生支持(TTS/ASR) 较完善',
        ihuiDetail: '灵活对接多家语音',
        competitorDetail: '讯飞语音原生集成',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: '基础智能体',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '讯飞 AIUI 平台',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型中立',
        competitor: '仅星火系列',
        ihuiDetail: '星火 + GPT + Claude + Qwen 等',
        competitorDetail: 'Spark Max/Pro/Mini',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '企业版',
        ihuiDetail: '多租户企业级',
        competitorDetail: '讯飞企业版协作',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '免费 + 企业版',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '企业版按席位',
      },
    ],
  },
}
