import type { CompetitorConfig } from '../types'

export const COMPETITORS_PART_2: Partial<Record<CompetitorConfig['id'], CompetitorConfig>> = {
  n8n: {
    id: 'n8n',
    name: 'n8n',
    tagline: 'n8n 偏工作流自动化;IHUI AI 在工作流上叠加 LLM + Agent + 六端',
    verdict:
      '如果你的需求是纯工作流自动化(无 AI),n8n 生态更丰富;如果你需要 LLM/Agent 作为工作流核心节点,IHUI AI 是更合适的选择。',
    rows: [
      {
        dimension: '定位',
        ihui: '全栈 AI 操作系统,含工作流',
        competitor: '工作流自动化平台',
        ihuiDetail: '工作流是组件,LLM/Agent 是一等公民',
        competitorDetail: '通用工作流,LLM 只是一个节点',
      },
      {
        dimension: 'AI 能力',
        ihui: '原生 AI 优先',
        competitor: '作为节点集成',
        ihuiDetail: 'LLM/Agent/Knowledge Base 是核心模块',
        competitorDetail: '通过 AI 节点接入,需自己配',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化拖拽 + 200+ 模板',
        competitor: '无 Agent 概念',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '需自己用 LLM 节点搭建',
      },
      {
        dimension: '知识库',
        ihui: '内置 RAG 模块',
        competitor: '需通过 Pinecone 等外部集成',
        ihuiDetail: '向量 + BM25 混合检索',
        competitorDetail: '外部向量库集成',
      },
      {
        dimension: 'MCP',
        ihui: true,
        competitor: '有限',
        ihuiDetail: '原生 MCP,100+ 预置',
        competitorDetail: '通过社区节点',
      },
      {
        dimension: '客户端',
        ihui: '6 端',
        competitor: 'Web + 自托管',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: 'Web 编辑器 + 自托管',
      },
      {
        dimension: '多模型',
        ihui: '10+ 模型 + 统一计费',
        competitor: '通过节点接入',
        ihuiDetail: 'OpenAI/Claude/Gemini 等',
        competitorDetail: '需分别配凭证',
      },
      {
        dimension: '工作流节点',
        ihui: 'AI 节点 + 通用节点',
        competitor: '通用节点(400+)',
        ihuiDetail: 'AI 节点更丰富',
        competitorDetail: '集成节点更丰富',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: 'Sustainable Use License',
        ihuiDetail: '完全开源,商业可用',
        competitorDetail: 'SUL 限制商业竞争',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '多用户协作',
        ihuiDetail: '多租户 + 积分共享',
        competitorDetail: '协作功能较基础',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '云版按工作流执行计费',
        ihuiDetail: '统一积分',
        competitorDetail: '按执行次数',
      },
    ],
  },
  'openai-agent': {
    id: 'openai-agent',
    name: 'OpenAI Agent Builder',
    tagline: 'OpenAI Agent Builder 锁定 OpenAI 生态;IHUI AI 跨 30+ 模型中立',
    verdict:
      '如果你的项目全栈使用 OpenAI 且不需要私有化,OpenAI Agent Builder 够用;如果你需要多模型切换、私有化部署、数据主权,IHUI AI 是更灵活的选择。',
    rows: [
      {
        dimension: '模型选择',
        ihui: '30+ 模型中立',
        competitor: '仅 OpenAI 系列',
        ihuiDetail: 'GPT-4o / Claude / Gemini / DeepSeek / Qwen 等',
        competitorDetail: 'GPT-4o / o1 / o3 系列',
      },
      {
        dimension: '开源',
        ihui: 'Apache 2.0',
        competitor: '闭源',
        ihuiDetail: '完全开源可审计',
        competitorDetail: '闭源,黑盒',
      },
      {
        dimension: '私有化',
        ihui: '完整支持',
        competitor: '不支持',
        ihuiDetail: 'Docker Compose / K8s 离线部署',
        competitorDetail: '仅 OpenAI 云端',
      },
      {
        dimension: '数据主权',
        ihui: '自托管 100% 自主',
        competitor: 'OpenAI 托管',
        ihuiDetail: '数据不出域',
        competitorDetail: '数据经 OpenAI',
      },
      {
        dimension: 'Agent 市场',
        ihui: '200+ 模板 + 创作者分成',
        competitor: 'GPT Store',
        ihuiDetail: 'Apache 2.0 可商用',
        competitorDetail: 'OpenAI 审核上架',
      },
      {
        dimension: '客户端',
        ihui: '6 端同源',
        competitor: 'Web API',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: 'SDK 自行开发',
      },
      {
        dimension: 'MCP 协议',
        ihui: '原生支持',
        competitor: '部分支持',
        ihuiDetail: '100+ 预置 MCP Server',
        competitorDetail: 'MCP 规范新发布',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 可对接外部',
        competitor: '需自己实现',
        ihuiDetail: '向量 + BM25 + 中文友好',
        competitorDetail: '依赖 Assistants File Search',
      },
      {
        dimension: '工作流',
        ihui: '可视化画布',
        competitor: '代码编排',
        ihuiDetail: '拖拽节点 + 触发器',
        competitorDetail: '主要靠 SDK 代码',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: 'OpenAI Workspace 基础',
        ihuiDetail: '多租户企业级',
        competitorDetail: '适合小团队',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '按 token 计费',
        ihuiDetail: '统一积分,跨模型成本优化',
        competitorDetail: 'GPT-4o 较贵,无优化空间',
      },
    ],
  },
  langchain: {
    id: 'langchain',
    name: 'LangChain / LangGraph',
    tagline: 'LangChain 是 Python SDK 框架;IHUI AI 是完整生产就绪操作系统',
    verdict:
      '如果你是研究/原型阶段,LangChain 灵活;如果需要生产就绪的 UI、Agent 市场、跨端分发、私有化,IHUI AI 是更优选择。',
    rows: [
      {
        dimension: '产品形态',
        ihui: '完整 OS(UI + 后端 + DB)',
        competitor: 'Python SDK',
        ihuiDetail: '开箱即用',
        competitorDetail: '需自己搭建前后端',
      },
      {
        dimension: '上手成本',
        ihui: '30 分钟注册',
        competitor: '2-3 天搭原型',
        ihuiDetail: '无需开发',
        competitorDetail: '需写 FastAPI/前端/数据库',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: 'LangGraph 代码编排',
        ihuiDetail: '拖拽 + 一键 fork',
        competitorDetail: 'StateGraph 编程式',
      },
      {
        dimension: 'Agent 市场',
        ihui: '内置社区市场',
        competitor: '无',
        ihuiDetail: '创作者分成 + 商用',
        competitorDetail: 'Hub 主要是组件库',
      },
      {
        dimension: 'MCP',
        ihui: '原生支持',
        competitor: 'MCP 适配器',
        ihuiDetail: '100+ 预置',
        competitorDetail: 'langchain-mcp-adapters',
      },
      {
        dimension: '客户端',
        ihui: '6 端同源',
        competitor: '0 端(库)',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '需自行开发',
      },
      {
        dimension: '知识库',
        ihui: '内置 RAG + 向量库',
        competitor: '集成外部向量库',
        ihuiDetail: 'pgvector / Qdrant / Milvus',
        competitorDetail: '需自己配 Pinecone/Chroma',
      },
      {
        dimension: '工作流',
        ihui: '可视化画布',
        competitor: 'LangGraph 代码',
        ihuiDetail: '业务人员可上手',
        competitorDetail: '需 Python 工程师',
      },
      {
        dimension: '部署',
        ihui: 'Docker Compose / K8s 一键',
        competitor: '自建',
        ihuiDetail: '生产就绪',
        competitorDetail: '需自己写 Dockerfile',
      },
      {
        dimension: '生产案例',
        ihui: '120+ 企业付费客户',
        competitor: '开发者自部署',
        ihuiDetail: '完整 SLA 保障',
        competitorDetail: '社区支持',
      },
      {
        dimension: '许可证',
        ihui: 'Apache 2.0',
        competitor: 'MIT',
        ihuiDetail: '完全开源商用',
        competitorDetail: '更宽松',
      },
    ],
  },
}
