// © 2026 IHUI AI (智汇AI) · 版权所有者: 李春川 (Li Chunchuan) · https://aizhs.top
// Provenance-watermarked. 未授权商用可被溯源追责 (Apache-2.0 须保留本声明与 NOTICE)。
// [IHUI-AI-PROVENANCE]:⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠

import {
  BarChart3,
  BookOpen,
  Bot,
  Building2,
  Cable,
  Code,
  Cpu,
  Database,
  FileText,
  Globe,
  ImageIcon,
  Network,
  Palette,
  Rocket,
  Send,
  ShieldCheck,
  Sparkles,
  Terminal,
  Workflow,
  Wrench,
} from 'lucide-react'
import type { ProjectPlugin } from './types'

export const PROJECT_PLUGINS: ProjectPlugin[] = [
  {
    id: 'mcp-projects',
    name: 'MCP 项目',
    description: 'Model Context Protocol 服务器管理,让 AI 调用外部工具与数据源',
    href: '/mcp-projects',
    icon: Cable,
    tags: ['MCP', '工具调用'],
    category: 'mcp',
  },
  {
    id: 'agents',
    name: 'AI 智能体',
    description: '创建与管理自定义 AI Agent,支持多模型编排与工具组合',
    href: '/agents',
    icon: Bot,
    tags: ['Agent', '多模型'],
    category: 'agent',
  },
  {
    id: 'workflows',
    name: '工作流',
    description: '可视化工作流编排,串联 AI 节点 / API 调用 / 条件分支',
    href: '/workflows',
    icon: Workflow,
    tags: ['工作流', '编排'],
    category: 'workflow',
  },
  {
    id: 'skills',
    name: 'AI 技能',
    description: '平台技能市场,管理与配置 AI 模型可调用的技能模板',
    href: '/models/skills',
    icon: Sparkles,
    tags: ['技能', '模板'],
    category: 'tool',
  },
  {
    id: 'tools',
    name: 'AI 工具',
    description: '在线 AI 工具集合,涵盖 PDF 处理 / 文档转换 / 文本分析等',
    href: '/tools',
    icon: Wrench,
    tags: ['工具', '在线'],
    category: 'tool',
  },
  {
    id: 'image-gen',
    name: '图像生成',
    description: 'AI 图像生成能力,支持文生图 / 图生图 / 多模型切换',
    href: '/image-gen',
    icon: ImageIcon,
    tags: ['图像', '生成'],
    category: 'creation',
  },
  {
    id: 'ai-generation',
    name: 'AI 创作',
    description: 'AI 内容创作中心,文案 / 脚本 / 小说 / 营销内容一键生成',
    href: '/ai-generation',
    icon: Sparkles,
    tags: ['创作', '内容'],
    category: 'creation',
  },
  {
    id: 'api-test',
    name: 'API 测试',
    description: '在线 API 调试与测试工具,支持参数配置 / 历史记录 / 结果对比',
    href: '/api-test',
    icon: Code,
    tags: ['API', '调试'],
    category: 'tool',
  },
  {
    id: 'ai-world',
    name: 'AI 世界',
    description: 'AI 应用探索中心,热门 AI 应用 / 智能创作 / 场景化体验',
    href: '/ai-world',
    icon: Globe,
    tags: ['应用', '探索'],
    category: 'creation',
  },
  {
    id: 'knowledge-graph',
    name: '知识图谱',
    description: '构建与管理知识图谱,实体关系可视化 / 图谱推理 / 关联查询',
    href: '/knowledge-graph',
    icon: Network,
    tags: ['图谱', '知识'],
    category: 'knowledge',
  },
  {
    id: 'knowledge-base',
    name: '知识库',
    description: '企业知识库管理,文档上传 / 分 chunk / 向量化 / 检索召回',
    href: '/knowledge-base',
    icon: BookOpen,
    tags: ['知识库', '向量'],
    category: 'knowledge',
  },
  {
    id: 'knowledge-rag',
    name: '知识检索 RAG',
    description: 'RAG 检索增强生成,文档问答 / 语义检索 / 引用溯源',
    href: '/knowledge-rag',
    icon: Database,
    tags: ['RAG', '检索'],
    category: 'knowledge',
  },
  {
    id: 'docs',
    name: '文档中心',
    description: '项目文档与 API 参考手册,开发者必读 / 接口契约 / 架构说明',
    href: '/feature-center/documents',
    icon: FileText,
    tags: ['文档', 'API'],
    category: 'knowledge',
  },
  {
    id: 'publish',
    name: '多平台发布',
    description: '一键多平台发布工具,支持 md / docx / html / pdf / 图片 / 视频 → 14 平台',
    href: '/publish',
    icon: Send,
    tags: ['发布', '多平台'],
    category: 'creation',
  },
  {
    id: 'articles',
    name: '文章',
    description: '长文创作与管理,支持 Markdown / 富文本 / 草稿 / 发布工作流',
    href: '/articles',
    icon: FileText,
    tags: ['文章', 'Markdown'],
    category: 'creation',
  },
  {
    id: 'models',
    name: '模型市场',
    description: '50+ 主流大模型市场,OpenAI / Anthropic / Google / 国产模型一网打尽',
    href: '/models',
    icon: Cpu,
    tags: ['模型', '市场'],
    category: 'model',
  },
  {
    id: 'developer',
    name: '开发者中心',
    description: '开发者工具集,API Key 管理 / Webhook / 调试 / 日志 / 监控',
    href: '/developer',
    icon: Terminal,
    tags: ['开发', 'API Key'],
    category: 'ide',
  },
  {
    id: 'n8n-agents',
    name: 'n8n Agents',
    description: 'n8n 工作流 Agent 集成,可视化编排 + AI 节点 + 自动化触发',
    href: '/n8n-agents',
    icon: Workflow,
    tags: ['n8n', '自动化'],
    category: 'workflow',
  },
  {
    id: 'openclaw',
    name: 'OpenClaw',
    description: '开源 AI Agent 平台,多智能体协作 / 工具调用 / 工作流编排',
    href: '/openclaw',
    icon: Rocket,
    tags: ['开源', 'Agent'],
    category: 'agent',
  },
  {
    id: 'dashboard',
    name: '数据看板',
    description: '平台运营数据看板,用户 / 收入 / 调用量 / 模型分布实时可视化',
    href: '/dashboard',
    icon: BarChart3,
    tags: ['数据', '看板'],
    category: 'tool',
  },
  {
    id: 'bi-dashboard',
    name: 'BI 仪表板',
    description: '商业智能仪表板,多维度数据分析 / 自定义图表 / 导出报表',
    href: '/bi-dashboard',
    icon: BarChart3,
    tags: ['BI', '报表'],
    category: 'tool',
  },
  {
    id: 'security-audit',
    name: '安全审计',
    description: '平台安全审计中心,API Key 泄露检测 / 权限审查 / 操作日志',
    href: '/security-audit',
    icon: ShieldCheck,
    tags: ['安全', '审计'],
    category: 'security',
  },
  {
    id: 'enterprise',
    name: '企业版',
    description: '企业级能力,SSO 单点登录 / 组织架构 / 配额管理 / 私有部署',
    href: '/enterprise',
    icon: Building2,
    tags: ['企业', 'SSO'],
    category: 'tool',
  },
  {
    id: 'design-system',
    name: '设计系统',
    description: 'UI 设计系统文档,组件库 / 色彩 token / 图标 / 间距规范',
    href: '/design-system',
    icon: Palette,
    tags: ['设计', 'UI'],
    category: 'design',
  },
]
// ⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠
