// © 2026 IHUI AI (智汇AI) · 版权所有者: 李春川 (Li Chunchuan) · https://aizhs.top
// Provenance-watermarked. 未授权商用可被溯源追责 (Apache-2.0 须保留本声明与 NOTICE)。
// [IHUI-AI-PROVENANCE]:⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠

import { Code, Cpu, Link2, MousePointer2, Server, Terminal, Workflow } from 'lucide-react'
import type { MarketPlugin } from '../types'

export const MARKET_PLUGINS_PART_8: MarketPlugin[] = [
  // ========================================
  // ★ 开发工具 / IDE 扩展 — 10 项
  // ========================================
  {
    id: 'cursor',
    name: 'Cursor',
    description: 'Cursor AI 代码编辑器,扩展市场 / MCP 集成 / 规则文件 / Agent 模式',
    url: 'https://cursor.com',
    fallbackIcon: MousePointer2,
    tags: ['IDE', '代码'],
    category: 'ide',
    official: true,
  },
  {
    id: 'vscode-marketplace',
    name: 'VSCode Marketplace',
    description: 'Visual Studio Code 扩展市场,AI 类扩展涵盖 Copilot / Continue / Cline',
    url: 'https://marketplace.visualstudio.com',
    vendor: 'microsoft',
    fallbackIcon: Code,
    tags: ['IDE', '微软'],
    category: 'ide',
    free: true,
    official: true,
  },
  {
    id: 'github-models',
    name: 'GitHub Models',
    description: 'GitHub 官方模型市场,免费体验主流 LLM,集成 Codespaces / Copilot',
    url: 'https://github.com/models',
    vendor: 'githubcopilot',
    fallbackIcon: Code,
    tags: ['模型', 'GitHub'],
    category: 'ide',
    free: true,
    official: true,
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    description: 'GitHub 官方 AI 编程助手,Copilot Chat / Agent / PR Review / 多 IDE 支持',
    url: 'https://github.com/features/copilot',
    vendor: 'githubcopilot',
    fallbackIcon: Code,
    tags: ['Copilot', '编程'],
    category: 'ide',
    official: true,
  },
  {
    id: 'cline',
    name: 'Cline',
    description: '开源 AI 编程 Agent,VSCode 扩展,支持 MCP / 自定义工具 / 浏览器控制',
    url: 'https://cline.bot',
    fallbackIcon: Terminal,
    tags: ['Agent', 'VSCode'],
    category: 'ide',
    free: true,
  },
  {
    id: 'continue',
    name: 'Continue',
    description: '开源 AI 编程助手,VSCode / JetBrains,自定义模型 / 代码补全 / Chat',
    url: 'https://continue.dev',
    fallbackIcon: Code,
    tags: ['开源', '补全'],
    category: 'ide',
    free: true,
  },
  {
    id: 'replit-agent',
    name: 'Replit Agent',
    description: 'Replit AI 编程 Agent 平台,云端开发环境 + Agent 商店 + 一键部署',
    url: 'https://replit.com',
    vendor: 'replit',
    fallbackIcon: Terminal,
    tags: ['IDE', '云端'],
    category: 'ide',
    official: true,
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    description: 'Codeium 出品 AI IDE,Cascade Agent / 多文件编辑 / MCP / Flux 工作流',
    url: 'https://codeium.com/windsurf',
    fallbackIcon: MousePointer2,
    tags: ['IDE', 'Agent'],
    category: 'ide',
    free: true,
  },
  {
    id: 'trae',
    name: 'Trae IDE',
    description: '字节跳动 Trae AI IDE,多 Agent 协作 / MCP / Skills / 国际版 + 国内版',
    url: 'https://trae.ai',
    fallbackIcon: MousePointer2,
    tags: ['IDE', '字跳'],
    category: 'ide',
    free: true,
    official: true,
  },
  {
    id: 'zed',
    name: 'Zed',
    description: 'Zed 高性能代码编辑器,Rust 编写 / 协作 / AI Assistant / 130+ 语言',
    url: 'https://zed.dev',
    fallbackIcon: Code,
    tags: ['IDE', 'Rust'],
    category: 'ide',
    free: true,
  },

  // ========================================
  // ★ 协议 / 注册中心 / 模型聚合 — 12 项
  // ========================================
  {
    id: 'mcp-registry',
    name: 'MCP Registry',
    description: 'Model Context Protocol 官方服务器注册表,10000+ MCP Server 跨客户端复用',
    url: 'https://modelcontextprotocol.io',
    vendor: 'anthropic',
    fallbackIcon: Server,
    tags: ['MCP', '协议'],
    category: 'mcp',
    free: true,
    official: true,
  },
  {
    id: 'smithery',
    name: 'Smithery MCP',
    description: 'Smithery MCP Server 注册中心,一键安装 / 运行 / 管理 MCP 服务器',
    url: 'https://smithery.ai',
    fallbackIcon: Server,
    tags: ['MCP', '注册中心'],
    category: 'mcp',
    free: true,
  },
  {
    id: 'mcp-get',
    name: 'mcp-get',
    description: 'mcp-get CLI 工具,一键安装 / 管理 MCP Server,跨客户端统一',
    url: 'https://mcp-get.com',
    fallbackIcon: Server,
    tags: ['MCP', 'CLI'],
    category: 'mcp',
    free: true,
  },
  {
    id: 'pulsemcp',
    name: 'PulseMCP',
    description: 'PulseMCP MCP Server 发现平台,精选 / 评分 / 分类 / 一键安装',
    url: 'https://pulsemcp.com',
    fallbackIcon: Server,
    tags: ['MCP', '目录'],
    category: 'mcp',
    free: true,
  },
  {
    id: 'langchain-hub',
    name: 'LangChain Hub',
    description: 'LangChain 官方 Prompt / Agent / Tool 仓库,LangGraph 工作流模板社区',
    url: 'https://smith.langchain.com/hub',
    fallbackIcon: Link2,
    tags: ['Prompt', 'Tool'],
    category: 'market',
    free: true,
    official: true,
  },
  {
    id: 'langgraph',
    name: 'LangGraph Studio',
    description: 'LangGraph 官方可视化 Agent 编排与调试工具,状态图 / 断点 / 回放',
    url: 'https://langchain.com/langgraph',
    fallbackIcon: Workflow,
    tags: ['LangGraph', '编排'],
    category: 'market',
    official: true,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    description: '统一 LLM API 路由,300+ 模型聚合,内置函数调用 / 工具 / 结构化输出',
    url: 'https://openrouter.ai',
    vendor: 'openrouter',
    fallbackIcon: Link2,
    tags: ['API', '聚合'],
    category: 'model',
    free: true,
    official: true,
  },
  {
    id: 'together-ai',
    name: 'Together AI',
    description: 'Together AI 推理平台,开源模型加速 / Fine-tune / Embedding / 重排',
    url: 'https://together.ai',
    vendor: 'together',
    fallbackIcon: Cpu,
    tags: ['推理', '开源'],
    category: 'model',
    official: true,
  },
]
// ⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠
