import { Bot, Boxes, Database, Globe, ShieldCheck, Star, Workflow } from 'lucide-react'
import type { MarketPlugin } from '../types'

export const MARKET_PLUGINS_PART_7: MarketPlugin[] = [
  {
    id: 'doubao',
    name: '字节豆包',
    description: '字节跳动豆包大模型,火山引擎方舟平台 / 多模态 / 低价调用',
    url: 'https://volcengine.com/product/doubao',
    vendor: 'doubao',
    fallbackIcon: Star,
    tags: ['豆包', '字跳'],
    category: 'market',
    official: true,
  },
  {
    id: 'baidu-ernie',
    name: '百度文心',
    description: '百度文心一言 / ERNIE 模型市场,千帆平台 / 知识增强 / 产业级',
    url: 'https://yiyan.baidu.com',
    vendor: 'baidu',
    fallbackIcon: Star,
    tags: ['文心', '百度'],
    category: 'market',
    official: true,
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    description: 'MiniMax 大模型平台,abab 系列 / 语音合成 / 视频生成全栈',
    url: 'https://minimaxi.com',
    vendor: 'minimax',
    fallbackIcon: Star,
    tags: ['MiniMax', '多模态'],
    category: 'market',
    official: true,
  },
  {
    id: 'hunyuan',
    name: '腾讯混元',
    description: '腾讯混元大模型,多模态 / 长文本 / 微信生态深度集成',
    url: 'https://hunyuan.tencent.com',
    vendor: 'hunyuan',
    fallbackIcon: Star,
    tags: ['混元', '腾讯'],
    category: 'market',
    official: true,
  },
  {
    id: 'yi',
    name: '零一万物 Yi',
    description: '李开复零一万物 Yi 系列模型,开源 / 闭源 / 长上下文',
    url: 'https://lingyiwanwu.com',
    vendor: 'yi',
    fallbackIcon: Star,
    tags: ['Yi', '零一'],
    category: 'market',
    official: true,
  },
  {
    id: 'spark',
    name: '讯飞星火',
    description: '科大讯飞星火大模型,语音交互 / 教育场景 / 国产自主',
    url: 'https://xinghuo.xfyun.cn',
    vendor: 'spark',
    fallbackIcon: Star,
    tags: ['星火', '讯飞'],
    category: 'market',
    official: true,
  },
  {
    id: 'baichuan',
    name: '百川智能',
    description: '王小川百川大模型,Baichuan 系列 / 搜索增强 / 医疗垂类',
    url: 'https://baichuan-ai.com',
    vendor: 'baichuan',
    fallbackIcon: Star,
    tags: ['百川', '搜索'],
    category: 'market',
    official: true,
  },

  // ========================================
  // ★ AI 应用开发平台 — 12 项
  // ========================================
  {
    id: 'coze',
    name: 'Coze 扣子',
    description: '字节跳动 AI Bot 开发平台,可视化编排 / 插件市场 / 知识库 / 工作流',
    url: 'https://www.coze.com',
    vendor: 'coze',
    fallbackIcon: Bot,
    tags: ['Bot', '字跳'],
    category: 'market',
    free: true,
    official: true,
  },
  {
    id: 'dify',
    name: 'Dify',
    description: 'Dify 开源 LLM 应用开发平台,工具 / 模型 / Agent 模板社区',
    url: 'https://dify.ai/marketplace',
    fallbackIcon: Boxes,
    tags: ['开源', 'LLMOps'],
    category: 'market',
    free: true,
  },
  {
    id: 'huggingface-spaces',
    name: 'Hugging Face Spaces',
    description: 'Hugging Face 模型演示空间,数十万 AI 应用 / Demo / 模型在线体验',
    url: 'https://huggingface.co/spaces',
    vendor: 'huggingface',
    fallbackIcon: Boxes,
    tags: ['Demo', '开源'],
    category: 'market',
    free: true,
    official: true,
  },
  {
    id: 'poe',
    name: 'Poe',
    description: 'Quora 旗下 Poe AI 平台,聚合 100+ 顶级模型 / 自定义 Bot / 一键创建',
    url: 'https://poe.com',
    fallbackIcon: Star,
    tags: ['聚合', 'Bot'],
    category: 'market',
    official: true,
  },
  {
    id: 'character-ai',
    name: 'Character.AI',
    description: 'Character.AI 角色对话平台,百万级 AI 角色 / 个性化 / 沉浸式',
    url: 'https://character.ai',
    fallbackIcon: Bot,
    tags: ['角色', '对话'],
    category: 'market',
    free: true,
  },
  {
    id: 'openwebui',
    name: 'OpenWebUI',
    description: '开源 AI Web UI,兼容 Ollama / OpenAI,内置工具 / 函数 / 知识库插件',
    url: 'https://openwebui.com',
    vendor: 'openwebui',
    fallbackIcon: Globe,
    tags: ['开源', 'Ollama'],
    category: 'market',
    free: true,
  },
  {
    id: 'lobehub-plugins',
    name: 'LobeHub Plugins',
    description: 'LobeChat 插件市场,数百个 AI 工具插件,搜索 / 联网 / 多模态',
    url: 'https://lobehub.com/plugins',
    fallbackIcon: Boxes,
    tags: ['插件', 'LobeChat'],
    category: 'market',
    free: true,
  },
  {
    id: 'flowise',
    name: 'Flowise',
    description: '开源无代码 LLM 应用构建器,拖拽式编排 / LangChain 可视化 / 自托管',
    url: 'https://flowiseai.com',
    fallbackIcon: Workflow,
    tags: ['无代码', '开源'],
    category: 'market',
    free: true,
  },
  {
    id: 'langflow',
    name: 'Langflow',
    description: 'DataStax 旗下开源 LangChain 可视化编排工具,拖拽构建 / 多模型',
    url: 'https://langflow.org',
    fallbackIcon: Workflow,
    tags: ['可视化', '开源'],
    category: 'market',
    free: true,
  },
  {
    id: 'anythingllm',
    name: 'AnythingLLM',
    description: '开源私有化 RAG 框架,文档问答 / 多用户 / 工作空间 / 自托管',
    url: 'https://anythingllm.com',
    fallbackIcon: Boxes,
    tags: ['RAG', '自托管'],
    category: 'market',
    free: true,
  },
  {
    id: 'privategpt',
    name: 'PrivateGPT',
    description: '开源私有化 LLM 框架,本地推理 / 文档问答 / 零数据泄露',
    url: 'https://privategpt.dev',
    fallbackIcon: ShieldCheck,
    tags: ['私有化', '本地'],
    category: 'market',
    free: true,
  },
  {
    id: 'quivr',
    name: 'Quivr',
    description: '开源 generative AI 第二大脑,知识库 / 多模型 / 团队协作',
    url: 'https://quivr.ai',
    fallbackIcon: Database,
    tags: ['第二大脑', '开源'],
    category: 'market',
    free: true,
  },
]
