import { BookOpen, Code, FileText, Layers, Mail, MessageSquare, Palette, Send } from 'lucide-react'
import type { MarketPlugin } from '../types'

export const MARKET_PLUGINS_PART_5: MarketPlugin[] = [
  {
    id: 's3-mcp',
    name: 'AWS S3 MCP',
    description: 'AWS S3 MCP Server,AI 操控对象存储 / 上传 / 下载 / 桶管理',
    url: 'https://aws.amazon.com/s3/',
    vendor: 'bedrock',
    fallbackIcon: FileText,
    tags: ['文件', 'S3'],
    category: 'data',
    official: true,
  },
  {
    id: 'box',
    name: 'Box',
    description: 'Box 企业内容管理平台,文件共享 / 协作 / 安全 / AI 集成',
    url: 'https://box.com',
    fallbackIcon: FileText,
    tags: ['文件', '企业'],
    category: 'data',
  },

  // ========================================
  // ★ 通信协作 MCP — 8 项
  // ========================================
  {
    id: 'slack-mcp',
    name: 'Slack MCP',
    description: 'Slack 官方 MCP Server,AI 发送消息 / 频道管理 / 搜索历史 / 工作流',
    url: 'https://slack.com/mcp',
    vendor: 'slack',
    fallbackIcon: MessageSquare,
    tags: ['通信', 'Slack'],
    category: 'communication',
    official: true,
  },
  {
    id: 'discord-mcp',
    name: 'Discord MCP',
    description: 'Discord MCP Server,AI 操控 Bot / 发消息 / 服务器管理 / 频道操作',
    url: 'https://discord.com',
    fallbackIcon: MessageSquare,
    tags: ['通信', 'Discord'],
    category: 'communication',
    free: true,
  },
  {
    id: 'telegram-mcp',
    name: 'Telegram Bot MCP',
    description: 'Telegram Bot MCP Server,AI 发送消息 / 群组管理 / 文件 / 通知',
    url: 'https://core.telegram.org/bots/api',
    fallbackIcon: Send,
    tags: ['通信', 'Bot'],
    category: 'communication',
    free: true,
  },
  {
    id: 'email-mcp',
    name: 'Email MCP',
    description: 'Email MCP Server,AI 发送 / 接收 / 管理邮件,IMAP / SMTP 协议支持',
    url: 'https://github.com/modelcontextprotocol/servers',
    fallbackIcon: Mail,
    tags: ['通信', '邮件'],
    category: 'communication',
    free: true,
  },
  {
    id: 'gmail-mcp',
    name: 'Gmail MCP',
    description: 'Gmail 官方 MCP Server,AI 管理 Gmail 邮件 / 标签 / 草稿 / 发送',
    url: 'https://developers.google.com/gmail/api',
    vendor: 'google',
    fallbackIcon: Mail,
    tags: ['通信', 'Gmail'],
    category: 'communication',
    official: true,
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp Business',
    description: 'WhatsApp Business API,企业消息 / 客户服务 / 通知 / AI 自动回复',
    url: 'https://business.whatsapp.com',
    fallbackIcon: MessageSquare,
    tags: ['通信', 'WhatsApp'],
    category: 'communication',
    official: true,
  },
  {
    id: 'microsoft-teams',
    name: 'Microsoft Teams',
    description: 'Microsoft Teams 协作平台,Bot / 消息 / 会议 / 文件 / AI 集成',
    url: 'https://www.microsoft.com/microsoft-teams',
    vendor: 'microsoft',
    fallbackIcon: MessageSquare,
    tags: ['通信', '微软'],
    category: 'communication',
    official: true,
  },
  {
    id: 'feishu',
    name: '飞书 Lark',
    description: '飞书 Lark 开放平台,消息 / 文档 / 多维表格 / 日历 / 审批 MCP 集成',
    url: 'https://open.feishu.cn',
    fallbackIcon: MessageSquare,
    tags: ['通信', '飞书'],
    category: 'communication',
    official: true,
  },

  // ========================================
  // ★ 知识与生产力 MCP — 8 项
  // ========================================
  {
    id: 'notion-mcp',
    name: 'Notion MCP',
    description: 'Notion 官方 MCP Server,AI 搜索 / 创建 / 编辑 Notion 页面 / 数据库',
    url: 'https://www.notion.com/my-integrations',
    vendor: 'notion',
    fallbackIcon: BookOpen,
    tags: ['知识', 'Notion'],
    category: 'productivity',
    official: true,
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'Obsidian 知识管理工具,本地 Markdown / 双向链接 / MCP 集成',
    url: 'https://obsidian.md',
    fallbackIcon: BookOpen,
    tags: ['知识', 'Markdown'],
    category: 'productivity',
    free: true,
  },
  {
    id: 'linear-mcp',
    name: 'Linear MCP',
    description: 'Linear 官方 MCP Server,AI 创建 / 更新 / 查询 Issue / 项目管理',
    url: 'https://linear.app/docs/mcp',
    vendor: 'linear',
    fallbackIcon: Layers,
    tags: ['任务', 'Linear'],
    category: 'productivity',
    official: true,
  },
  {
    id: 'jira-mcp',
    name: 'Jira MCP',
    description: 'Atlassian Jira MCP Server,AI 管理 Issue / Sprint / 看板 / 工作流',
    url: 'https://www.atlassian.com/software/jira',
    fallbackIcon: Layers,
    tags: ['任务', 'Jira'],
    category: 'productivity',
    official: true,
  },
  {
    id: 'github-mcp',
    name: 'GitHub MCP',
    description: 'GitHub 官方 MCP Server,AI 管理 Repo / Issue / PR / Action / Workflow',
    url: 'https://github.com/github/github-mcp-server',
    vendor: 'githubcopilot',
    fallbackIcon: Code,
    tags: ['任务', 'GitHub'],
    category: 'productivity',
    free: true,
    official: true,
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description: 'GitLab DevOps 平台,Repo / CI/CD / Issue / Wiki / MCP 集成',
    url: 'https://gitlab.com',
    fallbackIcon: Code,
    tags: ['任务', 'GitLab'],
    category: 'productivity',
    official: true,
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'Asana 项目管理平台,任务 / 项目 / 时间线 / 团队协作 / API 集成',
    url: 'https://asana.com',
    fallbackIcon: Layers,
    tags: ['任务', '项目'],
    category: 'productivity',
    official: true,
  },
  {
    id: 'trello',
    name: 'Trello',
    description: 'Atlassian Trello 看板管理,看板 / 列表 / 卡片 / Drag & Drop / Atlassian',
    url: 'https://trello.com',
    fallbackIcon: Layers,
    tags: ['任务', '看板'],
    category: 'productivity',
    free: true,
    official: true,
  },

  // ========================================
  // ★ 设计创作 — 8 项
  // ========================================
  {
    id: 'figma-mcp',
    name: 'Figma MCP',
    description: 'Figma 官方 MCP Server,AI 读取 / 修改 / 生成设计 / Dev Mode 集成',
    url: 'https://www.figma.com/developers',
    vendor: 'figma',
    fallbackIcon: Palette,
    tags: ['设计', 'Figma'],
    category: 'design',
    official: true,
  },
]
