import {
  Bot,
  Boxes,
  Cloud,
  Cpu,
  Database,
  Search as SearchIcon,
  Sparkles,
  Terminal,
  Zap,
} from 'lucide-react'
import type { MarketPlugin } from '../types'

export const MARKET_PLUGINS_PART_3: MarketPlugin[] = [
  {
    id: 'supabase',
    name: 'Supabase',
    description: '开源 Firebase 替代,Postgres / Auth / 实时订阅 / Storage / Edge Functions',
    url: 'https://supabase.com',
    vendor: 'supabase',
    fallbackIcon: Database,
    tags: ['BaaS', 'Postgres'],
    category: 'devops',
    free: true,
    official: true,
  },
  {
    id: 'railway',
    name: 'Railway',
    description: '现代化应用部署平台,数据库 / 后端 / 前端一键部署 / 无 Docker 配置',
    url: 'https://railway.app',
    fallbackIcon: Cloud,
    tags: ['部署', '全栈'],
    category: 'devops',
    free: true,
  },
  {
    id: 'render',
    name: 'Render',
    description: '云应用部署平台,Web Service / 后台任务 / 数据库 / 静态站点',
    url: 'https://render.com',
    fallbackIcon: Cloud,
    tags: ['部署', '云'],
    category: 'devops',
    free: true,
  },
  {
    id: 'fly-io',
    name: 'Fly.io',
    description: '边缘应用部署平台,全球数据中心 / Firecracker VM / Apps v2',
    url: 'https://fly.io',
    fallbackIcon: Cloud,
    tags: ['部署', '边缘'],
    category: 'devops',
    free: true,
  },
  {
    id: 'deno-deploy',
    name: 'Deno Deploy',
    description: 'Deno 官方边缘部署平台,JavaScript / TypeScript / 全球 35 区域',
    url: 'https://deno.com/deploy',
    vendor: 'deno',
    fallbackIcon: Cloud,
    tags: ['部署', 'Deno'],
    category: 'devops',
    free: true,
    official: true,
  },
  {
    id: 'github-pages',
    name: 'GitHub Pages',
    description: 'GitHub 静态站点托管,免费 / 自定义域名 / HTTPS / 与 Git 仓库深度集成',
    url: 'https://pages.github.com',
    vendor: 'github',
    fallbackIcon: Cloud,
    tags: ['部署', 'GitHub'],
    category: 'devops',
    free: true,
    official: true,
  },
  {
    id: 'docker',
    name: 'Docker',
    description: '容器化平台,Docker Hub / Compose / Build Cloud / 容器化部署行业标杆',
    url: 'https://docker.com',
    vendor: 'docker',
    fallbackIcon: Boxes,
    tags: ['容器', '部署'],
    category: 'devops',
    official: true,
  },
  {
    id: 'koyeb',
    name: 'Koyeb',
    description: 'Serverless 应用部署平台,Docker / Git 部署 / 全球边缘 / 自动扩缩',
    url: 'https://koyeb.com',
    fallbackIcon: Cloud,
    tags: ['部署', 'Serverless'],
    category: 'devops',
    free: true,
  },
  {
    id: 'workers-ai',
    name: 'Cloudflare Workers AI',
    description: 'Cloudflare Workers AI 推理平台,Llama / Mistral / 嵌入模型边缘推理',
    url: 'https://developers.cloudflare.com/workers-ai/',
    vendor: 'cloudflare',
    fallbackIcon: Cpu,
    tags: ['部署', 'AI'],
    category: 'devops',
    free: true,
    official: true,
  },

  // ========================================
  // ★ Superpowers 与 AI 能力增强 — 8 项
  // ========================================
  {
    id: 'superpowers',
    name: 'Superpowers',
    description: 'Anthropic 推出的 Claude 增强能力,长期记忆 / 持续工作 / 自主任务执行',
    url: 'https://github.com/obra/superpowers',
    vendor: 'anthropic',
    fallbackIcon: Zap,
    tags: ['Superpowers', '增强'],
    category: 'agent',
    free: true,
  },
  {
    id: 'anthropic-skills',
    name: 'Anthropic Skills',
    description: 'Claude Skills 市场,Bash / Artifacts / Computer Use / Filesystem 官方技能集',
    url: 'https://docs.anthropic.com/claude/docs/skills',
    vendor: 'anthropic',
    fallbackIcon: Sparkles,
    tags: ['Claude', 'Skills'],
    category: 'agent',
    free: true,
    official: true,
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    description: 'Anthropic 官方 CLI 编程 Agent,终端原生 / 多文件编辑 / 工具调用',
    url: 'https://docs.anthropic.com/claude/docs/claude-code',
    vendor: 'anthropic',
    fallbackIcon: Terminal,
    tags: ['Claude', 'CLI'],
    category: 'ide',
    official: true,
  },
  {
    id: 'openai-codex',
    name: 'OpenAI Codex',
    description: 'OpenAI Codex CLI,开源命令行 AI 编程助手,GPT-4 / o3 模型 / 多语言',
    url: 'https://github.com/openai/codex',
    vendor: 'openai',
    fallbackIcon: Terminal,
    tags: ['OpenAI', 'CLI'],
    category: 'ide',
    free: true,
    official: true,
  },
  {
    id: 'gemini-cli',
    name: 'Gemini CLI',
    description: 'Google Gemini CLI,开源命令行 AI 助手,Gemini 2.5 Pro / 1M 上下文',
    url: 'https://github.com/google-gemini/gemini-cli',
    vendor: 'google',
    fallbackIcon: Terminal,
    tags: ['Gemini', 'CLI'],
    category: 'ide',
    free: true,
    official: true,
  },
  {
    id: 'aider',
    name: 'Aider',
    description: '开源 AI pair programming,终端 / Git 集成 / 多模型 / 多文件编辑',
    url: 'https://aider.chat',
    fallbackIcon: Terminal,
    tags: ['开源', '编程'],
    category: 'ide',
    free: true,
  },
  {
    id: 'openai-operator-plus',
    name: 'OpenAI ChatGPT Agent',
    description: 'ChatGPT Agent 能力,长任务自主执行 / 浏览器操作 / 编程 / 文件操作',
    url: 'https://openai.com/index/introducing-chatgpt-agent/',
    vendor: 'openai',
    fallbackIcon: Bot,
    tags: ['Agent', 'OpenAI'],
    category: 'agent',
    official: true,
  },
  {
    id: 'devin',
    name: 'Devin',
    description: 'Cognition Labs Devin AI 软件工程师,自主完成开发任务 / 修复 bug / PR',
    url: 'https://devin.ai',
    fallbackIcon: Bot,
    tags: ['Agent', '工程师'],
    category: 'agent',
  },

  // ========================================
  // ★ 搜索能力 — 8 项
  // ========================================
  {
    id: 'brave-search-mcp',
    name: 'Brave Search MCP',
    description: 'Brave Search 官方 MCP Server,AI 调用隐私搜索 / 网页 / 新闻 / 图片',
    url: 'https://brave.com/search/api/',
    vendor: 'brave',
    fallbackIcon: SearchIcon,
    tags: ['搜索', 'MCP'],
    category: 'search',
    free: true,
    official: true,
  },
]
