// © 2026 IHUI AI (智汇AI) · 版权所有者: 李春川 (Li Chunchuan) · https://aizhs.top
// Provenance-watermarked. 未授权商用可被溯源追责 (Apache-2.0 须保留本声明与 NOTICE)。
// [IHUI-AI-PROVENANCE]:⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠

import { Image as ImageIcon, Palette, Star, Store, Zap } from 'lucide-react'
import type { MarketPlugin } from '../types'

export const MARKET_PLUGINS_PART_6: MarketPlugin[] = [
  {
    id: 'framer',
    name: 'Framer',
    description: 'Framer 无代码网站构建,可视化设计 / 响应式 / CMS / AI 生成',
    url: 'https://framer.com',
    fallbackIcon: Palette,
    tags: ['设计', '网站'],
    category: 'design',
    official: true,
  },
  {
    id: 'canva',
    name: 'Canva',
    description: 'Canva 在线设计平台,模板 / 图片 / 视频 / 演示文稿 / AI 设计助手',
    url: 'https://canva.com',
    fallbackIcon: Palette,
    tags: ['设计', '模板'],
    category: 'design',
    free: true,
    official: true,
  },
  {
    id: 'adobe-firefly',
    name: 'Adobe Firefly',
    description: 'Adobe Firefly AI 创作全家桶,图像 / 视频 / 音频 / 矢量 / 字体生成',
    url: 'https://firefly.adobe.com',
    vendor: 'adobe',
    fallbackIcon: Palette,
    tags: ['设计', 'Adobe'],
    category: 'design',
    official: true,
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    description: 'Midjourney AI 图像生成,艺术风格 / 高质量 / Discord / 网页版',
    url: 'https://midjourney.com',
    fallbackIcon: ImageIcon,
    tags: ['设计', 'AI 生成'],
    category: 'design',
  },
  {
    id: 'dalle',
    name: 'OpenAI DALL·E',
    description: 'OpenAI DALL·E 3 文生图模型,集成 ChatGPT / API / 编辑 / 变体',
    url: 'https://openai.com/dall-e-3',
    vendor: 'openai',
    fallbackIcon: ImageIcon,
    tags: ['设计', 'OpenAI'],
    category: 'design',
    official: true,
  },
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion',
    description: 'Stability AI 开源图像生成模型,SDXL / SD3 / 自托管 / LoRA 微调',
    url: 'https://stability.ai',
    fallbackIcon: ImageIcon,
    tags: ['设计', '开源'],
    category: 'design',
    free: true,
  },
  {
    id: 'flux',
    name: 'Black Forest Labs FLUX',
    description: 'Black Forest Labs FLUX.1 图像生成模型,质量顶尖 / 开源 / 速度快',
    url: 'https://blackforestlabs.ai',
    fallbackIcon: ImageIcon,
    tags: ['设计', 'FLUX'],
    category: 'design',
    free: true,
  },

  // ========================================
  // ★ 大模型厂商官方市场 — 18 项
  // ========================================
  {
    id: 'gpt-store',
    name: 'OpenAI GPT Store',
    description: 'OpenAI 官方 GPTs 市场,百万级自定义 GPT 机器人,涵盖工作 / 学习 / 生活',
    url: 'https://chatgpt.com/gpts',
    vendor: 'openai',
    fallbackIcon: Store,
    tags: ['GPTs', '官方'],
    category: 'market',
    free: true,
    official: true,
  },
  {
    id: 'claude-skills',
    name: 'Anthropic Claude',
    description: 'Claude 官方技能与工具市场,Artifacts / Computer Use / MCP 原生支持',
    url: 'https://anthropic.com/claude',
    vendor: 'anthropic',
    fallbackIcon: Star,
    tags: ['Claude', '官方'],
    category: 'market',
    official: true,
  },
  {
    id: 'gemini-gems',
    name: 'Google Gemini Gems',
    description: 'Google Gemini 官方定制 Gems 市场,个性化 AI 助手 / 多模态 / 原生多语言',
    url: 'https://gemini.google.com',
    vendor: 'google',
    fallbackIcon: Star,
    tags: ['Gemini', '官方'],
    category: 'market',
    free: true,
    official: true,
  },
  {
    id: 'grok',
    name: 'xAI Grok',
    description: 'Elon Musk 的 xAI 公司 Grok 模型,实时信息 / 幽默风格 / X 平台深度集成',
    url: 'https://x.ai',
    vendor: 'xai',
    fallbackIcon: Zap,
    tags: ['Grok', 'xAI'],
    category: 'market',
    official: true,
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    description: '欧洲 Mistral AI 开源模型平台,Mixtral / Codestral / 函数调用原生支持',
    url: 'https://mistral.ai',
    vendor: 'mistral',
    fallbackIcon: Star,
    tags: ['Mistral', '开源'],
    category: 'market',
    official: true,
  },
  {
    id: 'cohere',
    name: 'Cohere',
    description: 'Cohere 企业级 LLM 平台,Command R+ / Rerank / Embed 多模型协同',
    url: 'https://cohere.com',
    vendor: 'cohere',
    fallbackIcon: Star,
    tags: ['Cohere', '企业'],
    category: 'market',
    official: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    description: 'Perplexity AI 搜索引擎,实时联网 / 引用溯源 / Pro 模型多选',
    url: 'https://perplexity.ai',
    vendor: 'perplexity',
    fallbackIcon: Star,
    tags: ['搜索', '联网'],
    category: 'market',
    official: true,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek 深度求索',
    description: 'DeepSeek 开源大模型,V3 / R1 推理模型 / 极低价格 / 代码能力领先',
    url: 'https://deepseek.com',
    vendor: 'deepseek',
    fallbackIcon: Star,
    tags: ['DeepSeek', '开源'],
    category: 'market',
    free: true,
    official: true,
  },
  {
    id: 'qwen',
    name: '阿里通义千问',
    description: '阿里巴巴通义千问模型市场,Qwen 系列 / 开源闭源双线 / 多模态',
    url: 'https://qwen.com',
    vendor: 'qwen',
    fallbackIcon: Star,
    tags: ['Qwen', '阿里'],
    category: 'market',
    free: true,
    official: true,
  },
  {
    id: 'zhipu',
    name: '智谱 GLM',
    description: '智谱 AI GLM 系列模型市场,GLM-4 / CogVideoX / 开源 ChatGLM',
    url: 'https://open.bigmodel.cn',
    vendor: 'zhipu',
    fallbackIcon: Star,
    tags: ['GLM', '智谱'],
    category: 'market',
    official: true,
  },
  {
    id: 'moonshot',
    name: '月之暗面 Kimi',
    description: 'Moonshot AI Kimi 模型,超长上下文 / 文档解析 / 联网搜索',
    url: 'https://kimi.moonshot.cn',
    vendor: 'moonshot',
    fallbackIcon: Star,
    tags: ['Kimi', '长上下文'],
    category: 'market',
    official: true,
  },
]
// ⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠
