// © 2026 IHUI AI (智汇AI) · 版权所有者: 李春川 (Li Chunchuan) · https://aizhs.top
// Provenance-watermarked. 未授权商用可被溯源追责 (Apache-2.0 须保留本声明与 NOTICE)。
// [IHUI-AI-PROVENANCE]:⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠

import { Cloud, Monitor, Video } from 'lucide-react'
import type { MarketPlugin } from '../types'

export const MARKET_PLUGINS_PART_2: MarketPlugin[] = [
  {
    id: 'claude-desktop',
    name: 'Claude Desktop',
    description: 'Anthropic Claude 桌面应用,本地 MCP 集成 / 文件访问 / 应用操控',
    url: 'https://claude.ai/download',
    vendor: 'anthropic',
    fallbackIcon: Monitor,
    tags: ['电脑', '桌面'],
    category: 'computer',
    free: true,
    official: true,
  },
  {
    id: 'agsafety-agent',
    name: 'Agent.exe',
    description: '开源跨平台 AI 桌面 Agent,基于 E2B 沙箱 + Computer Use,自然语言控制电脑',
    url: 'https://github.com/E2B-Dev/agent',
    fallbackIcon: Monitor,
    tags: ['电脑', 'E2B'],
    category: 'computer',
    free: true,
  },
  {
    id: 'openai-operator',
    name: 'OpenAI Operator',
    description: 'OpenAI Operator AI Agent,CU 计算机使用模型,云端浏览器代理自动完成任务',
    url: 'https://openai.com/index/introducing-operator/',
    vendor: 'openai',
    fallbackIcon: Monitor,
    tags: ['电脑', 'Operator'],
    category: 'computer',
    official: true,
  },

  // ========================================
  // ★ 视频创作(用户特别提到)— 12 项
  // ========================================
  {
    id: 'remotion',
    name: 'Remotion',
    description: 'React 程序化视频创作框架,组件化视频 / 数据驱动 / SSR 渲染,前端开发者首选',
    url: 'https://remotion.dev',
    vendor: 'remotion',
    fallbackIcon: Video,
    tags: ['视频', 'React'],
    category: 'video',
    free: true,
    official: true,
  },
  {
    id: 'hyperframes',
    name: 'Hyperframes',
    description: 'Hyperframes Studio 交互式 React 动画创作,代码 + 时间轴 / 导出 MP4 / GIF',
    url: 'https://hyperframes.studio',
    vendor: 'hyperframes',
    fallbackIcon: Video,
    tags: ['视频', '动画'],
    category: 'video',
    free: true,
  },
  {
    id: 'motion-canvas',
    name: 'Motion Canvas',
    description: 'TypeScript 程序化动画引擎,代码驱动动画 / 实时预览 / 导出 4K 视频',
    url: 'https://motioncanvas.io',
    fallbackIcon: Video,
    tags: ['视频', 'TS'],
    category: 'video',
    free: true,
  },
  {
    id: 'manim',
    name: 'Manim',
    description: '3Blue1Brown 数学动画引擎,Python 代码生成精确数学动画 / 教学视频',
    url: 'https://www.manim.community',
    fallbackIcon: Video,
    tags: ['视频', '数学'],
    category: 'video',
    free: true,
  },
  {
    id: 'ffmpeg-mcp',
    name: 'FFmpeg MCP',
    description: 'FFmpeg 视频 / 音频处理 MCP Server,AI 自然语言操控转码 / 剪辑 / 滤镜',
    url: 'https://ffmpeg.org',
    fallbackIcon: Video,
    tags: ['视频', 'FFmpeg'],
    category: 'video',
    free: true,
  },
  {
    id: 'runway',
    name: 'Runway',
    description: 'Runway AI 视频生成平台,Gen-3 / 文生视频 / 图生视频 / 视频风格化',
    url: 'https://runwayml.com',
    fallbackIcon: Video,
    tags: ['视频', 'AI 生成'],
    category: 'video',
    official: true,
  },
  {
    id: 'pika',
    name: 'Pika Labs',
    description: 'Pika AI 视频生成,文本 / 图片生成短视频 / Pikaffects 特效 / 创意社区',
    url: 'https://pika.art',
    fallbackIcon: Video,
    tags: ['视频', 'AI 生成'],
    category: 'video',
  },
  {
    id: 'sora',
    name: 'OpenAI Sora',
    description: 'OpenAI Sora 文生视频模型,长视频 / 高保真 / 物理世界模拟 / 故事创作',
    url: 'https://openai.com/sora',
    vendor: 'openai',
    fallbackIcon: Video,
    tags: ['视频', 'Sora'],
    category: 'video',
    official: true,
  },
  {
    id: 'kling',
    name: '快手可灵 Kling',
    description: '快手可灵 AI 视频生成,国产顶尖 / 长视频 / 1080P / 物理规律 / 中国美学',
    url: 'https://kling.kuaishou.com',
    fallbackIcon: Video,
    tags: ['视频', '国产'],
    category: 'video',
    official: true,
  },
  {
    id: 'hailuo',
    name: 'MiniMax 海螺',
    description: 'MiniMax 海螺 AI 视频生成,国产 / 文生视频 / 图生视频 / 速度快',
    url: 'https://hailuoai.video',
    vendor: 'minimax',
    fallbackIcon: Video,
    tags: ['视频', '国产'],
    category: 'video',
    official: true,
  },
  {
    id: 'veo',
    name: 'Google Veo',
    description: 'Google DeepMind Veo 文生视频模型,1080P / 长视频 / 物理一致 / 电影级',
    url: 'https://deepmind.google/technologies/veo/',
    vendor: 'google',
    fallbackIcon: Video,
    tags: ['视频', 'Google'],
    category: 'video',
    official: true,
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    description: 'Synthesia AI 数字人视频生成,140+ 语言 / 自定义 avatar / 企业培训视频',
    url: 'https://synthesia.io',
    fallbackIcon: Video,
    tags: ['视频', '数字人'],
    category: 'video',
  },

  // ========================================
  // ★ 开发部署(用户特别提到 Vercel)— 12 项
  // ========================================
  {
    id: 'vercel',
    name: 'Vercel',
    description: '前端云平台,Next.js 母公司 / Edge Functions / 预览部署 / 全球 CDN',
    url: 'https://vercel.com',
    vendor: 'vercel',
    fallbackIcon: Cloud,
    tags: ['部署', 'Edge'],
    category: 'devops',
    free: true,
    official: true,
  },
  {
    id: 'netlify',
    name: 'Netlify',
    description: '静态站点 / JAMstack 部署平台,自动 CI/CD / Edge Functions / 表单处理',
    url: 'https://netlify.com',
    fallbackIcon: Cloud,
    tags: ['部署', 'JAMstack'],
    category: 'devops',
    free: true,
    official: true,
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'Cloudflare Workers / Pages / R2 / D1 / KV,边缘计算全栈平台',
    url: 'https://cloudflare.com',
    vendor: 'cloudflare',
    fallbackIcon: Cloud,
    tags: ['部署', '边缘'],
    category: 'devops',
    free: true,
    official: true,
  },
]
// ⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠
