import {
  Database,
  FileSpreadsheet,
  FileText,
  Globe,
  Lock,
  Presentation,
  ShieldCheck,
} from 'lucide-react'
import type { MarketPlugin } from '../types'

export const MARKET_PLUGINS_PART_11: MarketPlugin[] = [
  {
    id: 'bitwarden',
    name: 'Bitwarden',
    description: 'Bitwarden 开源密码管理,跨平台 / 团队共享 / MCP Server / 自托管',
    url: 'https://bitwarden.com',
    fallbackIcon: Lock,
    tags: ['安全', '开源'],
    category: 'security',
    free: true,
  },
  {
    id: 'auth0',
    name: 'Auth0',
    description: 'Okta Auth0 身份认证平台,SSO / MFA / OAuth2 / 社交登录 / 企业级',
    url: 'https://auth0.com',
    fallbackIcon: Lock,
    tags: ['安全', '认证'],
    category: 'security',
    official: true,
  },
  {
    id: 'clerk',
    name: 'Clerk',
    description: 'Clerk 现代化用户认证,React / Next.js 友好 / 多因子 / B2B / 组织',
    url: 'https://clerk.com',
    fallbackIcon: Lock,
    tags: ['安全', 'Next.js'],
    category: 'security',
  },
  {
    id: 'cloudflare-waf',
    name: 'Cloudflare WAF',
    description: 'Cloudflare Web 应用防火墙,DDoS 防护 / Bot 管理 / API 安全',
    url: 'https://cloudflare.com/waf',
    vendor: 'cloudflare',
    fallbackIcon: ShieldCheck,
    tags: ['安全', 'WAF'],
    category: 'security',
    official: true,
  },
  {
    id: 'snyk',
    name: 'Snyk',
    description: 'Snyk 开发者安全平台,依赖漏洞 / 容器 / IaC / 代码安全 / AI 修复',
    url: 'https://snyk.io',
    fallbackIcon: ShieldCheck,
    tags: ['安全', '漏洞'],
    category: 'security',
  },

  // ========================================
  // ★ 数据分析 / BI — 6 项
  // ========================================
  {
    id: 'airtable-mcp',
    name: 'Airtable MCP',
    description: 'Airtable MCP Server,AI 操控低代码数据库 / 表格 / 视图 / 自动化',
    url: 'https://airtable.com/developers',
    vendor: 'airtable',
    fallbackIcon: Database,
    tags: ['数据', 'Airtable'],
    category: 'data',
    official: true,
  },
  {
    id: 'google-sheets-mcp',
    name: 'Google Sheets MCP',
    description: 'Google Sheets MCP Server,AI 读写 / 分析 / 计算 / 图表 / 数据透视',
    url: 'https://developers.google.com/sheets',
    vendor: 'google',
    fallbackIcon: Database,
    tags: ['数据', 'Sheets'],
    category: 'data',
    official: true,
  },
  {
    id: 'excel-mcp',
    name: 'Microsoft Excel MCP',
    description: 'Microsoft Excel MCP Server,AI 操控工作簿 / 公式 / 图表 / 数据分析',
    url: 'https://www.microsoft.com/excel',
    vendor: 'microsoft',
    fallbackIcon: Database,
    tags: ['数据', 'Excel'],
    category: 'data',
    official: true,
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    description: 'Snowflake 云数据仓库,AI 数据云 / Cortex AI / Streamlit / 数据共享',
    url: 'https://snowflake.com',
    fallbackIcon: Database,
    tags: ['数据', '云'],
    category: 'data',
    official: true,
  },
  {
    id: 'databricks',
    name: 'Databricks',
    description: 'Databricks 数据 + AI 平台,Lakehouse / MLflow / Mosaic AI / Delta',
    url: 'https://databricks.com',
    fallbackIcon: Database,
    tags: ['数据', 'AI'],
    category: 'data',
    official: true,
  },
  {
    id: 'motherduck',
    name: 'MotherDuck',
    description: 'MotherDuck DuckDB 云端数据仓库,本地 + 云 / SQL / AI 数据分析',
    url: 'https://motherduck.com',
    fallbackIcon: Database,
    tags: ['数据', 'DuckDB'],
    category: 'data',
    free: true,
  },

  // ========================================
  // ★ Codex 必装 10 插件补全(2026-07-31 新增,4 个 catalog 缺失项)
  // ========================================
  {
    id: 'build-web-apps',
    name: 'Build Web Apps',
    description:
      'AI 一句话生成前端网页应用,React / Vue / Next.js / Tailwind / shadcn 全栈项目脚手架',
    url: 'https://vercel.com',
    vendor: 'vercel',
    fallbackIcon: Globe,
    tags: ['构建', 'Web', '脚手架'],
    category: 'creation',
    free: true,
    official: true,
  },
  {
    id: 'documents',
    name: 'Documents',
    description: 'AI 帮你交付正式文档,Word / Markdown / PDF / 合同 / 报告 / API 文档模板化生成',
    url: 'https://www.notion.com/product/ai',
    vendor: 'notion',
    fallbackIcon: FileText,
    tags: ['文档', 'AI 写作'],
    category: 'creation',
    free: true,
  },
  {
    id: 'presentations',
    name: 'Presentations',
    description: 'AI 帮你生成高质量 PPT,大纲 → 排版 → 配图 → 导出 PPTX / Google Slides 一气呵成',
    url: 'https://gamma.app',
    fallbackIcon: Presentation,
    tags: ['PPT', '演示'],
    category: 'creation',
    free: true,
  },
  {
    id: 'spreadsheets',
    name: 'Spreadsheets',
    description: 'AI 数据分析师,Excel / Google Sheets 公式生成 / 数据透视 / 图表可视化 / 数据清洗',
    url: 'https://sheets.google.com',
    vendor: 'google',
    fallbackIcon: FileSpreadsheet,
    tags: ['表格', '数据分析'],
    category: 'data',
    free: true,
  },
]
