import { AppWindow, Bot, Cloud, Monitor, MousePointer2, Terminal } from 'lucide-react'
import type { MarketPlugin } from '../types'

export const MARKET_PLUGINS_PART_1: MarketPlugin[] = [
  // ========================================
  // ★ 浏览器控制(用户重点需求)— 12 项
  // ========================================
  {
    id: 'playwright-mcp',
    name: 'Playwright MCP',
    description: '微软出品浏览器自动化 MCP Server,跨 Chromium / Firefox / WebKit,AI 操控真实浏览器',
    url: 'https://github.com/microsoft/playwright-mcp',
    vendor: 'microsoft',
    fallbackIcon: MousePointer2,
    tags: ['浏览器', 'MCP'],
    category: 'browser',
    free: true,
    official: true,
  },
  {
    id: 'puppeteer',
    name: 'Puppeteer',
    description: 'Google Chrome DevTools 团队出品 Node.js 浏览器自动化框架,Headless Chrome 控制',
    url: 'https://pptr.dev',
    vendor: 'google',
    fallbackIcon: MousePointer2,
    tags: ['浏览器', 'Chrome'],
    category: 'browser',
    free: true,
    official: true,
  },
  {
    id: 'browser-use',
    name: 'Browser Use',
    description: 'AI 浏览器控制开源框架,LLM 直接操控网页,自然语言指令完成复杂任务',
    url: 'https://browser-use.com',
    vendor: 'chrome',
    fallbackIcon: AppWindow,
    tags: ['浏览器', 'AI'],
    category: 'browser',
    free: true,
  },
  {
    id: 'browserbase',
    name: 'Browserbase',
    description: '云端浏览器基础设施,Serverless 浏览器 / Stealth Mode / 大规模并发自动化',
    url: 'https://browserbase.com',
    fallbackIcon: Cloud,
    tags: ['浏览器', '云端'],
    category: 'browser',
    official: true,
  },
  {
    id: 'stagehand',
    name: 'Stagehand',
    description: 'Browserbase 出品 AI 浏览器自动化 SDK,act / extract / observe 三大原语',
    url: 'https://stagehand.dev',
    fallbackIcon: MousePointer2,
    tags: ['浏览器', 'SDK'],
    category: 'browser',
    free: true,
  },
  {
    id: 'skyvern',
    name: 'Skyvern',
    description: 'AI 浏览器工作流自动化,LLM + 视觉模型操控浏览器,自动完成表单 / 工作流',
    url: 'https://skyvern.com',
    fallbackIcon: MousePointer2,
    tags: ['浏览器', '自动化'],
    category: 'browser',
    free: true,
  },
  {
    id: 'browserless',
    name: 'Browserless',
    description: '云端浏览器即服务,大规模 Headless Chrome 集群 / PDF 生成 / 截图 / 抓取',
    url: 'https://browserless.io',
    fallbackIcon: Cloud,
    tags: ['浏览器', 'SaaS'],
    category: 'browser',
  },
  {
    id: 'selenium',
    name: 'Selenium',
    description: '经典浏览器自动化框架,跨浏览器 / 跨语言 / WebDriver 协议,Web 测试行业标杆',
    url: 'https://www.selenium.dev',
    fallbackIcon: MousePointer2,
    tags: ['浏览器', '测试'],
    category: 'browser',
    free: true,
    official: true,
  },
  {
    id: 'playwright',
    name: 'Playwright',
    description: '微软现代浏览器自动化框架,跨浏览器 / 跨语言 / 自动等待 / 网络拦截',
    url: 'https://playwright.dev',
    vendor: 'microsoft',
    fallbackIcon: MousePointer2,
    tags: ['浏览器', '微软'],
    category: 'browser',
    free: true,
    official: true,
  },
  {
    id: 'multion',
    name: 'MultiOn',
    description: 'AI 浏览器代理,自然语言操控浏览器完成购物 / 预订 / 数据采集等任务',
    url: 'https://multion.ai',
    fallbackIcon: MousePointer2,
    tags: ['浏览器', 'Agent'],
    category: 'browser',
  },
  {
    id: 'axiom',
    name: 'Axiom.ai',
    description: '无代码浏览器自动化平台,录制回放 / 可视化编排 / 数据抓取,无需编程',
    url: 'https://axiom.ai',
    fallbackIcon: MousePointer2,
    tags: ['浏览器', '无代码'],
    category: 'browser',
  },
  {
    id: 'brightdata',
    name: 'Bright Data',
    description: 'Bright Data 浏览器自动化,7200 万住宅 IP / 反检测 / 大规模数据采集',
    url: 'https://brightdata.com',
    fallbackIcon: MousePointer2,
    tags: ['浏览器', '采集'],
    category: 'browser',
  },

  // ========================================
  // ★ 电脑控制(用户重点需求)— 10 项
  // ========================================
  {
    id: 'anthropic-computer-use',
    name: 'Anthropic Computer Use',
    description: 'Claude 官方电脑控制能力,截图识别 + 鼠标键盘操作,直接操控桌面应用',
    url: 'https://anthropic.com/news/3-5-models-and-computer-use',
    vendor: 'anthropic',
    fallbackIcon: Monitor,
    tags: ['电脑', 'Claude'],
    category: 'computer',
    official: true,
  },
  {
    id: 'open-interpreter',
    name: 'Open Interpreter',
    description: '让 LLM 在本地执行代码 / 命令,自然语言操控电脑,Python / Shell / JS 全栈',
    url: 'https://openinterpreter.com',
    fallbackIcon: Terminal,
    tags: ['电脑', '本地'],
    category: 'computer',
    free: true,
  },
  {
    id: 'auto-gpt',
    name: 'AutoGPT',
    description: '自主 AI Agent 鼻祖,设定目标后自动拆解任务 + 联网 + 执行 + 迭代',
    url: 'https://github.com/Significant-Gravitas/AutoGPT',
    fallbackIcon: Bot,
    tags: ['电脑', 'Agent'],
    category: 'computer',
    free: true,
  },
  {
    id: 'babyagi',
    name: 'BabyAGI',
    description: '任务驱动 AI Agent 框架,自动创建 / 优先级排序 / 执行任务循环',
    url: 'https://github.com/yoheinakajima/babyagi',
    fallbackIcon: Bot,
    tags: ['电脑', '任务'],
    category: 'computer',
    free: true,
  },
  {
    id: 'self-operating-computer',
    name: 'Self-Operating Computer',
    description: '开源 AI 操控电脑框架,自然语言指令 + 视觉模型 + 鼠标键盘控制',
    url: 'https://github.com/OthersideAI/self-operating-computer',
    fallbackIcon: Monitor,
    tags: ['电脑', '开源'],
    category: 'computer',
    free: true,
  },
  {
    id: 'openadapt',
    name: 'OpenAdapt',
    description: '开源 AI 桌面自动化,录制人类操作 + LLM 生成自动化脚本,零代码 RPA',
    url: 'https://openadapt.ai',
    fallbackIcon: Monitor,
    tags: ['电脑', 'RPA'],
    category: 'computer',
    free: true,
  },
  {
    id: 'adept-act',
    name: 'Adept ACT-1',
    description: 'Adept AI 出品 ACT-1 模型,自然语言操控浏览器 / 软件 / 工具,企业级 Agent',
    url: 'https://adept.ai',
    fallbackIcon: Monitor,
    tags: ['电脑', 'Adept'],
    category: 'computer',
  },
]
