// © 2026 IHUI AI (智汇AI) · 版权所有者: 李春川 (Li Chunchuan) · https://aizhs.top
// Provenance-watermarked. 未授权商用可被溯源追责 (Apache-2.0 须保留本声明与 NOTICE)。
// [IHUI-AI-PROVENANCE]:⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠

import { Database, FileText, Search as SearchIcon } from 'lucide-react'
import type { MarketPlugin } from '../types'

export const MARKET_PLUGINS_PART_4: MarketPlugin[] = [
  {
    id: 'tavily',
    name: 'Tavily AI',
    description: 'Tavily AI 搜索 API,LLM 优化 / 实时结果 / 摘要 / 答案,Agent 首选搜索',
    url: 'https://tavily.com',
    fallbackIcon: SearchIcon,
    tags: ['搜索', 'AI'],
    category: 'search',
  },
  {
    id: 'exa',
    name: 'Exa AI',
    description: 'Exa 神经网络搜索 API,语义搜索 / 全文内容 / 相似度查询 / 大规模抓取',
    url: 'https://exa.ai',
    fallbackIcon: SearchIcon,
    tags: ['搜索', '语义'],
    category: 'search',
  },
  {
    id: 'google-search-mcp',
    name: 'Google Search MCP',
    description: 'Google Search 官方 MCP Server,自定义搜索 API / Serp / 知识图谱',
    url: 'https://developers.google.com/custom-search',
    vendor: 'google',
    fallbackIcon: SearchIcon,
    tags: ['搜索', 'Google'],
    category: 'search',
    official: true,
  },
  {
    id: 'serpapi',
    name: 'SerpAPI',
    description: 'SerpAPI 搜索引擎结果 API,Google / Bing / 百度 / 淘宝等 20+ 引擎结构化数据',
    url: 'https://serpapi.com',
    fallbackIcon: SearchIcon,
    tags: ['搜索', 'API'],
    category: 'search',
  },
  {
    id: 'bing-search',
    name: 'Microsoft Bing',
    description: '微软 Bing 搜索 API,Web / News / Image / Video / Web Search MCP Server',
    url: 'https://www.microsoft.com/bing/apis',
    vendor: 'microsoft',
    fallbackIcon: SearchIcon,
    tags: ['搜索', '微软'],
    category: 'search',
    official: true,
  },
  {
    id: 'duckduckgo',
    name: 'DuckDuckGo',
    description: 'DuckDuckGo 隐私搜索 API,无追踪 / 即时答案 / AI Agent 调用',
    url: 'https://duckduckgo.com',
    fallbackIcon: SearchIcon,
    tags: ['搜索', '隐私'],
    category: 'search',
    free: true,
  },
  {
    id: 'jina-reader',
    name: 'Jina Reader',
    description: 'Jina AI Reader,任意 URL → Markdown,LLM 友好内容提取 / 全网可读',
    url: 'https://jina.ai/reader',
    fallbackIcon: SearchIcon,
    tags: ['搜索', 'Reader'],
    category: 'search',
    free: true,
  },

  // ========================================
  // ★ 数据存储 MCP — 8 项
  // ========================================
  {
    id: 'postgres-mcp',
    name: 'Postgres MCP',
    description: 'PostgreSQL 官方 MCP Server,AI 自然语言查询 / Schema 探索 / SQL 执行',
    url: 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres',
    fallbackIcon: Database,
    tags: ['数据库', 'MCP'],
    category: 'data',
    free: true,
    official: true,
  },
  {
    id: 'sqlite-mcp',
    name: 'SQLite MCP',
    description: 'SQLite MCP Server,本地轻量数据库 / AI 查询 / 嵌入式数据存储',
    url: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite',
    fallbackIcon: Database,
    tags: ['数据库', 'SQLite'],
    category: 'data',
    free: true,
  },
  {
    id: 'mongodb-mcp',
    name: 'MongoDB MCP',
    description: 'MongoDB 官方 MCP Server,AI 操控 NoSQL / 文档数据库 / 聚合管道',
    url: 'https://www.mongodb.com/docs/mongodb-ai-voice/mcp',
    vendor: 'mongodb',
    fallbackIcon: Database,
    tags: ['数据库', 'NoSQL'],
    category: 'data',
    free: true,
    official: true,
  },
  {
    id: 'redis-mcp',
    name: 'Redis MCP',
    description: 'Redis MCP Server,AI 操控缓存 / 队列 / 发布订阅 / 数据结构',
    url: 'https://redis.io/mcp',
    vendor: 'redis',
    fallbackIcon: Database,
    tags: ['数据库', 'Redis'],
    category: 'data',
    free: true,
    official: true,
  },
  {
    id: 'supabase-mcp',
    name: 'Supabase MCP',
    description: 'Supabase 官方 MCP Server,AI 操控 Postgres / Auth / Storage / Edge',
    url: 'https://supabase.com/docs/guides/getting-started/mcp',
    vendor: 'supabase',
    fallbackIcon: Database,
    tags: ['数据库', 'Supabase'],
    category: 'data',
    free: true,
    official: true,
  },
  {
    id: 'neon',
    name: 'Neon Postgres',
    description: 'Neon Serverless Postgres,分支 / 即时恢复 / Scale to zero / MCP 集成',
    url: 'https://neon.tech',
    fallbackIcon: Database,
    tags: ['数据库', 'Serverless'],
    category: 'data',
    free: true,
  },
  {
    id: 'planetscale',
    name: 'PlanetScale',
    description: 'PlanetScale Serverless MySQL,分支 / 在线 Schema 变更 / 全球分布',
    url: 'https://planetscale.com',
    fallbackIcon: Database,
    tags: ['数据库', 'MySQL'],
    category: 'data',
  },
  {
    id: 'turso',
    name: 'Turso',
    description: 'Turso 边缘 SQLite,libSQL / 多区域复制 / 嵌入式 / Serverless',
    url: 'https://turso.tech',
    fallbackIcon: Database,
    tags: ['数据库', '边缘'],
    category: 'data',
    free: true,
  },

  // ========================================
  // ★ 文件与存储 MCP — 6 项
  // ========================================
  {
    id: 'filesystem-mcp',
    name: 'Filesystem MCP',
    description: 'Filesystem MCP Server,官方文件系统访问 / 读写 / 搜索 / 目录操作',
    url: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
    fallbackIcon: FileText,
    tags: ['文件', 'MCP'],
    category: 'data',
    free: true,
    official: true,
  },
  {
    id: 'google-drive-mcp',
    name: 'Google Drive MCP',
    description: 'Google Drive 官方 MCP Server,AI 搜索 / 读取 / 管理 Drive 文件',
    url: 'https://developers.google.com/drive',
    vendor: 'google',
    fallbackIcon: FileText,
    tags: ['文件', 'Google'],
    category: 'data',
    official: true,
  },
  {
    id: 'onedrive-mcp',
    name: 'OneDrive MCP',
    description: 'Microsoft OneDrive MCP Server,AI 访问 / 搜索 / 管理 OneDrive 文件',
    url: 'https://www.microsoft.com/en-us/microsoft-365/onedrive/online-cloud-storage',
    vendor: 'microsoft',
    fallbackIcon: FileText,
    tags: ['文件', '微软'],
    category: 'data',
    official: true,
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    description: 'Dropbox 云存储,文件同步 / 共享 / 版本 / API 集成 AI 工作流',
    url: 'https://dropbox.com',
    fallbackIcon: FileText,
    tags: ['文件', '云存储'],
    category: 'data',
    official: true,
  },
]
// ⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠
