// © 2026 IHUI AI (智汇AI) · 版权所有者: 李春川 (Li Chunchuan) · https://aizhs.top
// Provenance-watermarked. 未授权商用可被溯源追责 (Apache-2.0 须保留本声明与 NOTICE)。
// [IHUI-AI-PROVENANCE]:⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠

import { Cpu, Layers, Workflow, Zap } from 'lucide-react'
import type { MarketPlugin } from '../types'

export const MARKET_PLUGINS_PART_9: MarketPlugin[] = [
  {
    id: 'fireworks-ai',
    name: 'Fireworks AI',
    description: 'Fireworks AI 高速推理平台,开源模型 / serverless / 函数调用',
    url: 'https://fireworks.ai',
    vendor: 'fireworks',
    fallbackIcon: Zap,
    tags: ['推理', 'serverless'],
    category: 'model',
    official: true,
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'Groq 超低延迟推理平台,LPU 芯片 / 开源模型 / 毫秒级响应',
    url: 'https://groq.com',
    vendor: 'groq',
    fallbackIcon: Zap,
    tags: ['推理', 'LPU'],
    category: 'model',
    free: true,
    official: true,
  },
  {
    id: 'replicate',
    name: 'Replicate',
    description: 'Replicate 模型运行平台,开源模型 / API 调用 / 一键部署 / 图片视频生成',
    url: 'https://replicate.com',
    vendor: 'replicate',
    fallbackIcon: Layers,
    tags: ['模型', '部署'],
    category: 'model',
    official: true,
  },
  {
    id: 'huggingface-models',
    name: 'Hugging Face Models',
    description: 'Hugging Face 模型仓库,百万级开源模型 / 权重下载 / Inference API',
    url: 'https://huggingface.co/models',
    vendor: 'huggingface',
    fallbackIcon: Cpu,
    tags: ['模型', '开源'],
    category: 'model',
    free: true,
    official: true,
  },

  // ========================================
  // ★ 本地 / 推理 / 国产 — 10 项
  // ========================================
  {
    id: 'ollama',
    name: 'Ollama',
    description: 'Ollama 本地大模型运行框架,一行命令跑 Llama / Qwen / DeepSeek / 离线',
    url: 'https://ollama.com',
    vendor: 'ollama',
    fallbackIcon: Cpu,
    tags: ['本地', '开源'],
    category: 'model',
    free: true,
  },
  {
    id: 'lm-studio',
    name: 'LM Studio',
    description: 'LM Studio 本地 LLM 桌面应用,GUI / 模型下载 / OpenAI 兼容 API',
    url: 'https://lmstudio.ai',
    fallbackIcon: Cpu,
    tags: ['本地', 'GUI'],
    category: 'model',
    free: true,
  },
  {
    id: 'jan',
    name: 'Jan',
    description: 'Jan 开源本地 AI 助手,桌面应用 / 离线 / OpenAI 兼容 / 自托管',
    url: 'https://jan.ai',
    fallbackIcon: Cpu,
    tags: ['本地', '开源'],
    category: 'model',
    free: true,
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    description: 'Cerebras 超快推理平台,Wafer-Scale Engine / 极速 token 生成',
    url: 'https://cerebras.ai',
    vendor: 'cerebras',
    fallbackIcon: Cpu,
    tags: ['推理', '极速'],
    category: 'model',
    official: true,
  },
  {
    id: 'sambanova',
    name: 'SambaNova',
    description: 'SambaNova AI 推理平台,RDU 芯片 / 开源模型 / 企业级部署',
    url: 'https://sambanova.ai',
    vendor: 'sambanova',
    fallbackIcon: Cpu,
    tags: ['推理', '企业'],
    category: 'model',
    official: true,
  },
  {
    id: 'siliconcloud',
    name: '硅基流动 SiliconCloud',
    description: 'SiliconCloud 国产模型聚合推理平台,开源模型 / 极低价格 / 高并发',
    url: 'https://siliconflow.cn',
    vendor: 'siliconcloud',
    fallbackIcon: Cpu,
    tags: ['推理', '国产'],
    category: 'model',
    free: true,
  },
  {
    id: 'modelscope',
    name: 'ModelScope 魔搭',
    description: '阿里达摩院 ModelScope 模型社区,国产开源模型 / Demo / 数据集',
    url: 'https://modelscope.cn',
    vendor: 'modelscope',
    fallbackIcon: Cpu,
    tags: ['模型', '阿里'],
    category: 'model',
    free: true,
    official: true,
  },
  {
    id: 'volcengine',
    name: '火山方舟',
    description: '字节跳动火山引擎方舟大模型平台,豆包 / 多模型 / 精调 / 推理加速',
    url: 'https://volcengine.com/product/ark',
    vendor: 'volcengine',
    fallbackIcon: Cpu,
    tags: ['火山', '字跳'],
    category: 'model',
    official: true,
  },
  {
    id: 'bailian',
    name: '阿里百炼',
    description: '阿里云百炼大模型平台,通义系列 / 精调 / RAG / Agent 一站式',
    url: 'https://bailian.console.aliyun.com',
    vendor: 'bailian',
    fallbackIcon: Cpu,
    tags: ['百炼', '阿里'],
    category: 'model',
    official: true,
  },
  {
    id: 'tencent-cloud-lke',
    name: '腾讯云大模型知识引擎',
    description: '腾讯云 LKE 大模型知识引擎,RAG / Agent / 知识库 / 行业模型',
    url: 'https://lke.cloud.tencent.com',
    vendor: 'tencent',
    fallbackIcon: Cpu,
    tags: ['腾讯', 'RAG'],
    category: 'model',
    official: true,
  },

  // ========================================
  // ★ 自动化 / 工作流 — 8 项
  // ========================================
  {
    id: 'n8n-templates',
    name: 'n8n Templates',
    description: 'n8n 工作流自动化平台模板市场,数千个 AI 工作流模板一键导入',
    url: 'https://n8n.io/templates',
    fallbackIcon: Workflow,
    tags: ['工作流', '自动化'],
    category: 'workflow',
    free: true,
  },
  {
    id: 'make-com',
    name: 'Make.com',
    description: 'Make 可视化自动化平台,1500+ 应用集成 / AI 节点 / 场景化模板',
    url: 'https://make.com',
    fallbackIcon: Workflow,
    tags: ['自动化', '集成'],
    category: 'workflow',
    official: true,
  },
  {
    id: 'zapier-ai',
    name: 'Zapier AI Actions',
    description: 'Zapier AI Actions 市场,7000+ 应用集成 / AI 中央 / Agent 自动化',
    url: 'https://zapier.com/ai',
    fallbackIcon: Zap,
    tags: ['自动化', 'AI'],
    category: 'workflow',
    official: true,
  },
  {
    id: 'pipedream',
    name: 'Pipedream',
    description: 'Pipedream 开发者自动化平台,2600+ 应用 / 代码 + 无代码 / AI 工作流',
    url: 'https://pipedream.com',
    fallbackIcon: Workflow,
    tags: ['自动化', '开发者'],
    category: 'workflow',
    free: true,
  },
]
// ⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠
