import { Bot, Building2, Cloud, Code, Lock, Terminal, Workflow } from 'lucide-react'
import type { MarketPlugin } from '../types'

export const MARKET_PLUGINS_PART_10: MarketPlugin[] = [
  {
    id: 'activepieces',
    name: 'Activepieces',
    description: '开源 AI 自动化平台,200+ 集成 / 自托管 / Zapier 替代品',
    url: 'https://activepieces.com',
    fallbackIcon: Workflow,
    tags: ['自动化', '开源'],
    category: 'workflow',
    free: true,
  },
  {
    id: 'n8n-cloud',
    name: 'n8n Cloud',
    description: 'n8n 官方云端版本,AI 工作流 / Agent / 自动化 / 无需自托管',
    url: 'https://n8n.io/cloud',
    fallbackIcon: Workflow,
    tags: ['自动化', '云端'],
    category: 'workflow',
    official: true,
  },
  {
    id: 'relay',
    name: 'Relay.app',
    description: 'Relay 现代化自动化平台,AI 步骤 / 人机协作 / 100+ 应用集成',
    url: 'https://relay.app',
    fallbackIcon: Workflow,
    tags: ['自动化', 'AI'],
    category: 'workflow',
  },
  {
    id: 'bardeen',
    name: 'Bardeen',
    description: 'Bardeen AI 浏览器自动化,Chrome 扩展 / 一键自动化 / AI 工作流',
    url: 'https://bardeen.ai',
    fallbackIcon: Workflow,
    tags: ['自动化', '浏览器'],
    category: 'workflow',
    free: true,
  },

  // ========================================
  // ★ 云厂商 AI 平台 — 8 项
  // ========================================
  {
    id: 'aws-bedrock',
    name: 'AWS Bedrock',
    description: 'Amazon Bedrock 托管 LLM 服务,多模型 / Knowledge Base / Agent / Guardrails',
    url: 'https://aws.amazon.com/bedrock',
    vendor: 'bedrock',
    fallbackIcon: Building2,
    tags: ['AWS', '云'],
    category: 'market',
    official: true,
  },
  {
    id: 'azure-ai',
    name: 'Azure AI Foundry',
    description: 'Microsoft Azure AI Foundry 模型目录,OpenAI / 开源模型 / 多模态 / 企业级',
    url: 'https://ai.azure.com',
    vendor: 'azureai',
    fallbackIcon: Building2,
    tags: ['Azure', '云'],
    category: 'market',
    official: true,
  },
  {
    id: 'vertex-ai',
    name: 'Vertex AI Agent Builder',
    description: 'Google Cloud Vertex AI Agent Builder,企业级 Agent / RAG / 模型花园',
    url: 'https://cloud.google.com/vertex-ai',
    vendor: 'vertexai',
    fallbackIcon: Building2,
    tags: ['GCP', 'Agent'],
    category: 'market',
    official: true,
  },
  {
    id: 'copilot-studio',
    name: 'Microsoft Copilot Studio',
    description: 'Microsoft Copilot Studio 低代码 Agent 构建平台,深度集成 M365 生态',
    url: 'https://copilotstudio.microsoft.com',
    vendor: 'microsoft',
    fallbackIcon: Bot,
    tags: ['微软', 'Copilot'],
    category: 'market',
    official: true,
  },
  {
    id: 'aws-q-developer',
    name: 'Amazon Q Developer',
    description: 'AWS Amazon Q Developer AI 编程助手,代码生成 / 安全扫描 / AWS 集成',
    url: 'https://aws.amazon.com/q/developer',
    vendor: 'bedrock',
    fallbackIcon: Code,
    tags: ['AWS', '编程'],
    category: 'ide',
    official: true,
  },
  {
    id: 'watsonx',
    name: 'IBM watsonx',
    description: 'IBM watsonx AI 平台,企业级 / watsonx.ai / watsonx Assistant / 治理',
    url: 'https://ibm.com/watsonx',
    vendor: 'ibm',
    fallbackIcon: Building2,
    tags: ['IBM', '企业'],
    category: 'market',
    official: true,
  },
  {
    id: 'alibaba-cloud-bailian',
    name: '阿里云百炼',
    description: '阿里云百炼大模型平台,通义千问 / 精调 / RAG / Agent 一站式',
    url: 'https://bailian.aliyun.com',
    vendor: 'alibaba-cloud',
    fallbackIcon: Building2,
    tags: ['阿里云', '百炼'],
    category: 'market',
    official: true,
  },
  {
    id: 'huawei-cloud-pangu',
    name: '华为云盘古大模型',
    description: '华为云盘古大模型,行业 AI / 工业质检 / 气象 / 金融 / 政企',
    url: 'https://huaweicloud.com/product/pangu.html',
    vendor: 'huawei-cloud',
    fallbackIcon: Building2,
    tags: ['华为云', '盘古'],
    category: 'market',
    official: true,
  },

  // ========================================
  // ★ 代码执行 / 沙箱 — 6 项
  // ========================================
  {
    id: 'e2b',
    name: 'E2B',
    description: 'E2B 沙箱代码执行平台,LLM 安全运行代码 / 文件系统 / 进程 / 网络隔离',
    url: 'https://e2b.dev',
    fallbackIcon: Terminal,
    tags: ['沙箱', '代码'],
    category: 'tool',
    free: true,
  },
  {
    id: 'code-interpreter-mcp',
    name: 'Code Interpreter MCP',
    description: 'OpenAI Code Interpreter 兼容 MCP Server,AI 执行 Python / 数据分析',
    url: 'https://github.com/modelcontextprotocol/servers',
    fallbackIcon: Terminal,
    tags: ['沙箱', 'Python'],
    category: 'tool',
    free: true,
  },
  {
    id: 'daytona',
    name: 'Daytona',
    description: 'Daytona 开源开发环境管理,沙箱 / 远程工作区 / AI 代码执行环境',
    url: 'https://daytona.io',
    fallbackIcon: Terminal,
    tags: ['沙箱', '开源'],
    category: 'tool',
    free: true,
  },
  {
    id: 'modal',
    name: 'Modal',
    description: 'Modal Serverless Python 云计算,跑 AI / 数据 / 模型推理 / 任务编排',
    url: 'https://modal.com',
    fallbackIcon: Cloud,
    tags: ['Serverless', 'Python'],
    category: 'tool',
    free: true,
  },
  {
    id: 'replit-mobile',
    name: 'Replit Mobile',
    description: 'Replit 移动编程,手机 / 平板写代码 / AI Agent / 云端 IDE',
    url: 'https://replit.com/mobile',
    vendor: 'replit',
    fallbackIcon: Terminal,
    tags: ['IDE', '移动'],
    category: 'ide',
    free: true,
  },
  {
    id: 'jupyter',
    name: 'Jupyter AI',
    description: 'Jupyter AI Notebook,AI 助手 / 代码生成 / 解释 / 多模型支持',
    url: 'https://jupyter.org/ai',
    fallbackIcon: Terminal,
    tags: ['Notebook', 'AI'],
    category: 'tool',
    free: true,
  },

  // ========================================
  // ★ 安全 / 鉴权 — 6 项
  // ========================================
  {
    id: '1password-mcp',
    name: '1Password MCP',
    description: '1Password MCP Server,AI 安全访问密码 / 凭据 / 保险库 / 自动填充',
    url: 'https://1password.com',
    fallbackIcon: Lock,
    tags: ['安全', '密码'],
    category: 'security',
    official: true,
  },
]
