"""扫描所有 zh-CN 模块中含中英混杂或英文短语直接作为 zh-CN 值的回归.

判定规则:
1. 值 = 纯英文 (^[A-Z][a-zA-Z]+$ 形式) 且不等于 key
2. 值含中英混杂 (中文后接英文, 或英文后接中文, 单词边界)
3. 排除合理的英文术语如 "ID", "VIP", "API" 等
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(r"g:\IHUI-AI\client\src\locales\modules\zh-CN")
if not ROOT.exists():
    print(f"[FATAL] zh-CN 模块目录不存在: {ROOT}", file=sys.stderr)
    sys.exit(1)

# 允许的纯英文短词（合理术语）
ALLOWED_PURE_ENGLISH = {
    "id", "Id", "ID", "ip", "IP", "ai", "AI", "ui", "UI", "url", "URL", "uri", "URI",
    "json", "JSON", "xml", "XML", "html", "HTML", "css", "CSS", "js", "JS", "ts", "TS",
    "vue", "Vue", "VUE", "react", "React", "node", "Node", "npm", "NPM",
    "ok", "OK", "no", "No", "NO", "yes", "Yes", "YES",
    "title", "name", "type", "status", "code", "msg", "data", "time", "date",
    "user", "admin", "token", "icon", "logo", "tag", "tags", "label", "value",
    "true", "false", "null", "undefined",
    "min", "max", "total", "page", "size", "limit", "offset",
    "asc", "desc", "top", "bottom", "left", "right", "center", "middle",
    "row", "col", "rowIndex", "colIndex", "rowKey",
    "rowClassName", "headerRowClassName", "cellClassName", "headerCellClassName",
    "showOverflowTooltip", "formatter",
    "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday",
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
    "Jan", "Feb", "Mar", "Apr", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
    "am", "pm", "AM", "PM",
    "PC", "pc", "Mac", "mac", "iOS", "ios", "Android", "android", "Windows", "windows",
    "Linux", "linux", "Web", "web", "App", "app", "H5", "h5",
    "VIP", "vip", "Vip",  # 单独 VIP 允许
    "USD", "CNY", "EUR", "JPY", "KRW", "TWD", "RMB",  # 货币
    "UUID", "uuid",
    "OT", "ot",  # 加班
    "on", "off", "auto", "manual",
    "live", "Live", "LIVE",
    "step", "Step", "Step1", "Step2", "Step3",
    "label", "Label",
    "icon", "Icon",
    "bi", "Bi", "BI",
    "edu", "Edu", "EDU",
    "k12", "K12", "K-12",
    "to", "from", "by", "at", "in", "of",
    "delete", "Delete", "update", "Update", "create", "Create",
    "submit", "Submit", "cancel", "Cancel", "save", "Save",
    "edit", "Edit", "add", "Add", "remove", "Remove",
    "view", "View", "list", "List", "search", "Search",
    "all", "All", "any", "Any", "some", "Some",
    "first", "First", "last", "Last", "next", "Next", "prev", "Prev", "Previous",
    "new", "New", "old", "Old", "default", "Default",
    "public", "Public", "private", "Private", "protected", "Protected",
    "open", "Open", "close", "Close", "closed", "Closed", "opened", "Opened",
    "enable", "Enable", "disable", "Disable", "enabled", "Disabled",
    "active", "Active", "inactive", "Inactive",
    "success", "Success", "fail", "Fail", "failed", "Failed", "error", "Error",
    "warning", "Warning", "info", "Info", "debug", "Debug",
    "loading", "Loading", "pending", "Pending", "complete", "Complete",
    "running", "Running", "stopped", "Stopped", "paused", "Paused",
    "draft", "Draft", "published", "Published",
    "available", "Available", "unavailable", "Unavailable",
    "normal", "Normal", "abnormal", "Abnormal", "anomaly", "Anomaly",
    "online", "Online", "offline", "Offline",
    "yes", "Yes", "no", "No", "ok", "Ok", "OK",
    "more", "More", "less", "Less",
    "start", "Start", "end", "End", "begin", "Begin", "finish", "Finish",
    "log", "Log", "logs", "Logs", "logger", "Logger",
    "menu", "Menu", "submenu", "Submenu",
    "home", "Home", "settings", "Settings", "profile", "Profile",
    "about", "About", "help", "Help", "feedback", "Feedback",
    "file", "File", "folder", "Folder", "directory", "Directory",
    "image", "Image", "video", "Video", "audio", "Audio",
    "document", "Document", "doc", "Doc", "docs", "Docs",
    "download", "Download", "upload", "Upload", "import", "Import", "export", "Export",
    "copy", "Copy", "paste", "Paste", "cut", "Cut",
    "print", "Print",
    "share", "Share", "like", "Like", "favorite", "Favorite", "favourite", "Favourite",
    "follow", "Follow", "subscribe", "Subscribe",
    "comment", "Comment", "reply", "Reply",
    "send", "Send", "receive", "Receive", "push", "Push",
    "login", "Login", "logout", "Logout", "register", "Register", "signup", "Signup",
    "signin", "Signin", "signout", "Signout",
    "password", "Password", "username", "Username", "nickname", "Nickname",
    "email", "Email", "phone", "Phone", "mobile", "Mobile", "tel", "Tel",
    "address", "Address", "location", "Location", "city", "City", "country", "Country",
    "company", "Company", "department", "Department", "team", "Team", "group", "Group",
    "role", "Role", "permission", "Permission", "authority", "Authority",
    "member", "Member", "user", "User", "admin", "Admin", "operator", "Operator",
    "customer", "Customer", "client", "Client", "server", "Server",
    "service", "Service", "module", "Module", "plugin", "Plugin",
    "version", "Version", "release", "Release", "update", "Update", "upgrade", "Upgrade",
    "config", "Config", "configuration", "Configuration", "setting", "Setting",
    "task", "Task", "job", "Job", "work", "Work", "project", "Project",
    "order", "Order", "product", "Product", "item", "Item", "goods", "Goods",
    "category", "Category", "tag", "Tag", "label", "Label",
    "level", "Level", "rank", "Rank", "grade", "Grade", "score", "Score", "point", "Point",
    "balance", "Balance", "amount", "Amount", "money", "Money", "price", "Price",
    "discount", "Discount", "coupon", "Coupon", "voucher", "Voucher",
    "pay", "Pay", "payment", "Payment", "refund", "Refund", "recharge", "Recharge",
    "withdraw", "Withdraw", "withdrawal", "Withdrawal", "transfer", "Transfer",
    "recharge", "Recharge", "cash", "Cash", "coin", "Coin", "credit", "Credit",
    "wallet", "Wallet", "bank", "Bank", "card", "Card",
    "message", "Message", "notification", "Notification", "notice", "Notice",
    "email", "Email", "sms", "SMS", "push", "Push", "mail", "Mail",
    "inbox", "Inbox", "outbox", "Outbox", "draft", "Draft", "sent", "Sent", "trash", "Trash",
    "report", "Report", "chart", "Chart", "graph", "Graph", "table", "Table",
    "form", "Form", "input", "Input", "output", "Output", "button", "Button",
    "text", "Text", "textarea", "Textarea", "select", "Select", "option", "Option",
    "radio", "Radio", "checkbox", "Checkbox", "switch", "Switch", "slider", "Slider",
    "tab", "Tab", "tabs", "Tabs", "panel", "Panel", "card", "Card", "modal", "Modal",
    "dialog", "Dialog", "drawer", "Drawer", "popover", "Popover", "tooltip", "Tooltip",
    "menu", "Menu", "dropdown", "Dropdown", "navbar", "Navbar", "sidebar", "Sidebar",
    "header", "Header", "footer", "Footer", "content", "Content", "main", "Main",
    "section", "Section", "block", "Block", "container", "Container", "wrapper", "Wrapper",
    "row", "Row", "col", "Col", "column", "Column", "cell", "Cell",
    "border", "Border", "padding", "Padding", "margin", "Margin",
    "color", "Color", "background", "Background", "text", "Text",
    "font", "Font", "size", "Size", "weight", "Weight", "style", "Style",
    "bold", "Bold", "italic", "Italic", "underline", "Underline",
    "left", "Left", "right", "Right", "center", "Center", "top", "Top", "bottom", "Bottom",
    "width", "Width", "height", "Height", "min", "Min", "max", "Max",
    "show", "Show", "hide", "Hide", "visible", "Visible", "hidden", "Hidden",
    "open", "Open", "close", "Close", "expand", "Expand", "collapse", "Collapse",
    "rotate", "Rotate", "flip", "Flip", "zoom", "Zoom", "scale", "Scale",
    "move", "Move", "drag", "Drag", "drop", "Drop", "sort", "Sort", "filter", "Filter",
    "search", "Search", "find", "Find", "query", "Query", "select", "Select",
    "add", "Add", "remove", "Remove", "insert", "Insert", "delete", "Delete",
    "edit", "Edit", "modify", "Modify", "update", "Update", "change", "Change",
    "create", "Create", "new", "New", "destroy", "Destroy", "remove", "Remove",
    "enable", "Enable", "disable", "Disable", "activate", "Activate", "deactivate", "Deactivate",
    "start", "Start", "stop", "Stop", "pause", "Pause", "resume", "Resume", "restart", "Restart",
    "lock", "Lock", "unlock", "Unlock", "block", "Block", "unblock", "Unblock",
    "approve", "Approve", "reject", "Reject", "review", "Review",
    "submit", "Submit", "cancel", "Cancel", "confirm", "Confirm", "abort", "Abort",
    "success", "Success", "failure", "Failure", "warning", "Warning", "error", "Error",
    "info", "Info", "debug", "Debug", "trace", "Trace",
    "log", "Log", "audit", "Audit", "monitor", "Monitor",
    "test", "Test", "demo", "Demo", "sample", "Sample", "example", "Example",
    "default", "Default", "custom", "Custom", "user-defined", "User-defined",
    "global", "Global", "local", "Local", "public", "Public", "private", "Private",
    "current", "Current", "previous", "Previous", "next", "Next",
    "first", "First", "last", "Last", "begin", "Begin", "end", "End",
    "primary", "Primary", "secondary", "Secondary", "tertiary", "Tertiary",
    "main", "Main", "sub", "Sub", "minor", "Minor", "major", "Major",
    "important", "Important", "urgent", "Urgent", "normal", "Normal",
    "easy", "Easy", "hard", "Hard", "simple", "Simple", "complex", "Complex",
    "fast", "Fast", "slow", "Slow", "quick", "Quick",
    "high", "High", "low", "Low", "medium", "Medium", "middle", "Middle",
    "big", "Big", "small", "Small", "large", "Large", "tiny", "Tiny",
    "long", "Long", "short", "Short",
    "wide", "Wide", "narrow", "Narrow",
    "thick", "Thick", "thin", "Thin",
    "heavy", "Heavy", "light", "Light",
    "strong", "Strong", "weak", "Weak",
    "hot", "Hot", "cold", "Cold", "warm", "Warm", "cool", "Cool",
    "new", "New", "old", "Old", "fresh", "Fresh", "stale", "Stale",
    "clean", "Clean", "dirty", "Dirty",
    "full", "Full", "empty", "Empty",
    "rich", "Rich", "poor", "Poor",
    "best", "Best", "worst", "Worst", "better", "Better", "worse", "Worse",
    "more", "More", "less", "Less", "most", "Most", "least", "Least",
    "many", "Many", "few", "Few", "several", "Several", "some", "Some", "any", "Any",
    "all", "All", "none", "None", "nothing", "Nothing", "something", "Something", "everything", "Everything",
    "one", "One", "two", "Two", "three", "Three", "four", "Four", "five", "Five",
    "six", "Six", "seven", "Seven", "eight", "Eight", "nine", "Nine", "ten", "Ten",
    "first", "First", "second", "Second", "third", "Third", "fourth", "Fourth", "fifth", "Fifth",
    "last", "Last", "final", "Final",
    "top", "Top", "bottom", "Bottom",
    "front", "Front", "back", "Back", "middle", "Middle",
    "inside", "Inside", "outside", "Outside", "inner", "Inner", "outer", "Outer",
    "up", "Up", "down", "Down", "left", "Left", "right", "Right",
    "forward", "Forward", "backward", "Backward", "back", "Back",
    "clockwise", "Clockwise", "counter-clockwise", "Counter-clockwise",
    "horizontal", "Horizontal", "vertical", "Vertical", "diagonal", "Diagonal",
    "clockwise", "Clockwise", "counterclockwise", "Counterclockwise",
    "yes", "Yes", "no", "No", "ok", "Ok", "OK", "cancel", "Cancel",
    "on", "On", "off", "Off",
    "true", "True", "false", "False",
    "and", "And", "or", "Or", "not", "Not", "but", "But",
    "if", "If", "else", "Else", "then", "Then", "elseif", "Elseif",
    "for", "For", "while", "While", "do", "Do", "loop", "Loop",
    "function", "Function", "method", "Method", "class", "Class", "object", "Object",
    "variable", "Variable", "constant", "Constant", "parameter", "Parameter", "argument", "Argument",
    "return", "Return", "yield", "Yield", "break", "Break", "continue", "Continue",
    "try", "Try", "catch", "Catch", "finally", "Finally", "throw", "Throw",
    "import", "Import", "export", "Export", "from", "From", "as", "As",
    "with", "With", "without", "Without", "use", "Use", "using", "Using",
    "include", "Include", "exclude", "Exclude", "except", "Except",
    "before", "Before", "after", "After", "during", "During", "since", "Since",
    "until", "Until", "while", "While", "when", "When", "where", "Where",
    "because", "Because", "so", "So", "therefore", "Therefore",
    "however", "However", "although", "Although", "though", "Though",
    "if", "If", "unless", "Unless", "provided", "Provided",
    "in", "In", "out", "Out", "into", "Into", "onto", "Onto",
    "to", "To", "from", "From", "by", "By", "via", "Via", "through", "Through",
    "of", "Of", "off", "Off", "on", "On", "at", "At",
    "between", "Between", "among", "Among", "within", "Within",
    "about", "About", "around", "Around", "near", "Near", "far", "Far",
    "above", "Above", "below", "Below", "under", "Under", "over", "Over",
    "across", "Across", "along", "Along", "against", "Against",
    "per", "Per", "each", "Each", "every", "Every", "any", "Any",
    "such", "Such", "like", "Like", "unlike", "Unlike",
    "as", "As", "than", "Than",
    "title", "Title",
    "vip", "Vip", "VIP",
    "small", "Small", "big", "Big", "tiny", "Tiny", "huge", "Huge",
    "label", "Label", "tags", "Tags",
    "badge", "Badge", "card", "Card",
    "step", "Step", "page", "Page",
    "list", "List", "detail", "Detail", "details", "Details",
    "summary", "Summary", "info", "Info", "description", "Description",
    "name", "Name", "code", "Code", "value", "Value",
    "key", "Key", "keys", "Keys",
    "min", "Min", "max", "Max", "avg", "Avg", "sum", "Sum", "count", "Count",
    "limit", "Limit", "offset", "Offset", "size", "Size", "total", "Total",
    "page", "Page", "pages", "Pages", "pageSize", "PageSize", "pageNum", "PageNum",
    "row", "Row", "rows", "Rows", "col", "Col", "cols", "Cols", "column", "Column", "columns", "Columns",
    "cell", "Cell", "cells", "Cells",
    "header", "Header", "body", "Body", "footer", "Footer",
    "menu", "Menu", "menus", "Menus", "submenu", "Submenu", "submenus", "Submenus",
    "tab", "Tab", "tabs", "Tabs",
    "icon", "Icon", "icons", "Icons",
    "btn", "Btn", "BTN", "button", "Button", "buttons", "Buttons",
    "input", "Input", "inputs", "Inputs", "output", "Output", "outputs", "Outputs",
    "form", "Form", "forms", "Forms", "field", "Field", "fields", "Fields",
    "tip", "Tip", "tips", "Tips", "hint", "Hint", "hints", "Hints",
    "modal", "Modal", "modals", "Modals", "dialog", "Dialog", "dialogs", "Dialogs",
    "drawer", "Drawer", "drawers", "Drawers", "popup", "Popup", "popups", "Popups",
    "tooltip", "Tooltip", "tooltips", "Tooltips", "popover", "Popover", "popovers", "Popovers",
    "panel", "Panel", "panels", "Panels", "card", "Card", "cards", "Cards",
    "tag", "Tag", "tags", "Tags", "label", "Label", "labels", "Labels",
    "badge", "Badge", "badges", "Badges",
    "alert", "Alert", "alerts", "Alerts", "notice", "Notice", "notices", "Notices",
    "toast", "Toast", "toasts", "Toasts", "message", "Message", "messages", "Messages",
    "notification", "Notification", "notifications", "Notifications",
    "loading", "Loading", "spinner", "Spinner", "spinners", "Spinners",
    "empty", "Empty", "placeholder", "Placeholder", "placeholders", "Placeholders",
    "skeleton", "Skeleton", "skeletons", "Skeletons",
    "divider", "Divider", "dividers", "Dividers", "separator", "Separator", "separators", "Separators",
    "spacer", "Spacer", "spacers", "Spacers",
    "grid", "Grid", "grids", "Grids",
    "layout", "Layout", "layouts", "Layouts",
    "sidebar", "Sidebar", "sidebars", "Sidebars", "navbar", "Navbar", "navbars", "Navbars",
    "header", "Header", "headers", "Headers", "footer", "Footer", "footers", "Footers",
    "main", "Main", "mains", "Mains", "aside", "Aside", "asides", "Asides",
    "section", "Section", "sections", "Sections", "article", "Article", "articles", "Articles",
    "block", "Block", "blocks", "Blocks",
    "container", "Container", "containers", "Containers", "wrapper", "Wrapper", "wrappers", "Wrappers",
    "row", "Row", "rows", "Rows", "col", "Col", "cols", "Cols", "column", "Column", "columns", "Columns",
    "cell", "Cell", "cells", "Cells", "item", "Item", "items", "Items",
    "node", "Node", "nodes", "Nodes", "leaf", "Leaf", "leaves", "Leaves",
    "tree", "Tree", "trees", "Trees", "branch", "Branch", "branches", "Branches",
    "root", "Root", "roots", "Roots", "parent", "Parent", "parents", "Parents",
    "child", "Child", "children", "Children", "sibling", "Sibling", "siblings", "Siblings",
    "ancestor", "Ancestor", "ancestors", "Ancestors", "descendant", "Descendant", "descendants", "Descendants",
    "prev", "Prev", "previous", "Previous", "next", "Next",
    "first", "First", "last", "Last", "begin", "Begin", "end", "End",
    "start", "Start", "finish", "Finish", "stop", "Stop",
    "top", "Top", "bottom", "Bottom", "left", "Left", "right", "Right",
    "front", "Front", "back", "Back", "middle", "Middle",
    "head", "Head", "tail", "Tail", "headIdx", "tailIdx", "headIndex", "tailIndex",
    "head", "Head", "header", "Header", "body", "Body", "footer", "Footer",
    "caption", "Caption", "title", "Title", "subtitle", "Subtitle",
    "summary", "Summary", "abstract", "Abstract",
    "label", "Label", "value", "Value", "text", "Text",
    "icon", "Icon", "image", "Image", "img", "Img",
    "link", "Link", "url", "URL", "href", "Href",
    "src", "Src", "alt", "Alt", "title", "Title",
    "width", "Width", "height", "Height", "size", "Size",
    "color", "Color", "background", "Background", "bg", "Bg",
    "font", "Font", "weight", "Weight", "style", "Style",
    "border", "Border", "radius", "Radius",
    "padding", "Padding", "margin", "Margin",
    "position", "Position", "top", "Top", "left", "Left", "right", "Right", "bottom", "Bottom",
    "zIndex", "z-index", "zindex", "ZIndex",
    "display", "Display", "visibility", "Visibility", "opacity", "Opacity",
    "overflow", "Overflow", "scroll", "Scroll",
    "cursor", "Cursor", "pointer", "Pointer",
    "shadow", "Shadow", "gradient", "Gradient",
    "transition", "Transition", "animation", "Animation",
    "transform", "Transform", "rotate", "Rotate", "scale", "Scale", "translate", "Translate", "skew", "Skew",
    "filter", "Filter", "blur", "Blur", "brightness", "Brightness", "contrast", "Contrast",
    "saturation", "Saturation", "hue", "Hue", "invert", "Invert", "opacity", "Opacity",
    "mix-blend-mode", "MixBlendMode", "background-blend-mode", "BackgroundBlendMode",
    "isolation", "Isolation",
    "page", "Page", "page-break", "PageBreak", "page-break-before", "PageBreakBefore", "page-break-after", "PageBreakAfter",
    "page-break-inside", "PageBreakInside",
    "widows", "Widows", "orphans", "Orphans",
    "marks", "Marks", "mark", "Mark", "marker", "Marker",
    "column-count", "ColumnCount", "column-gap", "ColumnGap", "column-rule", "ColumnRule",
    "column-span", "ColumnSpan", "column-fill", "ColumnFill", "column-width", "ColumnWidth",
    "columns", "Columns",
    "flex", "Flex", "flex-direction", "FlexDirection", "flex-wrap", "FlexWrap",
    "flex-flow", "FlexFlow", "justify-content", "JustifyContent", "align-items", "AlignItems",
    "align-self", "AlignSelf", "align-content", "AlignContent", "flex-grow", "FlexGrow",
    "flex-shrink", "FlexShrink", "flex-basis", "FlexBasis", "flex", "Flex", "order", "Order",
    "grid", "Grid", "grid-template", "GridTemplate", "grid-template-columns", "GridTemplateColumns",
    "grid-template-rows", "GridTemplateRows", "grid-template-areas", "GridTemplateAreas",
    "grid-area", "GridArea", "grid-row", "GridRow", "grid-column", "GridColumn",
    "grid-row-start", "GridRowStart", "grid-row-end", "GridRowEnd",
    "grid-column-start", "GridColumnStart", "grid-column-end", "GridColumnEnd",
    "grid-gap", "GridGap", "grid-row-gap", "GridRowGap", "grid-column-gap", "GridColumnGap",
    "gap", "Gap", "row-gap", "RowGap", "column-gap", "ColumnGap",
    "place-items", "PlaceItems", "place-content", "PlaceContent", "place-self", "PlaceSelf",
    "auto-flow", "AutoFlow", "grid-auto-flow", "GridAutoFlow",
    "grid-auto-rows", "GridAutoRows", "grid-auto-columns", "GridAutoColumns",
    "writing-mode", "WritingMode", "direction", "Direction",
    "unicode-bidi", "UnicodeBidi",
    "text-align", "TextAlign", "text-align-last", "TextAlignLast",
    "text-decoration", "TextDecoration", "text-decoration-line", "TextDecorationLine",
    "text-decoration-color", "TextDecorationColor", "text-decoration-style", "TextDecorationStyle",
    "text-decoration-thickness", "TextDecorationThickness",
    "text-indent", "TextIndent", "text-justify", "TextJustify",
    "text-orientation", "TextOrientation", "text-overflow", "TextOverflow",
    "text-rendering", "TextRendering", "text-shadow", "TextShadow",
    "text-transform", "TextTransform", "text-underline-offset", "TextUnderlineOffset",
    "text-underline-position", "TextUnderlinePosition",
    "line-break", "LineBreak", "line-height", "LineHeight",
    "letter-spacing", "LetterSpacing", "word-spacing", "WordSpacing",
    "word-break", "WordBreak", "word-wrap", "WordWrap", "overflow-wrap", "OverflowWrap",
    "white-space", "WhiteSpace", "tab-size", "TabSize",
    "caret-color", "CaretColor",
    "caret", "Caret", "caret-shape", "CaretShape",
    "hyphens", "Hyphens",
    "font", "Font", "font-family", "FontFamily", "font-size", "FontSize",
    "font-size-adjust", "FontSizeAdjust", "font-stretch", "FontStretch",
    "font-style", "FontStyle", "font-variant", "FontVariant",
    "font-variant-caps", "FontVariantCaps", "font-variant-numeric", "FontVariantNumeric",
    "font-variant-ligatures", "FontVariantLigatures",
    "font-weight", "FontWeight", "font-feature-settings", "FontFeatureSettings",
    "font-kerning", "FontKerning", "font-language-override", "FontLanguageOverride",
    "font-optical-sizing", "FontOpticalSizing", "font-palette", "FontPalette",
    "font-variation-settings", "FontVariationSettings",
    "color", "Color", "color-scheme", "ColorScheme",
    "background", "Background", "background-color", "BackgroundColor",
    "background-image", "BackgroundImage", "background-clip", "BackgroundClip",
    "background-origin", "BackgroundOrigin", "background-position", "BackgroundPosition",
    "background-position-x", "BackgroundPositionX", "background-position-y", "BackgroundPositionY",
    "background-repeat", "BackgroundRepeat", "background-size", "BackgroundSize",
    "background-attachment", "BackgroundAttachment", "background-blend-mode", "BackgroundBlendMode",
    "mask", "Mask", "mask-clip", "MaskClip", "mask-composite", "MaskComposite",
    "mask-image", "MaskImage", "mask-mode", "MaskMode", "mask-origin", "MaskOrigin",
    "mask-position", "MaskPosition", "mask-repeat", "MaskRepeat", "mask-size", "MaskSize",
    "mask-type", "MaskType",
    "clip-path", "ClipPath", "clip-rule", "ClipRule", "clip", "Clip",
    "filter", "Filter", "backdrop-filter", "BackdropFilter",
    "mix-blend-mode", "MixBlendMode", "isolation", "Isolation",
    "opacity", "Opacity", "visibility", "Visibility",
    "overflow", "Overflow", "overflow-x", "OverflowX", "overflow-y", "OverflowY",
    "overflow-anchor", "OverflowAnchor", "overflow-clip-margin", "OverflowClipMargin",
    "scroll-behavior", "ScrollBehavior", "scroll-margin", "ScrollMargin",
    "scroll-padding", "ScrollPadding", "scroll-snap-align", "ScrollSnapAlign",
    "scroll-snap-stop", "ScrollSnapStop", "scroll-snap-type", "ScrollSnapType",
    "scrollbar-color", "ScrollbarColor", "scrollbar-gutter", "ScrollbarGutter",
    "scrollbar-width", "ScrollbarWidth", "overscroll-behavior", "OverscrollBehavior",
    "position", "Position", "top", "Top", "right", "Right", "bottom", "Bottom", "left", "Left",
    "inset", "Inset", "inset-block", "InsetBlock", "inset-inline", "InsetInline",
    "inset-block-start", "InsetBlockStart", "inset-block-end", "InsetBlockEnd",
    "inset-inline-start", "InsetInlineStart", "inset-inline-end", "InsetInlineEnd",
    "z-index", "ZIndex", "zIndex",
    "float", "Float", "clear", "Clear",
    "display", "Display", "display-inside", "DisplayInside", "display-outside", "DisplayOutside",
    "display-internal", "DisplayInternal", "display-listitem", "DisplayListItem",
    "display-box", "DisplayBox", "display-caption", "DisplayCaption",
    "visibility", "Visibility", "collapse", "Collapse",
    "vertical-align", "VerticalAlign", "baseline-shift", "BaselineShift",
    "dominant-baseline", "DominantBaseline", "alignment-baseline", "AlignmentBaseline",
    "writing-mode", "WritingMode", "text-orientation", "TextOrientation",
    "direction", "Direction", "unicode-bidi", "UnicodeBidi",
    "all", "All", "none", "None", "revert", "Revert", "revert-layer", "RevertLayer",
    "initial", "Initial", "inherit", "Inherit", "unset", "Unset",
    "var", "Var", "calc", "Calc", "clamp", "Clamp", "min", "Min", "max", "Max",
    "minmax", "Minmax", "minmax", "MinMax",
    "auto", "Auto", "min-content", "MinContent", "max-content", "MaxContent",
    "fit-content", "FitContent", "stretch", "Stretch", "available", "Available",
    "border", "Border", "border-top", "BorderTop", "border-right", "BorderRight",
    "border-bottom", "BorderBottom", "border-left", "BorderLeft",
    "border-block", "BorderBlock", "border-inline", "BorderInline",
    "border-block-start", "BorderBlockStart", "border-block-end", "BorderBlockEnd",
    "border-inline-start", "BorderInlineStart", "border-inline-end", "BorderInlineEnd",
    "border-width", "BorderWidth", "border-top-width", "BorderTopWidth",
    "border-right-width", "BorderRightWidth", "border-bottom-width", "BorderBottomWidth",
    "border-left-width", "BorderLeftWidth",
    "border-style", "BorderStyle", "border-top-style", "BorderTopStyle",
    "border-right-style", "BorderRightStyle", "border-bottom-style", "BorderBottomStyle",
    "border-left-style", "BorderLeftStyle",
    "border-color", "BorderColor", "border-top-color", "BorderTopColor",
    "border-right-color", "BorderRightColor", "border-bottom-color", "BorderBottomColor",
    "border-left-color", "BorderLeftColor",
    "border-radius", "BorderRadius", "border-top-left-radius", "BorderTopLeftRadius",
    "border-top-right-radius", "BorderTopRightRadius",
    "border-bottom-left-radius", "BorderBottomLeftRadius",
    "border-bottom-right-radius", "BorderBottomRightRadius",
    "border-image", "BorderImage", "border-image-source", "BorderImageSource",
    "border-image-slice", "BorderImageSlice", "border-image-width", "BorderImageWidth",
    "border-image-outset", "BorderImageOutset", "border-image-repeat", "BorderImageRepeat",
    "box-shadow", "BoxShadow", "box-decoration-break", "BoxDecorationBreak",
    "box-sizing", "BoxSizing", "width", "Width", "min-width", "MinWidth", "max-width", "MaxWidth",
    "height", "Height", "min-height", "MinHeight", "max-height", "MaxHeight",
    "aspect-ratio", "AspectRatio",
    "padding", "Padding", "padding-top", "PaddingTop", "padding-right", "PaddingRight",
    "padding-bottom", "PaddingBottom", "padding-left", "PaddingLeft",
    "padding-block", "PaddingBlock", "padding-inline", "PaddingInline",
    "padding-block-start", "PaddingBlockStart", "padding-block-end", "PaddingBlockEnd",
    "padding-inline-start", "PaddingInlineStart", "padding-inline-end", "PaddingInlineEnd",
    "margin", "Margin", "margin-top", "MarginTop", "margin-right", "MarginRight",
    "margin-bottom", "MarginBottom", "margin-left", "MarginLeft",
    "margin-block", "MarginBlock", "margin-inline", "MarginInline",
    "margin-block-start", "MarginBlockStart", "margin-block-end", "MarginBlockEnd",
    "margin-inline-start", "MarginInlineStart", "margin-inline-end", "MarginInlineEnd",
    "outline", "Outline", "outline-color", "OutlineColor", "outline-style", "OutlineStyle",
    "outline-width", "OutlineWidth", "outline-offset", "OutlineOffset",
    "box-shadow", "BoxShadow", "text-shadow", "TextShadow",
    "transition", "Transition", "transition-property", "TransitionProperty",
    "transition-duration", "TransitionDuration", "transition-timing-function", "TransitionTimingFunction",
    "transition-delay", "TransitionDelay",
    "animation", "Animation", "animation-name", "AnimationName",
    "animation-duration", "AnimationDuration", "animation-timing-function", "AnimationTimingFunction",
    "animation-delay", "AnimationDelay", "animation-iteration-count", "AnimationIterationCount",
    "animation-direction", "AnimationDirection", "animation-fill-mode", "AnimationFillMode",
    "animation-play-state", "AnimationPlayState",
    "transform", "Transform", "transform-origin", "TransformOrigin",
    "transform-style", "TransformStyle", "perspective", "Perspective",
    "perspective-origin", "PerspectiveOrigin", "backface-visibility", "BackfaceVisibility",
    "cursor", "Cursor", "pointer-events", "PointerEvents", "touch-action", "TouchAction",
    "user-select", "UserSelect", "resize", "Resize", "appearance", "Appearance",
    "accent-color", "AccentColor", "color-scheme", "ColorScheme",
    "print-color-adjust", "PrintColorAdjust", "forced-color-adjust", "ForcedColorAdjust",
    "image-rendering", "ImageRendering", "image-orientation", "ImageOrientation",
    "image-resolution", "ImageResolution", "object-fit", "ObjectFit",
    "object-position", "ObjectPosition",
    "content", "Content", "quotes", "Quotes", "counter-reset", "CounterReset",
    "counter-increment", "CounterIncrement", "counter-set", "CounterSet",
    "list-style", "ListStyle", "list-style-type", "ListStyleType",
    "list-style-position", "ListStylePosition", "list-style-image", "ListStyleImage",
    "table-layout", "TableLayout", "caption-side", "CaptionSide",
    "border-collapse", "BorderCollapse", "border-spacing", "BorderSpacing",
    "empty-cells", "EmptyCells",
    "cursor", "Cursor",
    "content-visibility", "ContentVisibility", "contain", "Contain",
    "contain-intrinsic-size", "ContainIntrinsicSize", "contain-intrinsic-width", "ContainIntrinsicWidth",
    "contain-intrinsic-height", "ContainIntrinsicHeight",
    "will-change", "WillChange",
    "pointer-events", "PointerEvents",
    "*", "html", "body", "head", "title", "meta", "link", "style", "script", "noscript",
    "iframe", "frame", "frameset", "noframes", "embed", "object", "param",
    "video", "audio", "source", "track", "map", "area", "picture",
    "a", "abbr", "address", "area", "article", "aside", "audio", "b", "base", "bdi", "bdo",
    "blockquote", "body", "br", "button", "canvas", "caption", "cite", "code", "col",
    "colgroup", "data", "datalist", "dd", "del", "details", "dfn", "dialog", "dir",
    "div", "dl", "dt", "em", "embed", "fieldset", "figcaption", "figure", "footer",
    "form", "h1", "h2", "h3", "h4", "h5", "h6", "head", "header", "hgroup", "hr",
    "html", "i", "iframe", "img", "input", "ins", "kbd", "keygen", "label", "legend",
    "li", "link", "main", "map", "mark", "marquee", "menu", "menuitem", "meta", "meter",
    "nav", "noscript", "object", "ol", "optgroup", "option", "output", "p", "param",
    "picture", "pre", "progress", "q", "rp", "rt", "ruby", "s", "samp", "script",
    "section", "select", "slot", "small", "source", "span", "strong", "style", "sub",
    "summary", "sup", "table", "tbody", "td", "template", "textarea", "tfoot", "th",
    "thead", "time", "title", "tr", "track", "u", "ul", "var", "video", "wbr",
    "circle", "rect", "ellipse", "line", "polyline", "polygon", "path", "text", "tspan",
    "defs", "g", "svg", "use", "symbol", "marker", "pattern", "mask", "filter",
    "linearGradient", "radialGradient", "stop", "clipPath", "feBlend", "feColorMatrix",
    "feComponentTransfer", "feComposite", "feConvolveMatrix", "feDiffuseLighting",
    "feDisplacementMap", "feDistantLight", "feFlood", "feFuncA", "feFuncB", "feFuncG",
    "feFuncR", "feGaussianBlur", "feImage", "feMerge", "feMergeNode", "feMorphology",
    "feOffset", "fePointLight", "feSpecularLighting", "feSpotLight", "feTile",
    "feTurbulence",
    "AES", "DES", "RSA", "SHA", "MD5", "HMAC", "PBKDF2", "bcrypt", "scrypt", "Argon2",
    "TLS", "SSL", "HTTPS", "HTTP", "TCP", "UDP", "IP", "DNS", "DHCP", "ARP", "ICMP",
    "FTP", "SFTP", "SSH", "Telnet", "SMTP", "POP3", "IMAP", "NNTP", "LDAP", "Kerberos",
    "OAuth", "JWT", "JWS", "JWE", "JWK", "JWA", "OpenID", "SAML", "SSO", "MFA", "2FA",
    "TOTP", "HOTP", "U2F", "WebAuthn", "FIDO", "PKI", "CA", "CSR", "CRL", "OCSP",
    "XSS", "CSRF", "SQL", "NoSQL", "ORM", "ODM", "ACID", "BASE", "CAP", "PACELC",
    "DDL", "DML", "DCL", "TCL", "OLAP", "OLTP", "ETL", "ELT", "BI", "BA", "DA",
    "ML", "DL", "AI", "NLP", "CV", "OCR", "ASR", "TTS", "RL", "GAN", "CNN", "RNN",
    "LSTM", "GRU", "BERT", "GPT", "LLM", "RAG", "LoRA", "RLHF", "DPO", "PPO",
    "SVG", "Canvas", "WebGL", "WebGPU", "WebRTC", "WebSocket", "WebWorker", "ServiceWorker",
    "PWA", "SPA", "MPA", "SSR", "CSR", "SSG", "ISR", "DPR", "CDN", "DNS", "ICP",
    "GDPR", "CCPA", "HIPAA", "PCI-DSS", "SOX", "ISO", "IEC", "IEEE", "ANSI", "W3C",
    "RFC", "BCP", "STD",
    "zh", "en", "ja", "ko", "zh-CN", "zh-TW", "en-US", "en-GB",
    "Mac", "mac", "iOS", "ios", "Android", "android", "Windows", "windows",
    "Linux", "linux", "Unix", "unix", "Ubuntu", "Debian", "CentOS", "RedHat",
    "PostgreSQL", "MySQL", "MongoDB", "Redis", "Memcached", "Elasticsearch", "Kafka",
    "RabbitMQ", "ActiveMQ", "RocketMQ", "Nginx", "Apache", "Tomcat", "Jetty",
    "Spring", "Django", "Flask", "FastAPI", "Express", "Koa", "NestJS", "Laravel",
    "Vue", "React", "Angular", "Svelte", "Solid", "Preact", "Ember", "Backbone",
    "jQuery", "Bootstrap", "Tailwind", "Element", "Ant", "MUI", "Material", "iView",
    "Vite", "Webpack", "Rollup", "Parcel", "esbuild", "SWC", "Babel", "PostCSS",
    "Sass", "Less", "Stylus", "PostCSS", "Stylelint", "ESLint", "Prettier", "Jest",
    "Mocha", "Chai", "Sinon", "Jasmine", "Cypress", "Playwright", "Puppeteer", "Vitest",
    "Pytest", "unittest", "nose", "tox", "coverage", "flake8", "pylint", "mypy", "black",
    "Docker", "Kubernetes", "Helm", "Istio", "Envoy", "Prometheus", "Grafana", "Loki",
    "Tempo", "Jaeger", "Zipkin", "OpenTelemetry", "Fluentd", "Fluent", "Logstash",
    "Kibana", "Splunk", "Datadog", "NewRelic", "Dynatrace", "AppDynamics",
    "AWS", "GCP", "Azure", "Aliyun", "Tencent", "Huawei", "Baidu",
    "Lambda", "S3", "EC2", "ECS", "EKS", "Fargate", "CloudFront", "Route53",
    "RDS", "Aurora", "DynamoDB", "ElastiCache", "SQS", "SNS", "SES", "Step Functions",
    "API", "REST", "GraphQL", "gRPC", "WebSocket", "SOAP", "WSDL", "UDDI", "JSON-RPC",
    "XML-RPC", "CORBA", "RMI", "DCOM", "COM", "ActiveX", "JNI", "JNA", "P/Invoke",
    "SDK", "API", "CLI", "GUI", "TUI", "REPL", "IDE", "VSCode", "IntelliJ", "PyCharm",
    "WebStorm", "Sublime", "Atom", "Vim", "Emacs", "Nano", "Notepad",
    "Git", "SVN", "Mercurial", "CVS", "Perforce", "TFS", "ClearCase", "BitKeeper",
    "GitHub", "GitLab", "Bitbucket", "Gitee", "Coding", "GitBook",
    "Jira", "Confluence", "Trello", "Asana", "Notion", "Slack", "Teams", "Zoom",
    "Meet", "Webex", "Skype", "Discord", "Telegram", "WhatsApp", "Signal", "WeChat",
    "QQ", "DingTalk", "Feishu", "Lark", "Moka", "Worktile", "Tower", "TAPD",
    "LarkSuite", "Lark", "Feishu", "DingTalk", "WeCom", "LarkDoc", "LarkSheet", "LarkBase",
    "LarkSlide", "LarkWiki", "LarkDrive", "LarkTask", "LarkCal", "LarkMail", "LarkVC",
    "LarkOKR", "LarkApproval", "LarkAttendance", "LarkEvent", "LarkWebhook",
}

# 关键: 中英混杂的检测
# 模式 1: 形如 "中文Text" "Text中文" "中文Text中文"
# 模式 2: 形如 "validFile" "fileTooLarge" 这种 "value=key" 但其实是混合词
def is_zh_en_mixed(value: str) -> bool:
    """检测值是否含中英混杂."""
    has_zh = bool(re.search(r"[\u4e00-\u9fa5]", value))
    has_en = bool(re.search(r"[A-Za-z]", value))
    return has_zh and has_en


def is_pure_english_key_like(value: str, key: str) -> bool:
    """检测值是否 = 纯英文 camelCase / PascalCase 形式（疑似 key-as-value）."""
    if not re.match(r"^[A-Za-z][A-Za-z0-9]*$", value):
        return False
    if value in ALLOWED_PURE_ENGLISH:
        return False
    # camelCase 或 PascalCase 且不是允许的术语
    return True


def walk(obj, prefix: str, results: list):
    """递归遍历 JSON, 收集叶子节点."""
    if isinstance(obj, dict):
        for k, v in obj.items():
            new_prefix = f"{prefix}.{k}" if prefix else k
            walk(v, new_prefix, results)
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            new_prefix = f"{prefix}[{i}]"
            walk(v, new_prefix, results)
    else:
        results.append((prefix, obj))


bad_files: list[tuple[Path, list[tuple[str, str, str]]]] = []  # (file, [(full_key, value, reason)])
total_files = 0
for json_path in sorted(ROOT.rglob("*.json")):
    total_files += 1
    try:
        with json_path.open("r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        print(f"[ERROR] 解析失败 {json_path}: {e}")
        continue
    leaves: list[tuple[str, object]] = []
    walk(data, "", leaves)
    bad: list[tuple[str, str, str]] = []
    for full_key, value in leaves:
        if not isinstance(value, str):
            continue
        leaf_key = full_key.split(".")[-1] if "." in full_key else full_key
        # 检查中英混杂
        if is_zh_en_mixed(value):
            bad.append((full_key, value, "zh-en-mixed"))
        # 检查 value=key (camelCase 形式)
        elif is_pure_english_key_like(value, leaf_key):
            bad.append((full_key, value, "value-equals-key"))
    if bad:
        bad_files.append((json_path, bad))

print(f"扫描完成: {total_files} 个 zh-CN 模块")
print(f"发现回归: {len(bad_files)} 个文件")
print("=" * 80)
for fp, bads in bad_files:
    print(f"\n## {fp.relative_to(ROOT.parent.parent.parent)}")
    for full_key, value, reason in bads:
        print(f"  [{reason}] {full_key} = {value!r}")

if bad_files:
    sys.exit(2)
else:
    print("\n[PASS] 无 i18n 回归")
    sys.exit(0)
