// © 2026 IHUI AI (智汇AI) · 版权所有者: 李春川 (Li Chunchuan) · https://aizhs.top
// Provenance-watermarked. 未授权商用可被溯源追责 (Apache-2.0 须保留本声明与 NOTICE)。
// [IHUI-AI-PROVENANCE]:⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠

import type { CompetitorConfig } from './types'

export const domesticAiPlatformsCompetitors: Partial<
  Record<CompetitorConfig['id'], CompetitorConfig>
> = {
  ernie: {
    id: 'ernie',
    name: 'ERNIE Bot / 文心一言',
    tagline: '文心一言是百度 C 端 AI 助手;IHUI AI 是企业级 Agent 操作系统',
    verdict:
      '如果只是个人问答对话,文心一言够用;如果企业需要构建专属 Agent + 私有知识库 + 跨端分发 + 团队协作,IHUI AI 是更系统化的选择。',
    rows: [
      {
        dimension: '定位',
        ihui: '企业级 Agent 操作系统',
        competitor: 'C 端通用 AI 助手',
        ihuiDetail: 'Agent 市场 + 知识库 + 工作流 + 六端分发',
        competitorDetail: '问答对话 + 百度生态集成',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'Web + APP + 小程序',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '百度系 APP 为主',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '闭源',
        ihuiDetail: '完全开源可商用可审计',
        competitorDetail: '闭源 SaaS,无法自托管',
      },
      {
        dimension: '私有化部署',
        ihui: '完整支持',
        competitor: '不支持',
        ihuiDetail: 'Docker Compose + K8s 离线部署',
        competitorDetail: '仅百度云端',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化拖拽 + 200+ 模板',
        competitor: '基础对话 + 插件',
        ihuiDetail: 'Agent 市场 + 一键 fork + 创作者分成',
        competitorDetail: '插件生态,无 Agent 市场',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 向量/BM25/知识图谱',
        competitor: '百度搜索集成',
        ihuiDetail: '企业私有知识库,数据不出域',
        competitorDetail: '依赖百度搜索,无私有知识库',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型中立',
        competitor: '仅 ERNIE 系列',
        ihuiDetail: 'GPT/Claude/Gemini/Qwen/DeepSeek/ERNIE 等',
        competitorDetail: 'ERNIE 4.0 / Speed / Lite',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '个人账号',
        ihuiDetail: '多租户 + 积分共享 + 审计日志',
        competitorDetail: '无企业协作功能',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '免费 + Pro ¥49.9/月',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '按 token 计费,无自托管',
      },
    ],
  },

  'qwen-platform': {
    id: 'qwen-platform',
    name: 'Tongyi Qianwen / 通义千问',
    tagline: '通义千问是阿里大模型平台;IHUI AI 跨 30+ 模型中立 + Agent 市场化',
    verdict:
      '如果只用通义千问模型 API,阿里平台够用;如果需要跨模型调度 + Agent 编排 + 六端分发 + 团队协作,IHUI AI 是更完整方案。',
    rows: [
      {
        dimension: '定位',
        ihui: '全栈 AI 操作系统',
        competitor: '阿里大模型平台',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端',
        competitorDetail: '模型 API + 阿里云集成',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'Web + API',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '需自行开发客户端',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '部分开源(Qwen 模型)',
        ihuiDetail: '平台完全开源',
        competitorDetail: '模型开源,平台闭源',
      },
      {
        dimension: '私有化部署',
        ihui: '完整支持',
        competitor: '受限',
        ihuiDetail: 'Docker Compose + K8s',
        competitorDetail: '需阿里云灵积 API 或自部署 Qwen',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: 'API 调用',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '需自己写编排逻辑',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 多格式',
        competitor: '需自建',
        ihuiDetail: '向量 + BM25 + 知识图谱',
        competitorDetail: '需对接阿里云向量检索',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型中立',
        competitor: '仅通义系列',
        ihuiDetail: '跨厂商 + 自动 fallback',
        competitorDetail: 'Qwen-Max/Plus/Turbo',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '阿里云 RAM',
        ihuiDetail: '多租户工作区',
        competitorDetail: '依赖阿里云权限',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '按 token 计费',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '云版按量,无统一积分',
      },
    ],
  },

  'kimi-platform': {
    id: 'kimi-platform',
    name: 'Kimi / 月之暗面',
    tagline: 'Kimi 在长文本对话方面有特色;IHUI AI 是全栈 Agent 操作系统(含 Kimi 模型)',
    verdict:
      '如果只需要长文本阅读/对话,Kimi 体验较好;如果需要构建 Agent 产品 + 知识库 + 跨端分发 + 团队协作,IHUI AI 是更完整方案(且可接入 Kimi 模型)。',
    rows: [
      {
        dimension: '定位',
        ihui: '全栈 AI 操作系统',
        competitor: '长文本 AI 助手',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端',
        competitorDetail: '200 万字长文本对话',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'Web + APP',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: 'Web + 移动 APP',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '闭源',
        ihuiDetail: '完全开源可商用',
        competitorDetail: '闭源 SaaS',
      },
      {
        dimension: '私有化部署',
        ihui: '完整支持',
        competitor: '不支持',
        ihuiDetail: 'Docker Compose + K8s',
        competitorDetail: '仅 Kimi 云端',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: '基础对话',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '无 Agent 编排',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 多格式',
        competitor: '文件上传对话',
        ihuiDetail: '向量 + BM25 + 知识图谱',
        competitorDetail: '临时文件解析,无持久化知识库',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型(含 Kimi)',
        competitor: '仅 Kimi',
        ihuiDetail: '可接入 Kimi + GPT + Claude 等',
        competitorDetail: '锁定 Moonshot 模型',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '个人账号',
        ihuiDetail: '多租户企业级',
        competitorDetail: '无企业协作',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '免费 + Pro ¥X/月',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '按 token 计费',
      },
    ],
  },

  doubao: {
    id: 'doubao',
    name: 'Doubao / 豆包',
    tagline: '豆包是字节 C 端 AI 助手;IHUI AI 是企业级开源 Agent 平台',
    verdict:
      '如果个人日常问答/创作,豆包免费好用;如果企业需要私有化部署 + 数据主权 + Agent 编排 + 跨端分发,IHUI AI 是更合适的选择。',
    rows: [
      {
        dimension: '定位',
        ihui: '企业级 Agent 操作系统',
        competitor: 'C 端 AI 助手',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端',
        competitorDetail: '日常对话 + 创作 + 抖音生态',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'Web + APP',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '字节系 APP 为主',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '闭源',
        ihuiDetail: '完全开源可商用',
        competitorDetail: '闭源 SaaS',
      },
      {
        dimension: '私有化部署',
        ihui: '完整支持',
        competitor: '不支持',
        ihuiDetail: 'Docker Compose + K8s',
        competitorDetail: '仅字节云',
      },
      {
        dimension: '数据主权',
        ihui: '自托管 100% 数据自有',
        competitor: '字节云托管',
        ihuiDetail: '数据不出域',
        competitorDetail: '数据由字节掌控',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: '基础对话 + 扣子集成',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '需配合扣子平台',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型中立',
        competitor: '仅豆包系列',
        ihuiDetail: '跨厂商 + 自动 fallback',
        competitorDetail: '豆包 Pro/Lite/Function call',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '个人账号',
        ihuiDetail: '多租户企业级',
        competitorDetail: '无企业协作',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '免费',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '免费但有调用上限',
      },
    ],
  },

  'deepseek-platform': {
    id: 'deepseek-platform',
    name: 'DeepSeek Platform',
    tagline: 'DeepSeek 是推理模型 API;IHUI AI 含 DeepSeek + 30+ 模型 + Agent 编排',
    verdict:
      '如果只需调用 DeepSeek API,官方平台较直接;如果需要 Agent 编排 + 知识库 + 工作流 + 六端分发 + 团队协作,IHUI AI 是更完整方案(且原生支持 DeepSeek 模型)。',
    rows: [
      {
        dimension: '定位',
        ihui: '全栈 AI 操作系统',
        competitor: '大模型 API 平台',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端',
        competitorDetail: 'V3/R1/Reasoner API',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'API only',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '需自行开发客户端',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '模型 MIT(平台闭源)',
        ihuiDetail: '平台完全开源',
        competitorDetail: '模型权重开源,平台闭源',
      },
      {
        dimension: '私有化部署',
        ihui: '完整支持',
        competitor: '模型可自部署',
        ihuiDetail: 'Docker Compose + K8s',
        competitorDetail: '需自部署 DeepSeek 模型 + 自建平台',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: 'API 调用',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '需自己写编排',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 多格式',
        competitor: '需自建',
        ihuiDetail: '向量 + BM25 + 知识图谱',
        competitorDetail: '需对接外部向量库',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型(含 DeepSeek)',
        competitor: '仅 DeepSeek',
        ihuiDetail: 'DeepSeek + GPT + Claude + Qwen 等',
        competitorDetail: 'V3 / R1 / Reasoner',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: 'API Key 管理',
        ihuiDetail: '多租户企业级',
        competitorDetail: '基础 Key 管理',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '按 token 计费(极低)',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: 'API 极低价,但需自建平台',
      },
    ],
  },

  zhipu: {
    id: 'zhipu',
    name: 'Zhipu Qingyan / 智谱清言',
    tagline: '智谱清言是 GLM 模型应用;IHUI AI 跨模型 + Agent 市场 + 六端分发',
    verdict:
      '如果只用 GLM 系列模型,智谱清言够用;如果需要跨模型调度 + Agent 编排 + 六端分发 + 团队协作,IHUI AI 是更完整方案(且原生支持 GLM 模型)。',
    rows: [
      {
        dimension: '定位',
        ihui: '全栈 AI 操作系统',
        competitor: 'GLM 模型应用平台',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端',
        competitorDetail: 'GLM-4 + 智能体 + 阿里云集成',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'Web + APP',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: 'Web + 移动 APP',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '部分开源(GLM 模型)',
        ihuiDetail: '平台完全开源',
        competitorDetail: 'GLM 模型部分开源,平台闭源',
      },
      {
        dimension: '私有化部署',
        ihui: '完整支持',
        competitor: '受限',
        ihuiDetail: 'Docker Compose + K8s',
        competitorDetail: '需自部署 GLM 模型 + 自建平台',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: '智谱智能体',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '智谱智能体平台',
      },
      {
        dimension: '知识库 RAG',
        ihui: '内置 + 多格式',
        competitor: '需自建',
        ihuiDetail: '向量 + BM25 + 知识图谱',
        competitorDetail: '需对接外部向量库',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型(含 GLM)',
        competitor: '仅 GLM 系列',
        ihuiDetail: 'GLM + GPT + Claude + Qwen 等',
        competitorDetail: 'GLM-4 / GLM-4-Plus / GLM-4V',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '个人 + 团队空间',
        ihuiDetail: '多租户企业级',
        competitorDetail: '基础团队功能',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '免费 + 按量',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: 'GLM-4 按量计费',
      },
    ],
  },

  spark: {
    id: 'spark',
    name: 'iFlytek Spark / 讯飞星火',
    tagline: '星火偏教育/语音 AI;IHUI AI 是全栈 Agent 操作系统跨行业',
    verdict:
      '如果业务聚焦教育/语音交互,讯飞星火生态成熟;如果需要跨行业 Agent 编排 + 六端分发 + 私有化 + 团队协作,IHUI AI 是更通用方案。',
    rows: [
      {
        dimension: '定位',
        ihui: '全栈 AI 操作系统',
        competitor: '教育/语音 AI 平台',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端',
        competitorDetail: '星火大模型 + 讯飞语音 + 教育',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'Web + APP + 硬件',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: '讯飞硬件 + APP',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '闭源',
        ihuiDetail: '完全开源可商用',
        competitorDetail: '闭源 SaaS',
      },
      {
        dimension: '私有化部署',
        ihui: '完整支持',
        competitor: '企业版支持',
        ihuiDetail: 'Docker Compose + K8s',
        competitorDetail: '讯飞企业版(付费)',
      },
      {
        dimension: '语音能力',
        ihui: '可对接讯飞/百度/Whisper',
        competitor: '原生支持(TTS/ASR) 较完善',
        ihuiDetail: '灵活对接多家语音',
        competitorDetail: '讯飞语音原生集成',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: '基础智能体',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '讯飞 AIUI 平台',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型中立',
        competitor: '仅星火系列',
        ihuiDetail: '星火 + GPT + Claude + Qwen 等',
        competitorDetail: 'Spark Max/Pro/Mini',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: '企业版',
        ihuiDetail: '多租户企业级',
        competitorDetail: '讯飞企业版协作',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '免费 + 企业版',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '企业版按席位',
      },
    ],
  },

  minimax: {
    id: 'minimax',
    name: 'MiniMax',
    tagline: 'MiniMax 是多模态大模型 API;IHUI AI 含 MiniMax + Agent 编排 + 六端',
    verdict:
      '如果只需多模态模型 API(文本/语音/视频),MiniMax 直接够用;如果需要 Agent 编排 + 知识库 + 工作流 + 六端分发 + 团队协作,IHUI AI 是更完整方案。',
    rows: [
      {
        dimension: '定位',
        ihui: '全栈 AI 操作系统',
        competitor: '多模态大模型 API',
        ihuiDetail: 'Agent + 知识库 + 工作流 + 六端',
        competitorDetail: 'abab 系列 + 语音/视频',
      },
      {
        dimension: '客户端覆盖',
        ihui: '6 端同源',
        competitor: 'API + 海螺 AI',
        ihuiDetail: 'Web/桌面/小程序/扩展/移动/CLI',
        competitorDetail: 'API + 海螺 APP',
      },
      {
        dimension: '开源协议',
        ihui: 'Apache 2.0',
        competitor: '闭源',
        ihuiDetail: '完全开源可商用',
        competitorDetail: '闭源 API',
      },
      {
        dimension: '私有化部署',
        ihui: '完整支持',
        competitor: '不支持',
        ihuiDetail: 'Docker Compose + K8s',
        competitorDetail: '仅 MiniMax 云端',
      },
      {
        dimension: '多模态',
        ihui: '可对接 MiniMax/百度/字节',
        competitor: '原生支持',
        ihuiDetail: '灵活对接多家',
        competitorDetail: '文本/语音/视频原生',
      },
      {
        dimension: 'Agent 编排',
        ihui: '可视化 + 200+ 模板',
        competitor: 'API 调用',
        ihuiDetail: 'Agent 市场 + 一键 fork',
        competitorDetail: '需自己写编排',
      },
      {
        dimension: '多模型',
        ihui: '30+ 模型(含 MiniMax)',
        competitor: '仅 MiniMax',
        ihuiDetail: 'MiniMax + GPT + Claude + Qwen',
        competitorDetail: 'abab6 / abab5.5 / 语音',
      },
      {
        dimension: '团队协作',
        ihui: '完整 RBAC + 审计 + SSO',
        competitor: 'API Key',
        ihuiDetail: '多租户企业级',
        competitorDetail: '基础 Key 管理',
      },
      {
        dimension: '定价',
        ihui: '个人免费 + Pro ¥49/月',
        competitor: '按 token 计费',
        ihuiDetail: '开源自托管零费用',
        competitorDetail: '按量计费',
      },
    ],
  },
}
// ⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠
