export { fetchApi, setTokenProvider, setBaseUrl, streamChat } from './client.js'
export type { TokenProvider, StreamChatOptions } from './client.js'
export { ApiError, isNotFound, isErrorCode } from './api-error.js'
export { eduApi, buildQs } from './utils.js'
export type { PageData, PageQuery } from './utils.js'

export * from './endpoints/admin.js'
export * from './endpoints/admin-auth.js'
export * from './endpoints/admin-member.js'
export * from './endpoints/admin-monitor.js'
export * from './endpoints/admin-system.js'
export * from './endpoints/agent.js'
export * from './endpoints/ai.js'
export * from './endpoints/ai-media.js'
export * from './endpoints/auth.js'
export * from './endpoints/business.js'
export * from './endpoints/category.js'
export * from './endpoints/chat.js'
export * from './endpoints/community.js'
export * from './endpoints/course.js'
export * from './endpoints/developer.js'
export * from './endpoints/distribution.js'
export * from './endpoints/exam.js'
export * from './endpoints/learn.js'
export * from './endpoints/live.js'
export * from './endpoints/misc.js'
export * from './endpoints/notification.js'
export * from './endpoints/order.js'
export * from './endpoints/payment.js'
export * from './endpoints/resource.js'
export * from './endpoints/share.js'
export * from './endpoints/system.js'
export * from './endpoints/token.js'
export * from './endpoints/user.js'
export * from './endpoints/vip.js'
export * from './endpoints/wallet.js'
export * from './endpoints/workspace.js'

// Explicit re-exports to resolve naming conflicts between modules.
// These同名函数签名/用途不�?显式指定主来源以消除 export * 歧义(TS2308)�?// 仍可通过子路�?@ihui/api-client/endpoints/<name> 访问任一模块的同名导出�?export { getRanking } from './endpoints/business.js'
export { getMessages, sendMessage } from './endpoints/chat.js'
export { getCategories } from './endpoints/system.js'
export { getUserStatistics } from './endpoints/user.js'
export { getAuthRole, updateAuthRole } from './endpoints/admin-system.js'
