export { fetchApi, setTokenProvider, setBaseUrl } from './client'
export type { TokenProvider } from './client'
export { ApiError, isNotFound, isErrorCode } from './api-error'
export { eduApi, buildQs } from './utils'
export type { PageData, PageQuery } from './utils'

export * from './endpoints/admin'
export * from './endpoints/agent'
export * from './endpoints/ai'
export * from './endpoints/ai-media'
export * from './endpoints/auth'
export * from './endpoints/business'
export * from './endpoints/category'
export * from './endpoints/chat'
export * from './endpoints/community'
export * from './endpoints/course'
export * from './endpoints/developer'
export * from './endpoints/distribution'
export * from './endpoints/exam'
export * from './endpoints/learn'
export * from './endpoints/live'
export * from './endpoints/misc'
export * from './endpoints/notification'
export * from './endpoints/order'
export * from './endpoints/payment'
export * from './endpoints/resource'
export * from './endpoints/share'
export * from './endpoints/system'
export * from './endpoints/token'
export * from './endpoints/user'
export * from './endpoints/vip'
export * from './endpoints/wallet'
export * from './endpoints/workspace'

// Explicit re-exports to resolve naming conflicts between modules.
// These同名函数签名/用途不同,显式指定主来源以消除 export * 歧义(TS2308)。
// 仍可通过子路径 @ihui/api-client/endpoints/<name> 访问任一模块的同名导出。
export { getRanking } from './endpoints/business'
export { getMessages, sendMessage } from './endpoints/chat'
export { getCategories } from './endpoints/system'
export { getUserStatistics } from './endpoints/user'
