import type { Model } from '../../types'

export const FALLBACK_MODELS_PART_4: Model[] = [
  {
    id: 'vertex/gemini-1.5-pro',
    name: 'Vertex Gemini 1.5 Pro',
    provider: 'vertexai',
    description: 'model.gemini-2-flash.description',
    contextLength: 2000000,
    inputPrice: 1.25,
    features: ['Enterprise', 'Long Context'],
  },
  // === Microsoft Copilot / Bing Chat(2 个) ===
  {
    id: 'microsoft-copilot',
    name: 'Microsoft Copilot',
    provider: 'copilot',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Search', 'Assistant', 'Free'],
  },
  {
    id: 'bing-chat-creative',
    name: 'Bing Chat Creative',
    provider: 'bing',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Search', 'Creative'],
  },
  // === Qwen 通义千问(4 个) ===
  {
    id: 'qwen-plus',
    name: 'Qwen Plus',
    provider: 'qwen',
    description: 'model.gpt-4o.description',
    contextLength: 131072,
    inputPrice: 0.4,
    features: ['Chinese-Optimized', 'Reasoning'],
  },
  {
    id: 'qwen-max',
    name: 'Qwen Max',
    provider: 'qwen',
    description: 'model.gpt-4o.description',
    contextLength: 32768,
    inputPrice: 1.6,
    features: ['Chinese-Optimized', 'Frontier'],
  },
  {
    id: 'qwen-turbo',
    name: 'Qwen Turbo',
    provider: 'qwen',
    description: 'model.gpt-4o.description',
    contextLength: 1000000,
    inputPrice: 0.05,
    features: ['Fast', 'Affordable'],
  },
  {
    id: 'qwen2.5-72b-instruct',
    name: 'Qwen2.5 72B Instruct',
    provider: 'qwen',
    description: 'model.gpt-4o.description',
    contextLength: 32768,
    inputPrice: 0.4,
    features: ['Open Source', 'Bilingual'],
  },
  // === Zhipu 智谱(3 个) ===
  {
    id: 'glm-4-plus',
    name: 'GLM-4 Plus',
    provider: 'zhipu',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0.7,
    features: ['Chinese-Optimized', 'Reasoning'],
  },
  {
    id: 'glm-4.5',
    name: 'GLM-4.5',
    provider: 'zhipu',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0.6,
    features: ['Chinese-Optimized', 'Frontier'],
  },
  {
    id: 'glm-4-air',
    name: 'GLM-4 Air',
    provider: 'zhipu',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0.1,
    features: ['Fast', 'Affordable'],
  },
  // === Moonshot 月之暗面(3 个) ===
  {
    id: 'moonshot-v1-8k',
    name: 'Moonshot v1 8K',
    provider: 'moonshot',
    description: 'model.gpt-4o.description',
    contextLength: 8192,
    inputPrice: 1.2,
    features: ['Long Context', 'Chinese-Optimized'],
  },
  {
    id: 'moonshot-v1-32k',
    name: 'Moonshot v1 32K',
    provider: 'moonshot',
    description: 'model.gpt-4o.description',
    contextLength: 32768,
    inputPrice: 2.4,
    features: ['Long Context', 'Chinese-Optimized'],
  },
  {
    id: 'kimi-k2',
    name: 'Kimi K2',
    provider: 'moonshot',
    description: 'model.gpt-4o.description',
    contextLength: 131072,
    inputPrice: 0.55,
    features: ['Long Context', 'Reasoning'],
  },
  // === Doubao 豆包(2 个) ===
  {
    id: 'doubao-1-6-pro',
    name: 'Doubao 1.6 Pro',
    provider: 'doubao',
    description: 'model.gpt-4o.description',
    contextLength: 32768,
    inputPrice: 0.11,
    features: ['Chinese-Optimized', 'Multimodal'],
  },
  {
    id: 'doubao-pro-32k',
    name: 'Doubao Pro 32K',
    provider: 'doubao',
    description: 'model.gpt-4o.description',
    contextLength: 32768,
    inputPrice: 0.05,
    features: ['Chinese-Optimized', 'Fast'],
  },
  // === StepFun 阶跃星辰(2 个) ===
  {
    id: 'stepfun/step-3.7-flash',
    name: 'Step 3.7 Flash',
    provider: 'stepfun',
    description: 'model.stepfun-3-7-flash.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Plan', 'Fast', 'Chinese-Optimized'],
  },
  {
    id: 'stepfun/step-3.5-flash',
    name: 'Step 3.5 Flash',
    provider: 'stepfun',
    description: 'model.stepfun-3-5-flash.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Plan', 'Fast'],
  },
  // === Tencent Hunyuan 腾讯混元(2 个) ===
  {
    id: 'hunyuan-pro',
    name: 'Hunyuan Pro',
    provider: 'hunyuan',
    description: 'model.gpt-4o.description',
    contextLength: 32768,
    inputPrice: 0.45,
    features: ['Chinese-Optimized', 'Reasoning'],
  },
  {
    id: 'hunyuan-turbo',
    name: 'Hunyuan Turbo',
    provider: 'hunyuan',
    description: 'model.gpt-4o.description',
    contextLength: 32768,
    inputPrice: 0.1,
    features: ['Fast', 'Affordable'],
  },
  // === Baidu Wenxin 百度文心一言(2 个) ===
  {
    id: 'ernie-4.0-turbo-8k',
    name: 'ERNIE 4.0 Turbo',
    provider: 'wenxin',
    description: 'model.gpt-4o.description',
    contextLength: 8192,
    inputPrice: 0.5,
    features: ['Chinese-Optimized', 'Multimodal'],
  },
  {
    id: 'ernie-speed-128k',
    name: 'ERNIE Speed 128K',
    provider: 'wenxin',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0.05,
    features: ['Long Context', 'Fast'],
  },
  // === MiniMax(2 个) ===
  {
    id: 'abab6.5s-chat',
    name: 'ABAB 6.5s Chat',
    provider: 'minimax',
    description: 'model.gpt-4o.description',
    contextLength: 245760,
    inputPrice: 0.1,
    features: ['Long Context', 'Chinese-Optimized'],
  },
]
