import type { Model } from '../../types'

export const FALLBACK_MODELS_PART_8: Model[] = [
  {
    id: 'nvidia/mistral-nemo-minitron-8b-base',
    name: 'Mistral Nemo Minitron 8B (NVIDIA NIM 免费)',
    provider: 'nvidia_nim',
    description: 'model.gpt-4o.description',
    contextLength: 8192,
    inputPrice: 0,
    features: ['Free', 'Open Source'],
  },
  {
    id: 'nvidia/llama-3.3-nemotron-super-49b-v1',
    name: 'Llama 3.3 Nemotron Super 49B (NVIDIA NIM 免费)',
    provider: 'nvidia_nim',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Free', 'Reasoning', 'Open Source'],
  },
  // GitHub Models(Copilot Free tier)
  {
    id: 'github/Phi-4',
    name: 'Phi 4 (GitHub Models 免费)',
    provider: 'github_models',
    description: 'model.gpt-4o.description',
    contextLength: 16384,
    inputPrice: 0,
    features: ['Free', 'Small', 'Reasoning'],
  },
  {
    id: 'github/Mistral-Small-3.1',
    name: 'Mistral Small 3.1 (GitHub Models 免费)',
    provider: 'github_models',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Free', 'Long Context'],
  },
  {
    id: 'github/gpt-4o',
    name: 'GPT-4o (GitHub Models 免费)',
    provider: 'github_models',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Free', 'Multimodal', 'Vision'],
  },
  {
    id: 'github/Meta-Llama-3.1-405B-Instruct',
    name: 'Llama 3.1 405B (GitHub Models 免费)',
    provider: 'github_models',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Free', 'Open Source', 'Frontier'],
  },
  // Vercel AI Gateway($5/月免费额度)
  {
    id: 'vercel/auto',
    name: 'Vercel AI Gateway Auto (聚合路由)',
    provider: 'vercel_ai_gateway',
    description: 'model.openrouter-auto.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Free', 'Auto-Route', 'Multi-Provider'],
  },
  // OpenCode Zen(完全免费)
  {
    id: 'opencode/big-pickle-stealth',
    name: 'Big Pickle Stealth (OpenCode Zen 免费)',
    provider: 'opencode_zen',
    description: 'model.gpt-4o.description',
    contextLength: 256000,
    inputPrice: 0,
    features: ['Free', 'Long Context'],
  },
  {
    id: 'opencode/deepseek-v4-flash-free',
    name: 'DeepSeek V4 Flash Free (OpenCode Zen 免费)',
    provider: 'opencode_zen',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Free', 'Fast'],
  },
  // Modal($5 注册赠送)
  {
    id: 'modal/labcompute/qwen2.5-72b',
    name: 'Qwen2.5 72B (Modal 试用 credits)',
    provider: 'modal',
    description: 'model.gpt-4o.description',
    contextLength: 32768,
    inputPrice: 0,
    features: ['Trial Credits', 'Open Source'],
  },
  // Inference.net($1 注册送)
  {
    id: 'inferencenet/meta-llama/Llama-3.3-70B-Instruct',
    name: 'Llama 3.3 70B (Inference.net 试用 credits)',
    provider: 'inferencenet',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Trial Credits', 'Open Source'],
  },
  // NLP Cloud($15 注册送)
  {
    id: 'nlpcloud/finetuned-llama-3-70b',
    name: 'Finetuned Llama 3 70B (NLP Cloud 试用 credits)',
    provider: 'nlpcloud',
    description: 'model.gpt-4o.description',
    contextLength: 32768,
    inputPrice: 0,
    features: ['Trial Credits', 'Fine-Tuned'],
  },
  {
    id: 'nlpcloud/dolphin',
    name: 'Dolphin (NLP Cloud 试用 credits)',
    provider: 'nlpcloud',
    description: 'model.gpt-4o.description',
    contextLength: 32768,
    inputPrice: 0,
    features: ['Trial Credits', 'Open Source'],
  },
  {
    id: 'nlpcloud/chatdolphin',
    name: 'ChatDolphin (NLP Cloud 试用 credits)',
    provider: 'nlpcloud',
    description: 'model.gpt-4o.description',
    contextLength: 32768,
    inputPrice: 0,
    features: ['Trial Credits', 'Conversational'],
  },
  // Scaleway(1M tokens 免费)
  {
    id: 'scaleway/mistral-small-3.2-24b-instruct-2506',
    name: 'Mistral Small 3.2 24B (Scaleway 1M tokens 免费)',
    provider: 'scaleway',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Free', 'Long Context'],
  },
  {
    id: 'scaleway/qwen3-coder-30b-a3b-instruct',
    name: 'Qwen3 Coder 30B (Scaleway 1M tokens 免费)',
    provider: 'scaleway',
    description: 'model.gpt-4o.description',
    contextLength: 131072,
    inputPrice: 0,
    features: ['Free', 'Coding', 'Long Context'],
  },
  {
    id: 'scaleway/llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B (Scaleway 1M tokens 免费)',
    provider: 'scaleway',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Free', 'Open Source'],
  },
  // Alibaba Cloud International Model Studio(1M tokens/模型 免费)
  {
    id: 'alibaba-intl/qwen-max',
    name: 'Qwen Max (Alibaba Intl 1M tokens/模型 免费)',
    provider: 'alibaba_intl',
    description: 'model.gpt-4o.description',
    contextLength: 131072,
    inputPrice: 0,
    features: ['Free', 'Chinese-Optimized', 'Frontier'],
  },
  {
    id: 'alibaba-intl/qwen-plus',
    name: 'Qwen Plus (Alibaba Intl 1M tokens/模型 免费)',
    provider: 'alibaba_intl',
    description: 'model.gpt-4o.description',
    contextLength: 131072,
    inputPrice: 0,
    features: ['Free', 'Chinese-Optimized'],
  },
  {
    id: 'alibaba-intl/qwen-turbo',
    name: 'Qwen Turbo (Alibaba Intl 1M tokens/模型 免费)',
    provider: 'alibaba_intl',
    description: 'model.gpt-4o.description',
    contextLength: 131072,
    inputPrice: 0,
    features: ['Free', 'Fast', 'Chinese-Optimized'],
  },
  {
    id: 'alibaba-intl/qwen3-coder-plus',
    name: 'Qwen3 Coder Plus (Alibaba Intl 1M tokens/模型 免费)',
    provider: 'alibaba_intl',
    description: 'model.gpt-4o.description',
    contextLength: 131072,
    inputPrice: 0,
    features: ['Free', 'Coding', 'Chinese-Optimized'],
  },
  {
    id: 'alibaba-intl/qwen3-235b-a22b',
    name: 'Qwen3 235B A22B (Alibaba Intl 1M tokens/模型 免费)',
    provider: 'alibaba_intl',
    description: 'model.gpt-4o.description',
    contextLength: 131072,
    inputPrice: 0,
    features: ['Free', 'Frontier', 'Chinese-Optimized'],
  },
]
