import type { Model } from '../../types'

export const FALLBACK_MODELS_PART_1: Model[] = [
  // === 默认主力(与 ai-service default_models.json 第 1 位对齐)===
  {
    id: 'stepfun/step-router-v1',
    name: 'Step Router v1',
    provider: 'stepfun',
    description: 'model.stepfun-router-v1.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Plan', 'Auto-Route'],
  },
  // === OpenAI(7 个) ===
  {
    id: 'openrouter/auto',
    name: 'model.openrouter-auto.name',
    provider: 'meta',
    description: 'model.openrouter-auto.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Free', 'Auto-Route', 'Multi-Provider'],
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 2.5,
    features: ['Vision', 'Function Calling', 'Multimodal'],
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o mini',
    provider: 'openai',
    description: 'model.gpt-4o-mini.description',
    contextLength: 128000,
    inputPrice: 0.15,
    features: ['Fast', 'Affordable'],
  },
  {
    id: 'gpt-4.1',
    name: 'GPT-4.1',
    provider: 'openai',
    description: 'model.gpt-4o.description',
    contextLength: 1047576,
    inputPrice: 2.0,
    features: ['Long Context', 'Coding'],
  },
  {
    id: 'gpt-4.1-mini',
    name: 'GPT-4.1 mini',
    provider: 'openai',
    description: 'model.gpt-4o-mini.description',
    contextLength: 1047576,
    inputPrice: 0.4,
    features: ['Fast', 'Coding'],
  },
  {
    id: 'o3',
    name: 'o3',
    provider: 'openai',
    description: 'model.gpt-4o.description',
    contextLength: 200000,
    inputPrice: 60.0,
    features: ['Reasoning', 'PhD-Level'],
  },
  {
    id: 'o3-mini',
    name: 'o3 mini',
    provider: 'openai',
    description: 'model.gpt-4o-mini.description',
    contextLength: 200000,
    inputPrice: 1.1,
    features: ['Reasoning', 'Fast'],
  },
  {
    id: 'o4-mini',
    name: 'o4 mini',
    provider: 'openai',
    description: 'model.gpt-4o-mini.description',
    contextLength: 200000,
    inputPrice: 1.1,
    features: ['Reasoning', 'Multimodal'],
  },
  // === Anthropic(5 个) ===
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'anthropic',
    description: 'model.claude-3-5-sonnet.description',
    contextLength: 200000,
    inputPrice: 3.0,
    features: ['Reasoning', 'Writing', 'Vision'],
  },
  {
    id: 'claude-3-5-haiku',
    name: 'Claude 3.5 Haiku',
    provider: 'anthropic',
    description: 'model.claude-3-5-sonnet.description',
    contextLength: 200000,
    inputPrice: 0.8,
    features: ['Fast', 'Affordable'],
  },
  {
    id: 'claude-3-7-sonnet',
    name: 'Claude 3.7 Sonnet',
    provider: 'anthropic',
    description: 'model.claude-3-5-sonnet.description',
    contextLength: 200000,
    inputPrice: 3.0,
    features: ['Reasoning', 'Coding', 'Vision'],
  },
  {
    id: 'claude-opus-4',
    name: 'Claude Opus 4',
    provider: 'anthropic',
    description: 'model.claude-3-5-sonnet.description',
    contextLength: 200000,
    inputPrice: 15.0,
    features: ['Reasoning', 'Frontier'],
  },
  {
    id: 'claude-sonnet-4',
    name: 'Claude Sonnet 4',
    provider: 'anthropic',
    description: 'model.claude-3-5-sonnet.description',
    contextLength: 200000,
    inputPrice: 3.0,
    features: ['Reasoning', 'Coding'],
  },
  // === Google Gemini(3 个) ===
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'google',
    description: 'model.gemini-2-flash.description',
    contextLength: 1048576,
    inputPrice: 0.1,
    features: ['Long Context', 'Multimodal', 'Fast'],
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'google',
    description: 'model.gemini-2-flash.description',
    contextLength: 1048576,
    inputPrice: 1.25,
    features: ['Long Context', 'Reasoning'],
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'google',
    description: 'model.gemini-2-flash.description',
    contextLength: 1048576,
    inputPrice: 0.075,
    features: ['Long Context', 'Fast'],
  },
  // === Google Gemma 开源(2 个) ===
  {
    id: 'gemma-2-27b-it',
    name: 'Gemma 2 27B',
    provider: 'gemma',
    description: 'model.gemini-2-flash.description',
    contextLength: 8192,
    inputPrice: 0.1,
    features: ['Open Source', 'Lightweight'],
  },
  {
    id: 'gemma-2-9b-it',
    name: 'Gemma 2 9B',
    provider: 'gemma',
    description: 'model.gemini-2-flash.description',
    contextLength: 8192,
    inputPrice: 0.03,
    features: ['Open Source', 'Small'],
  },
  // === DeepSeek(3 个) ===
  {
    id: 'deepseek-chat',
    name: 'DeepSeek Chat',
    provider: 'deepseek',
    description: 'model.gpt-4o.description',
    contextLength: 64000,
    inputPrice: 0.27,
    features: ['Affordable', 'Chinese-Optimized'],
  },
  {
    id: 'deepseek-reasoner',
    name: 'DeepSeek Reasoner (R1)',
    provider: 'deepseek',
    description: 'model.gpt-4o.description',
    contextLength: 64000,
    inputPrice: 0.55,
    features: ['Reasoning', 'Open Source'],
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    provider: 'deepseek',
    description: 'model.gpt-4o.description',
    contextLength: 64000,
    inputPrice: 0.27,
    features: ['Affordable', 'Frontier'],
  },
]
