import type { Model } from '../../types'

export const FALLBACK_MODELS_PART_2: Model[] = [
  // === Meta Llama(2 个) ===
  {
    id: 'llama-3.3-70b-versatile',
    name: 'Llama 3.3 70B',
    provider: 'meta',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0.59,
    features: ['Open Source', 'Reasoning'],
  },
  {
    id: 'llama-3.1-405b-instruct',
    name: 'Llama 3.1 405B',
    provider: 'meta',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 3.0,
    features: ['Open Source', 'Frontier'],
  },
  // === Mistral AI 法国(3 个) ===
  {
    id: 'mistral-large-latest',
    name: 'Mistral Large',
    provider: 'mistral',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 2.0,
    features: ['Reasoning', 'Multilingual'],
  },
  {
    id: 'codestral-latest',
    name: 'Codestral',
    provider: 'mistral',
    description: 'model.gpt-4o.description',
    contextLength: 256000,
    inputPrice: 0.3,
    features: ['Coding', 'Fast'],
  },
  {
    id: 'pixtral-large-latest',
    name: 'Pixtral Large',
    provider: 'mistral',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 2.0,
    features: ['Multimodal', 'Vision'],
  },
  // === xAI Grok(2 个) ===
  {
    id: 'grok-2',
    name: 'Grok 2',
    provider: 'xai',
    description: 'model.gpt-4o.description',
    contextLength: 131072,
    inputPrice: 2.0,
    features: ['Realtime', 'Humor'],
  },
  {
    id: 'grok-3',
    name: 'Grok 3',
    provider: 'xai',
    description: 'model.gpt-4o.description',
    contextLength: 131072,
    inputPrice: 3.0,
    features: ['Reasoning', 'Realtime'],
  },
  // === Cohere 加拿大(2 个) ===
  {
    id: 'command-r-plus',
    name: 'Command R+',
    provider: 'cohere',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 2.5,
    features: ['RAG', 'Tool Use'],
  },
  {
    id: 'command-a',
    name: 'Command A',
    provider: 'cohere',
    description: 'model.gpt-4o.description',
    contextLength: 256000,
    inputPrice: 2.5,
    features: ['RAG', 'Long Context'],
  },
  // === Nvidia 英伟达(2 个) ===
  {
    id: 'nemotron-4-340b-instruct',
    name: 'Nemotron 4 340B',
    provider: 'nvidia',
    description: 'model.gpt-4o.description',
    contextLength: 4096,
    inputPrice: 0,
    features: ['Synthetic Data', 'Open Source'],
  },
  {
    id: 'llama-3.1-nemotron-70b-instruct',
    name: 'Llama 3.1 Nemotron 70B',
    provider: 'nvidia',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0.12,
    features: ['Aligned', 'Open Source'],
  },
  // === AI21 Labs 以色列(1 个) ===
  {
    id: 'jamba-1-5-large',
    name: 'Jamba 1.5 Large',
    provider: 'ai21',
    description: 'model.gpt-4o.description',
    contextLength: 256000,
    inputPrice: 2.0,
    features: ['SSM-Transformer', 'Long Context'],
  },
  // === Microsoft 微软 Phi 系列(2 个) ===
  {
    id: 'phi-4',
    name: 'Phi 4',
    provider: 'microsoft',
    description: 'model.gpt-4o.description',
    contextLength: 16384,
    inputPrice: 0.07,
    features: ['Small', 'Reasoning'],
  },
  {
    id: 'phi-3.5-mini-instruct',
    name: 'Phi 3.5 Mini',
    provider: 'microsoft',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0.075,
    features: ['Small', 'Fast'],
  },
  // === Perplexity 美国搜索引擎(2 个) ===
  {
    id: 'sonar-large',
    name: 'Sonar Large',
    provider: 'perplexity',
    description: 'model.gpt-4o.description',
    contextLength: 127072,
    inputPrice: 2.0,
    features: ['Search', 'Realtime'],
  },
  {
    id: 'sonar-small',
    name: 'Sonar Small',
    provider: 'perplexity',
    description: 'model.gpt-4o.description',
    contextLength: 127072,
    inputPrice: 0.2,
    features: ['Search', 'Fast'],
  },
  // === AWS Amazon Nova(2 个) ===
  {
    id: 'amazon-nova-pro',
    name: 'Amazon Nova Pro',
    provider: 'aws',
    description: 'model.gpt-4o.description',
    contextLength: 300000,
    inputPrice: 0.8,
    features: ['Multimodal', 'Long Context'],
  },
  {
    id: 'amazon-nova-lite',
    name: 'Amazon Nova Lite',
    provider: 'aws',
    description: 'model.gpt-4o.description',
    contextLength: 300000,
    inputPrice: 0.06,
    features: ['Fast', 'Affordable'],
  },
  // === AWS Bedrock 聚合(2 个) ===
  {
    id: 'bedrock/anthropic.claude-3-5-sonnet-20241022-v2',
    name: 'Bedrock Claude 3.5 Sonnet v2',
    provider: 'bedrock',
    description: 'model.claude-3-5-sonnet.description',
    contextLength: 200000,
    inputPrice: 3.0,
    features: ['Reasoning', 'Multimodal'],
  },
  {
    id: 'bedrock/meta.llama3-1-405b-instruct-v1',
    name: 'Bedrock Llama 3.1 405B',
    provider: 'bedrock',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 3.0,
    features: ['Open Source', 'Reasoning'],
  },
  // === Microsoft Azure OpenAI(2 个) ===
  {
    id: 'azure/gpt-4o',
    name: 'Azure GPT-4o',
    provider: 'azure',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 2.5,
    features: ['Vision', 'Multimodal'],
  },
]
