import type { Model } from '../../types'

export const FALLBACK_MODELS_PART_7: Model[] = [
  {
    id: 'claude-opus-4.8',
    name: 'Claude Opus 4.8 (Anthropic 深度推理)',
    provider: 'anthropic',
    description: 'model.claude-3-5-sonnet.description',
    contextLength: 524288,
    inputPrice: 20.0,
    features: ['Reasoning', 'PhD-Level', 'Long Context'],
  },
  // Google Gemini 3.5
  {
    id: 'gemini-3.5-pro',
    name: 'Gemini 3.5 Pro (Google 多模态旗舰)',
    provider: 'google',
    description: 'model.gemini-2-flash.description',
    contextLength: 2097152,
    inputPrice: 2.0,
    features: ['Multimodal', 'Long Context', 'Frontier'],
  },
  // xAI Grok 4.5
  {
    id: 'grok-4.5',
    name: 'Grok 4.5 (xAI 实时增强)',
    provider: 'xai',
    description: 'model.gpt-4o.description',
    contextLength: 262144,
    inputPrice: 4.0,
    features: ['Real-Time', 'Reasoning', 'Long Context'],
  },
  // DeepSeek V4 系列
  {
    id: 'deepseek-v4-pro',
    name: 'DeepSeek V4 Pro (国产开源旗舰)',
    provider: 'deepseek',
    description: 'model.gpt-4o.description',
    contextLength: 131072,
    inputPrice: 0.6,
    features: ['Open Source', 'Reasoning', 'Frontier'],
  },
  {
    id: 'deepseek-v4-flash',
    name: 'DeepSeek V4 Flash (国产开源快版)',
    provider: 'deepseek',
    description: 'model.gpt-4o.description',
    contextLength: 131072,
    inputPrice: 0.15,
    features: ['Open Source', 'Fast', 'Affordable'],
  },
  // 智谱 GLM-5.2
  {
    id: 'glm-5.2',
    name: 'GLM-5.2 (智谱清言新一代)',
    provider: 'zhipu',
    description: 'model.gpt-4o.description',
    contextLength: 262144,
    inputPrice: 1.0,
    features: ['Chinese-Optimized', 'Frontier', 'Long Context'],
  },
  // Qwen3.7 Max
  {
    id: 'qwen3.7-max',
    name: 'Qwen3.7 Max (阿里通义千问旗舰)',
    provider: 'qwen',
    description: 'model.gpt-4o.description',
    contextLength: 262144,
    inputPrice: 2.0,
    features: ['Chinese-Optimized', 'Frontier', 'Long Context'],
  },
  // 腾讯混元 3 代
  {
    id: 'hunyuan-hy3',
    name: 'Hunyuan Hy3 (腾讯混元 3 代)',
    provider: 'hunyuan',
    description: 'model.gpt-4o.description',
    contextLength: 262144,
    inputPrice: 1.5,
    features: ['Chinese-Optimized', 'Multimodal', 'Long Context'],
  },
  // Moonshot Kimi K3 长上下文旗舰
  {
    id: 'kimi-k3',
    name: 'Kimi K3 (Moonshot 长上下文旗舰)',
    provider: 'moonshot',
    description: 'model.gpt-4o.description',
    contextLength: 2097152,
    inputPrice: 0.8,
    features: ['Long Context', 'Chinese-Optimized', 'Frontier'],
  },
  // 国内新增 3 家新势力
  {
    id: 'ornith-1.0',
    name: 'Ornith 1.0 (国产新势力)',
    provider: 'ornith',
    description: 'model.gpt-4o.description',
    contextLength: 131072,
    inputPrice: 0.8,
    features: ['Chinese-Optimized', 'Frontier', 'Fast'],
  },
  {
    id: 'codebrain-1',
    name: 'CodeBrain-1 (代码专精模型)',
    provider: 'codebrain',
    description: 'model.gpt-4o.description',
    contextLength: 65536,
    inputPrice: 0.3,
    features: ['Coding', 'Affordable', 'Fast'],
  },
  {
    id: 'mai-thinking-1',
    name: 'MAI-Thinking-1 (深度推理模型)',
    provider: 'mai',
    description: 'model.gpt-4o.description',
    contextLength: 131072,
    inputPrice: 1.2,
    features: ['Reasoning', 'PhD-Level', 'Deep-Thinking'],
  },

  // === 2026-07-22 新增免费 / 试用 credits provider(参考 cheahjs/free-llm-api-resources) ===
  // Cloudflare Workers AI(10,000 neurons/day 免费)
  {
    id: '@cf/meta/llama-3.3-70b-instruct-fp8-fast',
    name: 'Llama 3.3 70B Fast (Cloudflare 免费)',
    provider: 'cloudflare_workers_ai',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Free', 'Open Source', 'Fast'],
  },
  {
    id: '@cf/qwen/qwen2.5-coder-32b-instruct',
    name: 'Qwen2.5 Coder 32B (Cloudflare 免费)',
    provider: 'cloudflare_workers_ai',
    description: 'model.gpt-4o.description',
    contextLength: 32768,
    inputPrice: 0,
    features: ['Free', 'Coding', 'Open Source'],
  },
  {
    id: '@cf/google/gemma-3-12b-it',
    name: 'Gemma 3 12B (Cloudflare 免费)',
    provider: 'cloudflare_workers_ai',
    description: 'model.gpt-4o.description',
    contextLength: 8192,
    inputPrice: 0,
    features: ['Free', 'Open Source'],
  },
  {
    id: '@cf/meta/llama-3.2-3b-instruct',
    name: 'Llama 3.2 3B (Cloudflare 免费)',
    provider: 'cloudflare_workers_ai',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Free', 'Small', 'Open Source'],
  },
  {
    id: '@cf/mistral/mistral-7b-instruct',
    name: 'Mistral 7B (Cloudflare 免费)',
    provider: 'cloudflare_workers_ai',
    description: 'model.gpt-4o.description',
    contextLength: 32768,
    inputPrice: 0,
    features: ['Free', 'Open Source'],
  },
  {
    id: '@cf/deepseek-ai/deepseek-r1-distill-qwen-32b',
    name: 'DeepSeek R1 Distill Qwen 32B (Cloudflare 免费)',
    provider: 'cloudflare_workers_ai',
    description: 'model.gpt-4o.description',
    contextLength: 8192,
    inputPrice: 0,
    features: ['Free', 'Reasoning', 'Open Source'],
  },
  {
    id: '@cf/meta/llama-4-scout-17b-16e-instruct',
    name: 'Llama 4 Scout 17B (Cloudflare 免费)',
    provider: 'cloudflare_workers_ai',
    description: 'model.gpt-4o.description',
    contextLength: 131072,
    inputPrice: 0,
    features: ['Free', 'Long Context', 'Open Source'],
  },
  // NVIDIA NIM(40 req/min 免费)
  {
    id: 'nvidia/llama-3.1-nemotron-70b-instruct',
    name: 'Llama 3.1 Nemotron 70B (NVIDIA NIM 免费)',
    provider: 'nvidia_nim',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Free', 'Reasoning', 'Open Source'],
  },
  {
    id: 'nvidia/llama-3.1-nemotron-nano-8b-v1',
    name: 'Llama 3.1 Nemotron Nano 8B (NVIDIA NIM 免费)',
    provider: 'nvidia_nim',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0,
    features: ['Free', 'Small', 'Open Source'],
  },
]
