import type { Model } from '../../types'

export const FALLBACK_MODELS_PART_3: Model[] = [
  {
    id: 'azure/gpt-4o-mini',
    name: 'Azure GPT-4o mini',
    provider: 'azure',
    description: 'model.gpt-4o-mini.description',
    contextLength: 128000,
    inputPrice: 0.15,
    features: ['Fast', 'Affordable'],
  },
  // === OpenRouter 聚合平台(2 个) ===
  {
    id: 'openrouter/auto',
    name: 'OpenRouter Auto',
    provider: 'openrouter',
    description: 'model.openrouter-auto.description',
    contextLength: 200000,
    inputPrice: 0,
    features: ['Auto-Route', 'Multi-Provider'],
  },
  {
    id: 'openrouter/anthropic/claude-3.5-sonnet',
    name: 'OR Claude 3.5 Sonnet',
    provider: 'openrouter',
    description: 'model.claude-3-5-sonnet.description',
    contextLength: 200000,
    inputPrice: 3.0,
    features: ['Reasoning', 'Vision'],
  },
  // === HuggingFace 推理(1 个) ===
  {
    id: 'huggingface/meta-llama/Llama-3.3-70B-Instruct',
    name: 'HF Llama 3.3 70B',
    provider: 'huggingface',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0.59,
    features: ['Open Source', 'Inference API'],
  },
  // === Replicate 推理(1 个) ===
  {
    id: 'replicate/meta/llama-3-70b-instruct',
    name: 'Replicate Llama 3 70B',
    provider: 'replicate',
    description: 'model.gpt-4o.description',
    contextLength: 8192,
    inputPrice: 0.6,
    features: ['Open Source', 'Inference API'],
  },
  // === Stability AI 美国(1 个) ===
  {
    id: 'stablelm-2-12b-chat',
    name: 'StableLM 2 12B',
    provider: 'stability',
    description: 'model.gpt-4o.description',
    contextLength: 16384,
    inputPrice: 0,
    features: ['Open Source', 'Multilingual'],
  },
  // === Inflection AI 美国 Pi 助手(2 个) ===
  {
    id: 'inflection-3-pi',
    name: 'Inflection 3 Pi',
    provider: 'inflection',
    description: 'model.gpt-4o.description',
    contextLength: 8000,
    inputPrice: 1.0,
    features: ['Conversational', 'Empathetic'],
  },
  {
    id: 'inflection-3-productivity',
    name: 'Inflection 3 Productivity',
    provider: 'inflection',
    description: 'model.gpt-4o.description',
    contextLength: 8000,
    inputPrice: 1.0,
    features: ['Productivity', 'Writing'],
  },
  // === IBM watsonx Granite(2 个) ===
  {
    id: 'watsonx/granite-3-8b-instruct',
    name: 'Granite 3 8B',
    provider: 'ibm',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0.2,
    features: ['Open Source', 'Enterprise'],
  },
  {
    id: 'watsonx/granite-3-2b-instruct',
    name: 'Granite 3 2B',
    provider: 'ibm',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0.05,
    features: ['Small', 'Enterprise'],
  },
  // === Cerebras 美国 推理加速(2 个) ===
  {
    id: 'cerebras/llama3.1-8b',
    name: 'Cerebras Llama 3.1 8B',
    provider: 'cerebras',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0.1,
    features: ['Ultra Fast', 'Open Source'],
  },
  {
    id: 'cerebras/llama3.1-70b',
    name: 'Cerebras Llama 3.1 70B',
    provider: 'cerebras',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0.7,
    features: ['Ultra Fast', 'Open Source'],
  },
  // === SambaNova 美国 推理加速(2 个) ===
  {
    id: 'sambanova/llama-3.1-70b-instruct',
    name: 'SambaNova Llama 3.1 70B',
    provider: 'sambanova',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0.7,
    features: ['Fast', 'Open Source'],
  },
  {
    id: 'sambanova/llama-3.1-405b-instruct',
    name: 'SambaNova Llama 3.1 405B',
    provider: 'sambanova',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 3.0,
    features: ['Fast', 'Reasoning'],
  },
  // === Snowflake Arctic(1 个) ===
  {
    id: 'snowflake-arctic',
    name: 'Snowflake Arctic',
    provider: 'snowflake',
    description: 'model.gpt-4o.description',
    contextLength: 4096,
    inputPrice: 0,
    features: ['Open Source', 'Enterprise'],
  },
  // === DeepInfra 美国 推理(1 个) ===
  {
    id: 'deepinfra/meta-llama/Llama-3.3-70B-Instruct',
    name: 'DeepInfra Llama 3.3 70B',
    provider: 'deepinfra',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 0.27,
    features: ['Open Source', 'Affordable'],
  },
  // === Aleph Alpha 德国(2 个) ===
  {
    id: 'luminous-base',
    name: 'Luminous Base',
    provider: 'alephalpha',
    description: 'model.gpt-4o.description',
    contextLength: 2048,
    inputPrice: 0,
    features: ['Multilingual', 'European'],
  },
  {
    id: 'luminous-supreme',
    name: 'Luminous Supreme',
    provider: 'alephalpha',
    description: 'model.gpt-4o.description',
    contextLength: 2048,
    inputPrice: 0,
    features: ['Multilingual', 'European', 'Multimodal'],
  },
  // === NousResearch 美国 Hermes 系列(2 个) ===
  {
    id: 'nous-hermes-2-mixtral-8x7b-dpo',
    name: 'Nous Hermes 2 Mixtral 8x7B',
    provider: 'nous',
    description: 'model.gpt-4o.description',
    contextLength: 32768,
    inputPrice: 0.27,
    features: ['Open Source', 'Fine-Tuned'],
  },
  {
    id: 'nous-hermes-3-llama-3.1-405b',
    name: 'Nous Hermes 3 Llama 3.1 405B',
    provider: 'nous',
    description: 'model.gpt-4o.description',
    contextLength: 128000,
    inputPrice: 3.0,
    features: ['Open Source', 'Fine-Tuned', 'Reasoning'],
  },
  // === Google Vertex AI(2 个) ===
  {
    id: 'vertex/claude-3-5-sonnet',
    name: 'Vertex Claude 3.5 Sonnet',
    provider: 'vertexai',
    description: 'model.claude-3-5-sonnet.description',
    contextLength: 200000,
    inputPrice: 3.0,
    features: ['Enterprise', 'Reasoning'],
  },
]
