CREATE TABLE zhs_agent_buy (
  id varchar(36) NOT NULL DEFAULT (uuid()) COMMENT 'id',
  agent_id varchar(64) DEFAULT NULL COMMENT '智能体id,对应botId',
  agent_name varchar(128) DEFAULT NULL COMMENT '智能体名称',
  agent_order_uuid varchar(36) DEFAULT NULL COMMENT '智能体开发者uuId',
  bug_uuid varchar(36) DEFAULT NULL COMMENT '购买人uuid',
  bug_name varchar(138) DEFAULT NULL COMMENT '购买人名称',
  bug_time datetime DEFAULT NULL COMMENT '购买时间',
  category_id varchar(36) DEFAULT NULL COMMENT '对应配置表ID',
  discount int(4) DEFAULT NULL COMMENT '折扣，按照100写 8折 写80',
  real_price int(10) DEFAULT NULL COMMENT '实际标价，折扣后的实际支付金额 单位：分',
  price int(10) DEFAULT NULL COMMENT '标价配置表中的account',
  count int(4) DEFAULT NULL COMMENT '购买数量-单位:月',
  expiration_date datetime DEFAULT NULL COMMENT '过期时间，计算后的续费过期时间',
  order_no varchar(36) DEFAULT NUll COMMENT '订单编号',
  status varchar(2) DEFAULT NULL COMMENT '状态 0生效 1过期',
  settlement varchar(2) DEFAULT NULL COMMENT '是否结算 0未结算 1已结算',
  prologue text DEFAULT NULL COMMENT '智能体开场白',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户支付购买智能体记录表';