/*
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * BodyImageToImageApiV1TongyiImage2imageImageToImagePost
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-18T02:17:25.485400500+08:00[Asia/Shanghai]", comments = "Generator version: 7.23.0")
public class BodyImageToImageApiV1TongyiImage2imageImageToImagePost {
  public static final String SERIALIZED_NAME_MODEL = "model";
  @SerializedName(SERIALIZED_NAME_MODEL)
  @javax.annotation.Nullable
  private String model = "wanx2.1-imageedit";

  public static final String SERIALIZED_NAME_IMAGE_URL = "image_url";
  @SerializedName(SERIALIZED_NAME_IMAGE_URL)
  @javax.annotation.Nonnull
  private String imageUrl;

  public static final String SERIALIZED_NAME_PROMPT = "prompt";
  @SerializedName(SERIALIZED_NAME_PROMPT)
  @javax.annotation.Nonnull
  private String prompt;

  public static final String SERIALIZED_NAME_STRENGTH = "strength";
  @SerializedName(SERIALIZED_NAME_STRENGTH)
  @javax.annotation.Nullable
  private BigDecimal strength = new BigDecimal("0.8");

  public static final String SERIALIZED_NAME_STYLE = "style";
  @SerializedName(SERIALIZED_NAME_STYLE)
  @javax.annotation.Nullable
  private String style;

  public BodyImageToImageApiV1TongyiImage2imageImageToImagePost() {
  }

  public BodyImageToImageApiV1TongyiImage2imageImageToImagePost model(@javax.annotation.Nullable String model) {
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @javax.annotation.Nullable
  public String getModel() {
    return model;
  }

  public void setModel(@javax.annotation.Nullable String model) {
    this.model = model;
  }


  public BodyImageToImageApiV1TongyiImage2imageImageToImagePost imageUrl(@javax.annotation.Nonnull String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

  /**
   * Get imageUrl
   * @return imageUrl
   */
  @javax.annotation.Nonnull
  public String getImageUrl() {
    return imageUrl;
  }

  public void setImageUrl(@javax.annotation.Nonnull String imageUrl) {
    this.imageUrl = imageUrl;
  }


  public BodyImageToImageApiV1TongyiImage2imageImageToImagePost prompt(@javax.annotation.Nonnull String prompt) {
    this.prompt = prompt;
    return this;
  }

  /**
   * Get prompt
   * @return prompt
   */
  @javax.annotation.Nonnull
  public String getPrompt() {
    return prompt;
  }

  public void setPrompt(@javax.annotation.Nonnull String prompt) {
    this.prompt = prompt;
  }


  public BodyImageToImageApiV1TongyiImage2imageImageToImagePost strength(@javax.annotation.Nullable BigDecimal strength) {
    this.strength = strength;
    return this;
  }

  /**
   * Get strength
   * @return strength
   */
  @javax.annotation.Nullable
  public BigDecimal getStrength() {
    return strength;
  }

  public void setStrength(@javax.annotation.Nullable BigDecimal strength) {
    this.strength = strength;
  }


  public BodyImageToImageApiV1TongyiImage2imageImageToImagePost style(@javax.annotation.Nullable String style) {
    this.style = style;
    return this;
  }

  /**
   * Get style
   * @return style
   */
  @javax.annotation.Nullable
  public String getStyle() {
    return style;
  }

  public void setStyle(@javax.annotation.Nullable String style) {
    this.style = style;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BodyImageToImageApiV1TongyiImage2imageImageToImagePost bodyImageToImageApiV1TongyiImage2imageImageToImagePost = (BodyImageToImageApiV1TongyiImage2imageImageToImagePost) o;
    return Objects.equals(this.model, bodyImageToImageApiV1TongyiImage2imageImageToImagePost.model) &&
        Objects.equals(this.imageUrl, bodyImageToImageApiV1TongyiImage2imageImageToImagePost.imageUrl) &&
        Objects.equals(this.prompt, bodyImageToImageApiV1TongyiImage2imageImageToImagePost.prompt) &&
        Objects.equals(this.strength, bodyImageToImageApiV1TongyiImage2imageImageToImagePost.strength) &&
        Objects.equals(this.style, bodyImageToImageApiV1TongyiImage2imageImageToImagePost.style);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(model, imageUrl, prompt, strength, style);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BodyImageToImageApiV1TongyiImage2imageImageToImagePost {\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("    prompt: ").append(toIndentedString(prompt)).append("\n");
    sb.append("    strength: ").append(toIndentedString(strength)).append("\n");
    sb.append("    style: ").append(toIndentedString(style)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("model", "image_url", "prompt", "strength", "style"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("image_url", "prompt"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BodyImageToImageApiV1TongyiImage2imageImageToImagePost
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BodyImageToImageApiV1TongyiImage2imageImageToImagePost.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BodyImageToImageApiV1TongyiImage2imageImageToImagePost is not found in the empty JSON string", BodyImageToImageApiV1TongyiImage2imageImageToImagePost.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BodyImageToImageApiV1TongyiImage2imageImageToImagePost.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BodyImageToImageApiV1TongyiImage2imageImageToImagePost` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BodyImageToImageApiV1TongyiImage2imageImageToImagePost.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("model") != null && !jsonObj.get("model").isJsonNull()) && !jsonObj.get("model").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `model` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model").toString()));
      }
      if (!jsonObj.get("image_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `image_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("image_url").toString()));
      }
      if (!jsonObj.get("prompt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `prompt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("prompt").toString()));
      }
      if ((jsonObj.get("style") != null && !jsonObj.get("style").isJsonNull()) && !jsonObj.get("style").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `style` to be a primitive type in the JSON string but got `%s`", jsonObj.get("style").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BodyImageToImageApiV1TongyiImage2imageImageToImagePost.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BodyImageToImageApiV1TongyiImage2imageImageToImagePost' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BodyImageToImageApiV1TongyiImage2imageImageToImagePost> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BodyImageToImageApiV1TongyiImage2imageImageToImagePost.class));

       return (TypeAdapter<T>) new TypeAdapter<BodyImageToImageApiV1TongyiImage2imageImageToImagePost>() {
           @Override
           public void write(JsonWriter out, BodyImageToImageApiV1TongyiImage2imageImageToImagePost value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BodyImageToImageApiV1TongyiImage2imageImageToImagePost read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BodyImageToImageApiV1TongyiImage2imageImageToImagePost given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BodyImageToImageApiV1TongyiImage2imageImageToImagePost
   * @throws IOException if the JSON string is invalid with respect to BodyImageToImageApiV1TongyiImage2imageImageToImagePost
   */
  public static BodyImageToImageApiV1TongyiImage2imageImageToImagePost fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BodyImageToImageApiV1TongyiImage2imageImageToImagePost.class);
  }

  /**
   * Convert an instance of BodyImageToImageApiV1TongyiImage2imageImageToImagePost to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

