/*
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * BodyLuyalaEmbeddings
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-18T02:17:25.485400500+08:00[Asia/Shanghai]", comments = "Generator version: 7.23.0")
public class BodyLuyalaEmbeddings {
  public static final String SERIALIZED_NAME_INPUT_TEXT = "input_text";
  @SerializedName(SERIALIZED_NAME_INPUT_TEXT)
  @javax.annotation.Nonnull
  private String inputText;

  public static final String SERIALIZED_NAME_MODEL = "model";
  @SerializedName(SERIALIZED_NAME_MODEL)
  @javax.annotation.Nullable
  private String model = "luyala-embed";

  public BodyLuyalaEmbeddings() {
  }

  public BodyLuyalaEmbeddings inputText(@javax.annotation.Nonnull String inputText) {
    this.inputText = inputText;
    return this;
  }

  /**
   * Get inputText
   * @return inputText
   */
  @javax.annotation.Nonnull
  public String getInputText() {
    return inputText;
  }

  public void setInputText(@javax.annotation.Nonnull String inputText) {
    this.inputText = inputText;
  }


  public BodyLuyalaEmbeddings model(@javax.annotation.Nullable String model) {
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @javax.annotation.Nullable
  public String getModel() {
    return model;
  }

  public void setModel(@javax.annotation.Nullable String model) {
    this.model = model;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BodyLuyalaEmbeddings bodyLuyalaEmbeddings = (BodyLuyalaEmbeddings) o;
    return Objects.equals(this.inputText, bodyLuyalaEmbeddings.inputText) &&
        Objects.equals(this.model, bodyLuyalaEmbeddings.model);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inputText, model);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BodyLuyalaEmbeddings {\n");
    sb.append("    inputText: ").append(toIndentedString(inputText)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("input_text", "model"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("input_text"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BodyLuyalaEmbeddings
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BodyLuyalaEmbeddings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BodyLuyalaEmbeddings is not found in the empty JSON string", BodyLuyalaEmbeddings.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BodyLuyalaEmbeddings.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BodyLuyalaEmbeddings` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BodyLuyalaEmbeddings.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("input_text").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `input_text` to be a primitive type in the JSON string but got `%s`", jsonObj.get("input_text").toString()));
      }
      if ((jsonObj.get("model") != null && !jsonObj.get("model").isJsonNull()) && !jsonObj.get("model").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `model` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BodyLuyalaEmbeddings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BodyLuyalaEmbeddings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BodyLuyalaEmbeddings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BodyLuyalaEmbeddings.class));

       return (TypeAdapter<T>) new TypeAdapter<BodyLuyalaEmbeddings>() {
           @Override
           public void write(JsonWriter out, BodyLuyalaEmbeddings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BodyLuyalaEmbeddings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BodyLuyalaEmbeddings given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BodyLuyalaEmbeddings
   * @throws IOException if the JSON string is invalid with respect to BodyLuyalaEmbeddings
   */
  public static BodyLuyalaEmbeddings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BodyLuyalaEmbeddings.class);
  }

  /**
   * Convert an instance of BodyLuyalaEmbeddings to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

