/*
 * ZHS Platform
 * ZHS Platform API - AI Agent Marketplace & Educational Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CategoryCreateBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-18T02:17:25.485400500+08:00[Asia/Shanghai]", comments = "Generator version: 7.23.0")
public class CategoryCreateBody {
  public static final String SERIALIZED_NAME_AGENT_ID = "agent_id";
  @SerializedName(SERIALIZED_NAME_AGENT_ID)
  @javax.annotation.Nonnull
  private String agentId;

  public static final String SERIALIZED_NAME_GROUP = "group";
  @SerializedName(SERIALIZED_NAME_GROUP)
  @javax.annotation.Nullable
  private Integer group = 2;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private String type = "1";

  public static final String SERIALIZED_NAME_TYPE_CHILD = "type_child";
  @SerializedName(SERIALIZED_NAME_TYPE_CHILD)
  @javax.annotation.Nullable
  private String typeChild = "1";

  public static final String SERIALIZED_NAME_LIMIT_FREE = "limit_free";
  @SerializedName(SERIALIZED_NAME_LIMIT_FREE)
  @javax.annotation.Nullable
  private String limitFree;

  public static final String SERIALIZED_NAME_ACCOUNT = "account";
  @SerializedName(SERIALIZED_NAME_ACCOUNT)
  @javax.annotation.Nullable
  private Integer account = 0;

  public CategoryCreateBody() {
  }

  public CategoryCreateBody agentId(@javax.annotation.Nonnull String agentId) {
    this.agentId = agentId;
    return this;
  }

  /**
   * Get agentId
   * @return agentId
   */
  @javax.annotation.Nonnull
  public String getAgentId() {
    return agentId;
  }

  public void setAgentId(@javax.annotation.Nonnull String agentId) {
    this.agentId = agentId;
  }


  public CategoryCreateBody group(@javax.annotation.Nullable Integer group) {
    this.group = group;
    return this;
  }

  /**
   * Get group
   * @return group
   */
  @javax.annotation.Nullable
  public Integer getGroup() {
    return group;
  }

  public void setGroup(@javax.annotation.Nullable Integer group) {
    this.group = group;
  }


  public CategoryCreateBody type(@javax.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
  }


  public CategoryCreateBody typeChild(@javax.annotation.Nullable String typeChild) {
    this.typeChild = typeChild;
    return this;
  }

  /**
   * Get typeChild
   * @return typeChild
   */
  @javax.annotation.Nullable
  public String getTypeChild() {
    return typeChild;
  }

  public void setTypeChild(@javax.annotation.Nullable String typeChild) {
    this.typeChild = typeChild;
  }


  public CategoryCreateBody limitFree(@javax.annotation.Nullable String limitFree) {
    this.limitFree = limitFree;
    return this;
  }

  /**
   * Get limitFree
   * @return limitFree
   */
  @javax.annotation.Nullable
  public String getLimitFree() {
    return limitFree;
  }

  public void setLimitFree(@javax.annotation.Nullable String limitFree) {
    this.limitFree = limitFree;
  }


  public CategoryCreateBody account(@javax.annotation.Nullable Integer account) {
    this.account = account;
    return this;
  }

  /**
   * Get account
   * @return account
   */
  @javax.annotation.Nullable
  public Integer getAccount() {
    return account;
  }

  public void setAccount(@javax.annotation.Nullable Integer account) {
    this.account = account;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoryCreateBody categoryCreateBody = (CategoryCreateBody) o;
    return Objects.equals(this.agentId, categoryCreateBody.agentId) &&
        Objects.equals(this.group, categoryCreateBody.group) &&
        Objects.equals(this.type, categoryCreateBody.type) &&
        Objects.equals(this.typeChild, categoryCreateBody.typeChild) &&
        Objects.equals(this.limitFree, categoryCreateBody.limitFree) &&
        Objects.equals(this.account, categoryCreateBody.account);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(agentId, group, type, typeChild, limitFree, account);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoryCreateBody {\n");
    sb.append("    agentId: ").append(toIndentedString(agentId)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    typeChild: ").append(toIndentedString(typeChild)).append("\n");
    sb.append("    limitFree: ").append(toIndentedString(limitFree)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("agent_id", "group", "type", "type_child", "limit_free", "account"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("agent_id"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CategoryCreateBody
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CategoryCreateBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CategoryCreateBody is not found in the empty JSON string", CategoryCreateBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CategoryCreateBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CategoryCreateBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CategoryCreateBody.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("agent_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `agent_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("agent_id").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("type_child") != null && !jsonObj.get("type_child").isJsonNull()) && !jsonObj.get("type_child").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type_child` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type_child").toString()));
      }
      if ((jsonObj.get("limit_free") != null && !jsonObj.get("limit_free").isJsonNull()) && !jsonObj.get("limit_free").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `limit_free` to be a primitive type in the JSON string but got `%s`", jsonObj.get("limit_free").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CategoryCreateBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CategoryCreateBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CategoryCreateBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CategoryCreateBody.class));

       return (TypeAdapter<T>) new TypeAdapter<CategoryCreateBody>() {
           @Override
           public void write(JsonWriter out, CategoryCreateBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CategoryCreateBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CategoryCreateBody given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CategoryCreateBody
   * @throws IOException if the JSON string is invalid with respect to CategoryCreateBody
   */
  public static CategoryCreateBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CategoryCreateBody.class);
  }

  /**
   * Convert an instance of CategoryCreateBody to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

