/*
ZHS Platform

ZHS Platform API - AI Agent Marketplace & Educational Platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zhs_api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// DeepSeekChatAPIService DeepSeekChatAPI service
type DeepSeekChatAPIService service

type ApiDeepseekChatApiV1ChatChatPostRequest struct {
	ctx context.Context
	ApiService *DeepSeekChatAPIService
	message *string
	model *string
}

func (r ApiDeepseekChatApiV1ChatChatPostRequest) Message(message string) ApiDeepseekChatApiV1ChatChatPostRequest {
	r.message = &message
	return r
}

func (r ApiDeepseekChatApiV1ChatChatPostRequest) Model(model string) ApiDeepseekChatApiV1ChatChatPostRequest {
	r.model = &model
	return r
}

func (r ApiDeepseekChatApiV1ChatChatPostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.DeepseekChatApiV1ChatChatPostExecute(r)
}

/*
DeepseekChatApiV1ChatChatPost DeepSeek 同步聊天

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiDeepseekChatApiV1ChatChatPostRequest
*/
func (a *DeepSeekChatAPIService) DeepseekChatApiV1ChatChatPost(ctx context.Context) ApiDeepseekChatApiV1ChatChatPostRequest {
	return ApiDeepseekChatApiV1ChatChatPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *DeepSeekChatAPIService) DeepseekChatApiV1ChatChatPostExecute(r ApiDeepseekChatApiV1ChatChatPostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DeepSeekChatAPIService.DeepseekChatApiV1ChatChatPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/chat/chat"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.message == nil {
		return localVarReturnValue, nil, reportError("message is required and must be specified")
	}

	if r.model != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "model", r.model, "form", "")
	} else {
		var defaultValue string = "deepseek-chat"
		parameterAddToHeaderOrQuery(localVarQueryParams, "model", defaultValue, "form", "")
		r.model = &defaultValue
	}
	parameterAddToHeaderOrQuery(localVarQueryParams, "message", r.message, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeepseekChatStreamApiV1ChatChatStreamPostRequest struct {
	ctx context.Context
	ApiService *DeepSeekChatAPIService
	message *string
	model *string
}

func (r ApiDeepseekChatStreamApiV1ChatChatStreamPostRequest) Message(message string) ApiDeepseekChatStreamApiV1ChatChatStreamPostRequest {
	r.message = &message
	return r
}

func (r ApiDeepseekChatStreamApiV1ChatChatStreamPostRequest) Model(model string) ApiDeepseekChatStreamApiV1ChatChatStreamPostRequest {
	r.model = &model
	return r
}

func (r ApiDeepseekChatStreamApiV1ChatChatStreamPostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.DeepseekChatStreamApiV1ChatChatStreamPostExecute(r)
}

/*
DeepseekChatStreamApiV1ChatChatStreamPost DeepSeek 流式聊天（SSE）

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiDeepseekChatStreamApiV1ChatChatStreamPostRequest
*/
func (a *DeepSeekChatAPIService) DeepseekChatStreamApiV1ChatChatStreamPost(ctx context.Context) ApiDeepseekChatStreamApiV1ChatChatStreamPostRequest {
	return ApiDeepseekChatStreamApiV1ChatChatStreamPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *DeepSeekChatAPIService) DeepseekChatStreamApiV1ChatChatStreamPostExecute(r ApiDeepseekChatStreamApiV1ChatChatStreamPostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DeepSeekChatAPIService.DeepseekChatStreamApiV1ChatChatStreamPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/chat/chat/stream"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.message == nil {
		return localVarReturnValue, nil, reportError("message is required and must be specified")
	}

	if r.model != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "model", r.model, "form", "")
	} else {
		var defaultValue string = "deepseek-chat"
		parameterAddToHeaderOrQuery(localVarQueryParams, "model", defaultValue, "form", "")
		r.model = &defaultValue
	}
	parameterAddToHeaderOrQuery(localVarQueryParams, "message", r.message, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
