/*
ZHS Platform

ZHS Platform API - AI Agent Marketplace & Educational Platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package zhs_api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"os"
)


// AIVoiceprintAPIService AIVoiceprintAPI service
type AIVoiceprintAPIService service

type ApiAddVoiceprintApiV1AiAudioGroupsGroupIdUsersPostRequest struct {
	ctx context.Context
	ApiService *AIVoiceprintAPIService
	groupId string
	voiceprintFeatureCreate *VoiceprintFeatureCreate
}

func (r ApiAddVoiceprintApiV1AiAudioGroupsGroupIdUsersPostRequest) VoiceprintFeatureCreate(voiceprintFeatureCreate VoiceprintFeatureCreate) ApiAddVoiceprintApiV1AiAudioGroupsGroupIdUsersPostRequest {
	r.voiceprintFeatureCreate = &voiceprintFeatureCreate
	return r
}

func (r ApiAddVoiceprintApiV1AiAudioGroupsGroupIdUsersPostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.AddVoiceprintApiV1AiAudioGroupsGroupIdUsersPostExecute(r)
}

/*
AddVoiceprintApiV1AiAudioGroupsGroupIdUsersPost Add voiceprint to group

Add a voiceprint feature (speaker profile) to a group.

Provide either audio_url or audio_base64 containing the speaker's voice sample.
The audio will be processed by DashScope to extract voice characteristics.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param groupId
 @return ApiAddVoiceprintApiV1AiAudioGroupsGroupIdUsersPostRequest
*/
func (a *AIVoiceprintAPIService) AddVoiceprintApiV1AiAudioGroupsGroupIdUsersPost(ctx context.Context, groupId string) ApiAddVoiceprintApiV1AiAudioGroupsGroupIdUsersPostRequest {
	return ApiAddVoiceprintApiV1AiAudioGroupsGroupIdUsersPostRequest{
		ApiService: a,
		ctx: ctx,
		groupId: groupId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *AIVoiceprintAPIService) AddVoiceprintApiV1AiAudioGroupsGroupIdUsersPostExecute(r ApiAddVoiceprintApiV1AiAudioGroupsGroupIdUsersPostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AIVoiceprintAPIService.AddVoiceprintApiV1AiAudioGroupsGroupIdUsersPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/ai/audio/groups/{group_id}/users"
	localVarPath = strings.Replace(localVarPath, "{"+"group_id"+"}", url.PathEscape(parameterValueToString(r.groupId, "groupId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.voiceprintFeatureCreate == nil {
		return localVarReturnValue, nil, reportError("voiceprintFeatureCreate is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.voiceprintFeatureCreate
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPostRequest struct {
	ctx context.Context
	ApiService *AIVoiceprintAPIService
	groupId string
	file *os.File
	name *string
	desc *string
}

func (r ApiAddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPostRequest) File(file *os.File) ApiAddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPostRequest {
	r.file = file
	return r
}

func (r ApiAddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPostRequest) Name(name string) ApiAddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPostRequest {
	r.name = &name
	return r
}

func (r ApiAddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPostRequest) Desc(desc string) ApiAddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPostRequest {
	r.desc = &desc
	return r
}

func (r ApiAddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.AddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPostExecute(r)
}

/*
AddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPost Add voiceprint via file upload

Add a voiceprint feature by uploading an audio file.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param groupId
 @return ApiAddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPostRequest
*/
func (a *AIVoiceprintAPIService) AddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPost(ctx context.Context, groupId string) ApiAddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPostRequest {
	return ApiAddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPostRequest{
		ApiService: a,
		ctx: ctx,
		groupId: groupId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *AIVoiceprintAPIService) AddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPostExecute(r ApiAddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AIVoiceprintAPIService.AddVoiceprintUploadApiV1AiAudioGroupsGroupIdUsersUploadPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/ai/audio/groups/{group_id}/users/upload"
	localVarPath = strings.Replace(localVarPath, "{"+"group_id"+"}", url.PathEscape(parameterValueToString(r.groupId, "groupId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.file == nil {
		return localVarReturnValue, nil, reportError("file is required and must be specified")
	}
	if r.name == nil {
		return localVarReturnValue, nil, reportError("name is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	var fileLocalVarFormFileName string
	var fileLocalVarFileName     string
	var fileLocalVarFileBytes    []byte

	fileLocalVarFormFileName = "file"
	fileLocalVarFile := r.file

	if fileLocalVarFile != nil {
		fbs, _ := io.ReadAll(fileLocalVarFile)

		fileLocalVarFileBytes = fbs
		fileLocalVarFileName = fileLocalVarFile.Name()
		fileLocalVarFile.Close()
		formFiles = append(formFiles, formFile{fileBytes: fileLocalVarFileBytes, fileName: fileLocalVarFileName, formFileName: fileLocalVarFormFileName})
	}
	parameterAddToHeaderOrQuery(localVarFormParams, "name", r.name, "", "")
	if r.desc != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "desc", r.desc, "", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCreateVoiceprintGroupApiV1AiAudioGroupsCreatePostRequest struct {
	ctx context.Context
	ApiService *AIVoiceprintAPIService
	voiceprintGroupCreate *VoiceprintGroupCreate
}

func (r ApiCreateVoiceprintGroupApiV1AiAudioGroupsCreatePostRequest) VoiceprintGroupCreate(voiceprintGroupCreate VoiceprintGroupCreate) ApiCreateVoiceprintGroupApiV1AiAudioGroupsCreatePostRequest {
	r.voiceprintGroupCreate = &voiceprintGroupCreate
	return r
}

func (r ApiCreateVoiceprintGroupApiV1AiAudioGroupsCreatePostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.CreateVoiceprintGroupApiV1AiAudioGroupsCreatePostExecute(r)
}

/*
CreateVoiceprintGroupApiV1AiAudioGroupsCreatePost Create voiceprint group

Create a new voiceprint group for organizing speaker profiles.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateVoiceprintGroupApiV1AiAudioGroupsCreatePostRequest
*/
func (a *AIVoiceprintAPIService) CreateVoiceprintGroupApiV1AiAudioGroupsCreatePost(ctx context.Context) ApiCreateVoiceprintGroupApiV1AiAudioGroupsCreatePostRequest {
	return ApiCreateVoiceprintGroupApiV1AiAudioGroupsCreatePostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *AIVoiceprintAPIService) CreateVoiceprintGroupApiV1AiAudioGroupsCreatePostExecute(r ApiCreateVoiceprintGroupApiV1AiAudioGroupsCreatePostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AIVoiceprintAPIService.CreateVoiceprintGroupApiV1AiAudioGroupsCreatePost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/ai/audio/groups/create"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.voiceprintGroupCreate == nil {
		return localVarReturnValue, nil, reportError("voiceprintGroupCreate is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.voiceprintGroupCreate
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeleteVoiceprintApiV1AiAudioGroupsGroupIdUsersFeatureIdDeleteRequest struct {
	ctx context.Context
	ApiService *AIVoiceprintAPIService
	groupId string
	featureId string
}

func (r ApiDeleteVoiceprintApiV1AiAudioGroupsGroupIdUsersFeatureIdDeleteRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.DeleteVoiceprintApiV1AiAudioGroupsGroupIdUsersFeatureIdDeleteExecute(r)
}

/*
DeleteVoiceprintApiV1AiAudioGroupsGroupIdUsersFeatureIdDelete Delete voiceprint from group

Delete a voiceprint feature from a group.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param groupId
 @param featureId
 @return ApiDeleteVoiceprintApiV1AiAudioGroupsGroupIdUsersFeatureIdDeleteRequest
*/
func (a *AIVoiceprintAPIService) DeleteVoiceprintApiV1AiAudioGroupsGroupIdUsersFeatureIdDelete(ctx context.Context, groupId string, featureId string) ApiDeleteVoiceprintApiV1AiAudioGroupsGroupIdUsersFeatureIdDeleteRequest {
	return ApiDeleteVoiceprintApiV1AiAudioGroupsGroupIdUsersFeatureIdDeleteRequest{
		ApiService: a,
		ctx: ctx,
		groupId: groupId,
		featureId: featureId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *AIVoiceprintAPIService) DeleteVoiceprintApiV1AiAudioGroupsGroupIdUsersFeatureIdDeleteExecute(r ApiDeleteVoiceprintApiV1AiAudioGroupsGroupIdUsersFeatureIdDeleteRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AIVoiceprintAPIService.DeleteVoiceprintApiV1AiAudioGroupsGroupIdUsersFeatureIdDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/ai/audio/groups/{group_id}/users/{feature_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"group_id"+"}", url.PathEscape(parameterValueToString(r.groupId, "groupId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"feature_id"+"}", url.PathEscape(parameterValueToString(r.featureId, "featureId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiIdentifySpeakerApiV1AiAudioIdentifyPostRequest struct {
	ctx context.Context
	ApiService *AIVoiceprintAPIService
	speakerIdentifyRequest *SpeakerIdentifyRequest
}

func (r ApiIdentifySpeakerApiV1AiAudioIdentifyPostRequest) SpeakerIdentifyRequest(speakerIdentifyRequest SpeakerIdentifyRequest) ApiIdentifySpeakerApiV1AiAudioIdentifyPostRequest {
	r.speakerIdentifyRequest = &speakerIdentifyRequest
	return r
}

func (r ApiIdentifySpeakerApiV1AiAudioIdentifyPostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.IdentifySpeakerApiV1AiAudioIdentifyPostExecute(r)
}

/*
IdentifySpeakerApiV1AiAudioIdentifyPost Identify speaker from audio

Identify a speaker by comparing audio against voiceprint group features.

Uses DashScope ASR to transcribe the audio, then compares against
registered voiceprints in the specified group.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiIdentifySpeakerApiV1AiAudioIdentifyPostRequest
*/
func (a *AIVoiceprintAPIService) IdentifySpeakerApiV1AiAudioIdentifyPost(ctx context.Context) ApiIdentifySpeakerApiV1AiAudioIdentifyPostRequest {
	return ApiIdentifySpeakerApiV1AiAudioIdentifyPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *AIVoiceprintAPIService) IdentifySpeakerApiV1AiAudioIdentifyPostExecute(r ApiIdentifySpeakerApiV1AiAudioIdentifyPostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AIVoiceprintAPIService.IdentifySpeakerApiV1AiAudioIdentifyPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/ai/audio/identify"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.speakerIdentifyRequest == nil {
		return localVarReturnValue, nil, reportError("speakerIdentifyRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.speakerIdentifyRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiIdentifySpeakerUploadApiV1AiAudioGroupsGroupIdIdentifyPostRequest struct {
	ctx context.Context
	ApiService *AIVoiceprintAPIService
	groupId string
	file *os.File
}

func (r ApiIdentifySpeakerUploadApiV1AiAudioGroupsGroupIdIdentifyPostRequest) File(file *os.File) ApiIdentifySpeakerUploadApiV1AiAudioGroupsGroupIdIdentifyPostRequest {
	r.file = file
	return r
}

func (r ApiIdentifySpeakerUploadApiV1AiAudioGroupsGroupIdIdentifyPostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.IdentifySpeakerUploadApiV1AiAudioGroupsGroupIdIdentifyPostExecute(r)
}

/*
IdentifySpeakerUploadApiV1AiAudioGroupsGroupIdIdentifyPost Identify speaker (file upload)

Identify a speaker by uploading an audio file.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param groupId
 @return ApiIdentifySpeakerUploadApiV1AiAudioGroupsGroupIdIdentifyPostRequest
*/
func (a *AIVoiceprintAPIService) IdentifySpeakerUploadApiV1AiAudioGroupsGroupIdIdentifyPost(ctx context.Context, groupId string) ApiIdentifySpeakerUploadApiV1AiAudioGroupsGroupIdIdentifyPostRequest {
	return ApiIdentifySpeakerUploadApiV1AiAudioGroupsGroupIdIdentifyPostRequest{
		ApiService: a,
		ctx: ctx,
		groupId: groupId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *AIVoiceprintAPIService) IdentifySpeakerUploadApiV1AiAudioGroupsGroupIdIdentifyPostExecute(r ApiIdentifySpeakerUploadApiV1AiAudioGroupsGroupIdIdentifyPostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AIVoiceprintAPIService.IdentifySpeakerUploadApiV1AiAudioGroupsGroupIdIdentifyPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/ai/audio/groups/{group_id}/identify"
	localVarPath = strings.Replace(localVarPath, "{"+"group_id"+"}", url.PathEscape(parameterValueToString(r.groupId, "groupId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.file == nil {
		return localVarReturnValue, nil, reportError("file is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	var fileLocalVarFormFileName string
	var fileLocalVarFileName     string
	var fileLocalVarFileBytes    []byte

	fileLocalVarFormFileName = "file"
	fileLocalVarFile := r.file

	if fileLocalVarFile != nil {
		fbs, _ := io.ReadAll(fileLocalVarFile)

		fileLocalVarFileBytes = fbs
		fileLocalVarFileName = fileLocalVarFile.Name()
		fileLocalVarFile.Close()
		formFiles = append(formFiles, formFile{fileBytes: fileLocalVarFileBytes, fileName: fileLocalVarFileName, formFileName: fileLocalVarFormFileName})
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListVoiceprintGroupsApiV1AiAudioGroupsListGetRequest struct {
	ctx context.Context
	ApiService *AIVoiceprintAPIService
}

func (r ApiListVoiceprintGroupsApiV1AiAudioGroupsListGetRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.ListVoiceprintGroupsApiV1AiAudioGroupsListGetExecute(r)
}

/*
ListVoiceprintGroupsApiV1AiAudioGroupsListGet List voiceprint groups

List all voiceprint groups.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiListVoiceprintGroupsApiV1AiAudioGroupsListGetRequest
*/
func (a *AIVoiceprintAPIService) ListVoiceprintGroupsApiV1AiAudioGroupsListGet(ctx context.Context) ApiListVoiceprintGroupsApiV1AiAudioGroupsListGetRequest {
	return ApiListVoiceprintGroupsApiV1AiAudioGroupsListGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *AIVoiceprintAPIService) ListVoiceprintGroupsApiV1AiAudioGroupsListGetExecute(r ApiListVoiceprintGroupsApiV1AiAudioGroupsListGetRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AIVoiceprintAPIService.ListVoiceprintGroupsApiV1AiAudioGroupsListGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/ai/audio/groups/list"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListVoiceprintsApiV1AiAudioGroupsGroupIdUsersGetRequest struct {
	ctx context.Context
	ApiService *AIVoiceprintAPIService
	groupId string
}

func (r ApiListVoiceprintsApiV1AiAudioGroupsGroupIdUsersGetRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.ListVoiceprintsApiV1AiAudioGroupsGroupIdUsersGetExecute(r)
}

/*
ListVoiceprintsApiV1AiAudioGroupsGroupIdUsersGet List voiceprints in group

List all voiceprint features in a group.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param groupId
 @return ApiListVoiceprintsApiV1AiAudioGroupsGroupIdUsersGetRequest
*/
func (a *AIVoiceprintAPIService) ListVoiceprintsApiV1AiAudioGroupsGroupIdUsersGet(ctx context.Context, groupId string) ApiListVoiceprintsApiV1AiAudioGroupsGroupIdUsersGetRequest {
	return ApiListVoiceprintsApiV1AiAudioGroupsGroupIdUsersGetRequest{
		ApiService: a,
		ctx: ctx,
		groupId: groupId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *AIVoiceprintAPIService) ListVoiceprintsApiV1AiAudioGroupsGroupIdUsersGetExecute(r ApiListVoiceprintsApiV1AiAudioGroupsGroupIdUsersGetRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AIVoiceprintAPIService.ListVoiceprintsApiV1AiAudioGroupsGroupIdUsersGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/ai/audio/groups/{group_id}/users"
	localVarPath = strings.Replace(localVarPath, "{"+"group_id"+"}", url.PathEscape(parameterValueToString(r.groupId, "groupId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
